envoyproxy/gateway

internal/gatewayapi/backendtrafficpolicy.go
internal/gatewayapi/testdata/backendtrafficpolicy-with-healthcheck.out.yaml
internal/gatewayapi/testdata/backendtrafficpolicy-with-tcp-udp-listeners-apply-on-gateway.out.yaml
internal/gatewayapi/testdata/backendtrafficpolicy-with-tcp-udp-listeners-apply-on-route.out.yaml
internal/ir/xds.go
internal/ir/xds_test.go
internal/xds/translator/cluster.go
internal/xds/translator/testdata/in/xds-ir/health-check.yaml
internal/xds/translator/testdata/out/xds-ir/health-check.clusters.yaml

Set host for http health checker explicitly to avoid using the cluster name as host header for http health checking request.

---

.github/codecov.yml

Add ignore-paths to codecov config to ignore certain paths, give the coverage a boost by ignoring unrelevant code.

chore: add ignore path for codecov

---

internal/gatewayapi/sort.go
internal/gatewayapi/testdata/grpcroute-with-service-match.out.yaml

fix
Like <https://github.com/kubernetes-sigs/gateway-api/issues/1770>, I've encountered a case when converting the following ingress definition:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: sentry
namespace: sentry
spec:
tls:
- hosts:
- sentry.selfhosted.tld
rules:
- host: sentry.selfhosted.tld
http:
paths:
- path: /api/store
pathType: ImplementationSpecific
backend:
service:
name: sentry-relay
port:
number: 3000
- path: /api/[1-9][0-9]*/(.*)
pathType: ImplementationSpecific
backend:
service:
name: sentry-relay
port:
number: 3000
- path: /
pathType: ImplementationSpecific
backend:
service:
name: sentry-web
port:
number: 9000
```
to
```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: …
```

Change route sorting order to Exact > RegularExpression > PathPrefix

---

.github/workflows/docs.yaml

Pin version of linkinator npm package in docs workflow in order to increase OpenSSF `Pinned-Dependencies` score:

ci: pin linkinator version in docs workflow

---

OWNERS

I have not been able to commit time to this project for awhile now and with my new role that wont be changing any time soon. So, just updating to reflect reality.
Congratulations team on V1.0.0 and wish you the best of luck going forward!

team: remove LanceEA as a gateway-reviewer

---

internal/xds/translator/testdata/out/xds-ir/tracing.listeners.yaml
internal/xds/translator/tracing.go

According the [doc](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/tracing#different-modes-of-envoy), EG should set `SpawnUpstreamSpan` to `true`.
```
//   - If Envoy is used as gateway or independent proxy, or users want to make the sidecar and its
//     application as different hops in the trace chain, this flag should be set to true.
```

translator: set SpawnUpstreamSpan to true

---

tools/make/golang.mk
tools/make/kube.mk

Separated from https://github.com/envoyproxy/gateway/pull/3080, xref: https://github.com/envoyproxy/gateway/pull/3080/files?diff=split&w=0#r1547213400
CEL must be validated on supported k8s versions.

run cel validation on different k8s versions

---

.github/workflows/build_and_test.yaml

* dont fail CI is Codecov upload fails
Codecov uploads recently started failing
relates to https://github.com/codecov/codecov-action/issues/1359
* fix lint
---------
(cherry picked from commit e12fdeb138506a8f52419aaf8d18898982ba8e44)

[release/v1.0] dont fail CI if codecov upload fails (#3123)

---

internal/infrastructure/kubernetes/infra_client.go
internal/infrastructure/kubernetes/infra_resource.go
internal/infrastructure/kubernetes/proxy_deployment_test.go
test/cel-validation/clienttrafficpolicy_test.go
test/e2e/tests/gateway_infra_resource.go

Full context #3111
This PR will refactor the infra client which is moving from an imperative to a declarative way to manage the resources, specifically with the server-side apply mechanism, including a full refactor on `CreateOrUpdate` to `ServerSideApply`.
The reason, quoted from https://github.com/envoyproxy/gateway/issues/3111#issuecomment-2041443070:
> Apply expects to manage the entire lifecycle of the object, so when you created independently, it had no record of the original applied content, so it didn't know your updated manifest should remove the old port.
In previous attempts, we created a resource using the Create operation but then attempted updates using the Apply operation. This led us to identify issues on certain fields, such as …

refactor: infra client CreateOrUpdate to ServerSideApply

---

site/content/en/latest/releases/v1.0.0.md
site/content/en/v1.0.1/releases/v1.0.1.md

fix: date and sync release note to v1.0.1

---

site/content/en/latest/api/extension_types.md

fix gen-check merge race caused by #3078

---

charts/gateway-helm/values.tmpl.yaml
site/content/en/latest/install/api.md
test/helm/default.yaml

This is painless workaround for ArgoCD bug: argoproj/argo-cd#6880

fix(chart): set ttlSecondsAfterFinished on certgen job to 30 by default

---

api/v1alpha1/wasm_types.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml

This PR fixes the validation enum values of the `WasmCodeSourceType` type. 
When the following `EnvoyExtensionPolicy` resource was deployed, the CRD validation failed
```yaml
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
name: my-wasm-1
namespace: envoy-gateway-system
spec:
targetRef:
kind: Gateway
name: eg
group: gateway.networking.k8s.io
wasm:
- name: my_wasm_1
code:
type: Image
image:
url: oci://example.com/project/my-wasm:latest
pullSecret:
name: "some-secret-name"
failOpen: true
config:
foo: value1
```
The validation message:
```
The EnvoyExtensionPolicy "my-wasm-1" is invalid: 
* spec.wasm[0].code.type: Unsupported value: "Image": supported values: "Global", "Local"
* <nil>: Invalid value: "": "spec.wasm[0].code.type" must validate all the …
```

api: fix WasmCodeSourceType enum validation

---

.github/workflows/cherrypick.yaml

Move write permissions to job level in cherrypick workflow. With this fix `Token-Permissions` ossf score becomes 10.
Fixes #

ci: move write permissions to job level in cherrypick workflow

---

site/content/en/latest/tasks/extensibility/envoy-patch-policy.md
site/content/en/latest/tasks/security/backend-tls.md
site/content/en/latest/tasks/security/basic-auth.md
site/content/en/latest/tasks/security/mutual-tls.md
site/content/en/latest/tasks/security/secure-gateways.md
site/content/en/latest/tasks/security/tls-passthrough.md
site/content/en/latest/tasks/traffic/gateway-address.md
site/content/en/latest/tasks/traffic/http3.md
site/content/en/latest/tasks/traffic/routing-outside-kubernetes.md
site/content/en/latest/tasks/traffic/udp-routing.md
site/content/en/v1.0.1/tasks/extensibility/envoy-patch-policy.md
site/content/en/v1.0.1/tasks/security/backend-tls.md
site/content/en/v1.0.1/tasks/security/basic-auth.md
site/content/en/v1.0.1/tasks/security/mutual-tls.md
site/content/en/v1.0.1/tasks/security/secure-gateways.md
site/content/en/v1.0.1/tasks/security/tls-passthrough.md
site/content/en/v1.0.1/tasks/traffic/gateway-address.md
site/content/en/v1.0.1/tasks/traffic/http3.md
site/content/en/v1.0.1/tasks/traffic/routing-outside-kubernetes.md
site/content/en/v1.0.1/tasks/traffic/udp-routing.md

* docs: replaces kubectl patch with json bodies to yaml, for better legibility
improves the docs.
Fixes #3180

docs: replaces json patch bodies with yaml format

---

test/e2e/tests/ext_auth_http_service.go

Hopefully, this can fix https://github.com/envoyproxy/gateway/issues/3040

fix flaky ext auth e2e

---

internal/utils/helm/package.go
site/content/en/latest/tasks/operations/egctl.md

feat: support egctl install output manifests and fix bugs
This PR did the following three things:
+ **Add `-o` flags**:    If the user installs EnvoyGateway via `egctl install`, it will be difficult for the user to know what is installed by default. Even though it is possible to print manifests to STDOUT via `--dry-run`, this makes it uncomfortable for users to see. We support outputting manifests to specified files through `-o`.
+ **Bug fix**:    Fixed the problem of detecting the existence of CRDs when `--dry-run` is specified.
+ **Change `--release-name` to `--name`**:    Please refer to [comment](https://github.com/envoyproxy/gateway/pull/2859#discussion_r1546064226) for details

feat: support egctl install output manifests and fix bugs

---

site/content/en/latest/tasks/traffic/http-routing.md
site/content/en/v1.0.1/tasks/traffic/http-routing.md

Fix commands for testing jwt based routing.
docs: Fix commands for testing jwt based routing
The commands used for testing jwt based routing miss host headers which cause 404.
https://github.com/envoyproxy/gateway/issues/3242
Fixes #3242 commands for testing jwt based routing

docs: Fix commands for testing jwt based routing

---

internal/utils/file/file.go

The `file.Write` function is used exclusively by unit tests to override testdata output. It is also a convenience to create the initial testdata output YAML files.
There's no reason to create YAML files with the executable bit set. This PR modifies the default mode used for file creation to not turn on the executable flag.

fix: make Write create files without the executable bit set

---

site/content/en/latest/tasks/traffic/global-rate-limit.md
site/content/en/v1.0.1/tasks/traffic/global-rate-limit.md

Fix's the doc to use the correct enum names for the sourceCIDR type for global rate limiting.  This could be a bug in the translator but this fixes the doc in case it not.

docs: Fix global rate limit doc for sourceCIDR type

---

api/v1alpha1/ratelimit_types.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml
test/e2e/testdata/ratelimit-cidr-match.yaml
test/e2e/testdata/ratelimit-multiple-listeners.yaml

Adds validation to SourceMatch to only allow the accepted values. This is to prevent people using a lowercase  version of "Distinct" which will then default to using "Exact" for the ratelimiting. 
I lost a few hours to this 😄

fix: Add SourceMatchType validation for acceptable values

---

.github/workflows/trivy.yml

Introduced Trivy image vulnerabilities scan workflow:
* This workflow will be triggered on merge to main and also once a week. I thought about triggering it also on PRs but I decided to avoid it in order to not block all PRs when a new vulnerability is detected.
* I didn't upload scan results to GitHub code scanning since when choosing `sarif` output format results don't appear in stdin. Since code scanning results are not public I kept the default `table` format so anyone can see it. See related [issue](https://github.com/aquasecurity/trivy-action/issues/116).
* Currently only `eg` image is scanned. Regarding `envoy-proxy` and `rate-limit` images, I think that they should be scanned as part of their ow repos CI process. We can discuss it later if …

ci: add trivy image vulnerabilities scan workflow

---

.github/workflows/trivy.yml
README.md

Add status badges for security scans related workflows:
* CodeQL
* OSV-Scanner
* Trivy
Fixes #

ci: add badges for security scans

---

site/content/en/latest/tasks/security/oidc.md
site/content/en/latest/tasks/security/secure-gateways.md
site/content/en/v1.0.1/tasks/security/oidc.md
site/content/en/v1.0.1/tasks/security/secure-gateways.md

This PR updates odic docs:
* splits the task into two sub-tasks: OIDC Authentication for a specific HTTPRoute and OIDC Authentication for a Gateway
* adds https setup to the Prerequisites section since browsers don't allow secure cookies for HTTP connections
Fix https://github.com/envoyproxy/gateway/issues/2913

doc: update oidc docs

---

site/content/en/latest/tasks/quickstart.md
site/content/en/latest/tasks/security/backend-tls.md
site/content/en/latest/tasks/security/mutual-tls.md
site/content/en/latest/tasks/security/secure-gateways.md
site/content/en/latest/tasks/security/tls-passthrough.md
site/content/en/latest/tasks/security/tls-termination.md
site/content/en/latest/tasks/traffic/http3.md

Updates tasks in docs to use tabs for testing with & without load balancer support:
- tasks/traffic/http3.md
- tasks/security/tls-passthrough.md
- tasks/security/secure-gateways.md
- tasks/security/backend-tls.md
- tasks/security/mutual-tls.md
- tasks/security/tls-termination.md
Also reverses the order: with lb support first, without second.
Fixes #3259

docs: updates task testing instructions to use tabs for with|without external load balancer 

---

internal/gatewayapi/envoyextensionpolicy.go
internal/provider/kubernetes/indexers.go
test/e2e/base/manifests.yaml
test/e2e/testdata/use-client-protocol.yaml
test/e2e/tests/use_client_protocol.go

e2e: Add an e2e test for useClientProtocol

---

.github/workflows/build_and_test.yaml
.github/workflows/latest_release.yaml
.github/workflows/release.yaml
charts/gateway-helm/values.tmpl.yaml
site/content/en/latest/install/api.md
tools/make/common.mk
tools/make/docs.mk
tools/make/helm.mk
tools/make/kube.mk

1. `ImagePullPolicy` be one of params of `make helm-generate`
2. make sure set `ImagePullPolicy=Always/IfNotPresent` when run `make helm-package` and `generate-manifests`
cc @arkodg

fix helm IfNotPresent

---

test/e2e/merge_gateways/merge_gateways_test.go
test/e2e/testdata/basic-merge-gateways.yaml
test/e2e/tests/merge_gateways.go

e2e: fix flaky merge-gateways test

---

internal/xds/translator/proxy_protocol.go
internal/xds/translator/proxy_protocol_test.go

fix: add proxy protocol always as first listenerFilter
As you can see I did issue about 3 months ago and since that I have had random issues that envoy will not reply anything back. Now I decided that I will go through the egctl dumps and I found out that the order in tls and proxy protocol listenerFilters are incorrect somehow.
not working
```
"listenerFilters": [
{
"name": "envoy.filters.listener.tls_inspector",
"typedConfig": {
"@type": "type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector"
}
},
{
"name": "envoy.filters.listener.proxy_protocol",
"typedConfig": {
"@type": "type.googleapis.com/envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol"
}
}
],
```
working
``` …
```

fix: add proxy protocol always as first listenerFilter

---

internal/infrastructure/kubernetes/proxy/resource.go
internal/xds/bootstrap/bootstrap.go
internal/xds/bootstrap/bootstrap.yaml.tpl
internal/xds/bootstrap/bootstrap_test.go

chore: correct typos in comments and code

---

site/content/en/latest/tasks/security/backend-tls.md
site/content/en/latest/tasks/security/ext-auth.md

Fix `BackendTLSPolicy` samples in docs so they will be aligned with Gateway API v1.1.0.
Fixes #

docs: fix broken BackendTLSPolicy samples

---

internal/provider/kubernetes/controller.go

fix: security policy reference grant from field type
When creating a SecurityPolicy  in a different namespace than the targeted service, the controller expects a ReferenceGrant resource with an entry in the *from* field of the type `HTTPRoute`. 
```yaml
spec:
from:
- group: gateway.networking.k8s.io
kind: HTTPRoute
namespace: envoy-gateway-system
```
That resource does not even exist in our tests because the HTTPRoute lives in other namespace. But the securitypolicy only works if we add that entry.
This PR fixes that and requires the existence of a referencegrant with a securitypolicy type in the *from* field.
Not created any issue. Just submitting the fix.

fix: security policy reference grant from field type

---

.github/workflows/license-scan.yml

* Added license scan workflow for project dependencies which is aligned with [CNCF guidelines](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md).
* osv-scanner [experimental license scanning](https://google.github.io/osv-scanner/experimental/license-scanning/) is used as agreed [here](https://github.com/envoyproxy/gateway/issues/2917#issuecomment-2091176893).
* The license scan is running in non-blocking mode since it is currently failing. Once all issues are resolved we can configure it to fail the build. See more details [here](https://github.com/envoyproxy/gateway/issues/2917#issuecomment-2089656466).
* The license scan is running together with vulnerability scan. I opened an issue to add support for running only …

ci: add license scan workflow

---

internal/xds/translator/extauth.go
internal/xds/translator/testdata/out/xds-ir/ext-auth.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/multiple-listeners-same-port-with-different-filters.listeners.yaml

This PR set ignoreCase to true for header matchers in extAuth.
HTTP Header names are case-insensitive according to [RFC 2616](http://www.ietf.org/rfc/rfc2616.txt) and [envoy will normalize the header keys to be all lowercase by default](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/header_casing).
Fixes #3372

fix(translator): set ignoreCase for header matchers in extAuth

---

internal/xds/cache/metrics.go
internal/xds/cache/snapshotcache.go
internal/xds/server/runner/runner.go

feat: add metrics instrumentation for xds server

---

internal/extension/registry/extension_manager.go
internal/gatewayapi/status/gatewayclass_test.go
internal/xds/server/runner/runner.go
internal/xds/translator/extproc.go
internal/xds/translator/httpfilters.go
internal/xds/translator/runner/runner_test.go
test/cel-validation/envoyextensionpolicy_test.go
test/cel-validation/securitypolicy_test.go
test/e2e/tests/backend_upgrade.go
test/e2e/tests/tcp_route.go
test/e2e/tests/utils.go
tools/linter/golangci-lint/.golangci.yml

we have gci settings in https://github.com/envoyproxy/gateway/blob/e847d68c2665d471912d66250990937b73787dc6/tools/linter/golangci-lint/.golangci.yml#L39,
but this setting is somehow not be enabled.

chore: enable gci in golangci-lint

---

api/v1alpha1/clienttrafficpolicy_types.go
api/v1alpha1/zz_generated.deepcopy.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_clienttrafficpolicies.yaml
internal/gatewayapi/clienttrafficpolicy.go
internal/gatewayapi/testdata/clienttrafficpolicy-mtls-forward-client-cert-custom-data.in.yaml
internal/gatewayapi/testdata/clienttrafficpolicy-mtls-forward-client-cert-custom-data.out.yaml
internal/gatewayapi/testdata/clienttrafficpolicy-mtls-forward-client-cert.in.yaml
internal/gatewayapi/testdata/clienttrafficpolicy-mtls-forward-client-cert.out.yaml
internal/ir/xds.go
internal/ir/zz_generated.deepcopy.go
internal/xds/translator/listener.go
internal/xds/translator/testdata/in/xds-ir/mutual-tls-forward-client-certificate-with-custom-data.yaml
site/content/en/latest/api/extension_types.md
test/cel-validation/clienttrafficpolicy_test.go

This a follow-up PR to address comments on https://github.com/envoyproxy/gateway/pull/3202.
* XFCC header setting naming
* Add validation for xfcc setting
* Add some comments
Close https://github.com/envoyproxy/gateway/issues/2599

API: Follow up on XFCC header

---

site/content/en/latest/install/install-yaml.md
site/content/en/v1.0.1/install/install-yaml.md

Fixes: https://github.com/envoyproxy/gateway/issues/3257

docs:use server side apply when installing EG using kubectl

---

examples/grafana/dashboards/envoy-clusters.json
examples/grafana/dashboards/envoy-global.json
examples/grafana/dashboards/envoy-pod-resource.json

Fixes some panels in grafana to:
* Use the variable datasource like the rest of the panels
* Sets request latency unit to ms
* Makes envoy-pod-resource.json use variable datasource like the other dashboards

fix: Grafana dashboards conformance

---

.github/workflows/build_and_test.yaml
.github/workflows/experimental_conformance.yaml
site/content/en/latest/install/matrix.md

fixes: #3449
remove 1.26, add 1.30
bump:
1.27.11 -> 1.27.13
1.28.7 -> 1.28.9
1.29.2 -> 1.29.4

chore: update matrix

---

internal/cmd/egctl/translate.go
internal/provider/kubernetes/controller.go
internal/provider/kubernetes/routes.go

fixes: https://github.com/envoyproxy/gateway/issues/3411

chore: use sets.Set[T] instead of map[T]struct{}

---

internal/provider/kubernetes/controller.go
internal/provider/kubernetes/indexers.go
internal/provider/kubernetes/predicates.go
internal/provider/kubernetes/predicates_test.go

fixes: https://github.com/envoyproxy/gateway/issues/3412

Trigger a reconcile when EnvoyProxy backendRefs changes

---

internal/gatewayapi/envoyextensionpolicy.go
internal/gatewayapi/securitypolicy.go
internal/gatewayapi/testdata/envoyextensionpolicy-with-extproc-with-backendtlspolicy.in.yaml
internal/gatewayapi/testdata/envoyextensionpolicy-with-extproc-with-multiple-backendrefs.in.yaml
internal/gatewayapi/validate.go

Fix validation of policy backend references to consider all policy types. Fix reference grants in test accordingly.

fix: EEP RG enforcement

---

internal/extension/registry/extension_manager.go

Noticed that the amount of memory being used for the in-memory extension server buffer was too large due to a typo.

fix: Reduce the amount of memory used by the in-memory extension manager gRPC server buffer

---

site/content/zh/latest/api/extension_types.md

fix: merge race between #3418 and #3444,#3423

---

.github/workflows/build_and_test.yaml

The `make helm-push` already relys on `make helm-package`, remove redundant command.
https://github.com/envoyproxy/gateway/blob/607d8bcd9a833841eee057b263c0bdc06de0fbea/tools/make/helm.mk#L39
Fixes #

chore: remove redundant `helm-package` command

---

internal/gatewayapi/helpers.go
internal/infrastructure/kubernetes/proxy/resource_provider.go
internal/infrastructure/kubernetes/proxy/resource_provider_test.go
internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-name.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-name.yaml
internal/infrastructure/kubernetes/proxy/testdata/hpa/with-deployment-name.yaml
internal/infrastructure/kubernetes/proxy/testdata/services/with-name.yaml
internal/provider/kubernetes/helpers.go
internal/provider/kubernetes/predicates.go
internal/provider/kubernetes/predicates_test.go

Relates to https://github.com/envoyproxy/gateway/pull/3527

feat: support custom names for generated k8s resources

---

api/v1alpha1/clienttrafficpolicy_types.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_clienttrafficpolicies.yaml
test/cel-validation/clienttrafficpolicy_test.go

Removed CEL validation that prevents specifying a `SectionName` for `ClientTrafficPolicy` resources.
The `ClientTrafficPolicy` translation does in-fact support targeting a specific `SectionName`, the CEL validation is wrong.

bug: ClientTrafficPolicy resources are prevented from targeting a SectionName by an incorrect CEL validation

---

tools/make/golang.mk

The cel test invocation was using the wrong verison of Kubernetes every time it was being run.
Here's what the Makefile did before the fix:
```bash
echo -e "\033[0;32m===========> Running go.test.cel ... \033[0m"
for ver in 1.27.1 1.28.0 1.29.0; do \
echo "Run CEL Validation on k8s $ver"; \
go clean -testcache; \
KUBEBUILDER_ASSETS="/home/user/.local/share/kubebuilder-envtest/k8s/1.30.0-linux-amd64" \
go test ./test/cel-validation --tags celvalidation -race; \
done
```
Notice that the `KUBEBUILDER_ASSETS` is already hardcoded to version 1.30. This is because the `$(shell)` expansion used is evaluated only once before make runs the for loop.
Here's what it looks like after the fix:
```bash
echo -e "\033[0;32m===========> Running go.test.cel ... \033[0m"
for ver in 1.27.1 1.28.0 1.29.0; do …
```

bug: cel tests are always run on a single version of Kubernetes

---

internal/cmd/egctl/status.go

fix: egctl x status gatewayclass example msg

fix: egctl x status gatewayclass example msg

---

charts/gateway-helm/README.md
charts/gateway-helm/values.tmpl.yaml
site/content/en/latest/install/gateway-helm-api.md
site/content/zh/latest/install/gateway-helm-api.md

doc: add certgen description into chart readme
ref: #3521

doc: add certgen description into chart readme

---

test/config/gatewayclass.yaml
test/e2e/upgrade/eg_upgrade_test.go

This PR delays readiness of envoy to allow XDS sync as discussed in #2810. This is done specifically for the upgrade test suite gateway class. 
Test flakiness seems to be related to 404 responses in early stages of the load test, which likely indicates that new proxy instances are ready before being programmed. 
```sh
--- FAIL: TestEGUpgrade (230.50s)
--- PASS: TestEGUpgrade/EGUpgrade (152.90s)
--- PASS: TestEGUpgrade/EGUpgrade/Upgrade_from_an_older_eg_release_should_succeed (152.89s)
--- FAIL: TestEGUpgrade/EnvoyShutdown (68.06s)
--- FAIL: TestEGUpgrade/EnvoyShutdown/All_requests_must_succeed (68.04s)
utils.go:176: failed to create load: error 404 for http://172.18.255.208/envoy-shutdown (82 bytes)
utils.go:185: Load completed after 0s with 2 …
```

fix: envoy shutdown flaky test

---

internal/xds/translator/route.go
internal/xds/translator/testdata/in/xds-ir/http-route-redirect.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-redirect.routes.yaml

fix: do not propagate well-known port number for xds portRedirect

---

site/content/en/v0.6.0/user/customize-envoyproxy.md

Make the example config match the api spec
The example config is invalid, the key should be `value` and not `bootstrap` according to the API reference: https://gateway.envoyproxy.io/v0.6.0/api/extension_types/#proxybootstrap

docs: Fix typo in bootstrap config

---

site/content/en/contributions/DEVELOP.md

We're on golang v1.22.x, and this PR modifies the prerequisite based on it.  
https://github.com/envoyproxy/gateway/blob/main/go.mod#L3
FYI, actually maybe we can just mention 1.21+ due to the following improvement, instead of mention the specific version, which is troublesome as we have to update the page every time we upgrade go version. 
> After installing Go 1.21, you’ll never have to manually download and install a Go toolchain again. The go command can do it for you.
https://go.dev/blog/toolchain
Fixes #

docs: Modify prerequisite go version

---

site/content/en/latest/install/install-egctl.md

fixes: https://github.com/envoyproxy/gateway/issues/3705

docs: install with brew

---

test/config/gatewayclass.yaml
test/e2e/tests/accesslog.go
test/e2e/tests/utils.go

fix: https://github.com/envoyproxy/gateway/issues/3735

e2e: add CEL to accesslog test

---

api/v1alpha1/loadbalancer_types.go
internal/gatewayapi/backendtrafficpolicy.go
internal/gatewayapi/testdata/backendtrafficpolicy-with-loadbalancer.in.yaml
internal/gatewayapi/testdata/backendtrafficpolicy-with-loadbalancer.out.yaml
internal/ir/xds.go
internal/ir/zz_generated.deepcopy.go
internal/xds/translator/route.go
internal/xds/translator/testdata/in/xds-ir/load-balancer.yaml
internal/xds/translator/testdata/out/xds-ir/load-balancer.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/load-balancer.endpoints.yaml
internal/xds/translator/testdata/out/xds-ir/load-balancer.routes.yaml
site/content/en/latest/api/extension_types.md
site/content/zh/latest/api/extension_types.md

Fixes: https://github.com/envoyproxy/gateway/issues/2624

feat: cookie based consistent hashing

---

internal/cmd/version/version.go

This PR adds golang version to the version command:
before:
```
ENVOY_GATEWAY_VERSION: v1.0.2
ENVOY_PROXY_VERSION: distroless-dev
GATEWAYAPI_VERSION: v1.1.0
GIT_COMMIT_ID: a3505782947c5a3da3a586e0f8e1d55d78e86bde
```
after:
```
ENVOY_GATEWAY_VERSION: v1.0.2
ENVOY_PROXY_VERSION: distroless-dev
GATEWAYAPI_VERSION: v1.1.0
GIT_COMMIT_ID: a3505782947c5a3da3a586e0f8e1d55d78e86bde
GOLANG_VERSION: go1.22.5
```

chore: show golang version in the version command

---

test/benchmark/suite/render.go
test/benchmark/suite/report.go
test/benchmark/suite/suite.go
test/benchmark/tests/scale_httproutes.go
tools/make/lint.mk

@shawnh2 please help to review the result.

chore: enable lint for benchmark

---

internal/gatewayapi/status/gateway.go
internal/gatewayapi/status/gateway_test.go

This PR changes the impl to mark programmed=false with an error when too many addresses are assigned.
The motivation here is to enhance the visibility of this error to users.
Fixes #3662

feat: mark programmed=false with an error when too many addresses are assigned

---

site/content/en/latest/tasks/observability/proxy-accesslog.md
site/content/en/latest/tasks/observability/proxy-observability.md

fix: https://github.com/envoyproxy/gateway/issues/3734

docs: CEL Expressions for Access Logging

---

internal/gatewayapi/envoyextensionpolicy.go
internal/gatewayapi/ext_service.go
release-notes/v1.1.0-rc.1.yaml
site/content/en/contributions/design/envoy-extension-policy.md
site/content/en/news/blogs/1.0-release/1.0-release.md

This is a really common mistake but WebAssembly is officially Wasm,
not WASM. This fixes that in various places in code base.

Use Wasm instead of WASM

---

test/e2e/e2e_test.go
test/e2e/testdata/client-timeout.yaml
test/e2e/tests/client_timeout.go

Uses fault filter to create a more predictable timeout for request, by delaying it before being sent upstream and triggering the timeout: 
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-request-timeout
> The amount of time that Envoy will wait for the entire request to be received. The timer is activated when the request is initiated, and is disarmed when the last byte of the request is sent upstream
Fixes #2720

fix: enable client timeout test

---

test/e2e/tests/accesslog.go
test/e2e/tests/utils.go

e2e: make sure ALS server is ready

---

internal/gatewayapi/extensionserverpolicy.go
internal/gatewayapi/extensionserverpolicy_test.go
internal/gatewayapi/helpers.go

This PR adds support for target selectors on extension server policies
Fixes #3798

feat: support target selectors on Envoy Gateway Extension Server policies

---

test/e2e/tests/authorization-client-ip.go
test/e2e/tests/authorization-default-action.go

fix: https://github.com/envoyproxy/gateway/issues/3837

fix flaky authorization tests

---

examples/extension-server/go.mod
examples/extension-server/go.sum
test/e2e/base/manifests.yaml
test/e2e/testdata/connection-limit.yaml
test/e2e/tests/connection_limit.go

move connection limit test resources out of the base to reduce resource consumption of e2e tests.

chore: move connection limit test resources out of the base

---

test/e2e/base/manifests.yaml
test/e2e/testdata/tcp-route.yaml

move tcp test resources out of the base to reduce resource consumption of e2e tests.

chore: move tcp test resources out of the base

---

test/e2e/base/manifests.yaml
test/e2e/testdata/backend-tls-settings.yaml
test/e2e/tests/oidc.go
test/e2e/tests/oidc_testclient.go
test/e2e/tests/utils.go

* move backend tls test resources out of the base to reduce resource consumption of e2e tests.
* fix flaky OIDC test.

chore: move backend tls test resources out of the base

---

internal/cmd/egctl/testdata/translate/out/default-resources.all.yaml
internal/cmd/egctl/testdata/translate/out/echo-gateway-api.cluster.yaml
internal/cmd/egctl/testdata/translate/out/echo-gateway-api.route.json
internal/cmd/egctl/testdata/translate/out/invalid-envoyproxy.all.yaml
internal/cmd/egctl/testdata/translate/out/rejected-http-route.route.yaml
internal/cmd/egctl/testdata/translate/out/valid-envoyproxy.all.yaml
internal/cmd/egctl/translate_test.go
internal/gatewayapi/status/gatewayclass.go

disable until the field moves from experiemental to stable so status writes for a GatewayClass dont fail when the datatypes differ
Relates to a breaking change soon to be introduced in https://github.com/kubernetes-sigs/gateway-api/pull/3200.

disable writing into GatewayClass.Status.SupportedFeatures

---

api/v1alpha1/backendtrafficpolicy_types.go
api/v1alpha1/clienttrafficpolicy_types.go
api/v1alpha1/envoyextensionypolicy_types.go
api/v1alpha1/securitypolicy_types.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_clienttrafficpolicies.yaml
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml
test/cel-validation/backendtrafficpolicy_test.go
test/cel-validation/clienttrafficpolicy_test.go
test/cel-validation/envoyextensionpolicy_test.go
test/cel-validation/securitypolicy_test.go

fix: fix the CEL definitions to allow policies that use target selectors without explicit targetRefs

---

test/e2e/e2e_test.go
test/e2e/merge_gateways/merge_gateways_test.go
test/e2e/multiple_gc/multiple_gc_test.go
test/e2e/tests/accesslog.go
test/e2e/tests/backend_health_check.go
test/e2e/tests/client_timeout.go
test/e2e/tests/connection_limit.go
test/e2e/tests/controlplane.go
test/e2e/tests/eg_upgrade.go
test/e2e/tests/load_balancing.go
test/e2e/tests/metric.go
test/e2e/tests/oidc.go
test/e2e/tests/retry.go
test/e2e/tests/tcp_route.go
test/e2e/tests/tracing.go
test/e2e/tests/udproute.go
test/e2e/tests/utils.go
test/e2e/tests/wasm_oci.go
test/e2e/upgrade/eg_upgrade_test.go

This is basically a new feature added to the current logging package.
This PR adds a better logging using package `tlog` provides helpers for adding timestamps to test logging.
Fixes #3902

feat(logger): Add tlog for better test logging

---

internal/cmd/egctl/collect.go
internal/cmd/egctl/utils.go
internal/troubleshoot/collect.go
test/benchmark/benchmark_test.go
test/e2e/e2e_test.go
test/e2e/merge_gateways/merge_gateways_test.go
test/e2e/multiple_gc/multiple_gc_test.go
test/e2e/tests/oidc.go
test/e2e/tests/utils.go
test/e2e/upgrade/eg_upgrade_test.go
test/utils/kubernetes/client.go

add function to debug https://github.com/envoyproxy/gateway/issues/3898

e2e: add hook to debug OIDC fail

---

internal/gatewayapi/backendtrafficpolicy.go
internal/gatewayapi/clienttrafficpolicy.go
internal/gatewayapi/envoyextensionpolicy.go
internal/gatewayapi/securitypolicy.go
internal/gatewayapi/testdata/backendtrafficpolicy-status-conditions.out.yaml
internal/gatewayapi/testdata/clienttrafficpolicy-status-conditions.out.yaml
internal/gatewayapi/testdata/envoyextensionpolicy-status-conditions.out.yaml
internal/gatewayapi/testdata/securitypolicy-status-conditions.out.yaml

Policies in the `v1.1.x` versions will have multiple targets. This PR makes error messages on failures to attach to a target more specific.
No issues were logged for this
@zirain, this PR replaces #3917, which I messed up with the wrong commits. It also includes changes in the test files.

printing name of the target when a policy fails to attach

---

internal/infrastructure/kubernetes/ratelimit/resource.go
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/custom.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/default-env.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/default.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/enable-tracing-custom.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/enable-tracing.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/extension-env.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/override-env.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/patch-deployment.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/redis-tls-settings.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/tolerations.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/volumes.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/with-node-selector.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/with-topology-spread-constraints.yaml

All EG components have resource requirements in their container specs except the statsd exporter. This PR adds the missing resource requirements for the statsd exporter container.

chore: add resoure requirements for statsd exporter

---

site/hugo.toml
site/layouts/_default/_markup/render-heading.html

introduced by https://github.com/envoyproxy/gateway/pull/3652
related to: https://github.com/google/docsy/pull/1831
cc @arkodg

docs: fix missing heading self-links

---

internal/xds/translator/route.go
internal/xds/translator/testdata/in/xds-ir/http-route-rewrite-sufixx-with-slash-url-prefix.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-sufixx-with-slash-url-prefix.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-sufixx-with-slash-url-prefix.endpoints.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-sufixx-with-slash-url-prefix.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-sufixx-with-slash-url-prefix.routes.yaml

when the pathMath.Prefix has suffix / but EG has removed it, 
https://github.com/envoyproxy/gateway/blob/f4c53f4899b543a6461e7bf666a9bfa3b476e6b4/internal/xds/translator/route.go#L148-L153
and the urlRewrite.Path.PrefixMatchReplace suffix with / the upstream will get unwanted /
Fixes #3989 , Fix #3807

bugfix: fix upstream get unwanted /.

---

api/v1alpha1/validation/envoygateway_validate.go
api/v1alpha1/validation/envoygateway_validate_test.go

Prepare for #3159, this part is very likely to get conflicts.

refactor: clean envoygateway validate methods

---

test/e2e/testdata/wasm-http.yaml

Envoy moved all their examples from the `envoy` repository to a new `examples` repository. The URL to the wasm example must be updated in the E2E tests.
https://github.com/envoyproxy/envoy/commit/56be4f40fc5c90b6dd15a5242470c1fcf7ee4222

fix: change the wasm download URL to point to the envoy examples repository

---

internal/provider/kubernetes/controller.go
test/e2e/testdata/multi-referencegrants-same-namespace-services.yaml
test/e2e/testdata/multi-referencegrants-same-namespace.yaml
test/e2e/tests/referencegrants.go

The current behavior of Envoy Gateway when working with multiple `ReferenceGrants` in the same namespace is problematic. When searching for a ReferenceGrant for corresponding resources, such as the `HTTPRoute`, it only checks the `ReferenceGrant.spec.from` semantics. However, during translation, the translator validates both the `ReferenceGrant.spec.from` and `ReferenceGrant.spec.to` semantics thoroughly.
As a result, the `findReferenceGrant` method only captures the first `ReferenceGrant` with the correct `From`, meaning other `ReferenceGrants` are not honored. This leads to the corresponding resource that uses two different resource references encountering an error message such as `Backend ref to service <namespace>/<service_name> not permitted by any …

fix: multiple reference grants in same namespace

---

site/content/en/docs/install/install-yaml.md
site/content/en/docs/tasks/quickstart.md
site/content/en/latest/install/install-yaml.md
site/content/en/latest/tasks/quickstart.md
site/content/en/v1.1/install/install-yaml.md
site/content/en/v1.1/tasks/quickstart.md

* also add the `--server-side` and `--force-conflicts` flag
* also updated min supported k8s version to v1.27
Fixes: https://github.com/envoyproxy/gateway/issues/3981
Takes https://github.com/envoyproxy/gateway/pull/3988 forward

move upgrade notes to install section

---

site/content/en/docs/tasks/security/backend-tls.md
site/content/en/latest/tasks/security/backend-tls.md
site/content/en/v1.0/tasks/security/backend-tls.md
site/content/en/v1.1/tasks/security/backend-tls.md

fix: backend tls docs

---

internal/gatewayapi/conformance/suite.go
internal/gatewayapi/helpers.go
internal/gatewayapi/route.go
internal/gatewayapi/testdata/gateway-http-listener-with-hostname-intersection.in.yaml
internal/gatewayapi/testdata/gateway-http-listener-with-hostname-intersection.out.yaml
internal/gatewayapi/tls.go

feat(gateway-api): add support for gateway HTTP listener isolation.
* Adds support for gateway HTTP listener isolation.
* Enables GatewayHTTPListenerIsolation conformance test
Fixes #3352

feat: gateway http listener isolation

---

internal/gatewayapi/clustersettings.go
internal/gatewayapi/testdata/backendtrafficpolicy-with-healthcheck.in.yaml
internal/gatewayapi/testdata/backendtrafficpolicy-with-healthcheck.out.yaml

If no expected status was explicitly set, use the default value as described in the documentation.
Fixes #4089

fix: active http healthcheck documents a default for expected status, but doesn't use it

---

internal/infrastructure/kubernetes/ratelimit/resource_provider.go

* should have been part of https://github.com/envoyproxy/gateway/pull/3537

support custom name for ratelimit deployment

---

site/content/en/contributions/design/envoy-extension-policy.md

the title says.
This document is misleading by using unimplemented field named "attributes" 
which presumably will be implemented in https://github.com/envoyproxy/gateway/issues/3170
N/A

docs: removes unimplemented attributes in the extproc example

---

api/v1alpha1/ext_auth_types.go
api/v1alpha1/ext_proc_types.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml
internal/gatewayapi/securitypolicy.go
internal/gatewayapi/testdata/securitypolicy-with-extauth-backend.in.yaml
internal/gatewayapi/testdata/securitypolicy-with-extauth-backend.out.yaml
internal/gatewayapi/testdata/securitypolicy-with-extauth-backendref.in.yaml
internal/gatewayapi/testdata/securitypolicy-with-extauth-backendref.out.yaml
internal/gatewayapi/testdata/securitypolicy-with-extauth-with-backendtlspolicy.out.yaml
internal/gatewayapi/testdata/securitypolicy-with-extauth.out.yaml
internal/xds/translator/testdata/in/xds-ir/ext-auth.yaml
internal/xds/translator/testdata/out/xds-ir/ext-auth.endpoints.yaml
test/cel-validation/securitypolicy_test.go

Support multiple Backends elements in ext-auth and remove the CEL limitation in ext-proc.
Fixes #4006

fix: remove the limitation for only one backendRef from ext-auth and ext-proc

---

internal/gatewayapi/backendtrafficpolicy.go
internal/gatewayapi/clustersettings.go
internal/gatewayapi/route.go
internal/gatewayapi/testdata/backendtrafficpolicy-with-httproute-timeout.in.yaml
internal/gatewayapi/testdata/backendtrafficpolicy-with-httproute-timeout.out.yaml
internal/gatewayapi/testdata/httproute-and-backendtrafficpolicy-with-timeout.out.yaml

fix: don't lose timeout settings that originate from the route when translating the backend traffic policy

---

api/v1alpha1/shared_types.go
site/content/en/latest/api/extension_types.md
site/content/zh/latest/api/extension_types.md

Clicking through the docs from `EnvoyProxy`, looking to customize a gateway Deployment or Service, you land on these docs. The type of `value` is given as k8s type `JSON`, but for what I assume are complicated api-machinery deserialization quirks, cannot acutally be a JSON string, which is how I read it. Adding clarification to that.
Ie
This is fine, and is not "JSON" in the simple meaning
```
value:
foo: bar
```
Note that the above is first-class, ie NOT
```
value: |
foo: bar
```
And this is actually _rejected_ 
```
value: '{ "foo": "bar" }'
```

docs: Clarification for type which calls itself "JSON" but actually cannot be.

---

internal/provider/kubernetes/controller.go

small fix : 
`unable to find the Secret/Configmap` should be returned when IsNotFound error is true.

Fix IsNotFound check for secret and configmap

---

.github/markdown_lint_config.json
site/content/en/latest/tasks/security/private-key-provider.md
tools/make/lint.mk

- improve `Private Key Provider` page
- add make target `make lint.markdown`(you need to install `markdownlint-cli` manually)

docs: improve Private Key Provider page layout

---

internal/gatewayapi/backendtrafficpolicy.go
internal/gatewayapi/clienttrafficpolicy.go
internal/gatewayapi/clustersettings.go
internal/gatewayapi/filters.go
internal/gatewayapi/helpers.go
internal/gatewayapi/http.go
internal/xds/translator/local_ratelimit.go
internal/xds/translator/ratelimit.go
internal/xds/translator/route.go
internal/xds/translator/utils.go
test/e2e/tests/backend_tls_settings.go
test/e2e/tests/envoy_shutdown.go
tools/linter/golangci-lint/.golangci.yml

exclude `gosec` rule G115: Potential integer overflow when converting between integer types

lint: ignore gosec G115

---

.github/workflows/osv-scanner.yml

Fixes openssf-scorecard issue: `Warn: no topLevel permission defined: .github/workflows/osv-scanner.yml:1`

ci: fix openssf-scorecard permission issue

---

site/layouts/shortcodes/helm-version.html
site/layouts/shortcodes/yaml-version.html

* Point current docs to v1.1.1

Fix website version

---

site/content/en/contributions/DEVELOP.md

docs: Correct benchmark command from `make benchmark-test` to `make benchmark`
The developer guide documentation contains an incorrect benchmark command. The current command is written as `make benchmark-test`, but the correct command is `make benchmark`. This PR fixes the issue to prevent confusion for developers following the guide.
Fixes #4236

docs: fix make command from benchmark-test to benchmark

---

site/content/en/docs/tasks/security/jwt-authentication.md
site/content/en/docs/tasks/traffic/global-rate-limit.md
site/content/en/docs/tasks/traffic/http-routing.md
site/content/en/latest/tasks/security/jwt-authentication.md
site/content/en/latest/tasks/traffic/global-rate-limit.md
site/content/en/latest/tasks/traffic/http-routing.md
site/content/en/v0.3/user/authn.md
site/content/en/v0.4/user/authn.md
site/content/en/v0.5/user/authn.md
site/content/en/v0.5/user/rate-limit.md
site/content/en/v0.6/user/jwt-authentication.md
site/content/en/v0.6/user/rate-limit.md
site/content/en/v1.0/tasks/security/jwt-authentication.md
site/content/en/v1.0/tasks/traffic/global-rate-limit.md
site/content/en/v1.0/tasks/traffic/http-routing.md
site/content/en/v1.1/tasks/security/jwt-authentication.md
site/content/en/v1.1/tasks/traffic/global-rate-limit.md
site/content/en/v1.1/tasks/traffic/http-routing.md
site/content/zh/latest/tasks/security/jwt-authentication.md

docs: fix incorrect decoding command in developer documentation
The developer guide documentation contains an incorrect command for decoding JWT tokens. The current example includes an unnecessary `-`argument in the base64 command. The correct version omits this extra argument, ensuring the command runs properly. This PR fixes the issue to prevent confusion when following the example.
Fixes #4240

docs: fix incorrect decoding command in developer documentation

---

osv-scanner.toml

Remove license override for github.com/moby/patternmatcher in osv-scanner configuration since https://github.com/google/deps.dev/issues/106 is resolved.

ci: remove license override for github.com/moby/patternmatcher

---

.github/workflows/license-scan.yml
.github/workflows/osv-scanner.yml

Enable `osv-scanner` call analysis since https://github.com/google/osv-scanner/issues/1220 was fixed in latest release(v1.8.5).

ci: enable osv-scanner call analysis

---

examples/extension-server/go.mod
examples/extension-server/go.sum
go.mod
go.sum
internal/xds/extensions/extensions.gen.go
internal/xds/translator/oidc.go
internal/xds/translator/testdata/out/xds-ir/multiple-listeners-same-port-with-different-filters.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/oidc.listeners.yaml

This PR introduce nonce support to the oauth2 authentication flow, enhancing EG's security posture by preventing malicious  users from injecting their own access token into a victim's session through CSRF attacks.
Additional background information can be found at:
* https://github.com/envoyproxy/envoy/issues/35232
* https://github.com/envoyproxy/envoy/pull/35919

OIDC: add nonce support to the oauth2 filter

---

internal/infrastructure/kubernetes/ratelimit/resource.go
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/custom.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/default-env.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/default.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/disable-prometheus.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/enable-tracing-custom.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/enable-tracing.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/extension-env.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/override-env.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/patch-deployment.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/redis-tls-settings.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/tolerations.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/volumes.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/with-node-selector.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/with-topology-spread-constraints.yaml
test/e2e/tests/ratelimit.go
test/e2e/tests/utils.go

fixes: https://github.com/envoyproxy/gateway/issues/3369

moving away from promStatsdExporterContainer

---

internal/gatewayapi/runner/runner.go
internal/ir/infra.go
internal/ir/xds.go

changing infra and xds IR log value from yaml to json
before:
after:
fix #3698
before:
after:
AYCS, the highest mem cost has been decreased from 1370MB to 590MB.

performance: changing Infra and Xds IR log values to JSONString

---

test/e2e/testdata/ext-auth-http-backend-securitypolicy.yaml
test/e2e/tests/ext_auth_http_backend.go

fixes: https://github.com/envoyproxy/gateway/issues/3609

e2e: add test for RecomputeRoute in ExtAuth

---

internal/gatewayapi/backendtlspolicy.go
internal/gatewayapi/testdata/backendtlspolicy-default-ns.in.yaml
internal/gatewayapi/testdata/backendtlspolicy-default-ns.out.yaml

Targeting a `sectionName` for `kind:backend` is invalid in BackendTLSPolicy because there is no notion of sections in Backend
Fixes: https://github.com/envoyproxy/gateway/issues/4291

fix: handle invalid sectionName in BackendTLSPolicy for Backend

---

test/e2e/e2e_test.go

chore: e2e: expose --allow-crds-mismatch from conformace test
This is to align `test/e2e` package with `test/conformance` package for consistency (i.e. --allow-crds-mismatch for both test suites). This is needed to run e2e test in cluster with pre-installed Gateway API CRDs.
Fixes #

chore: e2e: expose --allow-crds-mismatch from conformace test

---

api/v1alpha1/shared_types.go
internal/infrastructure/kubernetes/proxy/testdata/deployments/bootstrap.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/component-level.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/disable-prometheus.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/override-labels-and-annotations.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/patch-deployment.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/shutdown-manager.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-annotations.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-concurrency.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-extra-args.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-image-pull-secrets.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-node-selector.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-topology-spread-constraints.yaml

Release Notes: https://github.com/envoyproxy/envoy/releases/tag/v1.29.9

[release/v1.0] Bump Envoy Proxy to v1.29.9

---

site/content/en/docs/tasks/security/tls-cert-manager.md
site/content/en/latest/tasks/security/tls-cert-manager.md
site/content/en/v0.5/user/tls-cert-manager.md
site/content/en/v0.6/user/tls-cert-manager.md
site/content/en/v1.0/tasks/security/tls-cert-manager.md
site/content/en/v1.1/tasks/security/tls-cert-manager.md

Fixes https://github.com/envoyproxy/gateway/issues/4022

docs: fix patch command for adding TLS gateway listener

---

tools/hack/create-cluster.sh

feat: Add dual-stack (IPv4 and IPv6) support for kind cluster
This PR implements dual-stack (IPv4 and IPv6) support for our kind cluster setup. It modifies the `create-cluster.sh` script to enable both IPv4 and IPv6 networking in the kind cluster and configures MetalLB to use address pools for both protocols. This enhancement allows for testing and development in environments that require both IP protocols, improving our cluster's versatility and compatibility with modern network configurations.
Key changes:
1. Enable dual-stack networking in the kind cluster configuration
2. Calculate both IPv4 and IPv6 address ranges from the Docker network
3. Update MetalLB configuration to support both IPv4 and IPv6 address pools …

ci: dual-stack support for kind cluster

---

site/content/en/docs/tasks/quickstart.md
site/content/en/latest/tasks/quickstart.md
site/content/en/v1.1/tasks/quickstart.md

docs: remove comma

---

internal/admin/server.go
internal/admin/server_test.go
internal/metrics/metadata.go
internal/metrics/register.go

bugfix: EG loglevel error for admin and metrics module

---

internal/provider/kubernetes/status_updater.go

Fix https://github.com/envoyproxy/gateway/issues/4336

fix: some status updates are discarded by the status updater

---

api/v1alpha1/tracing_types.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
internal/xds/translator/testdata/in/xds-ir/tracing-datadog.yaml
internal/xds/translator/testdata/out/xds-ir/tracing-datadog.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/tracing-datadog.endpoints.yaml
internal/xds/translator/testdata/out/xds-ir/tracing-datadog.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/tracing-datadog.routes.yaml
internal/xds/translator/tracing.go
internal/xds/translator/translator_test.go
site/content/en/latest/api/extension_types.md
site/content/zh/latest/api/extension_types.md

Hi,
This pull request allows to configure Datadog tracing for envoy proxy via CRDs.

Datadog tracing support

---

internal/gatewayapi/contexts.go
internal/gatewayapi/listener.go
internal/gatewayapi/testdata/gateway-with-listener-with-unsupported-protocol.out.yaml

Fixes: https://github.com/envoyproxy/gateway/issues/4216
Relates to https://kubernetes.slack.com/archives/CR0H13KGA/p1727457195236889

set invalid Listener.SupportedKinds to empty list

---

tools/docker/envoy-gateway/Dockerfile

```
1 warning found (use docker --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)
```

chore: fix docker build warning

---

charts/gateway-addons-helm/dashboards/envoy-clusters.json
charts/gateway-addons-helm/dashboards/envoy-proxy-global.json
test/helm/gateway-addons-helm/default.out.yaml
test/helm/gateway-addons-helm/e2e.out.yaml

fix: some typos in Grafana dashboard.
Fixes #4421

fix dashboard typos

---

site/content/en/docs/tasks/traffic/global-rate-limit.md
site/content/en/latest/tasks/traffic/global-rate-limit.md
site/content/en/v1.1/tasks/traffic/global-rate-limit.md

docs: Fix capital D in ratelimit example
This is a super dummy 1-char fix to docs fixing the capitalization of a rate limit example.
I see the same error in the versioned docs, let me know and I can fix the rest of them (not sure since they seem to be tied to a released tag):
```
site/content/en/docs/tasks/traffic/global-rate-limit.md:            type: distinct
site/content/en/latest/tasks/traffic/global-rate-limit.md:            type: distinct
site/content/en/v0.5/user/rate-limit.md:          type: distinct
site/content/en/v0.6/user/rate-limit.md:            type: distinct
site/content/en/v1.1/tasks/traffic/global-rate-limit.md:            type: distinct
```

docs: Fix capital D in ratelimit example

---

go.mod
internal/provider/kubernetes/kubernetes.go

before:
```console
2024-10-16T11:42:37.646Z	INFO	provider	kubernetes/controller.go:190	no accepted gatewayclass	{"runner": "provider"}
I1016 11:42:53.639624       1 leaderelection.go:268] successfully acquired lease envoy-gateway-system/5b9825d2.gateway.envoyproxy.io
```
after:
```console
2024-10-16T12:35:52.033Z	INFO	provider	leaderelection/leaderelection.go:254	attempting to acquire leader lease envoy-gateway-system/5b9825d2.gateway.envoyproxy.io...	{"runner": "provider"}
2024-10-16T12:36:18.142Z	INFO	provider	leaderelection/leaderelection.go:268	successfully acquired lease envoy-gateway-system/5b9825d2.gateway.envoyproxy.io	{"runner": "provider"}
```

chore: set klog

---

api/v1alpha1/backend_types.go
internal/gatewayapi/route.go
internal/gatewayapi/testdata/backend-with-fallback.in.yaml
internal/gatewayapi/testdata/backend-with-fallback.out.yaml
site/content/en/latest/api/extension_types.md
site/content/zh/latest/api/extension_types.md

Relates to https://github.com/envoyproxy/gateway/issues/3055

feat: implement fallback for the Backend API

---

test/e2e/testdata/ratelimit-header-invert-match.yaml
test/e2e/tests/ratelimit.go

E2E tests for feature PR #4286 
E2E tests
Ref #2193

e2e: add tests for ratelimit invert matching headers

---

charts/gateway-addons-helm/Chart.lock
charts/gateway-addons-helm/Chart.yaml
charts/gateway-addons-helm/README.md
charts/gateway-addons-helm/values.yaml
site/content/en/latest/install/gateway-addons-helm-api.md
site/content/en/latest/tasks/observability/proxy-trace.md
site/content/zh/latest/install/gateway-addons-helm-api.md
test/e2e/testdata/tracing-datadog.yaml
test/e2e/tests/tracing.go
test/helm/gateway-addons-helm/e2e.out.yaml

Hi
This PR introduce documentation and end-to-end tests for Datadog tracing which added in https://github.com/envoyproxy/gateway/pull/4298
End-to-end test implemented via [Grafana Alloy](https://grafana.com/docs/alloy/latest/), where Alloy acts as adapter from [Datadog agent interface](https://github.com/DataDog/datadog-agent) into `OpenTelemetry` format.
Thanks

Docs/Tests: documentation and e2e tests for Datadog tracing

---

internal/provider/kubernetes/controller.go
internal/provider/kubernetes/resource.go
internal/provider/kubernetes/routes.go

Fixes #4395 and optimize for #4181 
before:
after

bugfix: filter repeated resources and optimize memory usage.

---

internal/gatewayapi/backendtrafficpolicy.go
internal/utils/ratelimit/unit.go
internal/xds/translator/local_ratelimit.go

xref: https://github.com/envoyproxy/gateway/pull/4495

chore: share UnitToDuration logic

---

internal/provider/kubernetes/controller.go

chore: refactor byNamespaceSelectorEnabled

---

internal/cmd/egctl/testdata/translate/in/backend-endpoint.yaml
internal/cmd/egctl/testdata/translate/out/backend-endpoint.all.yaml
internal/cmd/egctl/translate_test.go
internal/gatewayapi/resource/load.go

feat: enable load backend resources

---

internal/provider/kubernetes/controller.go
test/e2e/testdata/gateway-with-envoyproxy.yaml
test/e2e/tests/gatewayt-with-envoyproxy.go

Fix: https://github.com/envoyproxy/gateway/issues/3640

e2e test for Gateway with EnvoyProxy

---

internal/provider/kubernetes/controller.go
internal/provider/kubernetes/predicates.go
internal/provider/kubernetes/predicates_test.go
internal/provider/kubernetes/routes.go

* The ownership of CRD installation is not tied to a single entity https://gateway-api.sigs.k8s.io/guides/crd-management/#who-should-manage-crds This results in multiple entities taking ownership of CRD installation
* infra users
* implementations
* cloud providers
This complicates things for implementations who may not know which version and release of CRDs are installed, so this PR makes watching alpha versioned CRDs optional
* Even Envoy Gateway specific CRDs have been made optional to solve the use case where users want to only configure Gateway API resources
* GRPCRoute is the only exception, which is v1, but has been made optional because it just graduated to v1 in v1.2 but a lot of cloud providers or service mesh implementations have not moved to v1.2
Fixes: …

make watching alpha CRDs optional

---

internal/gatewayapi/envoyextensionpolicy.go
internal/gatewayapi/testdata/custom-filter-order.in.yaml
internal/gatewayapi/testdata/custom-filter-order.out.yaml
internal/gatewayapi/testdata/envoyextensionpolicy-with-wasm-targetrefs.in.yaml
internal/gatewayapi/testdata/envoyextensionpolicy-with-wasm-targetrefs.out.yaml
internal/gatewayapi/testdata/envoyextensionpolicy-with-wasm.in.yaml
internal/gatewayapi/testdata/envoyextensionpolicy-with-wasm.out.yaml
internal/gatewayapi/translator_test.go
release-notes/current.yaml
test/e2e/testdata/wasm-http.yaml
test/e2e/tests/wasm_http.go

Fixes: https://github.com/envoyproxy/gateway/issues/4379

Fix: xds translation failed when wasm http code source configured without sha

---

osv-scanner.toml

* Remove unneeded sections in `osv-scanner.toml`:
* `IgnoredVulns` for `GO-2022-0646` - no longer relevant since it's related to `github.com/aws/aws-sdk-go` package which was removed in #4161.
* `PackageOverrides` for `github.com/containers/storage` - since https://github.com/google/deps.dev/issues/104 is resolved.
* `PackageOverrides` for `sigs.k8s.io/json` - package license is now identified. 
* Use `license.ignore` instead of `license.override` for all MPL-2.0 packages which are approved by CNCF.

ci: cleanup osv-scanner config

---

.github/workflows/release.yaml
tools/make/kube.mk

* the release artifact for `egctl` was being pulled from the `latest` release instead of a binary associated with the release tag

fix egctl release artifacts

---

internal/gatewayapi/runner/runner.go

https://pkg.go.dev/github.com/go-logr/zapr#hdr-Implementation_Details
```
V(1) is equivalent to Zap's DebugLevel
```
Now after setting the log level to `default: debug`
I see
```
2024-10-31T01:59:31.138Z	DEBUG	gateway-api	runner/runner.go:176	{"proxy":{"metadata":{"labels":{"gateway.envoyproxy.io/owning-gateway-name":"eg","gateway.envoyproxy.io/owning-gateway-namespace":"default"}},"name":"default/eg","listeners":[{"name":"default/eg/http","address":null,"ports":[{"name":"http-80","protocol":"HTTP","servicePort":80,"containerPort":10080}]}]}}	{"runner": "gateway-api", "infra-ir": "default/eg"}
2024-10-31T01:59:31.138Z	DEBUG	gateway-api	runner/runner.go:187	{"accessLog":{"text":[{"path":"/dev/stdout"}]},"http":[{"name":"default/eg/http","address":"0.0.0.0","port":10080,"metadata":{"kind":"G …
```

fix debug level logging for IR

---

.github/workflows/build_and_test.yaml

xref: https://github.com/envoyproxy/gateway/issues/4572
seperate from https://github.com/envoyproxy/gateway/pull/4550

ci: enable test for dual stack cluster

---

api/v1alpha1/envoygateway_helpers.go
examples/extension-server/cmd/extension-server/main.go
internal/extension/registry/extension_manager.go
internal/gatewayapi/securitypolicy.go
internal/kubernetes/port_forwarder.go
internal/utils/net/port.go
internal/xds/bootstrap/bootstrap.go
test/e2e/tests/ratelimit.go

fixes: https://github.com/envoyproxy/gateway/issues/4597

chore: use net.JoinHostPort

---

test/e2e/testdata/oidc-keycloak.yaml

Fixes: https://github.com/envoyproxy/gateway/issues/4598
Release Notes: no
Old version:
```bash
k -n gateway-conformance-infra logs setup-keycloak-cw75d 
Defaulted container "setup-keycloak" out of: setup-keycloak, wait-for-keycloak (init)
+ /opt/keycloak/bin/kcadm.sh create users -s username=oidcuser -s enabled=true --server http://keycloak --realm master --user admin --password admin
Logging into http://keycloak as user admin of realm master
HTTPS required [invalid_request]
```
New version:
```bash
k -n gateway-conformance-infra exec -it keycloak-cbcd7848f-9nk7b -- bash 
bash-5.1$ /opt/keycloak/bin/kcadm.sh create users -s username=oidcuser -s enabled=true --server http://keycloak --realm master --user admin --password admin
Logging into http://keycloak as user admin of realm master …
```

fix keycloak ipv6 issue

---

internal/gatewayapi/contexts.go
internal/gatewayapi/testdata/httproute-with-multiple-gateways-from-different-ns.in.yaml
internal/gatewayapi/testdata/httproute-with-multiple-gateways-from-different-ns.out.yaml
internal/gatewayapi/testdata/httproute-with-multiple-gateways-from-same-ns.in.yaml
internal/gatewayapi/testdata/httproute-with-multiple-gateways-from-same-ns.out.yaml
release-notes/current.yaml

Fixes: https://github.com/envoyproxy/gateway/issues/4127

fix: Route with multiple parents has incorrect namespace in parentRef status

---

api/v1alpha1/shared_types.go
internal/infrastructure/kubernetes/proxy/testdata/daemonsets/component-level.yaml
internal/infrastructure/kubernetes/proxy/testdata/daemonsets/default.yaml
internal/infrastructure/kubernetes/proxy/testdata/daemonsets/disable-prometheus.yaml
internal/infrastructure/kubernetes/proxy/testdata/daemonsets/override-labels-and-annotations.yaml
internal/infrastructure/kubernetes/proxy/testdata/daemonsets/patch-daemonset.yaml
internal/infrastructure/kubernetes/proxy/testdata/daemonsets/shutdown-manager.yaml
internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-annotations.yaml
internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-concurrency.yaml
internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-extra-args.yaml
internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-image-pull-secrets.yaml
internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-name.yaml
internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-node-selector.yaml
internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-topology-spread-constraints.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/bootstrap.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/component-level.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/disable-prometheus.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/override-labels-and-annotations.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/patch-deployment.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/shutdown-manager.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-annotations.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-concurrency.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-empty-memory-limits.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-extra-args.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-image-pull-secrets.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-name.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-node-selector.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-topology-spread-constraints.yaml

[release/v1.1] bump envoy

---

release-notes/v1.1.3.yaml
site/content/en/news/releases/notes/v1.1.3.md
site/layouts/shortcodes/helm-version.html
site/layouts/shortcodes/yaml-version.html

[release/v1.1] release v1.1.3

---

site/layouts/shortcodes/helm-version.html
site/layouts/shortcodes/yaml-version.html

Wait until the v1.1.3 binary exists
Fixes: https://github.com/envoyproxy/gateway/issues/4614

Move v1.1 docs tag to v1.1.2

---

OWNERS
site/content/en/contributions/CODEOWNERS.md
site/content/en/news/releases/_index.md
site/content/en/v0.2/contributions/CODEOWNERS.md
site/content/en/v0.2/contributions/RELEASING.md
site/content/en/v0.3/contributions/CODEOWNERS.md
site/content/en/v0.3/contributions/RELEASING.md
site/content/en/v0.4/contributions/CODEOWNERS.md
site/content/en/v0.4/contributions/RELEASING.md
site/content/en/v0.5/contributions/CODEOWNERS.md
site/content/en/v0.5/contributions/RELEASING.md
site/content/en/v0.6/contributions/CODEOWNERS.md
site/content/en/v0.6/contributions/RELEASING.md
site/content/zh/contributions/CODEOWNERS.md
site/content/zh/contributions/RELEASING.md
site/content/zh/news/releases/_index.md

Removes myself from the active maintainers list and also updates any references to my previous GitHub username. 
It's been a good while since I've had any bandwidth to devote to contributing to or actively keeping up with events and reviews and I don't anticipate that I will be active enough to be considered a maintainer here any time soon either. I might still chime in with stray thoughts on the occasional PR or issue. 
Not sure about the docs ones. Didn't want to break any existing guides or historical references so other than renaming my username I left the older ones untouched.

remove myself from maintainers

---

test/e2e/tests/wasm_oci.go

Fixes https://github.com/envoyproxy/gateway/issues/4607
Tested locally with `IP_FAMILY=ipv6` 
```
utils.go:53: 2024-11-04T07:08:40.965216457Z: waiting for gateway-conformance-infra/[map[app:oci-registry]] to be Running...
{"stream":"Step 1/3 : FROM scratch"}
{"stream":"\n"}
{"stream":" ---\u003e \n"}
{"stream":"Step 2/3 : LABEL org.opencontainers.image.title test-wasm"}
{"stream":"\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 7dc4fa8137a0\n"}
{"stream":"Step 3/3 : COPY plugin.wasm ./"}
{"stream":"\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e b24ec92be1ee\n"}
{"aux":{"ID":"sha256:b24ec92be1ee0300dd2d9d94a6a69cc3d18692cc682070a754a7ff3c69bf584d"}}
{"stream":"Successfully built b24ec92be1ee\n"}
{"stream":"Successfully tagged …
```

fix: wasm oci image source e2e test failed when IP_FAMILY=ipv6

---

test/e2e/tests/oidc-backendcluster.go
test/e2e/tests/oidc.go

Delete and recreate SecurityPolicy to force repushing xDS to Envoy to recover from the OIDC test failure. This is just a workaround to reduce the time of e2e test due to  the failed OIDC test. We still need to investage the root cause and fix it.
Related issue: https://github.com/envoyproxy/gateway/issues/3898

workaroud for the flaky oidc e2e test

---

.github/workflows/release.yaml

Fix the `without_v_release_tag` release tag.
Tested locally:
```
➜  gateway git:(fix-release-build) ✗ export  GITHUB_REF=refs/tags/v1.2.0             
➜  gateway git:(fix-release-build) ✗ without_v_release_tag=$(echo ${GITHUB_REF##*/v})
➜  gateway git:(fix-release-build) ✗ echo $without_v_release_tag                     
1.2.0
```

fix release build

---

site/content/en/latest/tasks/traffic/failover.md

Fixes: https://github.com/envoyproxy/gateway/issues/4501

docs: Active Passive Failover

---

internal/utils/protocov/protocov.go
internal/xds/translator/accesslog.go
internal/xds/translator/authorization.go
internal/xds/translator/basicauth.go
internal/xds/translator/cluster.go
internal/xds/translator/cors.go
internal/xds/translator/extauth.go
internal/xds/translator/extproc.go
internal/xds/translator/fault.go
internal/xds/translator/healthcheck.go
internal/xds/translator/jwt.go
internal/xds/translator/listener.go
internal/xds/translator/listener_test.go
internal/xds/translator/local_ratelimit.go
internal/xds/translator/oidc.go
internal/xds/translator/proxy_protocol.go
internal/xds/translator/ratelimit.go
internal/xds/translator/testdata/in/xds-ir/accesslog-without-format.yaml
internal/xds/translator/testdata/in/xds-ir/accesslog.yaml
internal/xds/translator/testdata/out/xds-ir/accesslog-without-format.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/accesslog.listeners.yaml
internal/xds/translator/tracing.go
internal/xds/translator/translator.go
internal/xds/translator/wasm.go

Fix https://github.com/envoyproxy/gateway/issues/4504
(cherry picked from commit 05817fcc42d803caba384d54eee6d9f0c562c1ef)

[release/v1.1] fix: validate proto messages before converting them to anypb.Any (#4499)

---

site/content/en/news/releases/_index.md
site/content/en/news/releases/notes/v1.2.0.md
site/content/en/news/releases/v1.2.md

* Updates Release Notes on Website with Release Note content from https://github.com/envoyproxy/gateway/blob/main/release-notes/v1.2.0.yaml
* Updated Release News with the release summary
* Updated the Release Schedule matrix

Release News for v1.2.0

---

internal/provider/kubernetes/filters.go
test/e2e/testdata/direct-response.yaml
test/e2e/tests/direct-response.go
test/e2e/tests/response-override.go

body is an optional field, it may be nil

fix panic in provider when the direct response body is nil

---

internal/provider/kubernetes/filters.go
test/e2e/testdata/direct-response.yaml
test/e2e/tests/direct-response.go
test/e2e/tests/response-override.go

body is an optional field, it may be nil
(cherry picked from commit ad518329bd6025fb56493ff75b39029263de2d02)

[release/v1.2] fix panic in provider when the direct response body is nil (#4647)

---

site/content/en/contributions/design/metadata.md

The docs mention the wrong namespace for annotations. The namespace is set here I think: https://github.com/guydc/gateway/blob/e54b00f4e227e0e7d65bc6dbecf5b6d1f991dd7e/internal/gatewayapi/route.go#L35
It might be that i misunderstood the documentation and i'm mixing things up. If so, ill be happy to write a separate section with this example.
Small correction to the docs.
It adds the correct namespace, and a small example of how to use it.
-

Docs: fix incorrect namespace mention

---

test/e2e/tests/eg_upgrade.go

Update the `lastVersionTag` in the upgrade test to reflect the latest prior release. 

update the lastVersionTag of the upgrade test

---

api/v1alpha1/authorization_types.go
site/content/en/docs/api/extension_types.md
site/content/en/latest/api/extension_types.md
site/content/en/v1.2/api/extension_types.md
site/content/zh/latest/api/extension_types.md

Unhide JWT calim based authz in the API doc as it's already been implemented.

docs: unhide jwt claim authz

---

tools/hack/create-cluster.sh

xref: https://github.com/envoyproxy/gateway/issues/4572

chore: dnsSearch on kind cluster

---

site/content/en/docs/api/extension_types.md
site/content/en/latest/api/extension_types.md
site/content/en/v1.2/api/extension_types.md
site/content/zh/latest/api/extension_types.md
tools/make/docs.mk

fixes: https://github.com/envoyproxy/gateway/issues/4710

docs: fix api doc

---

test/e2e/testdata/httproute-to-backend-ip.yaml
test/e2e/testdata/tlsroute-to-backend-ip.yaml
test/e2e/tests/httproute_with_backend.go
test/e2e/tests/tlsroute_with_backend.go
test/e2e/tests/utils.go

Fixed v4 cluster IP will not working on IPv6 first cluster

e2e: fix EnvoyGatewayBackend/TLSRouteBackendIP test not working on IPv6 first cluster

---

api/v1alpha1/accesslogging_types.go
site/content/en/latest/api/extension_types.md
site/content/zh/latest/api/extension_types.md

this seems wrong for a long time.

docs: fix wrong description on ALSEnvoyProxyAccessLog

---

.github/workflows/docs.yaml

dont run docs workflows on release branches

---

site/content/en/docs/tasks/operations/customize-envoyproxy.md
site/content/en/latest/tasks/operations/customize-envoyproxy.md
site/content/en/v1.2/tasks/operations/customize-envoyproxy.md

Enhances the existing docs.
Fixes #4742

docs: added JSONPatch example for modifying Bootstrap config using the EnvoyProxy resource

---

.github/workflows/build_and_test.yaml

Reverts envoyproxy/gateway#4732
This is blocking CI: https://github.com/envoyproxy/gateway/actions/runs/12025151771/job/33521814999?pr=4754

Revert "build(deps): bump codecov/codecov-action from 4.6.0 to 5.0.2"

---

internal/provider/kubernetes/status_updater.go
release-notes/current.yaml

Reverts envoyproxy/gateway#4337
Fixes: https://github.com/envoyproxy/gateway/issues/4685
Release Note: Yes
To avoid regression of the bug fixed by #4337, a temporary buffer has been added to store events received before the Updater is enabled.
These events will be sent to the update channel once the Updater is enabled.
Tested the fix in my local env:
```bash
➜  k -n envoy-gateway-system logs envoy-gateway-7f7d68bd-q74m6 |grep "status update"                        
2024-11-26T05:56:03.461Z        INFO    provider        kubernetes/status_updater.go:185        received a status update while disabled, storing for later      {"runner": "provider", "event": {
"name":"ha-gateway","namespace":"gateway-upgrade-infra"}}
2024-11-26T05:56:03.764Z        INFO    provider …
```

Fix: frequent 503 errors when connecting to a Service experiencing high Pod churn

---

internal/infrastructure/common/proxy_args.go
internal/infrastructure/kubernetes/proxy/resource_provider_test.go
internal/infrastructure/kubernetes/proxy/testdata/deployments/ipv6.yaml
internal/xds/bootstrap/bootstrap.go
internal/xds/bootstrap/bootstrap_test.go
internal/xds/bootstrap/testdata/render/ipv6.yaml

xref: https://github.com/envoyproxy/gateway/issues/4572

xds: use `::1`  if IPFamily is IPv6 on admin server

---

internal/provider/kubernetes/status_updater.go

* use a waitGroup to synchronize to the `Send` method that the status updater is enabled and ready for updates

use a waitGroup instead of an enabled channel in the status updater

---

internal/cmd/egctl/testdata/translate/out/jwt-single-route-single-match-to-xds.all.json
internal/cmd/egctl/testdata/translate/out/jwt-single-route-single-match-to-xds.all.yaml
internal/cmd/egctl/testdata/translate/out/jwt-single-route-single-match-to-xds.listener.yaml
internal/xds/translator/jwt.go
internal/xds/translator/testdata/out/xds-ir/authorization-jwt-claim.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/authorization-jwt-scope.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/custom-filter-order.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/jwt-custom-extractor.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/jwt-multi-route-multi-provider.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/jwt-multi-route-single-provider.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/jwt-optional.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/jwt-ratelimit.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/jwt-single-route-single-match.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/securitypolicy-with-oidc-jwt-authz.listeners.yaml
release-notes/current.yaml

The current jwt implementation in the SecurityPolicy uses a default retry policy. While this default is reasonable from the perspective of a single Envoy, it could potentially overwhelm the JWKS server if multiple Envoys and SecurityPolicy instances are configured with the same JWKS.
This default retry policy can be removed as EG already enables https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#extensions-filters-http-jwt-authn-v3-jwksasyncfetch with a failed_refetch_duration of 1s, which will refetch the jwks every 1s if failed.
Fixes #4791

fix: remove the default retry policy for jwks fetch

---

charts/gateway-helm/crds/gatewayapi-crds.yaml
examples/extension-server/go.mod
examples/extension-server/go.sum
go.mod
go.sum

Relates Notes in https://github.com/kubernetes-sigs/gateway-api/releases/tag/v1.2.1

[release/v1.2] Bump to Gateway API v1.2.1

---

go.mod
go.sum

Use the latest commit of github.com/golang/groupcache to fix the license check.

fix license check

---

charts/gateway-helm/crds/gatewayapi-crds.yaml
examples/extension-server/go.mod
examples/extension-server/go.sum
go.mod
go.sum
test/e2e/tests/eg_upgrade.go

Manually fix https://github.com/envoyproxy/gateway/pull/4826

chore: Bump gateway api to 1.2.1

---

site/content/en/docs/tasks/extensibility/extension-server.md
site/content/en/latest/tasks/extensibility/extension-server.md

fix: Fix example documentation to include all the expected privileges for extension server policies

---

osv-scanner.toml

Fix license scan by overriding unidentified license of `github.com/golang/groupcache`. Also opened an issue in [deps.dev](https://github.com/google/deps.dev/issues/119).

ci: fix license scan

---

osv-scanner.toml

Fix license scan by removing whitespace in`github.com/golang/groupcache` license override.
Fixes #4885

chore: remove whitespace in osv-scanner config

---

site/content/en/docs/tasks/operations/customize-envoyproxy.md
site/content/en/latest/tasks/operations/customize-envoyproxy.md
site/content/en/v1.2/tasks/operations/customize-envoyproxy.md

- Added documentation for customizing EnvoyProxy IP family configuration
- Added note about cluster requirements for DualStack networking

docs: customize envoyproxy dualstack

---

.github/workflows/license-scan.yml
tools/osv-scanner/license-scan-config.toml

* Fix file name in `--config` arg - I used `yaml` instead of `toml` by mistake.
* Comment out `vulnerability.ignore` flag which was added [here](https://github.com/envoyproxy/gateway/pull/4895) since it's only supported in `osv-scanner` [v1.9.1](https://github.com/google/osv-scanner/releases/tag/v1.9.1). The current `osv-scanner-action` is `v1.9.0`. I opened an [issue](https://github.com/google/osv-scanner-action/issues/51) to release a new version.
* Add license override for `golang.org/x/crypto` since it doesn't appear yet on [deps.dev](https://deps.dev/).
Opened an [issue](https://github.com/google/deps.dev/issues/120).
BTW the workflow didn't fail because `127` status code is redirected to `0` when running inside osv-scanner container.
I opened …

chore: fix osv license scan config and add license override

---

release-notes/v1.1.4.yaml
site/content/en/news/releases/notes/v1.1.4.md
site/layouts/shortcodes/helm-version.html
site/layouts/shortcodes/yaml-version.html

[release/v1.1] release: v1.1.4

---

site/hugo.toml

* Use the same as the envoy proxy and envoy mobile websites
Relates to https://github.com/envoyproxy/envoy-website/issues/273 & https://github.com/envoyproxy/envoy-mobile/issues/2680

docs: Set GA4 ID

---

api/v1alpha1/kubernetes_helpers.go
api/v1alpha1/validation/envoyproxy_validate_test.go

Fix
Some of the test cases in `api/v1alpha1/validation/envoyproxy_validate_test.go` were misleading.
I initially noticed a couple test cases were named "invalid" but they were actually valid scenarios, and were being checked as such with the `expected: true` field in the test table. This was for e.g. `should be invalid when service patch type is empty`
Upon this, also realized there two tests were not testing what they were supposed to be. E.g. `should be invalid when pdb type not set` should be valid, and was only invalid because the test did have the patch type set and did not the patch object, causing the invalid result. The correct thing to test for would be a valid case where `type` is not set, but `patch` is.
Also …

fix: fixing some misleading unit test case names

---

site/content/en/docs/tasks/security/oidc.md
site/content/en/latest/tasks/security/oidc.md
site/content/en/v1.2/tasks/security/oidc.md

Fixes: https://github.com/envoyproxy/gateway/issues/4867

docs: how to connect to an OIDC provider with a self-signed cert

---

test/e2e/testdata/basic-auth.yaml
test/e2e/tests/basic_auth.go

e2e: add test case for basic auth

---

internal/provider/kubernetes/filters.go
internal/provider/kubernetes/resource.go
internal/provider/kubernetes/routes.go
internal/provider/kubernetes/routes_test.go
release-notes/current.yaml

Currently, EG accumulates multiple copies of extension filters (one for each reference). As a result, multiple matching filters can be found when processing routes, leading to the reported issue. 
Fixes #4989

fix: store one copy of HTTPRoute Extension Filters

---

internal/infrastructure/kubernetes/proxy/resource_provider.go
internal/infrastructure/kubernetes/proxy/resource_provider_test.go
internal/infrastructure/kubernetes/proxy/testdata/services/dualstack.yaml
internal/infrastructure/kubernetes/proxy/testdata/services/ipv4-singlestack.yaml
internal/infrastructure/kubernetes/proxy/testdata/services/ipv6-singlestack.yaml

fix: explicitly set ip family and family policy in gateway spec

---

api/v1alpha1/healthcheck_types.go
site/content/en/latest/api/extension_types.md
site/content/zh/latest/api/extension_types.md

Explain the "panic mode" where failed endpoints exceeds 50% as users were asking why requests were sent to unhealth endpoints.

docs: explain panic mode

---

internal/infrastructure/kubernetes/proxy/testdata/deployments/ipv6.yaml
internal/xds/bootstrap/bootstrap.yaml.tpl
internal/xds/bootstrap/testdata/render/ipv6.yaml

Bug fix.
Based on the [envoy docs](https://www.envoyproxy.io/docs/envoy/v1.22.11/api-v3/config/core/v3/address.proto#envoy-v3-api-field-config-core-v3-socketaddress-ipv4-compat) the `ipv4_compat` flag must be set anytime an envoy proxy is required to respond to IPv4 requests when the listening address is defined as `::`. There are two cases when this is required with the current gateway implementation: DualStack gateway and SingleStack IPv6 gateway on a DualStack IPv4-first cluster. The latter case is not handled without this, or a similar, change.
Reviewing a relevant Envoy proxy [PR](https://github.com/envoyproxy/envoy/pull/23616/files), this change should be safe to keep for SingleStack IPv6 config on a SingleStack …

fix: enable ipv4 compat mode for dual stack cluster support

---

internal/infrastructure/kubernetes/proxy/resource_provider.go
internal/infrastructure/kubernetes/ratelimit/resource_provider.go

This is no longer needed after
https://github.com/envoyproxy/gateway/pull/2816 was merged
Relates to https://github.com/envoyproxy/gateway/pull/4983#discussion_r1902269949

dont reset replicas when hpa is set

---

internal/xds/translator/session_persistence.go
internal/xds/translator/testdata/in/xds-ir/http-route-session-persistence.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-session-persistence.listeners.yaml

Fixes a null ptr exception when the cookie ttl is nil but was being accessed without checking if its valid or not

fix: check before setting cookie TTL in sessionPersistence

---

site/content/en/latest/api/extension_types.md
site/content/zh/latest/api/extension_types.md
tools/crd-ref-docs/templates/type.tpl

fixes: https://github.com/envoyproxy/gateway/issues/5028
only support maker like `	// +kubebuilder:default=1024`

docs: show API default value

---

internal/gatewayapi/clienttrafficpolicy.go
internal/gatewayapi/testdata/clienttrafficpolicy-invalid-settings.in.yaml
internal/gatewayapi/testdata/clienttrafficpolicy-invalid-settings.out.yaml
release-notes/current.yaml

* Return a 503 response when a ClientTrafficPolicy translation fails for HTTP/GRPC routes.
* Route client traffic to an empty dummy cluster when a ClientTrafficPolicy translation fails for TCP routes.
Implements: #4153

Translation: return 500 when CTP translation fails

---

test/e2e/testdata/authorization-client-ip-trusted-cidrs.yaml
test/e2e/tests/authorization_client_ip.go

e2e: fix trusted cidr e2e tests for ipv6

---

charts/gateway-addons-helm/dashboards/envoy-gateway-global.json
site/content/en/docs/tasks/observability/gateway-exported-metrics.md
site/content/en/latest/tasks/observability/gateway-exported-metrics.md
test/helm/gateway-addons-helm/default.out.yaml
test/helm/gateway-addons-helm/e2e.out.yaml

Update Grafana dashboard and exported metrics doc for watchable_panics_recovered_total
This PR updates the Grafana Dashboard to include the newly introduced metric watchable_panics_recovered_total, which tracks the total number of panics recovered in the Envoy Gateway system. It also updates the Exported Metrics Documentation to reflect the new metric and provide users with guidance on its use.
fix #4728

update grafana dashboard and exported metrics doc for watchable_panics_recovered_total

---

api/v1alpha1/envoygateway_types.go
api/v1alpha1/zz_generated.deepcopy.go
internal/cmd/certgen.go
site/content/en/latest/api/extension_types.md
site/content/zh/latest/api/extension_types.md

it was not implemented previously and instead must be specified as a cmd line arg for `certgen`

rm overwriteControlPlaneCerts from the EnvoyGateway API

---

api/v1alpha1/ext_proc_types.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml
internal/gatewayapi/envoyextensionpolicy.go
internal/gatewayapi/testdata/envoyextensionpolicy-with-extproc-with-backendtlspolicy.in.yaml
internal/gatewayapi/testdata/envoyextensionpolicy-with-extproc-with-backendtlspolicy.out.yaml
internal/ir/xds.go
internal/xds/translator/extproc.go
internal/xds/translator/testdata/in/xds-ir/ext-proc.yaml
internal/xds/translator/testdata/out/xds-ir/ext-proc.listeners.yaml
site/content/en/latest/api/extension_types.md
site/content/zh/latest/api/extension_types.md

Adds a new API for external processor 
This adds AllowModeOverride boolean config
to the external processing config.
N/A

api: adds AllowModeOverride for extproc

---

api/v1alpha1/tracing_types.go
api/v1alpha1/zz_generated.deepcopy.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
site/content/en/latest/api/extension_types.md
site/content/zh/latest/api/extension_types.md
test/cel-validation/envoyproxy_test.go

xref: https://github.com/envoyproxy/gateway/issues/5089

api: allow tracing sampleRate smaller than 1%

---

site/content/en/latest/tasks/traffic/response-compression.md

doc: response compression

---

site/content/en/latest/tasks/security/apikey-auth.md

* docs: add api key auth instructions
Fixes #5047

docs: add api key auth instructions

---

site/content/en/docs/tasks/extensibility/ext-proc.md
site/content/en/docs/tasks/security/ext-auth.md
site/content/en/docs/tasks/security/oidc.md
site/content/en/latest/tasks/extensibility/ext-proc.md
site/content/en/latest/tasks/security/ext-auth.md
site/content/en/latest/tasks/security/oidc.md
site/content/en/v1.2/tasks/extensibility/ext-proc.md
site/content/en/v1.2/tasks/security/ext-auth.md
site/content/en/v1.2/tasks/security/oidc.md

adds whats left from https://github.com/envoyproxy/gateway/pull/4868
deleted the sectionName in these examples because the Service spec does not define a port `Name`

docs: rm sectionName from some of the examples

---

.github/workflows/osv-scanner.yml

`osv-scanner-reusable-pr.yml` should be called when workflow is triggered from PR so scan will fail only if new vulnerabilities were introduced. It was renamed by accident to `osv-scanner-reusable.yml` [here](https://github.com/envoyproxy/gateway/pull/4956).

ci(fix): osv-scanner PR mode

---

examples/standalone/quickstart-containers.yaml
site/content/en/latest/tasks/operations/standalone-deployment-mode.md

This PR creates an instruction in the documentation about running Envoy Gateway Standalone in a container environment
Fixes #5054

wip: docs: add standalone in container instruction

---

release-notes/v1.3.0-rc.1.yaml
site/content/en/news/releases/notes/v1.3.0-rc.1.md

[release/v1.3] fix 1.3.0-rc.1 release note

---

internal/gatewayapi/backendtrafficpolicy.go
internal/gatewayapi/clustersettings.go
internal/gatewayapi/testdata/backendtrafficpolicy-with-retries.in.yaml
internal/gatewayapi/testdata/backendtrafficpolicy-with-retries.out.yaml

Fixes: https://github.com/envoyproxy/gateway/issues/5147

fail validation if baseInterval is 0s

---

site/hugo.toml
site/layouts/shortcodes/helm-version.html
site/layouts/shortcodes/yaml-version.html

fix shortcodes and version location

---

site/content/en/docs/tasks/security/apikey-auth.md
site/content/en/latest/tasks/security/apikey-auth.md
site/content/en/v1.3/tasks/security/apikey-auth.md

the namespace of the secret was set to `envoy-gateway-system` and was set in a different namespace than the SecurityPolicy
Fixes: https://github.com/envoyproxy/gateway/issues/5245

docs: fix config for api key

---

site/content/en/contributions/CONTRIBUTING.md
site/content/en/latest/tasks/traffic/http-request-mirroring.md

docs: fixed the docs for multiple request mirrorfilters and other typos
This PR contains the required documentation updates for the `Multiple HTTPRequestMirrorFilters` 
Fixes #5205

docs: fixed the documentation for multiple request mirrorfilter docs 

---

api/v1alpha1/envoyproxy_types.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
site/content/en/latest/api/extension_types.md
site/content/en/latest/tasks/operations/customize-envoyproxy.md
site/content/zh/latest/api/extension_types.md

Documentation for Merge Option in Custom bootstrap for EnvoyProxy
This PR contains the requested documentation updates for the custom bootstrap config for envoyproxy along with the `Merge` option
Fixes #2545
> Note: Had to previous PR due to some issues.

docs: added BootstrapConfig for Merge Option

---

api/v1alpha1/envoypatchpolicy_types.go
site/content/en/latest/api/extension_types.md
site/content/zh/latest/api/extension_types.md

Fixes: https://github.com/envoyproxy/gateway/issues/5200

docs: add secret enum in envoyPatchPolicy

---

site/content/en/latest/tasks/security/tls-cert-manager.md

Documentation change for the `cert-manager` installation using helm
This PR contains the updated helm installation docs for cert-manager and other changes.
Fixes #4781

docs: updated docs for cert-manager installation

---

.github/PULL_REQUEST_TEMPLATE.md
site/content/en/contributions/DEVELOP.md

Documentation changes
This contains the steps to perform when raising a PR in the repository. 
Fixes #5346

docs: updated the developer guide

---

internal/gatewayapi/securitypolicy.go
internal/gatewayapi/testdata/backendtrafficpolicy-dns-lookup-family.out.yaml
internal/gatewayapi/testdata/securitypolicy-with-extauth-backendref.in.yaml
internal/gatewayapi/testdata/securitypolicy-with-extauth-backendref.out.yaml
internal/xds/translator/testdata/in/xds-ir/ext-auth-backend.yaml
internal/xds/translator/testdata/out/xds-ir/ext-auth-backend.clusters.yaml
release-notes/current.yaml

Fixes: https://github.com/envoyproxy/gateway/issues/5371

fix: backendSettings for extAuth

---

cmd/envoy-gateway/main.go
internal/cmd/certgen.go
internal/cmd/server.go

Refactors cmd packages
Previously, the context was locally created inside the subcommand, and the context set to the cobra.Cmd was ignored. This made it difficult to use the root command as a library since the only way to cancel the command is sending the real OS singals hence it was impossible to write a unit tests around it.

Propagate contexts from root to subcommands

---

api/v1alpha1/ext_proc_types.go
internal/ir/xds.go
internal/xds/translator/extproc.go
site/content/en/latest/api/extension_types.md

`FULL_DUPLEX_STREAMED` is already a supported [processing_mode](https://github.com/envoyproxy/envoy/blob/60aed1c0ae520ed4e1d828c998ae961b4314542c/api/envoy/extensions/filters/http/ext_proc/v3/processing_mode.proto#L82-L111), and was asked to be supported in our project (xref: https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/388). I am currently using the patch policy to jsonPatch the field in, however it might be a simpler to expose the field via the more robust `EnvoyExtensionPolicy`
Fixes #

api: add full_duplex_streamed enum to ExtProcBodyProcessingMode

---

site/content/en/contributions/design/fuzzing.md

docs: add fuzz testing design document
Fixes #5426 

docs: add fuzz testing design document.

---

site/content/en/contributions/design/backend-traffic-policy.md

As of version v1.3.1, `BackendTrafficPolicy.spec.targetRef` does not contain any `namespace` field.
* "fix: fix docs"
As of version v1.3.1, BackendTrafficPolicy.spec.targetRef does not contain a namespace field.
This PR updates the documentation and API references to clarify this behavior.

docs: update backend-traffic-policy.md(remove targetRef.namespace)

---

go.mod
internal/cmd/egctl/translate.go
test/fuzz/ir_fuzz_test.go
tools/make/env.mk
tools/make/golang.mk

Implement fuzzers to target translateGatewayAPIToIR. 
- Use [go-fuzz-headers](https://github.com/AdaLogics/go-fuzz-headers) to generate pseudo-random Resources structs.
Fixes #5428

test: add fuzzers for `egctl.translateGatewayAPIToIR`

---

internal/gatewayapi/runner/runner.go
internal/gatewayapi/runner/runner_test.go

fix: permission error on startWasmCache
Previously, the cache directory for Wasm binaries is hardcoded to /var/lib/eg/wasm but it's not writable without root permission on macOS. This fixes it by making it default to ~/.eg/wasm.

fix: Wasm cache directory on macOS host

---

internal/provider/file/resources.go
internal/provider/file/resources_test.go

Enhances error message with file provider.
Previously, the file provider doesn't log any information about which file is wrong, so this fixes it and adds the missing test coverage.

Make file provider errors useful

---

test/fuzz/oss_fuzz_build.sh

Fixes #5492
This script will be referred from our `Dockerfile` in the **oss-fuzz** repository to build the Fuzzers in the **oss-fuzz** infra.
For example, take a look at **ArgoCD** integration here https://github.com/google/oss-fuzz/blob/master/projects/argo/build.sh
CC: @arkodg @nareddyt

test: Implement build script for oss-fuzz infra.

---

internal/provider/kubernetes/indexers.go
internal/provider/kubernetes/predicates_test.go

Includes any mirrored backendRefs in the httproute index
Fixes #5495

fix: check for mirror backendRef in httproute index

---

examples/envoy-ext-auth/Dockerfile
examples/envoy-ext-auth/go.mod
examples/extension-server/go.mod
examples/grpc-ext-proc/Dockerfile
examples/grpc-ext-proc/go.mod
examples/preserve-case-backend/Dockerfile
examples/preserve-case-backend/go.mod
examples/static-file-server/Dockerfile
examples/static-file-server/go.mod
go.mod
site/go.mod

xref: https://github.com/envoyproxy/gateway/pull/5510/files
```console
tools/hack/bump-golang.sh 1.24.0 1.24.1
```

chore: bump to go 1.24.1

---

internal/provider/runner/runner.go

fix: race condition
There's a race condition in provider/runner.Start where it writes values into `err` variable from multiple goroutines.
Fixes #5505

Fixes race condition on provider/runner

---

internal/gatewayapi/filters.go
internal/gatewayapi/testdata/httproute-with-header-filter-invalid-headers.in.yaml
internal/gatewayapi/testdata/httproute-with-header-filter-invalid-headers.out.yaml
internal/gatewayapi/testdata/httproute-with-response-header-filter-invalid-headers.in.yaml
internal/gatewayapi/testdata/httproute-with-response-header-filter-invalid-headers.out.yaml

Fix: https://github.com/envoyproxy/gateway/issues/5182

fix: host header should not be allowed to modify

---

site/assets/scss/_styles_project.scss

* docs: fix rendering of .td-content>h2 titles, which are overlapping with preceding sections, thus making links non-clickable.
This is impacting all pages where the h2 block is overlapping a links, e.g https://gateway.envoyproxy.io/latest/tasks/traffic/backend/, https://gateway.envoyproxy.io/latest/tasks/traffic/client-traffic-policy/, https://gateway.envoyproxy.io/latest/tasks/security/backend-tls/
See this video to better understand it (I first refresh the page, then try to click/double-click the link, which shows the title being highlighted):
https://github.com/user-attachments/assets/b4c029be-f32c-4c1a-8eba-2f16797a0ed8
This fixes non-clickable links due to the title overlapping (with higher z-index)
**Which …

Update CSS to address non-clickable links before td-content>h2

---

charts/gateway-helm/README.md
charts/gateway-helm/templates/envoy-gateway-service.yaml
charts/gateway-helm/values.tmpl.yaml
release-notes/current.yaml
site/content/en/latest/install/gateway-helm-api.md
test/helm/gateway-helm/service-customization.in.yaml
test/helm/gateway-helm/service-customization.out.yaml

feature: opt in control plane zone aware load balancing

---

site/content/en/latest/tasks/traffic/grpc-routing.md

Documentation update
Update GRPCRoute examples to use gateway.networking.k8s.io/v1 API version
Fixes #

docs: update GRPCRoute apiVersion to v1 in grpc-routing guide

---

test/benchmark/suite/render.go
test/benchmark/suite/report.go
test/benchmark/suite/suite.go

We used to collect metrics and profiles at the end of one benchmark test, the result may not be accurate, becasue the metrics like 
- `process_resident_memory_bytes` and `container_memory_working_set_bytes` are instant value, they only reflect the status at the time of our promql request, same as pprof profiles.
- `process_cpu_seconds_total` and `container_cpu_usage_seconds_total` are cumulative value, we should use `rate()` to get its value during a time range
So this PR samples metrics and profiles at test runtime, and report the min/max/mean of mem and cpu during the test run (ditto for pprof profiles), in order to make the benchmark result more accurate and trustworthy.
ref: #4516, …

benchmark: more accurate metrics and profiles

---

site/content/en/v1.3/tasks/traffic/session-persistence.md

Refer https://github.com/envoyproxy/gateway/pull/5567#issuecomment-2743349376
Fixes #

docs: add session persistence for v1.3

---

internal/provider/kubernetes/kubernetes.go
internal/provider/kubernetes/kubernetes_test.go

Fixes flaky k8s provider test by disabling health probe listener.
Fixes #5601

fix: flaky k8s provider test

---

site/content/en/latest/boilerplates/o11y_prerequisites.md
site/content/en/latest/tasks/observability/proxy-metric.md

docs: enhance Proxy Metrics documentation.

---

site/content/en/v1.2/boilerplates/o11y_prerequisites.md
site/content/en/v1.2/tasks/observability/proxy-metric.md
site/content/en/v1.3/boilerplates/o11y_prerequisites.md
site/content/en/v1.3/tasks/observability/proxy-metric.md

In PR #5568, the documentation for `Proxy Metrics` has been enhanced. 
This PR copies the same documentation to the `v1.3` and `v1.2` folders, as these versions also follow the same configuration steps for `Proxy Metrics`.

docs: copy latest observability documentation enhancements to v1.2 and v1.3

---

internal/gatewayapi/route.go
internal/gatewayapi/testdata/backendtlspolicy-serviceimport-target.in.yaml
internal/gatewayapi/testdata/backendtlspolicy-serviceimport-target.out.yaml
release-notes/current.yaml

ServiceImport `appProtocol` is currently not honored.
This PR add support for the user to specify `appProtocol = kubernetes.io/h2c` to configure xDS in H2 mode.
As discussed in https://github.com/envoyproxy/gateway/issues/5485#issuecomment-2737809512, we will **not** support the legacy `grpc` value. Only `kubernetes.io/h2c` is supported for `ServiceImport`. 
No changes are made to pre-existing behavior for `Service` `appProtocol` parsing.
Fixes https://github.com/envoyproxy/gateway/issues/5485

Support ServiceImport AppProtocol parsing

---

examples/envoy-ext-auth/Dockerfile
examples/envoy-ext-auth/go.mod
examples/extension-server/go.mod
examples/grpc-ext-proc/Dockerfile
examples/grpc-ext-proc/go.mod
examples/preserve-case-backend/Dockerfile
examples/preserve-case-backend/go.mod
examples/static-file-server/Dockerfile
examples/static-file-server/go.mod
go.mod
site/go.mod

xref: https://github.com/envoyproxy/gateway/actions/runs/14369743939/job/40290456459

chore: bump golang to 1.24.2

---

internal/provider/kubernetes/controller.go
internal/provider/kubernetes/predicates.go

xref: https://github.com/envoyproxy/gateway/issues/5695

provider: add missing predicates

---

site/layouts/partials/version-banner.html

docs: add tips for /latest

---

api/v1alpha1/shared_types.go
api/v1alpha1/validation/envoygateway_validate.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
internal/infrastructure/kubernetes/proxy/resource_provider_test.go
internal/infrastructure/kubernetes/proxy/testdata/deployments/component-level.yaml
release-notes/current.yaml
site/content/en/latest/api/extension_types.md

Support setting log level to `trace` for the Envoy Proxy fleet. This is often required for debugging purposes.

chore: support trace log level

---

test/fuzz/oss_fuzz_build.sh
test/fuzz/xds_fuzz_test.go

Adds an additional fuzzer without using the go-fuzz-headers library.

test: add a fuzzer without using /go-fuzz-headers

---

test/fuzz/oss_fuzz_build.sh
test/fuzz/xds_fuzz_test.go

To test the oss-fuzz integration, a temporary bug sumulator fuzzer is added.

test: add an error simulator fuzzer.

---

internal/xds/translator/ratelimit.go
internal/xds/translator/testdata/out/xds-ir/jwt-ratelimit.routes.yaml
internal/xds/translator/testdata/out/xds-ir/ratelimit-custom-domain.routes.yaml
internal/xds/translator/testdata/out/xds-ir/ratelimit-disable-headers.routes.yaml
internal/xds/translator/testdata/out/xds-ir/ratelimit-endpoint-stats.routes.yaml
internal/xds/translator/testdata/out/xds-ir/ratelimit-global-shared.routes.yaml
internal/xds/translator/testdata/out/xds-ir/ratelimit-headers-and-cidr.routes.yaml
internal/xds/translator/testdata/out/xds-ir/ratelimit-sourceip.routes.yaml
internal/xds/translator/testdata/out/xds-ir/ratelimit.routes.yaml

Revert https://github.com/envoyproxy/gateway/pull/5072
Some existing users may choose to keep using an old version of envoy while upgrading to new version of Envoy Gateway. To maintain compatibility, we're reverting this change so that rate limit configuration continues to work with older Envoy versions.
We can revisit this in a few versions, once we're confident that older Envoy versions are no longer in use.

chore: revert ratelimit per-rout config

---

site/content/en/latest/tasks/traffic/http-redirect.md
site/content/en/v1.3/tasks/traffic/http-redirect.md

Add a section to describe how to forcibly redirect all http requests to https.

docs: Add force http redirect section

---

charts/gateway-helm/README.md
charts/gateway-helm/templates/_helpers.tpl
charts/gateway-helm/values.tmpl.yaml
site/content/en/latest/install/gateway-helm-api.md
test/helm/gateway-helm/certgen-args.out.yaml
test/helm/gateway-helm/certjen-custom-scheduling.out.yaml
test/helm/gateway-helm/control-plane-with-pdb.out.yaml
test/helm/gateway-helm/default-config.out.yaml
test/helm/gateway-helm/deployment-custom-topology.out.yaml
test/helm/gateway-helm/deployment-images-config.out.yaml
test/helm/gateway-helm/deployment-priorityclass.out.yaml
test/helm/gateway-helm/deployment-securitycontext.out.yaml
test/helm/gateway-helm/envoy-gateway-config.out.yaml
test/helm/gateway-helm/global-images-config.out.yaml
test/helm/gateway-helm/horizontal-pod-autoscaler.out.yaml
test/helm/gateway-helm/service-customization.out.yaml

Adds the ability to enable extension APIs with the helm chart

feat(helm): Add management of extensionApis

---

test/benchmark/suite/report.go

fix: benchmarck sample metrics errors
In https://github.com/envoyproxy/gateway/actions/runs/14575101896/job/40880168538?pr=5780 I saw strange error messages with many wrapped nil errors ` %!w(<nil>)`

fix: benchmark sample metrics errors

---

internal/xds/translator/route.go
internal/xds/translator/testdata/in/xds-ir/retry.yaml
internal/xds/translator/testdata/out/xds-ir/retry.routes.yaml
release-notes/current.yaml

- When retryOn is set to an empty struct, existing defaults work as before.
- When users customize retryOn and leave retryOn.httpStatusCodes unset, the xds retriableStatusCodes will remain unset.
Fixes #5691

fix: allow users to set empty retriable status codes

---

examples/kubernetes/ext-auth-grpc-service.yaml

examples: fix deprecated interface

fix: ext auth example used a deprecated interface

---

internal/metrics/register.go
internal/metrics/restclient/metrics.go
internal/metrics/workqueue/metrics.go
internal/provider/kubernetes/controller.go
test/e2e/tests/metric.go

This PR introduces additional metrics to improve observability around the Envoy Gateway, specifically focusing on the REST client and the workqueue.
Motivation
There are currently several issues that limit our ability to effectively monitor and troubleshoot the system:
Lack of Metrics: The limited set of existing metrics makes it difficult to gain insights into the performance and health of the Envoy Gateway. This PR enhances observability and makes it easier to identify and diagnose performance issues—particularly those related to the workqueue.
Workqueue Metrics Conflict: Metrics for the workqueue are registered both by controller-runtime and k8s.io/component-base via init() functions. However, only one of these libraries can successfully register the metrics. In our setup, …

Added metrics for restclient and workqueue

---

charts/gateway-crds-helm/templates/gatewayapi-crds.yaml
charts/gateway-helm/crds/gatewayapi-crds.yaml
examples/extension-server/go.mod
examples/extension-server/go.sum
go.mod
go.sum
release-notes/current.yaml

chore: bump gateway api to 1.3.0

---

examples/redis/redis.yaml
test/config/envoy-gateway-config.yaml
tools/make/kube.mk

move e2e envoy gateway config out of redis example.

chore: move envoy gateway config out of redis example

---

internal/cmd/egctl/testdata/translate/out/backend-endpoint.all.yaml
internal/cmd/egctl/testdata/translate/out/default-namespace.all.yaml
internal/cmd/egctl/testdata/translate/out/default-resources.all.yaml
internal/cmd/egctl/testdata/translate/out/echo-gateway-api.cluster.yaml
internal/cmd/egctl/testdata/translate/out/echo-gateway-api.route.json
internal/cmd/egctl/testdata/translate/out/invalid-envoyproxy.all.yaml
internal/cmd/egctl/testdata/translate/out/quickstart.all.yaml
internal/cmd/egctl/testdata/translate/out/rejected-http-route.route.yaml
internal/cmd/egctl/testdata/translate/out/valid-envoyproxy.all.yaml
internal/gatewayapi/resource/load.go
internal/gatewayapi/resource/supported_kind.go
internal/gatewayapi/resource/testdata/all-resources.in.yaml
internal/gatewayapi/resource/testdata/all-resources.out.yaml
internal/provider/file/testdata/resources.all.yaml

- Add support for ReferenceGrant in `load`
- Add APIVersion field for each loaded resources
This is needed for #5767

enhancement: add api-version for load

---

go.mod
internal/wasm/imagefetcher.go
tools/linter/golangci-lint/.golangci.yml

chore: remove `github.com/hashicorp/go-multierror` dependency
`github.com/hashicorp/go-multierror` is under MPL-2.0 License which is not approved in CNCF Allowlist

chore: remove github.com/hashicorp/go-multierror dependency

---

internal/gatewayapi/ext_service.go
internal/gatewayapi/route.go
internal/gatewayapi/testdata/envoyextensionpolicy-with-extproc-with-mixed-backendrefs.out.yaml
internal/gatewayapi/testdata/httproute-attaching-to-listener-with-multiple-backend-backendrefs-diff-address-type.out.yaml
internal/gatewayapi/testdata/httproute-attaching-to-listener-with-multiple-serviceimport-backendrefs-diff-address-type.out.yaml
internal/gatewayapi/testdata/httproute-with-invalid-backend-ref-invalid-mixed-kind.out.yaml
internal/ir/xds.go
internal/ir/xds_test.go
internal/xds/translator/route.go
internal/xds/translator/testdata/in/xds-ir/http2-mixed.yaml
internal/xds/translator/testdata/out/xds-ir/http2-mixed.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/http2-mixed.endpoints.yaml
internal/xds/translator/testdata/out/xds-ir/http2-mixed.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http2-mixed.routes.yaml
internal/xds/translator/translator.go

Feat: support mixed address types across BackendRefs in xRoute
To support multiple address types across BackendRefs in xRoute, create XDS cluster per BackendRef.
Related #5667 

Feat: support mixed address types across BackendRefs in xRoute

---

tools/make/common.mk

Not enough space on the GHA runner, blocking the release can be triaged later
Relates to https://github.com/envoyproxy/gateway/actions/runs/14765129938/job/41457946081

skip building egctl for windows_arm64

---

tools/make/common.mk

Not enough space on the GHA runner, blocking the release can be triaged later
Relates to https://github.com/envoyproxy/gateway/actions/runs/14765129938/job/41457946081
(cherry picked from commit c699d88d08a6477d50fad734cf64fd81fe47b5e9)

[release/v1.4] skip building egctl for windows_arm64 (#5878)

---

.github/workflows/latest_release.yaml
.github/workflows/release.yaml

Relates to https://github.com/envoyproxy/gateway/pull/5878

ci: remove windows_arm64 uploads

---

.github/workflows/latest_release.yaml
.github/workflows/release.yaml

Relates to https://github.com/envoyproxy/gateway/pull/5878
(cherry picked from commit 19b7af3a45cf2fae134e0597e846d8cdc7b7679b)

[releae/v1.4] ci: remove windows_arm64 uploads (#5884)

---

internal/provider/kubernetes/topology_injector.go

* allow pods even if there is an internal error in the webhook processing the request
Relates to https://github.com/envoyproxy/gateway/issues/5890

fix: make topology injector best effort

---

site/archetypes/concept.md

Changes subtitle in Concept Template from "Configuration in Envoy Gateway" to "{Title} in Envoy Gateway", where the writer replaces Title with the name of the concept.
New title makes the intention of the section clearer.
Fixes #5892

docs: Change Subtitle of Concept Template

---

internal/provider/kubernetes/topology_injector.go

* fix: make topology injector best effort
* allow pods even if there is an internal error in the webhook processing the request
Relates to https://github.com/envoyproxy/gateway/issues/5890
(cherry picked from commit 5b8269d75a1f03c865015bb7e5c61528597ee555)

[release/v1.4] fix: make topology injector best effort (#5891)

---

charts/gateway-helm/templates/envoy-gateway-rbac.yaml
test/helm/gateway-helm/envoy-gateway-gateway-namespace-config-watch.out.yaml

* fix(chart): passing the root context to template so that e.g. .`Values.topologyInjector.enabled` is possible to resolve
gateway-helm chart fails without this fix
Relates https://github.com/envoyproxy/gateway/issues/5903

fix(chart): passing root context to template

---

internal/gatewayapi/sort.go
internal/gatewayapi/testdata/httproute-with-header-match-diff-number.in.yaml
internal/gatewayapi/testdata/httproute-with-header-match-diff-number.out.yaml
internal/gatewayapi/testdata/httproute-with-header-match-diff-type.in.yaml
internal/gatewayapi/testdata/httproute-with-header-match-diff-type.out.yaml
internal/gatewayapi/testdata/httproute-with-query-match-diff-number.in.yaml
internal/gatewayapi/testdata/httproute-with-query-match-diff-number.out.yaml
internal/gatewayapi/testdata/httproute-with-query-match-diff-type.in.yaml
internal/gatewayapi/testdata/httproute-with-query-match-diff-type.out.yaml

In sortXdsIRMap, use the match type of header and query param to determine precedence.
requirements in GW-API
> - “Exact” path match.
> - “Prefix” path match with largest number of characters.
> - Method match.
> - Largest number of header matches.
> - Largest number of query param matches.
> - Note: The precedence of RegularExpression path matches are implementation-specific.
So prefer header/query param matches numbers.
Only if matches numbers are same, sort based on number of Exact Header/Query param matches.
Fixes #5736

fix:  httproute precedence by considering header/query match type

---

site/content/en/latest/tasks/traffic/http-redirect.md
site/content/en/v1.3/tasks/traffic/http-redirect.md

docs: fix example for http redirects page
This PR fixes the `Gateway` examples on the HTTP Redirects documentation page. The field is called `allowedRoutes`, not `allowedRouters` (see [reference](https://gateway-api.sigs.k8s.io/reference/spec/#allowedroutes)). This PR also fixes a typo in the written text.
Fixes #

docs: fix example for http redirects page

---

site/content/en/latest/tasks/traffic/request-buffering.md

This is adding docs for the new request buffer feature added in #5661
First docs PR so hopefully didn't miss any other steps
Fixes #3706

docs: Add docs for request buffering

---

internal/gatewayapi/backendtlspolicy.go
internal/gatewayapi/testdata/envoyproxy-tls-settings-invalid-ns.out.yaml
internal/gatewayapi/testdata/envoyproxy-tls-settings-invalid.out.yaml

fixes: #5931
Errors from the EnvoyProxy TLS settings should not be reflected in the BackendTLSPolicy status.
Instead, the BackendTLSPolicy should be accepted, since its configuration is valid.
The EnvoyProxy TLS error is already reported in the HTTPRoute status, as shown in the following yaml snippet:
```
status:
parents:
- conditions:
- lastTransitionTime: null
message: Route is accepted
reason: Accepted
status: "True"
type: Accepted
- lastTransitionTime: null
message: 'Failed to process route rule 0 backendRef 0: failed to locate TLS
secret for client auth: envoy-gateway-system/client-auth-not-found specified
in EnvoyProxy envoy-gateway-system/test.'
reason: InvalidBackendTLS
status: "False"
type: ResolvedRefs
controllerName: gateway.envoyproxy.io/gatewayclass-controller
```

chore: clean up BTP status

---

test/e2e/e2e_test.go

xref: https://github.com/envoyproxy/gateway/issues/5956

e2e: disable DynamicResolverBackendTest on IPv6

---

internal/infrastructure/kubernetes/infra.go
internal/infrastructure/kubernetes/infra_resource.go
internal/infrastructure/kubernetes/proxy/resource_provider.go
internal/infrastructure/kubernetes/proxy/resource_provider_test.go
internal/infrastructure/kubernetes/proxy/testdata/deployments/gateway-namespace-mode.yaml
internal/infrastructure/kubernetes/proxy/testdata/serviceaccount/gateway-namespace-mode.yaml
internal/infrastructure/kubernetes/proxy/testdata/serviceaccount/with-annotations.yaml
internal/infrastructure/kubernetes/proxy_infra.go
internal/infrastructure/kubernetes/ratelimit/resource_provider.go

fix: proxy creation/deletion error handling in GatewayNamespace mode

---

internal/provider/kubernetes/controller.go

* instead of returning from Reconcile after encountering an err which processing a `GatewayClass`, `continue` instead to process all GatewayClasses
Fixes: https://github.com/envoyproxy/gateway/issues/5618

fix: process remaining gatewayClasses after encountering an err

---

internal/xds/translator/listener.go
internal/xds/translator/server_names_match_test.go

These changes ensure that when HTTP/3 is enabled through a ClientTrafficPolicy, the TLS inspector filter is only added to TCP listeners, not to UDP (QUIC) listeners, which prevents the nil pointer dereference.
Fixes #5660

fix: do not add tls inspector filter to quic listener

---

test/e2e/tests/preservecase.go

fixes: https://github.com/envoyproxy/gateway/issues/5965

e2e: fix PreserveCase flaky

---

test/e2e/tests/eg_upgrade.go

e2e: bump upgrade test version to v1.3.2

---

internal/gatewayapi/securitypolicy.go
internal/gatewayapi/testdata/httproute-with-api-key-auth-duplicated-api-key.in.yaml
internal/gatewayapi/testdata/httproute-with-api-key-auth-duplicated-api-key.out.yaml
release-notes/current.yaml
test/e2e/testdata/api-key-auth.yaml

Bug fix
Duplicate API keys in apiKeyAuth can cause the entire controller to stall.
The proposed changes address this by rejecting the affected SecurityPolicy and reporting the error through a status message.
Fixes #5729

fix: add validation for duplicated API keys

---

test/fuzz/xds_fuzz_test.go

[This](https://github.com/envoyproxy/gateway/blob/756d2ef625b74563a894c0592395686599a62fdb/internal/cmd/egctl/translate.go#L372) error should never reach to XDS translator. We fail the fuzzer for any input that causes above error so that we can handle those cases in either of
- API / CEL validation / kubebuilder CRD layer
- Gateway API layer
- IR layer

Fuzzing: Fail on xds translation error

---

internal/gatewayapi/backendtrafficpolicy.go
internal/gatewayapi/testdata/backendtrafficpolicy-strategic-merge-with-multi-parents.in.yaml
internal/gatewayapi/testdata/backendtrafficpolicy-strategic-merge-with-multi-parents.out.yaml

this patch fix an issue while merging a route with multiple parent refs.

fix btp merge not working when there's multi parent refs on router

---

tools/make/golang.mk

Currently, `go test -cover` default only recording code coverage for the package that is currently tested, not for all the packages from the project.
Add `-coverpkg=./...` to enable cross-package coverage, make the coverage result more accurate, increasing codecov from 65% to 70%.
close #199

chore: add coverpkg for coverage test

---

internal/xds/translator/accesslog.go
internal/xds/translator/testdata/out/xds-ir/accesslog-formatters.listeners.yaml

xref: https://github.com/envoyproxy/gateway/issues/5983
Change notes: https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.34/v1.34.0
> formatter: The formatter %CEL% and %METADATA% will be treated as built-in formatters and could be used directly in the substitution format string if the related extensions are linked.

Remoe check for accesslog formatter

---

test/e2e/tests/cors.go

fixes: https://github.com/envoyproxy/gateway/issues/5995

e2e: update CORS test

---

internal/cmd/server.go
internal/extension/registry/extension_manager.go

feat: adds support for extension server in standalone mode

---

test/e2e/e2e_test.go

temporarily disable the backend tls test to unblock the v1.4 release.
It'll be fixed in https://github.com/envoyproxy/gateway/pull/6029

temporarily disable the backend tls test

---

site/content/en/contributions/RELEASING.md

docs: add cherry-pick range example in release steps

---

.github/workflows/build_and_test.yaml

resilience-test is skipped in push flows https://github.com/envoyproxy/gateway/actions/runs/15009104216
which
breaks release https://github.com/envoyproxy/gateway/actions/runs/15009937798

chore: publish shouldnt wait for resilience-test

---

.github/workflows/build_and_test.yaml

resilience-test is skipped in push flows https://github.com/envoyproxy/gateway/actions/runs/15009104216
which
breaks release https://github.com/envoyproxy/gateway/actions/runs/15009937798
(cherry picked from commit 9b22b7ca1818dc22df64b3326c160471484e0769)

[release/v1.4] chore: publish shouldnt wait for resilience-test (#6053)

---

site/content/en/contributions/RELEASING.md

Fixes: https://github.com/envoyproxy/gateway/pull/6052/files#r2087921417

update release process

---

test/e2e/testdata/backendtrafficpolicy-translation-failed.yaml
test/e2e/tests/backend_upgrade.go

fixes: https://github.com/envoyproxy/gateway/issues/6035
Make sure listener is ready and health before run test.

e2e: fix BackendUpgrade flaky

---

test/config/gatewayclass.yaml

A temporary workaround for https://github.com/envoyproxy/gateway/issues/6077 before it's fixed upstream.

pin envoy image in e2e tests to avoid ext proc test failure

---

examples/kubernetes/gateway-namespace-mode.yaml
site/content/en/latest/tasks/operations/deployment-mode.md
site/content/en/latest/tasks/operations/gateway-namespace-mode.md
site/content/en/v1.4/tasks/operations/deployment-mode.md
site/content/en/v1.4/tasks/operations/gateway-namespace-mode.md

Fixes https://github.com/envoyproxy/gateway/issues/5971

docs: add gateway namespace mode documentation

---

test/config/gatewayclass.yaml

change back to the latest envoy image as https://github.com/envoyproxy/envoy/issues/39479 has been fixed upstream.

chore: use the latest envoy image for e2e

---

site/go.mod
site/go.sum
site/layouts/_default/_markup/render-heading.html

Update Docsy to v0.11.0 for Hugo 0.147.3 compatibility and update site/layouts/_default/_markup/render-heading.html
This PR addresses a compatibility issue between newer Hugo versions (0.147.3+) and the site's template system. When using Hugo 0.147.3, users encounter an error: HTML/template:_markup/render-heading.html:1:12: no such template "_default/_markup/td-render-heading.html," which prevents both site-building and archetype generation.
The PR:
- Updates Docsy from v0.10.0 to v0.11.0
- Updates related dependencies (Font-Awesome and Bootstrap)
- Fixes rendering templates to work with the newer Hugo version
Fixes #6098 

fix(site): fix archetypes with Hugo 0.147.3+ by updating Docsy and render-heading template

---

site/content/en/latest/boilerplates/testing.md
site/content/en/latest/tasks/traffic/client-traffic-policy.md
site/content/en/v1.4/boilerplates/testing.md
site/content/en/v1.4/tasks/traffic/client-traffic-policy.md

Updates commands and expected outputs in client traffic policy docs.
Need to update commands and expected outputs after migration to original IP detection extension. Related #4702  
Fixes #5558

Docs: fix client ip detection docs

---

test/e2e/testdata/weighted-backend-all-equal.yaml
test/e2e/testdata/weighted-backend-bluegreen.yaml
test/e2e/testdata/weighted-backend-completing-rollout.yaml
test/e2e/tests/weighted_backend.go
test/e2e/tests/zone_aware_routing.go

fixes: https://github.com/envoyproxy/gateway/issues/6008

e2e: fix flaky and refactor WeightedRoute test

---

charts/gateway-helm/templates/envoy-proxy-topology-injector-webhook.yaml
internal/provider/kubernetes/kubernetes.go
internal/provider/kubernetes/topology_injector.go
test/e2e/e2e_test.go
test/helm/gateway-helm/envoy-gateway-gateway-namespace-config-watch.out.yaml
test/helm/gateway-helm/envoy-gateway-gateway-namespace-config.out.yaml
tools/make/helm.mk

Remove `namespaceSelector` in `MutatingWebhookConfiguration` when enabling GNM.

fix: ZoneAwareRouting not working GNM(gateway namespace mode)

---

internal/xds/translator/api_key_auth.go
internal/xds/translator/authorization.go
internal/xds/translator/basicauth.go
internal/xds/translator/compressor.go
internal/xds/translator/cors.go
internal/xds/translator/credentialInjector.go
internal/xds/translator/custom_response.go
internal/xds/translator/extauth.go
internal/xds/translator/extproc.go
internal/xds/translator/fault.go
internal/xds/translator/healthcheck.go
internal/xds/translator/httpfilters.go
internal/xds/translator/jwt.go
internal/xds/translator/local_ratelimit.go
internal/xds/translator/lua.go
internal/xds/translator/oidc.go
internal/xds/translator/request_buffer.go
internal/xds/translator/route.go
internal/xds/translator/session_persistence.go
internal/xds/translator/testdata/out/xds-ir/local-ratelimit-distinct.routes.yaml
internal/xds/translator/testdata/out/xds-ir/local-ratelimit.routes.yaml
internal/xds/translator/translator.go
internal/xds/translator/wasm.go
release-notes/current.yaml
test/e2e/testdata/local-ratelimit.yaml
test/e2e/tests/local_ratelimit.go
test/e2e/tests/local_ratelimit_distinct_cidr.go
test/e2e/tests/local_ratelimit_distinct_header.go
test/e2e/utils/http.go
tools/make/golang.mk

xref: https://github.com/envoyproxy/gateway/issues/5693
- This doesn't complete #5693, which required upstream changes.
- Enable `x-ratelimit-[limit|remaining]` headers by default
- Users can disabled the headers by using `DisableRateLimitHeaders` in `ClientTrafficPolicy`(same as Global RateLimit).

feat: local ratelimit support XRateLimitHeaders 

---

site/content/en/v1.4/tasks/operations/gateway-namespace-mode.md

Fixes https://github.com/envoyproxy/gateway/issues/6138

fix: v1.4 gateway namespace mode deployment link

---

test/e2e/tests/weighted_backend.go
test/e2e/tests/zone_aware_routing.go

Fixes e2e flakiness after a refactoring
Fixes #6119

fix: zone-aware-routing e2e falkiness

---

internal/cmd/egctl/testdata/translate/out/backend-endpoint.all.yaml
internal/gatewayapi/envoyextensionpolicy.go
release-notes/current.yaml

fix: return early from buildwasms

---

site/content/en/latest/tasks/traffic/response-compression.md
site/content/en/v1.4/tasks/traffic/response-compression.md

Replaced links to Quickstart in the "Response Compression" doc with the prereq boilerplate for latest and v1.4.
The user can stay on the same page to install EG.
Fixes #6164

docs: Added prereq boilerplate to Response Compression doc in latest and v1.4

---

api/v1alpha1/backend_types.go
charts/gateway-crds-helm/templates/generated/gateway.envoyproxy.io_backends.yaml
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backends.yaml
site/content/en/latest/api/extension_types.md
test/cel-validation/backend_test.go
test/helm/gateway-crds-helm/all.out.yaml
test/helm/gateway-crds-helm/envoy-gateway-crds.out.yaml

This PR adds validation to limit Unix domain socket path length to 108 characters, which is the standard limit across Unix systems. This limitation exists for historical reasons related to the kernel's mbuf (memory buffer) data structure in early BSD implementations.
Fixes #6150 

add unix domain socket path length validation

---

api/v1alpha1/backend_types.go
charts/gateway-crds-helm/templates/generated/gateway.envoyproxy.io_backends.yaml
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backends.yaml
internal/gatewayapi/testdata/gateway-with-multiple-https-listeners-with-overlapping-hostnames-and-certs-merged-gateways.out.yaml
internal/gatewayapi/testdata/gateway-with-multiple-https-listeners-with-overlapping-hostnames-merged-gateways.out.yaml
test/cel-validation/backend_test.go
test/helm/gateway-crds-helm/all.out.yaml
test/helm/gateway-crds-helm/envoy-gateway-crds.out.yaml
tools/make/golang.mk
tools/make/kube.mk

fixes: https://github.com/envoyproxy/gateway/issues/6184

ci: fix go.test.cel

---

site/content/en/latest/tasks/traffic/fault-injection.md
site/content/en/v1.4/tasks/traffic/fault-injection.md

docs: fix incorrect policy name in fault-injection task
This PR fixes a documentation error in the Fault Injection task.
The policy name "SecurityPolicy" was incorrectly used and is now replaced with the correct term "BackendTrafficPolicy".
Fixes #6167

docs(fault-injection): fix incorrect policy name

---

test/e2e/testdata/envoyproxy-daemonset.yaml
test/e2e/tests/envoyproxy_daemonset.go

xref: https://github.com/envoyproxy/gateway/actions/runs/15255268202/job/42906197471

e2e: fix EnvoyProxyDaemonSet test

---

internal/cmd/egctl/collect.go
internal/cmd/egctl/root.go
internal/troubleshoot/collect.go
internal/troubleshoot/collect/config_dump.go
internal/troubleshoot/collect/prometheus_metrics.go
internal/utils/str/strconv.go
test/e2e/tests/utils.go

1. support collect other namespace for GNM(gateway namesapce mode)
2. mute klog
3. correct prometheus scrape logic

feat: improve egctl collect

---

internal/gatewayapi/conformance/suite.go
internal/gatewayapi/status/gatewayclass.go
test/conformance/conformance_test.go
test/conformance/experimental_conformance_test.go
tools/make/kube.mk

Separated from https://github.com/envoyproxy/gateway/pull/5996, to make it more clear.

test: make conformance test support RunTest

---

examples/extension-server/go.mod
examples/extension-server/go.sum
go.mod
go.sum
tools/make/kube.mk

this allow EG adopt changes for conformace test before a offical release.

decouple Gateway API version with go mod

---

test/conformance/conformance_test.go
test/conformance/experimental_conformance_test.go
test/e2e/e2e_test.go
test/e2e/hook.go
test/e2e/multiple_gc/multiple_gc_test.go
test/e2e/tests/eg_upgrade.go
test/e2e/tests/envoyproxy_daemonset.go
test/e2e/tests/httproute_with_dynamic_resolver_backend.go
test/e2e/upgrade/eg_upgrade_test.go

fixes: https://github.com/envoyproxy/gateway/issues/3415

e2e: use ConformanceOptions.Hook

---

api/v1alpha1/healthcheck_types.go
site/content/en/latest/api/extension_types.md

fix: add optional flag for hostname fix #6278

---

internal/provider/kubernetes/controller.go
test/e2e/multiple_gc/multiple_gc_test.go

chore: fix unnecessary type arguments lint

---

api/v1alpha1/securitypolicy_types.go
charts/gateway-crds-helm/templates/generated/gateway.envoyproxy.io_securitypolicies.yaml
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml
internal/gatewayapi/helpers.go
internal/gatewayapi/securitypolicy.go
internal/gatewayapi/testdata/securitypolicy-override-replace.in.yaml
internal/gatewayapi/testdata/securitypolicy-override-replace.out.yaml
test/cel-validation/securitypolicy_test.go
test/helm/gateway-crds-helm/all.out.yaml
test/helm/gateway-crds-helm/envoy-gateway-crds.out.yaml

feat: support listener name in SecurityPolicy target
It allows to target only a specific listener in a Security Policy. One usage example is attaching mtls authorization as described in https://github.com/envoyproxy/gateway/issues/5909

feat: support listener name in SecurityPolicy target

---

go.mod
go.sum

This will allow the standalone mode to use Envoy v1.34 on macos https://github.com/tetratelabs/func-e/commit/6a0f4e4780761107295d186eb434823d69a61897

deps: upgrades func-e to the latest to use latest Envoy with standalone

---

api/v1alpha1/shared_types.go
api/v1alpha1/zz_generated.deepcopy.go
charts/gateway-crds-helm/templates/generated/gateway.envoyproxy.io_envoyproxies.yaml
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
go.mod
internal/infrastructure/kubernetes/proxy/resource.go
internal/infrastructure/kubernetes/proxy/resource_test.go
site/content/en/latest/api/extension_types.md
test/cel-validation/envoyproxy_test.go
test/helm/gateway-crds-helm/all.out.yaml
test/helm/gateway-crds-helm/envoy-gateway-crds.out.yaml

This PR allows users to specify a custom image repository for **EnvoyProxy** without needing to provide a tag.
Fixes #6066

feat(api): allow pinning custom image repository for Envoy Proxy.

---

internal/gatewayapi/securitypolicy.go
internal/gatewayapi/securitypolicy_test.go

Fixes https://github.com/envoyproxy/gateway/issues/5581

fix: invalid basic auth data caused rds rejection

---

internal/gatewayapi/clienttrafficpolicy.go
internal/gatewayapi/securitypolicy.go
internal/gatewayapi/testdata/clienttrafficpolicy-status-conditions.out.yaml
internal/gatewayapi/testdata/securitypolicy-invalid-no-section-name-listener.in.yaml
internal/gatewayapi/testdata/securitypolicy-invalid-no-section-name-listener.out.yaml
internal/gatewayapi/validate.go

Folllow-up to #5916 
Added validation that the section name exists in the gateway's listeners.
Fixes #

feat: add validation of section name for Gateway listener

---

internal/provider/kubernetes/controller.go
internal/provider/kubernetes/controller_offline.go
internal/provider/kubernetes/indexers.go
internal/provider/kubernetes/predicates.go
internal/provider/kubernetes/predicates_test.go
internal/provider/kubernetes/test/utils.go
release-notes/current.yaml

fix: add configMap indexers for EEP reconciler
Updating the EEP Lua ConfigMap doesn't update the Lua filter applied to proxy. Tested this change locally and now updates seem to be reflecting.
Fixes #6356 

fix: add configMap indexers for EEP reconciler

---

internal/gatewayapi/backendtlspolicy.go
internal/gatewayapi/backendtrafficpolicy.go
internal/gatewayapi/clienttrafficpolicy.go
internal/gatewayapi/envoyextensionpolicy.go
internal/gatewayapi/envoypatchpolicy.go
internal/gatewayapi/extensionserverpolicy.go
internal/gatewayapi/securitypolicy.go
internal/gatewayapi/status/policy.go
internal/gatewayapi/testdata/backendtlspolicy-across-ns.in.yaml
internal/gatewayapi/testdata/backendtlspolicy-across-ns.out.yaml
internal/gatewayapi/testdata/backendtrafficpolicy-buffer-limit.in.yaml
internal/gatewayapi/testdata/backendtrafficpolicy-buffer-limit.out.yaml
internal/gatewayapi/testdata/clienttrafficpolicy-buffer-limit.in.yaml
internal/gatewayapi/testdata/clienttrafficpolicy-buffer-limit.out.yaml
internal/gatewayapi/testdata/envoyextensionpolicy-with-lua.in.yaml
internal/gatewayapi/testdata/envoyextensionpolicy-with-lua.out.yaml
internal/gatewayapi/testdata/envoypatchpolicy-valid.in.yaml
internal/gatewayapi/testdata/envoypatchpolicy-valid.out.yaml
internal/gatewayapi/testdata/securitypolicy-with-basic-auth.in.yaml
internal/gatewayapi/testdata/securitypolicy-with-basic-auth.out.yaml

fix: policy satus observedGeneration

---

site/content/en/about/index.md
site/content/en/tools/_index.md
site/content/en/tools/benchmark-report-explorer/index.md
site/hugo.toml
site/layouts/partials/navbar.html
site/layouts/partials/tools-grid.html
site/layouts/shortcodes/tools-grid.html

Following up on PR https://github.com/envoyproxy/gateway/pull/6399 to add a link to the Benchmark Report Explorer Tool.
I created a Tools page where we can have links to more tools as well in the future.
Make it easy to find tools.
Screenshot:
N/A

docs: add tools page for navigating to tools

---

.github/workflows/build_and_test.yaml

fixes: https://github.com/envoyproxy/gateway/issues/6035 https://github.com/envoyproxy/gateway/issues/6009

e2e: use appropriate values for upgrade test

---

tools/make/docs.mk

chore: fix doc link

---

api/v1alpha1/loadbalancer_types.go
charts/gateway-crds-helm/templates/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml
charts/gateway-crds-helm/templates/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml
charts/gateway-crds-helm/templates/generated/gateway.envoyproxy.io_envoyproxies.yaml
charts/gateway-crds-helm/templates/generated/gateway.envoyproxy.io_securitypolicies.yaml
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml
test/helm/gateway-crds-helm/all.out.yaml
test/helm/gateway-crds-helm/envoy-gateway-crds.out.yaml

Follow up to https://github.com/envoyproxy/gateway/pull/6154 and fixes a typo after updating field names
Fixes #

fix: typo in zoneAware API field

---

internal/gatewayapi/listener.go
internal/gatewayapi/testdata/envoyproxy-accesslog-file-json-no-format.out.yaml
internal/gatewayapi/testdata/envoyproxy-accesslog-without-format.out.yaml
release-notes/current.yaml

fixes: https://github.com/envoyproxy/gateway/issues/6440

fix: default accesslog not working

---

internal/gatewayapi/route.go
internal/gatewayapi/testdata/httproute-retry.out.yaml

fix: Do not set backendRequestTimeout when Retries are set

---

internal/gatewayapi/runner/runner.go
internal/gatewayapi/translator.go
internal/provider/kubernetes/controller.go
internal/provider/kubernetes/controller_test.go

this fix a error log when there more than one unaccepted gatewayclass like following:
```console
2025-06-23T04:32:40.628Z	INFO	provider	kubernetes/controller.go:361	secret	{"runner": "provider", "count": 2, "gwc": "eg"}
2025-06-23T04:32:40.629Z	INFO	provider	kubernetes/controller.go:361	secret	{"runner": "provider", "count": 2, "gwc": "eg"}
2025-06-23T04:33:08.944Z	INFO	provider	kubernetes/controller.go:361	secret	{"runner": "provider", "count": 2, "gwc": "eg"}
2025-06-23T04:34:07.884Z	INFO	provider	kubernetes/controller.go:361	secret	{"runner": "provider", "count": 2, "gwc": "envoy-gateway"}
2025-06-23T04:34:07.884Z	INFO	provider	kubernetes/controller.go:361	secret	{"runner": "provider", "count": 2, "gwc": "eg"}
2025-06-23T04:36:06.505Z	INFO	provider	kubernetes/controller.go:361	secret …
```

gatewayapi: don't append gwcResource if there's invalid GatewayClass

---

internal/gatewayapi/route.go
internal/gatewayapi/testdata/extensions/httproute-with-custom-backend-invalid-apiversion.out.yaml
internal/gatewayapi/testdata/extensions/httproute-with-custom-backend-mixed-multiple.out.yaml
internal/gatewayapi/testdata/extensions/httproute-with-custom-backend-mixed.out.yaml
internal/gatewayapi/testdata/extensions/httproute-with-custom-backend-multiple.out.yaml
internal/gatewayapi/testdata/extensions/httproute-with-custom-backend.out.yaml
internal/ir/xds.go
internal/provider/kubernetes/controller.go
internal/provider/kubernetes/controller_test.go

This PR fixed the custom backendRef weight not set properly, which will cause the destination settings empty and always get a 500 direct response.
This fix has tested in envoy ai gateway.

fix: custom backend weight not set properly

---

api/v1alpha1/envoyproxy_types.go
api/v1alpha1/zz_generated.deepcopy.go
charts/gateway-crds-helm/templates/generated/gateway.envoyproxy.io_envoyproxies.yaml
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
internal/cmd/egctl/testdata/translate/out/invalid-envoyproxy.all.yaml
internal/cmd/egctl/testdata/translate/out/valid-envoyproxy.all.yaml
internal/gatewayapi/envoyextensionpolicy.go
internal/gatewayapi/resource/testdata/all-resources.out.yaml
internal/gatewayapi/testdata/envoyextensionpolicy-with-invalid-lua-validation-disabled.in.yaml
internal/gatewayapi/testdata/envoyextensionpolicy-with-invalid-lua-validation-disabled.out.yaml
release-notes/current.yaml
site/content/en/latest/api/extension_types.md
test/helm/gateway-crds-helm/all.out.yaml
test/helm/gateway-crds-helm/envoy-gateway-crds.out.yaml

feat: introduce validation levels for lua
Introduce validation levels so users can disable or have runtime validations on their lua script. Will introduce a compile time validation in a follow up PR.
Related discussion in Slack [thread](https://envoyproxy.slack.com/archives/C03E6NHLESV/p1750276621696389?thread_ts=1750261902.415369&cid=C03E6NHLESV)
Related: #6172 #6176 

feat: introduce validation levels for lua

---

site/assets/scss/_styles_project.scss
site/content/en/tools/ai-chat/index.md
site/static/html/ai-chat-embed.html

Making a tool page for the kapa chat, so there is an option to view it in larger screen, as an addition to the modal view.
This provides a larger chat screen option to the modal view.
n/a

docs: create an embedded page for kapa chat

---

tools/make/docs.mk

Hope this can mitigate the flaky docs-link check.
```bash
hugo: collected modules in 11695 ms🏊‍♂️ crawling site/public/
[0] https://www.envoyproxy.io/docs/envoy/latest/operations/cli
site/public/docs/api/extension_types/
[0] https://www.envoyproxy.io/docs/envoy/latest/operations/cli
ERROR: Detected 1 broken links. Scanned 1411 links in 115.907 seconds.
```
https://github.com/envoyproxy/gateway/actions/runs/16335732136/job/46147426798?pr=6533

chore: retry when failing to check doc links

---

api/v1alpha1/ext_proc_types.go
charts/gateway-crds-helm/templates/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml
test/cel-validation/envoyextensionpolicy_test.go
test/helm/gateway-crds-helm/all.out.yaml
test/helm/gateway-crds-helm/envoy-gateway-crds.out.yaml

Fixes: https://github.com/envoyproxy/gateway/issues/6559

Fix EEP CEL Validations around FullDuplexStreamed and FailOpen

---

internal/provider/kubernetes/controller.go

bugfix
`corev1.Node` objects in Kubernetes are cluster-level resources that don't have a namespace, then `r.hasMatchingNamespaceLabels` function will always return `false, nil`.

fix: Node objects should not be subject to namespace label checks

---

go.mod
go.sum
internal/infrastructure/host/proxy_infra.go
internal/infrastructure/host/proxy_infra_test.go

dependency update
func-e is used for standalone mode, to run envoy as a library.
This updates to latest func-e which notably solves a package cycle introduced in its api package, removes an implicit dep on its cmd package, and makes runs more reliable.
See https://github.com/tetratelabs/func-e/releases/tag/v1.2.0

build(deps): updates to func-e 1.2

---

internal/xds/translator/route.go
internal/xds/translator/testdata/in/xds-ir/http-route-rewrite-url-fullpath.yaml
internal/xds/translator/testdata/in/xds-ir/http-route-rewrite-url-host.yaml
internal/xds/translator/testdata/in/xds-ir/http-route-rewrite-url-prefix.yaml
internal/xds/translator/testdata/in/xds-ir/http-route-rewrite-url-regex.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-url-fullpath.routes.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-url-host.routes.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-url-prefix.routes.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-url-regex.routes.yaml

feat: urlRewrite supports idleTimeout
The idleTimeout is ignored in HTTPRoute if there is urlRewrite. This PR fixes it so idleTimeout is applicable with urlRewrite.
Fixes #6530

feat: urlRewrite supports idleTimeout

---

internal/xds/translator/testdata/out/xds-ir/multiple-listeners-same-port-with-different-filters.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/multiple-listeners-same-port-with-different-filters.routes.yaml
internal/xds/translator/translator.go

HTTP filters are missing in the UDP listener when HTTP3 is enabled and multiple listeners are on the same port.
Fixes https://github.com/envoyproxy/gateway/pull/6544#discussion_r2225548956

fix: add missing HTTP filters for HTTP3 listener

---

internal/cmd/egctl/testdata/translate/out/default-resources.all.yaml
internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.json
internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.yaml
internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.listener.yaml
internal/xds/translator/httpfilters.go
internal/xds/translator/testdata/out/xds-ir/basic-auth-username-header.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/basic-auth.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/dns-lookup-family.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/ext-auth-backend.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/ext-auth-body.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/ext-auth-recomputation.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/ext-auth.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/ext-proc.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http2-route.listeners.yaml

ensures stability across translations, mitigating listener drains https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/listeners/listener_filters#filter-chain-only-update

sort httpFilters on name if priority order is same

---

internal/xds/cache/snapshotcache.go

In the snapshotcache, only snapshots for nodes with active connections are updated.
https://github.com/envoyproxy/gateway/blob/ceec66655765bea49635f951fa075796ca47796d/internal/xds/cache/snapshotcache.go#L92-L95
As far as I can tell, these snapshots are never deleted. When a node disconnects and then reconnects it will receive the configuration from the time it disconnected. It will only get the latest configuration when there is an update while it is still connected.
This is a big problem when you are running multiple replicas of envoy-gateway, if a proxy flips between which instance it is connected to it can receive data that is several days out of date. We have seen proxy instances suddenly start using certificates that are expired and have already been rotated, and use pod IPs that do …

fix(xds-server): clear snapshot on stream close

---

api/v1alpha1/envoyproxy_types.go
internal/cmd/egctl/testdata/translate/out/default-resources.all.yaml
internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.json
internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.yaml
internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.listener.yaml
internal/xds/translator/httpfilters.go
internal/xds/translator/testdata/out/xds-ir/dns-lookup-family.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http2-route.listeners.yaml
site/content/en/latest/api/extension_types.md

The `grpc_web` filter should be put in front of the `grpc_stats` filter,  otherwise `grpc_stats` won’t see the traffic as valid gRPC and may not work correctly.
Fixes: #6620

fix: set order for grpc_web and grpc_stats filters

---

api/v1alpha1/shared_types.go
charts/gateway-crds-helm/templates/generated/gateway.envoyproxy.io_envoyproxies.yaml
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
internal/infrastructure/kubernetes/proxy/resource_test.go
test/cel-validation/envoyproxy_test.go
test/helm/gateway-crds-helm/all.out.yaml
test/helm/gateway-crds-helm/envoy-gateway-crds.out.yaml

(cherry picked from commit c988ec5243baa79b5ebcd2badfae9fcc114f312b)

fix: allow imageRepository contains port (#6658)

---

site/content/en/latest/concepts/gateway_api_extensions/backend-traffic-policy.md
site/content/en/latest/concepts/gateway_api_extensions/client-traffic-policy.md
site/content/en/latest/concepts/gateway_api_extensions/security-policy.md

to better explain
* targets
* precedence
* merge types

docs: improve policy concepts section

---

site/content/en/contributions/RELEASING.md

fixes: https://github.com/envoyproxy/gateway/issues/6645

docs: highlight wait step

---

internal/xds/translator/listener.go
internal/xds/translator/testdata/out/xds-ir/xds-name-scheme-v2.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/xds-name-scheme-v2.routes.yaml
internal/xds/translator/translator.go
test/e2e/tests/connection_limit.go

Follow-up of https://github.com/envoyproxy/gateway/pull/6544
* RouteConfig:
* HTTP Listener:  before `envoy-gateway/gateway-1/http` after `http-80`
* HTTPS Listener: keep the current name `envoy-gateway/gateway-1/https`
* VirtualHost: before `envoy-gateway/gateway-1/https1/www_example_com` after `www_example_com`
* HCM StatPrefix: before `http-10080` after `http-80`

fix: xds name schema v2

---

api/v1alpha1/loadbalancer_types.go
site/content/en/latest/api/extension_types.md

Removes `notImplementedHide` for generated site docs
Fixes #

docs: unhide zoneaware api for docs

---

internal/gatewayapi/runner/runner.go
internal/message/watchutil.go
internal/message/watchutil_test.go
internal/provider/kubernetes/controller.go
internal/xds/translator/runner/runner.go

GC is unable to collect the temporary references created in `HandleStore`
Here is some `pprof` data between `v1.5.0-rc.1` and this PR
* Running with 2000 HTTPRoutes
* Agressive cacheSyncPeriod of `1m`
* T1 data is at 0m and T5 data is at 8m
Comparing T5 across 2 versions, there's a 19.93% decrease
```
$ go tool pprof -top -inuse_space -base v1.5.0-rc-profile/heap_profile_5_20250802_162916.pprof direct-store-profile/heap_profile_5_20250802_155443.pprof | grep Store
536.37kB  0.26%  5.65%   536.33kB  0.26%  github.com/telepresenceio/watchable.(*Map[go.shape.struct { Namespace string; Name string },go.shape.*uint8]).unlockedStore
512.19kB  0.25%  6.43%   512.19kB  0.25%  sigs.k8s.io/json/internal/golang/encoding/json.(*decodeState).literalStore
0     0%  3.90% -40453.66kB 19.93% …
```

watchable: use Store directly instead of HandleStore wrapper

---

site/content/en/latest/tasks/traffic/zone-aware-routing.md

Docs
Updates docs for Zone Aware Routing. There's now additional ways to configure it.
Fixes https://github.com/envoyproxy/gateway/issues/6649

docs: Update Zone Aware Routing for BackendTrafficPolicy configuration example

---

internal/metrics/register.go
release-notes/current.yaml

fixes: https://github.com/envoyproxy/gateway/issues/6687

fix: controller panic when reloading config

---

internal/gatewayapi/testdata/backend-tls-settings-invalid.in.yaml
internal/gatewayapi/testdata/backend-tls-settings-invalid.out.yaml
internal/provider/kubernetes/controller.go

fixes: https://github.com/envoyproxy/gateway/issues/6659

fix: don't block deployment creating when missing secret in EnvoyProxy

---

site/content/en/latest/install/install-egctl.md
site/content/en/v1.4/install/install-egctl.md

* we've removed the latest egctl artifacts
Relates to https://github.com/envoyproxy/gateway/pull/6551

docs: rm latest from install egctl docs

---

site/content/en/latest/tasks/security/backend-tls.md

fixes: https://github.com/envoyproxy/gateway/issues/6585

docs: ClusterTrustBundle Support in BackendTLSPolicy

---

.github/workflows/build_and_test.yaml

*A dependent job will be automatically skipped if its parent job is skipped.* 
that cause https://github.com/envoyproxy/gateway/actions/runs/16874483512/job/47796108557.
In this way, when there is a push event, we cannot skip the entire job.
Alternatively, we only run the 'check-changes' step on the `pull_request` event.

ci: skip step instead of job

---

internal/gatewayapi/route.go
internal/gatewayapi/testdata/envoyproxy-with-statname.out.yaml
release-notes/current.yaml

Make formatter more consistent with existing EG formats. All other operators are lower-cased by definition. User-defined strings are not being lower-cased. 
Fixes #6751

fix: cluster stat name: lowercase Kind

---

internal/provider/kubernetes/controller.go
internal/provider/kubernetes/controller_test.go
test/e2e/testdata/zone-aware-routing-btp-force-local-zone.yaml
test/e2e/testdata/zone-aware-routing-btp-no-force-local-zone.yaml
test/e2e/testdata/zone-aware-routing-gateways.yaml
test/e2e/tests/weighted_backend.go
test/e2e/tests/zone_aware_routing.go

fix!: fix envoy service cluster name for zone-aware routing
Currently, the new zone aware routing is not always functional when not using ForceLocalZone and using Envoy's normal distributional zone-aware routing.
This is the case when having a hard-coded name for the envoy's service in EnvoyProxy. The code always assumes the service has an autogenerated name, and so in other cases the discovery fails for envoy endpoints.
I've moved the call for `processServiceCluster` in case of unmerged gateways down after we do the `processGatewayParamsRef`, so that we can fetch EnvoyProxy directly from the `resourceTree`. If this might cause any other unintended problems, I can move it to where it was, and fetch EnvoyProxy manually …

fix: envoy service cluster name for zone-aware routing

---

internal/gatewayapi/route.go
internal/gatewayapi/testdata/accesslog-als-backend.out.yaml
internal/gatewayapi/testdata/envoyproxy-tracing-backend-uds.out.yaml
internal/gatewayapi/testdata/securitypolicy-with-extauth-backend.out.yaml
internal/ir/xds.go
internal/xds/translator/testdata/in/xds-ir/tracing-datadog-uds.yaml

fix: https://github.com/envoyproxy/gateway/issues/6408

IR: add DestinationAddressType UDS

---

.github/workflows/build_and_test.yaml
test/benchmark/suite/render.go

1. Upload the report for easy verification
2. Fixed the issue where file names with spaces were not rendered correctly in markdown.

benchmark: upload report and fix the filename issue

---

api/v1alpha1/shared_types.go
charts/gateway-crds-helm/templates/generated/gateway.envoyproxy.io_envoyproxies.yaml
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
test/cel-validation/envoyproxy_test.go
test/helm/gateway-crds-helm/all.out.yaml
test/helm/gateway-crds-helm/envoy-gateway-crds.out.yaml

fix image validation regex, support port in repository.
When we have port in repository, the image match validation will fail, eg:
https://regex101.com/r/sM9VFx/1
this PR update the regex to support port in repository.
regex tests:
https://regex101.com/r/iPjJcV/2
related PRs:
https://github.com/envoyproxy/gateway/pull/6720
https://github.com/envoyproxy/gateway/pull/6354
Fixes #

fix(api): image validation regex, support port in repository

---

test/benchmark/suite/report.go
test/benchmark/suite/suite.go
test/benchmark/tests/scale_httproutes.go

* determine the time duration more accurately instead of using 30s, which may be reading values across tests

benchmark: use custom duration in prom metric

---

internal/gatewayapi/filters.go
internal/gatewayapi/testdata/grpcroute-with-mirror.in.yaml
internal/gatewayapi/testdata/grpcroute-with-mirror.out.yaml

This fixes an unconditional panic when the RequestMirror filter is used with GRPCRoutes
Fixes #6874

fix(translator): Fix panic with request mirror + grpcroute

---

.github/workflows/build_and_test.yaml

Add missing SHA pinning to checkout action in 'Build and Test' workflow.

ci: pin checkout action

---

internal/gatewayapi/backendtrafficpolicy.go
internal/gatewayapi/contexts.go
internal/gatewayapi/envoyextensionpolicy.go
internal/gatewayapi/helpers.go
internal/gatewayapi/route.go
internal/gatewayapi/securitypolicy.go
internal/gatewayapi/validate.go
test/gobench/translate_test.go

```
goos: darwin
goarch: arm64
pkg: github.com/envoyproxy/gateway/test/fuzz
cpu: Apple M1 Pro
│   old.txt    │               new.txt               │
│    sec/op    │   sec/op     vs base                │
GatewayAPItoXDS/small-10    881.2µ ±  7%   813.4µ ± 8%   -7.69% (p=0.023 n=10)
GatewayAPItoXDS/medium-10   4.130m ± 26%   3.214m ± 4%  -22.17% (p=0.000 n=10)
GatewayAPItoXDS/large-10     5.375 ±  2%    4.585 ± 1%  -14.69% (p=0.000 n=10)
geomean                     26.94m         22.89m       -15.06%
│   old.txt    │               new.txt                │
│     B/op     │     B/op      vs base                │
GatewayAPItoXDS/small-10    507.2Ki ± 0%   500.1Ki ± 0%   -1.40% (p=0.000 n=10)
GatewayAPItoXDS/medium-10   2.545Mi ± 7%   2.138Mi ± 2%  -15.98% (p=0.000 n=10) …
```

Removes reflection from RouteContext to reduce allocations

---

internal/provider/kubernetes/controller.go
internal/provider/kubernetes/indexers.go
internal/provider/kubernetes/predicates_test.go
release-notes/current.yaml

fix: nil pointer dereference in btp configmap indexer
The BTP configmap indexer assumes that response always exists in responseOverride, which is optional after support was added for redirect.
Fixes #6912 

fix: nil pointer dereference in btp configmap indexer

---

tools/docker/envoy-gateway/Dockerfile

Update `gcr.io/distroless/base-nossl:nonroot` base image to latest digest to resolve 2 `glibc` CVEs:
Fixes #6950

fix: update distroless image to resolve glibc CVEs

---

internal/gatewayapi/testdata/securitypolicy-with-extauth-serviceimport-retry.in.yaml
internal/gatewayapi/testdata/securitypolicy-with-extauth-serviceimport-retry.out.yaml
internal/xds/translator/extauth.go
internal/xds/translator/extauth_test.go
internal/xds/translator/testdata/in/xds-ir/ext-auth-retry.yaml
internal/xds/translator/testdata/out/xds-ir/ext-auth-retry.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/ext-auth-retry.endpoints.yaml
internal/xds/translator/testdata/out/xds-ir/ext-auth-retry.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/ext-auth-retry.routes.yaml
release-notes/current.yaml

feat: support retry policy for gRPC ExtAuth SecurityPolicy
`SecurityPolicy` allows you to specify a `Retry` for various features. However, this retry feature is currently not implemented for ext auth callouts (gRPC and HTTP ext auth service).
This PR implements retry policy for **gRPC** ext auth callouts.
Related to https://github.com/envoyproxy/gateway/issues/6914, but let's keep it open for the long-term validation/docs fix.

feat: support retry policy for gRPC ExtAuth SecurityPolicy

---

test/benchmark/config/nighthawk-client.yaml
test/benchmark/config/nighthawk-test-server.yaml
test/benchmark/suite/suite.go

cherry-pick https://github.com/envoyproxy/gateway/commit/94e99a028e4710242cdfe33fcc0487c6f94a8246 to fix the broken benchmark test.

[release/v1.4] cherry-pick for #6979

---

internal/gatewayapi/route.go

* build it once and pass it in the caller
* also since EG annotations are rare, make sure to return early and reduce allocations

perf: reuse route rule metadata

---

internal/metrics/otel_label.go
internal/metrics/otel_metric_counter.go
internal/metrics/otel_metric_gauge.go
internal/metrics/otel_metric_histogram.go

```
│   old.txt    │       new.txt       │
│    sec/op    │    sec/op     vs base   │
MergeLabelValuesOld-12   354.6n ± 42%
MergeLabelValuesNew-12                  131.6n ± 18%
│  old.txt   │      new.txt      │
│    B/op    │    B/op     vs base   │
MergeLabelValuesOld-12   640.0 ± 0%
MergeLabelValuesNew-12                320.0 ± 0%
│  old.txt   │      new.txt      │
│ allocs/op  │ allocs/op   vs base   │
MergeLabelValuesOld-12   2.000 ± 0%
MergeLabelValuesNew-12                1.000 ± 0%
```

perf: reduce mem allocs in internal/metrics

---

internal/gatewayapi/contexts.go
internal/gatewayapi/filters.go
internal/gatewayapi/listener.go
internal/gatewayapi/resource/load.go
internal/gatewayapi/route.go
internal/gatewayapi/validate.go

* similar to https://github.com/envoyproxy/gateway/pull/6820
```
BenchmarkBackendRefContext_Old_HTTPBackendRef-12             	 5002508	       239.5 ns/op	     152 B/op	       3 allocs/op
BenchmarkBackendRefContext_Old_HTTPBackendRef-12             	 4764154	       264.1 ns/op	     152 B/op	       3 allocs/op
BenchmarkBackendRefContext_Old_HTTPBackendRef-12             	 4866708	       238.6 ns/op	     152 B/op	       3 allocs/op
BenchmarkBackendRefContext_Old_HTTPBackendRef-12             	 5032014	       243.8 ns/op	     152 B/op	       3 allocs/op
BenchmarkBackendRefContext_Old_HTTPBackendRef-12             	 4935594	       259.5 ns/op	     152 B/op	       3 allocs/op
BenchmarkBackendRefContext_Old_GRPCBackendRef-12             	 4833061	       245.3 ns/op	     152 B/op	       3 …
```

perf: remove reflect from BackendRefContext

---

.github/workflows/build_and_test.yaml
tools/hack/go-benchmark-compare.sh
tools/make/golang.mk

CI logs
```
[2025-09-23 20:09:09] Starting benchmark comparison with 5% regression threshold
[2025-09-23 20:09:09] Current branch: HEAD, commit: 852302ca
[2025-09-23 20:09:09] Running benchmarks on HEAD...
[2025-09-23 20:17:14] Benchmarks completed for HEAD
[2025-09-23 20:17:14] Switching to main branch...
[2025-09-23 20:17:14] Running benchmarks on origin/main...
[2025-09-23 20:22:11] Benchmarks completed for origin/main
[2025-09-23 20:22:11] Returning to original commit...
[2025-09-23 20:22:11] Comparing benchmark results...
Benchmark Comparison Results:
======================================
make: Entering directory '/home/runner/work/gateway/gateway'
make[1]: Entering directory '/home/runner/work/gateway/gateway'
goos: linux
goarch: amd64
pkg: …
```

ci: add benchstat to compare perf b/w main and PR branch

---

internal/utils/jsonpatch/patch.go
internal/xds/translator/jsonpatch.go

perf: avoid YAML to JSON conversion in JSONPatch

---

internal/provider/kubernetes/controller.go
internal/provider/kubernetes/helpers.go
internal/provider/kubernetes/helpers_test.go

seperated from https://github.com/envoyproxy/gateway/pull/7009
1. remove useless function
2. make the log format more consistent

chore: remove useless function and unify log format

---

internal/gatewayapi/backend.go
internal/gatewayapi/backendtlspolicy.go
internal/gatewayapi/envoyextensionpolicy.go
internal/gatewayapi/ext_service.go
internal/gatewayapi/filters.go
internal/gatewayapi/helpers.go
internal/gatewayapi/route.go
internal/gatewayapi/securitypolicy.go
internal/gatewayapi/status/gatewayclass.go
internal/gatewayapi/tls.go
internal/provider/file/resources.go
internal/provider/kubernetes/controller.go
internal/provider/kubernetes/indexers.go
internal/provider/kubernetes/routes.go
internal/provider/kubernetes/secrets.go
internal/utils/jsonpatch/jsonpathtopointer.go
internal/utils/slice/slice.go
internal/xds/cache/snapshotcache.go
internal/xds/translator/accesslog.go
internal/xds/translator/authorization.go
internal/xds/translator/cluster.go
internal/xds/translator/cors.go
internal/xds/translator/extauth.go
internal/xds/translator/header_mutation.go
internal/xds/translator/local_ratelimit.go
internal/xds/translator/session_persistence.go
test/e2e/tests/udproute.go
tools/linter/golangci-lint/.golangci.yml

* and fix all the warnings
Fixes: https://github.com/envoyproxy/gateway/issues/7053

perf: enable prealloc linter

---

internal/provider/kubernetes/controller.go
internal/provider/kubernetes/kubernetes_test.go
internal/provider/kubernetes/resource.go

If a service was refenered by different backendRef, shouldn't be added to `resourceMappings` multiple times.

fix: do not add same service multiple times

---

internal/provider/kubernetes/controller.go
internal/provider/kubernetes/controller_test.go
internal/provider/kubernetes/resource.go
internal/provider/kubernetes/routes_test.go

* Sets compare by value and BackendRef contain multiple ptrs to Kind, Group and Namespace, so this Set didnt really serve us any good purpose of deduping same backendRefs
* Instead use maps keyed by a util string - NamespaceNameWithGroupKind similar to what we use for ExtentionRefFilters

fix: use maps for backendRefMappings instead of Sets
