README.md
Adds EG introduction blog post reference in readme.
Fixes #56 
=> Adds intro blog post to readme

docs/design/SYSTEM_DESIGN.md
=> Document Gateway API and Envoy data plane mapping

README.md
=> README: add status badge for build & test workflow

docs/design/SYSTEM_DESIGN.md
=> Limit EG to a single GatewayClass

README.md
Signed-off-by: Xunzhuo <mixdeers@gmail.com>
=> Add redirect to gateway channel with one click

tools/docker/Dockerfile
Signed-off-by: hexiaodai <jianmin.he@daocloud.io>
=> Misc: unified dockerfile command style

.github/workflows/build_and_test.yaml, GOALS.md, tools/linter/lint-whitenoise, tools/make/lint.mk
=> lint: add whitenoise check

.github/workflows/stale.yml
=> ci: add stale bot

tools/make/golang.mk
=> ci: add tidy lint

.github/workflows/build_and_test.yaml, tools/make/common.mk, tools/make/golang.mk, tools/make/image.mk, tools/make/lint.mk
Update `make help`:
- add missing targets
- add run in docker comment as we still support it
=> chore: update help info

tools/make/image.mk
Fix https://github.com/envoyproxy/gateway/issues/140
=> chore: fix image build

tools/make/common.mk, tools/make/golang.mk, tools/make/image.mk
Introduce log function to unify log.
Usage:
```
target:
@$(LOG_TARGET)
@$(call log, "log info")
=> chore: unify log

.gitattributes
**Adds .gitattributes**
xref: https://github.com/envoyproxy/gateway/issues/127
Signed-off-by: Sachin Chavan <chavansachin295@gmail.com>
=> add .gitattributes to auto collapse generated files

internal/provider/kubernetes/kubernetes_test.go
=> internal/provider: make test eventually consistent

internal/gatewayapi/helpers.go, internal/gatewayapi/testdata/gateway-with-listener-with-tls-secret-in-other-namespace-allowed-by-refgrant.in.yaml, internal/gatewayapi/testdata/gateway-with-listener-with-tls-secret-in-other-namespace-allowed-by-refgrant.out.yaml, internal/gatewayapi/testdata/httproute-with-backendref-in-other-namespace-allowed-by-refgrant.in.yaml, internal/gatewayapi/testdata/httproute-with-backendref-in-other-namespace-allowed-by-refgrant.out.yaml, internal/gatewayapi/testdata/httproute-with-invalid-backendref-in-other-namespace.in.yaml, internal/gatewayapi/testdata/httproute-with-invalid-backendref-in-other-namespace.out.yaml, internal/gatewayapi/translator.go, internal/gatewayapi/translator_test.go
Adds support for ReferenceGrant for
Gateway to Secret TLS certificate refs
and HTTPRoute to Service backend
refs.
Closes #160.
=> implements ReferenceGrant

internal/ir/infra.go
Adds initial data plane infrastructure management IR.
xref #41
=> Adds Initial Infra IR

internal/ir/xds.go, internal/ir/xds_test.go
Fixes: https://github.com/envoyproxy/gateway/issues/119
=> [ir] Validate IR XDS

go.mod
Cleans-up go deps.
xref: https://github.com/envoyproxy/gateway/pull/202#discussion_r948171477
=> Tidys Go Deps

internal/provider/kubernetes/config/rbac/kustomization.yaml, internal/provider/kubernetes/config/rbac/role.yaml, internal/provider/kubernetes/config/rbac/role_binding.yaml, internal/provider/kubernetes/rbac.go, tools/make/kube.mk
=> add RBAC markers and fix RBAC generation

internal/infrastructure/kubernetes/deployment.go
fixes: https://github.com/envoyproxy/gateway/issues/225
=> Use strings.Builder to manage Envoy Bootstrap Config

tools/hack/create-cluster.sh
=> fix nit in create-cluster.sh

.gitignore
update gitignore for GoLand and vscode
=> update gitignore for GoLand and vscode

tools/make/kube.mk
Fix #255
Signed-off-by: Xunzhuo <mixdeers@gmail.com>
=> fix: make kube-undeploy repeated delete crds

internal/gatewayapi/runner/runner.go, internal/message/types.go, internal/message/types_test.go, internal/provider/kubernetes/httproute.go, internal/provider/kubernetes/kubernetes_test.go
Adds namespace support to watchable ProviderResources.
Fixes #229 
=> Adds Namespaces to Watchable ProviderResources

tools/hack/create-cluster.sh
Fix: #253
Signed-off-by: Xunzhuo <mixdeers@gmail.com>
=> fix: wrap confused error when creating kind

internal/infrastructure/kubernetes/deployment.go
=> Updates Envoy Label K/V Pair

internal/provider/kubernetes/config/rbac/role.yaml, internal/provider/kubernetes/rbac.go
Updates RBAC for Infra Manager to manage Envoy resources.
Fixes: #261 
=> Updates RBAC for Infra Manager Permissions

.github/workflows/build_and_test.yaml
Switch this to be a Make target
cc @LukeShu 
=> ci: use make targets instead actions

.github/workflows/release.yaml, tools/make/image.mk
=> feat(ci): add EG release workflows

internal/gatewayapi/testdata/gateway-allows-same-namespace-with-disallowed-httproute.out.yaml, internal/gatewayapi/translator.go
=> translator: Gateway API Translator Should Support * Listener Hostnames

.github/workflows/release.yaml
Resolves: https://github.com/envoyproxy/gateway/issues/311
=> feat: support auto upload release manifests

README.md, docs/user/QUICKSTART.MD
Fixes: #275 
Requires: https://github.com/envoyproxy/gateway/pull/300
=> Adds Quickstart Guide

docs/user/QUICKSTART.MD
Removes `tree` from the URL path.
=> Fixes Quickstart Guide URLs

internal/infrastructure/kubernetes/bootstrap.yaml.tpl, internal/infrastructure/kubernetes/deployment.go, internal/infrastructure/kubernetes/deployment_test.go
part of https://github.com/envoyproxy/gateway/issues/280
listener access log will be implement later
=> accesslog: make admin accesslog path configurable

.github/workflows/build_and_test.yaml
fix: https://github.com/envoyproxy/gateway/pull/313#discussion_r961019619
cc @arkodg 
before: https://github.com/envoyproxy/gateway/pull/313
=> fix: add dev image with commit tag in GHA

tools/make/image.mk
Fixes: https://github.com/envoyproxy/gateway/issues/307
=> fix: unexpected verify errors

docs/user/QUICKSTART.MD
=> fix: `GATEWAY_HOST` excuted failed

internal/infrastructure/kubernetes/infra.go, internal/infrastructure/manager.go
=> move infra kube logic into infra kube manager

README.md, docs/user/QUICKSTART.md
=> minor Quickstart nits

DEVELOPER.md
Fixes: https://github.com/envoyproxy/gateway/issues/295
=> update DEVELOPER docs

internal/infrastructure/kubernetes/infra.go, internal/utils/env/env.go, internal/utils/env/env_test.go
=> add utils/env package

tools/hack/create-cluster.sh, tools/hack/run-kube-local.sh, tools/make/lint.mk
Resolve: https://github.com/envoyproxy/gateway/issues/314
=> ci: add shellcheck to lint hack scripts

internal/gatewayapi/testdata/gateway-allows-same-namespace-with-allowed-httproute.out.yaml, internal/gatewayapi/testdata/gateway-allows-same-namespace-with-disallowed-httproute.out.yaml, internal/gatewayapi/testdata/gateway-with-listener-with-invalid-allowed-namespaces-selector.out.yaml, internal/gatewayapi/testdata/gateway-with-listener-with-invalid-allowed-routes-group.out.yaml, internal/gatewayapi/testdata/gateway-with-listener-with-invalid-allowed-routes-kind.out.yaml, internal/gatewayapi/testdata/gateway-with-listener-with-invalid-tls-configuration-invalid-mode.out.yaml, internal/gatewayapi/testdata/gateway-with-listener-with-invalid-tls-configuration-no-certificate-refs.out.yaml, internal/gatewayapi/testdata/gateway-with-listener-with-invalid-tls-configuration-secret-does-not-exist.out.yaml, internal/gatewayapi/testdata/gateway-with-listener-with-invalid-tls-configuration-secret-in-other-namespace.out.yaml, internal/gatewayapi/testdata/gateway-with-listener-with-invalid-tls-configuration-secret-is-not-valid.out.yaml, internal/gatewayapi/testdata/gateway-with-listener-with-missing-allowed-namespaces-selector.out.yaml, internal/gatewayapi/testdata/gateway-with-listener-with-tls-secret-in-other-namespace-allowed-by-refgrant.out.yaml, internal/gatewayapi/testdata/gateway-with-listener-with-unsupported-protocol.out.yaml, internal/gatewayapi/testdata/gateway-with-listener-with-valid-tls-configuration.out.yaml, internal/gatewayapi/testdata/gateway-with-two-listeners-with-same-port-and-hostname.out.yaml, internal/gatewayapi/testdata/gateway-with-two-listeners-with-same-port-and-incompatible-protocol.out.yaml, internal/gatewayapi/testdata/httproute-attaching-to-gateway-with-two-listeners.out.yaml, internal/gatewayapi/testdata/httproute-attaching-to-gateway.out.yaml, internal/gatewayapi/testdata/httproute-attaching-to-listener-on-gateway-with-two-listeners.out.yaml, internal/gatewayapi/testdata/httproute-attaching-to-listener.out.yaml, internal/gatewayapi/testdata/httproute-rule-with-multiple-backends-and-no-weights.out.yaml, internal/gatewayapi/testdata/httproute-rule-with-multiple-backends-and-weights.out.yaml, internal/gatewayapi/testdata/httproute-with-backendref-in-other-namespace-allowed-by-refgrant.out.yaml, internal/gatewayapi/testdata/httproute-with-invalid-backendref-in-other-namespace.out.yaml, internal/gatewayapi/testdata/httproute-with-non-matching-specific-hostname-attaching-to-gateway-with-wildcard-hostname.out.yaml, internal/gatewayapi/testdata/httproute-with-single-rule-with-exact-path-match.out.yaml, internal/gatewayapi/testdata/httproute-with-single-rule-with-path-prefix-and-exact-header-matches.out.yaml, internal/gatewayapi/testdata/httproute-with-specific-hostname-attaching-to-gateway-with-wildcard-hostname.out.yaml, internal/gatewayapi/testdata/httproute-with-two-specific-hostnames-attaching-to-gateway-with-wildcard-hostname.out.yaml, internal/ir/infra.go
=> infra: Pin Envoy Image to v1.23

internal/gatewayapi/runner/runner.go, internal/infrastructure/kubernetes/deployment.go, internal/infrastructure/kubernetes/deployment_test.go, internal/infrastructure/kubernetes/infra.go, internal/infrastructure/kubernetes/infra_test.go, internal/infrastructure/kubernetes/service.go, internal/infrastructure/kubernetes/service_test.go, internal/infrastructure/kubernetes/serviceaccount.go, internal/infrastructure/kubernetes/serviceaccount_test.go, internal/infrastructure/runner/runner.go, internal/provider/kubernetes/config/envoy-gateway/deploy_and_ns.yaml, internal/provider/kubernetes/gatewayclass.go, internal/provider/kubernetes/kubernetes_test.go, internal/xds/translator/runner/runner.go
Deletes managed proxy infra when `ir.Infra` is nil.
Fixes: #220 
=> Adds Delete Support to Infra Manager

internal/gatewayapi/contexts.go
=> fix: prevent panic when namespace is nil

internal/infrastructure/kubernetes/deployment.go, internal/infrastructure/kubernetes/deployment_test.go, internal/infrastructure/kubernetes/infra.go, internal/infrastructure/kubernetes/infra_test.go, internal/infrastructure/kubernetes/service.go, internal/infrastructure/kubernetes/service_test.go, internal/infrastructure/kubernetes/serviceaccount.go, internal/infrastructure/kubernetes/serviceaccount_test.go
Fixes: https://github.com/envoyproxy/gateway/issues/341
=> Update kube Infra resources if they already exist

internal/xds/translator/runner/runner_test.go
Fixes: https://github.com/envoyproxy/gateway/issues/227
=> Add test for xds translator runner

tools/hack/run-kube-local.sh, tools/make/kube.mk
=> fix: make run-kube-local failed

Makefile
=> chore: ignore unfriendly msg in every cmds

internal/provider/kubernetes/config/rbac/role.yaml, internal/provider/kubernetes/gateway.go, internal/provider/kubernetes/gateway_test.go, internal/provider/kubernetes/gatewayclass.go, internal/provider/kubernetes/kubernetes_test.go, internal/provider/kubernetes/rbac.go, internal/utils/slice/slice.go, internal/utils/slice/slice_test.go
=> Adds GatewayClass Finalizer

internal/provider/kubernetes/config/rbac/role.yaml, internal/provider/kubernetes/rbac.go
=> Updates Kube RBAC for Watching Envoy Deployment

DEVELOPER.md, tools/make/common.mk, tools/make/kube.mk
Fixes: #323 
+ Deploy custom EG image
+ Deploy latest EG image
+ Deploy released EG image
=> feat: support custom dev image in kube-deploy

internal/cmd/server.go
Fixes: https://github.com/envoyproxy/gateway/issues/405
=> close namespaces & services msgs when ctx is done

internal/gatewayapi/runner/runner.go
* wait until all the gateway API resources have been initialized before passing the xds IR to the xds translator
=> add checks for namespace and service notifications

test/conformance/conformance_test.go
Adds additional upstream conformance tests to improve coverage.
=> Adds Additional Conformance Tests

internal/infrastructure/runner/runner.go
=> infra-runner: move exit log statement out of loop

changelogs/0.0.1.yaml, changelogs/0.1.0.yaml
- Fixes the initial changelog incorrect semver.
- Changes the initial changelog area to "documentation" to more accurately reflect the initial release.
=> Fixes Changelog Bugs

internal/xds/translator/testdata/out/xds-ir/http-route-direct-response.listeners.yaml, internal/xds/translator/testdata/out/xds-ir/http-route-redirect.listeners.yaml, internal/xds/translator/testdata/out/xds-ir/http-route-request-headers.listeners.yaml, internal/xds/translator/testdata/out/xds-ir/http-route-weighted-invalid-backend.listeners.yaml, internal/xds/translator/testdata/out/xds-ir/http-route.listeners.yaml, internal/xds/translator/translator.go
Relates to https://github.com/envoyproxy/gateway/pull/458
=> Generate Delta xDs config in the xds translator

changelogs/0.2.0-rc1.yaml
This should have been done with the RC1 release.
=> Adds v0.2.0-RC1 Changelog

changelogs/0.2.0-rc2.yaml
=> Adds v0.2.0-rc2 Changelog

.github/workflows/release.yaml
=> release GHA: fix variable name for tag

docs/user/QUICKSTART.md
Updates the quickstart for the v0.2.0-rc2 release.
=> Updates Quickstart for v0.2.0-rc2

internal/xds/translator/runner/runner_test.go
attempt to fix flakes seen in CI such as
https://github.com/envoyproxy/gateway/actions/runs/3154385185/jobs/5131916404#step:4:111
=> increase require eventually timeout

DEVELOPER.md
Relates to https://github.com/envoyproxy/gateway/issues/284
=> document workaround for conformance tests on Mac

DEVELOPER.md
- Adds a lint to Kind docs.
- Fixes a grammatical error.
=> Updates Dev Guide

DEVELOPER.md
Relates to https://github.com/envoyproxy/gateway/pull/418
=> add `make kube-demo` to DEVELOPER docs

internal/xds/translator/runner/runner_test.go
Renable with https://github.com/envoyproxy/gateway/issues/504
=> Temporarily skip TestRunner

test/conformance/conformance_test.go
Fixes: https://github.com/envoyproxy/gateway/issues/430
Resolved by: https://github.com/envoyproxy/gateway/pull/508
=> fix(conformance): add HTTPRouteHeaderMatching case

internal/cmd/certgen.go, internal/cmd/versions.go
=> fix: cobra mismatched comments

tools/make/kube.mk
Fixes: https://github.com/envoyproxy/gateway/issues/527
=> fix: make kube-undeploy target failed

internal/cmd/server.go, internal/envoygateway/scheme.go, internal/gatewayapi/helpers.go, internal/gatewayapi/runner/runner.go, internal/message/types.go, internal/provider/kubernetes/gateway.go, internal/provider/kubernetes/gateway_test.go, internal/provider/kubernetes/testdata/in/referencegrant-experimental-crd.yaml, test/conformance/conformance_test.go
Adds support for TLS termination.
Fixes #471
=> Adds TLS Termination Support

test/conformance/conformance_test.go
=> rm duplicate HTTPRouteHeaderMatching test

examples/kubernetes/quickstart.yaml
Updates the `apiVersion` of the gateway API resources in `quickstart.yaml`. Resolves https://github.com/envoyproxy/gateway/issues/540
=> Update example manifest apiversion

tools/make/kube.mk
=> Removes run-kube-local Target

tools/make/golang.mk, tools/make/lint.mk, tools/make/tools.mk
Resolve: https://github.com/envoyproxy/gateway/issues/314
=> chore: add local shellcheck tools

docs/user/QUICKSTART.md
=> Fixes URL in Quickstart Doc

DEVELOPER.md
=> Updates Dev Doc to Use Gateway Ns/Name

examples/kubernetes/quickstart.yaml
Resolves: https://github.com/envoyproxy/gateway/issues/576
=> chore: use conformance echo-server

examples/kubernetes/quickstart.yaml
=> fix: add pod / ns env to echo server

.github/workflows/build_and_test.yaml, .github/workflows/pre_release.yaml
=> feat: support canary release of EG

DOCS.md
=> update docs.md with Markdown support

tools/make/kube.mk
=> fix: make kube-demo svc mismatched

docs/user/HTTP_REQUEST_HEADERS.md
Adds a user guide for configuring HTTPRoute request header modifications.
xref: https://github.com/envoyproxy/gateway/issues/501
=> Add HTTPRoute request header docs

docs/user/HTTP_REDIRECT.md, docs/user/http-redirect.md
Adds a user guide for configuring HTTPRoute redirects.
xref: #501 
=> Adds HTTPRoute Redirect Docs

internal/provider/kubernetes/gateway.go
Fixes: https://github.com/envoyproxy/gateway/issues/619
=> fix: panic when removing gateway

docs/dev/releasing.md
Requires: https://github.com/envoyproxy/gateway/pull/610
=> Update Release Procedure

.github/workflows/latest_release.yaml
=> Rename Canary Release workflow to Latest Release

docs/user/quickstart.md
Updates the Quickstart guide for the v0.2.0 release.
=> Updates Quickstart for v0.2.0 Release

docs/user/quickstart.md
Updates the Quickstart guide links for the v0.2.0 release.
=> Updates Quickstart Guide Links for v0.2.0 Release

.github/workflows/docs.yaml
=> Do not allow doc workflow to run when releasing for now

internal/gatewayapi/helpers.go, internal/gatewayapi/testdata/httproutes-with-multiple-matches.out.yaml, internal/gatewayapi/translator.go, internal/xds/translator/testdata/in/xds-ir/http-route.yaml, internal/xds/translator/testdata/out/xds-ir/http-route.routes.yaml
fix https://github.com/envoyproxy/gateway/issues/512
=> Add support for HTTPQueryParamMatch in Gateway API Translator

test/conformance/conformance_test.go
Relates to https://github.com/envoyproxy/gateway/issues/512
=> enable conformance tests for query param match

docs/design/system-design.md, docs/dev/DOCS.md
- Update the `watching.md` link's title on page https://gateway.envoyproxy.io/design/system-design.html
- Lack of env settings before you make the doc
=> docs: update a reference link and doc workflow

docs/dev/releasing.md
Adds a few details that are helpful to the release process.
=> Updates Release Doc

go.mod, go.sum
Fixes: https://github.com/envoyproxy/gateway/issues/599
=> bring in fixes from go-control-plane

docs/design/config-api.md, docs/design/gatewayapi-translator.md, docs/design/system-design.md, docs/design/watching.md
Updates design docs based on the current implementation (as of the v0.2).
=> Updates Design Docs for v0.2

docs/user/tls-passthrough.md
=> fix version to v0.2.0 in tls passthrough docs

internal/xds/translator/route.go, internal/xds/translator/testdata/out/xds-ir/http-route-weighted-invalid-backend.routes.yaml
=> xds: remove total_weights from weighted cluster

docs/dev/README.md, internal/ir/infra.go
=> update Envoy to v1.24

docs/releases.rst, docs/releases/README.md
Adds a doc that provides EG release details.
Fixes #663 
=> Adds Release Details Doc

internal/crypto/certgen_test.go
Signed-off-by: hexiaodai <jianmin.he@daocloud.io>
=> optimized generate certificate unit test

internal/gatewayapi/testdata/httproute-with-single-rule-with-multiple-rules.in.yaml, internal/gatewayapi/testdata/httproute-with-single-rule-with-multiple-rules.out.yaml, internal/gatewayapi/translator.go
Add regex support on http route matchtes
https://github.com/envoyproxy/gateway/issues/608
=> support regex on http route matches

README.md
Fixes broken links in README.
Fixes #692 
=> Fixes README Broken Links

.github/workflows/build_and_test.yaml
=> run conformance tests on three Kubernetes versions

docs/latest/user/http-redirect.md, docs/latest/user/secure-gateways.md, docs/v0.2.0/user/http-redirect.md, docs/v0.2.0/user/secure-gateways.md
Updates Secure Gateways and HTTP Redirect user guides to use echoserver instead of httpbin.
=> Updates User Docs to Use Echoserver

tools/make/docs.mk
Fixes: https://github.com/envoyproxy/gateway/issues/689
Created v0.2.0 to v0.5.0:
https://gateway.merbridge.cn/v0.5.0/
https://gateway.merbridge.cn/v0.4.0/
https://gateway.merbridge.cn/v0.3.0/
https://gateway.merbridge.cn/v0.2.0/
https://gateway.merbridge.cn/latest/
=> feat: support multi-release versions

internal/ir/infra.go
Fixes: https://github.com/envoyproxy/gateway/issues/672
=> feat: set envoyproxy image to envoy-dev latest in main

internal/ir/xds.go
Relates to https://github.com/envoyproxy/gateway/issues/642
=> Enhance HTTP IR to support GRPCRoute

GOVERNANCE.md
=> update VMware steering committee member

docs/latest/user/http-request-headers.md, docs/v0.2.0/user/http-request-headers.md
=> fix: request header modifier removing HTTPRoute

docs/latest/design/tcp-udp-design.md
=> minor wording changes on transparent mode

tools/make/common.mk, tools/make/docs.mk, tools/make/golang.mk, tools/make/kube.mk, tools/make/lint.mk
To solve the problem of invalid escape characters, add the - e option to the echo command in the ". mk" files in the gateway/tool/make directory
=> add -e to echo command

go.mod
=> chore: clean up go module

tools/make/common.mk, tools/make/docs.mk, tools/make/golang.mk, tools/make/image.mk, tools/make/kube.mk, tools/make/lint.mk
+ add LOG_TARGET to all make targets
+ sync and wrap all logs with log func
+ add errorlog func, and wrap all error log with it
=> chore: sync targets logs

tools/make/kube.mk
=> infra: wait for job succeeded

internal/infrastructure/kubernetes/bootstrap.yaml.tpl
fix: https://github.com/envoyproxy/gateway/issues/756
=> fix deprecated access_log_path

docs/latest/user/quickstart.md, docs/v0.2.0/user/quickstart.md
Adds a step to wait for Envoy Gateway to become available before creating Gateway API resources.
=> Adds Step to Quickstart

tools/make/lint.mk
Relates to https://github.com/envoyproxy/gateway/pull/490#discussion_r987335136
=> Explain why `lint-deps` was created

internal/provider/kubernetes/predicates.go
=> Refactors validateDeploymentForReconcile() Function

CODEOWNERS.md
fixes: https://github.com/envoyproxy/gateway/issues/785
thank you, folks!
cc @Xunzhuo @danehans @arkodg @AliceProxy
=> Adds zirain as a Maintainer

internal/gatewayapi/testdata/httproute-with-invalid-backend-ref-bad-port.out.yaml, internal/gatewayapi/translator.go
extract methods to remove duplication.
https://github.com/envoyproxy/gateway/issues/736
=> refactory gateway api translator

.github/workflows/docs.yaml, docs/latest/design/request-authentication.md, docs/latest/user/secure-gateways.md, docs/v0.2.0/user/secure-gateways.md
and also fix existing md errors
should address failures seen in https://github.com/envoyproxy/gateway/pull/826
=> Bump github-action-markdown-cli to 3.2.0

GOVERNANCE.md
Hi community:
From the very early stage of EG project, I started to participate and contribute to it. And I am one of maintainers of EG teams now. I am willing to contribute to EG for a long run. Meanwhile, I am working at @Tencent in China. I am applying Tencent to be one of members of Steering Committee : ) It would be great honor to be one of members of Steering Committee.
I list some infos about Tencent below:
[Tencent](https://www.tencent.com/en-us/index.html) is a world-leading internet and technology company that develops innovative products and services to improve the quality of life of people around the world.
Founded in 1998 with its headquarters in Shenzhen, China, Tencent's guiding principle is to use technology for good. Our communication and social services connect more than …
=> governmence: add Tencent to steering committee

internal/gatewayapi/helpers.go, internal/gatewayapi/resource.go, internal/gatewayapi/translator.go, internal/gatewayapi/zz_generated.deepcopy.go, internal/message/types.go, internal/provider/kubernetes/config/rbac/role.yaml, internal/provider/kubernetes/controller.go, internal/provider/kubernetes/predicates.go, internal/provider/kubernetes/predicates_test.go, internal/provider/kubernetes/rbac.go, internal/provider/kubernetes/routes.go, internal/provider/kubernetes/test/utils.go, internal/provider/kubernetes/testdata/in/grpcroute-experimental-crd.yaml
Relates to https://github.com/envoyproxy/gateway/issues/642
=> support GRPCRoute in kubernetes provider

tools/linter/yamllint/.yamllint
Fixes every comment in PR like
=> chore: ignore kustomization yaml linter

.github/dependabot.yml, tools/src/sphinx-build/requirements.txt
relates to https://github.com/envoyproxy/gateway/issues/848
=> revert sphinx to 5.3.0

internal/gatewayapi/contexts.go
Deduplicates the code associated with route status conditions
=> add RouteStatus API to RouteContext interface

docs/latest/releases/README.md
Fixes: https://github.com/envoyproxy/gateway/issues/846
=> schedule: add release manager of v0.3.0

internal/infrastructure/kubernetes/service.go
fixes: https://github.com/envoyproxy/gateway/issues/898
=> fix UDP service can't not be accessed through gateway cluster IP/external IP

.github/workflows/latest_release.yaml, tools/hack/check-latest-release.sh, tools/make/lint.mk
Fixes: https://github.com/envoyproxy/gateway/issues/888
Refer: https://github.com/Xunzhuo/gateway/actions/runs/3908443113/jobs/6678595581
=> feat: add check step to latest release

internal/gatewayapi/filters.go
=> fix: add mirrorFilter to HTTPFiltersTranslator interface

internal/cmd/version/version.go, internal/cmd/versions.go, tools/make/golang.mk
support json/yaml output
cc @Xunzhuo
=> cmd: improve version command

tools/make/docs.mk
fixes: #909
cc @Xunzhuo @arkodg
=> ci: fix make docs

.gitignore
This is for maintainer/contributor who wants to use GitHub Codespaces custom workspace.
cc @zirain @arkodg
=> chore: add devcontainer to gitignore

.github/dependabot.yml, .golangci.yml, internal/provider/kubernetes/config/samples/config_v1alpha1_envoyproxy.yaml, internal/xds/translator/testdata/in/xds-ir/multiple-listeners-same-port.yaml, internal/xds/translator/testdata/in/xds-ir/simple-tls.yaml, tools/linter/golangci-lint/.golangci.yml
=> lint: clean warn

docs/latest/design/ratelimit.md
part of https://github.com/envoyproxy/gateway/issues/857
cc @arkodg
=> ratelimit: fix doc demo

.golangci.yml, internal/xds/translator/translator_test.go, tools/linter/golangci-lint/.golangci.yml
=> golangci: add depguard

api/v1alpha1/ratelimitfilter_types.go, internal/gatewayapi/helpers.go, internal/gatewayapi/helpers_test.go, internal/gatewayapi/resource.go, internal/gatewayapi/zz_generated.deepcopy.go, internal/provider/kubernetes/config/crd/bases/gateway.envoyproxy.io_ratelimitfilters.yaml, internal/provider/kubernetes/config/crd/kustomization.yaml, internal/provider/kubernetes/config/rbac/role.yaml, internal/provider/kubernetes/controller.go, internal/provider/kubernetes/kubernetes_test.go, internal/provider/kubernetes/predicates.go, internal/provider/kubernetes/rbac.go, internal/provider/kubernetes/routes.go, internal/provider/kubernetes/routes_test.go, internal/provider/kubernetes/test/utils.go
=> Add RateLimitFilter support in k8s provider

docs/latest/user/udp-routing.md, docs/latest/user_docs.rst, examples/kubernetes/udp-routing-example-backend.yaml, examples/kubernetes/udp-routing.yaml
Docs for UDPRoute.
https://github.com/envoyproxy/gateway/issues/641
=> UDP Route doc

docs/latest/user/http-redirect.md, docs/latest/user/http-request-headers.md, docs/latest/user/http-response-headers.md, docs/latest/user/http-routing.md, docs/latest/user/http-traffic-splitting.md, docs/latest/user/http-urlrewrite.md, docs/latest/user/quickstart.md, docs/latest/user/secure-gateways.md, docs/latest/user/tcp-routing.md, docs/latest/user/tls-passthrough.md, docs/latest/user/udp-routing.md, docs/v0.2.0/user/http-redirect.md, docs/v0.2.0/user/http-request-headers.md, docs/v0.2.0/user/http-routing.md, docs/v0.2.0/user/http-traffic-splitting.md, docs/v0.2.0/user/quickstart.md, docs/v0.2.0/user/secure-gateways.md, docs/v0.2.0/user/tls-passthrough.md
- Adds line breaks to long lines.
- Removes static references to the supported Kube version in favor of linking to the compatibility matrix.
- Fixes grammatical errors.
- Adds spacing after section titles.
- Adds external link anchors where needed.
- Improves uniformity across user docs.
=> Minor User Doc Improvements

internal/gatewayapi/filters.go, internal/gatewayapi/testdata/httproute-with-valid-ratelimitfilter.in.yaml, internal/gatewayapi/testdata/httproute-with-valid-ratelimitfilter.out.yaml
=> ratelimit: support distinct header match

CODEOWNERS.md
Updates the title of the CODEOWNERS file.
=> Updates CODEOWNERS.md Title

internal/gatewayapi/helpers.go, internal/provider/kubernetes/controller.go, internal/provider/kubernetes/kubernetes_test.go, internal/provider/kubernetes/test/utils.go
=> Fixes RateLimit and Authn Index Funcs

.github/workflows/docs.yaml, docs/v0.2.0/conf.py
=> fix: gen docs failed

docs/latest/user/http-redirect.md, docs/latest/user/http-request-headers.md, docs/latest/user/http-response-headers.md, docs/latest/user/http-traffic-splitting.md, docs/latest/user/http-urlrewrite.md, docs/latest/user/quickstart.md, docs/latest/user/secure-gateways.md, examples/kubernetes/quickstart.yaml
Switch quickstart.yaml to use port 80, and update quickstart.md in the docs.
Fixes #644
Signed-off-by: Flynn <emissary@flynn.kodachi.com>
=> Switch the Quickstart to use port 80 instead of 8080.

internal/ir/infra.go
Reverts envoyproxy/gateway#958
=> Revert "Sets Envoy Proxy Image to v1.25"

internal/gatewayapi/contexts.go, internal/gatewayapi/filters.go, internal/gatewayapi/route.go
=> Grammar fixes for GRPCRoute related comments

docs/latest/dev/releasing.md
=> release: add missing VERSION update release step

internal/ir/infra.go
=> feat: set envoyproxy image tag to v1.25-latest

tools/make/image.mk
=> chore: add flags to skopeo to prevent errors

internal/xds/translator/authentication.go, internal/xds/translator/testdata/out/xds-ir/authn-multi-route-multi-provider.clusters.yaml, internal/xds/translator/testdata/out/xds-ir/authn-multi-route-single-provider.clusters.yaml, internal/xds/translator/testdata/out/xds-ir/authn-ratelimit.clusters.yaml, internal/xds/translator/testdata/out/xds-ir/authn-single-route-single-match.clusters.yaml
=> Use HTTP1.1 to connect to upstream jwks endpoint

internal/xds/translator/authentication.go, internal/xds/translator/ratelimit.go
=> align wellknown package

internal/globalratelimit/runner/runner.go, internal/infrastructure/kubernetes/deployment.go, internal/infrastructure/kubernetes/service.go, internal/xds/translator/listener.go, internal/xds/translator/ratelimit.go, internal/xds/translator/runner/runner.go, internal/xds/translator/testdata/out/xds-ir/authn-ratelimit.clusters.yaml, internal/xds/translator/testdata/out/xds-ir/ratelimit.clusters.yaml, internal/xds/translator/translator.go, internal/xds/translator/translator_test.go
=> Plug in rate limit service URL into xds cluster

docs/latest/user/rate-limit.md
=> user docs for global rate limit

docs/latest/user_docs.rst
Follow-up: https://github.com/envoyproxy/gateway/pull/989
=> docs: add ref to global ratelimit

api/config/v1alpha1/doc.go, api/config/v1alpha1/envoygateway_types.go, api/config/v1alpha1/envoyproxy_types.go, api/config/v1alpha1/shared_types.go, api/v1alpha1/authenticationfilter_types.go, api/v1alpha1/doc.go, api/v1alpha1/ratelimitfilter_types.go, docs/latest/api/config_types.md, docs/latest/api/extension_types.md, internal/provider/kubernetes/config/crd/bases/config.gateway.envoyproxy.io_envoyproxies.yaml, internal/provider/kubernetes/config/crd/bases/gateway.envoyproxy.io_authenticationfilters.yaml, internal/provider/kubernetes/config/crd/bases/gateway.envoyproxy.io_ratelimitfilters.yaml
Updates the godocs for APIs to improve the rendered markdown.
=> Updates API godocs for improved markdown rendering

internal/provider/kubernetes/testdata/in/gateway-experimental-crd.yaml, internal/provider/kubernetes/testdata/in/gatewayclass-experimental-crd.yaml, internal/provider/kubernetes/testdata/in/grpcroute-experimental-crd.yaml, internal/provider/kubernetes/testdata/in/httproute-experimental-crd.yaml, internal/provider/kubernetes/testdata/in/referencegrant-experimental-crd.yaml, internal/provider/kubernetes/testdata/in/tcproute-experimental-crd.yaml, internal/provider/kubernetes/testdata/in/tlsroute-experimental-crd.yaml, internal/provider/kubernetes/testdata/in/udproute-experimental-crd.yaml
=> chore: bump testdata to gwapi v0.6.1

.github/workflows/build_and_test.yaml, tools/hack/create-cluster.sh
Signed-off-by: Held, Jarad <jaradheld@gmail.com>
=> update to validate 1.26

docs/latest/releases.rst, docs/latest/releases/v0.3.md, release-notes/v0.3.0.yaml
=> release(v0.3.0): add release notes and release announcement

docs/latest/design/egctl.md, docs/latest/design/gatewayapi-support.md, docs/latest/design/request-authentication.md, docs/latest/design_docs.rst
Updates the Gateway API support doc.
=> Updates Gateway API Support Doc

docs/latest/user/authn.md, docs/latest/user/rate-limit.md, docs/v0.3.0/user/authn.md, docs/v0.3.0/user/rate-limit.md
=> use API docs links in authn & rateLimit doc

docs/latest/releases/README.md, docs/v0.3.0/releases/README.md
=> docs: update release management

internal/infrastructure/kubernetes/configmap.go, internal/infrastructure/kubernetes/deployment.go, internal/infrastructure/kubernetes/proxy_service.go, internal/infrastructure/kubernetes/service.go, internal/infrastructure/kubernetes/serviceaccount.go
fix #1041 
Signed-off-by: qicz <qiczzhu@gmail.com>
=> fix infra svc, deploy, cm update logic.

docs/latest/design/roadmap.md, docs/v0.3.0/design/roadmap.md
* Suggesting the theme to be - `Customize Envoy Gateway` to support a wider set of users and their use cases.
=> Update 0.4.0 roadmap items

internal/xds/translator/authentication.go, internal/xds/translator/testdata/in/xds-ir/authn-multi-route-multi-provider.yaml, internal/xds/translator/testdata/in/xds-ir/authn-ratelimit.yaml, internal/xds/translator/testdata/out/xds-ir/authn-multi-route-multi-provider.clusters.yaml, internal/xds/translator/testdata/out/xds-ir/authn-multi-route-multi-provider.listeners.yaml, internal/xds/translator/testdata/out/xds-ir/authn-multi-route-single-provider.clusters.yaml, internal/xds/translator/testdata/out/xds-ir/authn-ratelimit.clusters.yaml, internal/xds/translator/testdata/out/xds-ir/authn-ratelimit.listeners.yaml, internal/xds/translator/testdata/out/xds-ir/authn-single-route-single-match.clusters.yaml
=> translator: moves jwks DNS resolution into envoy

internal/cmd/egctl/config.go
=> fix: prevent egctl config all panics

internal/cmd/egctl/experimental.go, internal/cmd/egctl/translate.go
=> chore: add examples of egctl x translate examples

docs/latest/user/egctl.md, tools/hack/get-egctl.sh, tools/make/docs.mk
part of: https://github.com/envoyproxy/gateway/issues/1045
=> feat: add hack and docs for installing egctl

.github/workflows/build_and_test.yaml
Fixes: https://github.com/envoyproxy/gateway/actions/runs/4401024960/jobs/7707019204
=> ci: add helm login to prevent authorization failed

internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-root-path-url-prefix.clusters.yaml, internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-root-path-url-prefix.endpoints.yaml
main is broken after https://github.com/envoyproxy/gateway/pull/1118
=> fix error UT

internal/gatewayapi/filters.go, internal/gatewayapi/testdata/httproute-with-sourceip-ratelimit.in.yaml, internal/gatewayapi/testdata/httproute-with-sourceip-ratelimit.out.yaml, internal/ir/xds.go, internal/ir/zz_generated.deepcopy.go, internal/xds/translator/ratelimit.go, internal/xds/translator/testdata/in/ratelimit-config/masked-remote-address-match.yaml, internal/xds/translator/testdata/in/xds-ir/ratelimit-sourceip.yaml, internal/xds/translator/testdata/out/ratelimit-config/masked-remote-address-match.yaml, internal/xds/translator/testdata/out/xds-ir/ratelimit-sourceip.clusters.yaml, internal/xds/translator/testdata/out/xds-ir/ratelimit-sourceip.endpoints.yaml, internal/xds/translator/testdata/out/xds-ir/ratelimit-sourceip.listeners.yaml, internal/xds/translator/testdata/out/xds-ir/ratelimit-sourceip.routes.yaml, internal/xds/translator/translator_test.go
fixes: https://github.com/envoyproxy/gateway/issues/852
=> Implement source IP RateLimit

internal/gatewayapi/contexts.go
As #950 is fixed
Signed-off-by: muyuan0 <127020730+muyuan0@users.noreply.github.com>
=> Remove stale GRPCRoute workaround

internal/cmd/egctl/config.go, internal/cmd/egctl/config_test.go, internal/cmd/egctl/testdata/config/in/in.all.json, internal/cmd/egctl/testdata/config/out/out.all.json, internal/cmd/egctl/testdata/config/out/out.all.yaml, internal/cmd/egctl/testdata/config/out/out.endpoints.json, internal/cmd/egctl/testdata/config/out/out.endpoints.yaml
=> fix endpoint cannot retrieve bug.

docs/latest/user/egctl.md, internal/cmd/egctl/testdata/translate/in/default-resources.yaml, internal/cmd/egctl/testdata/translate/out/default-resources.all.yaml, internal/cmd/egctl/translate.go, internal/cmd/egctl/translate_test.go
Ref https://github.com/envoyproxy/gateway/issues/1122
=> feat(egctl): provide dummy Namespace resource

charts/gateway-helm/templates/NOTES.txt
We need to add ns to NOTES.txt.
=> helm: add namespace to notes

cmd/egctl/main.go, internal/cmd/egctl/config.go, internal/cmd/egctl/config_cmd.go, internal/cmd/egctl/experimental.go, internal/cmd/egctl/root.go, internal/cmd/egctl/translate.go, internal/cmd/egctl/version.go
- refactor egctl root cmd with the same way like eg
- refactor egctl config commands
- remove unnecessary new line
=> refactor: egctl root cmd & config commands.

api/config/v1alpha1/helpers.go, api/config/v1alpha1/shared_types.go, api/config/v1alpha1/zz_generated.deepcopy.go, charts/gateway-helm/crds/generated/config.gateway.envoyproxy.io_envoyproxies.yaml, internal/gatewayapi/testdata/envoyproxy-valid.in.yaml, internal/gatewayapi/testdata/envoyproxy-valid.out.yaml, internal/infrastructure/kubernetes/proxy_deployment.go, internal/infrastructure/kubernetes/proxy_deployment_test.go
=> support envoy proxy container resources settings.

go.mod, go.sum, internal/xds/server/runner/runner_test.go
=> test serveXdsServer failed to listen without gomonkey

OWNERS
=> owners: add @richarddli to admins

internal/cmd/egctl/testdata/translate/in/from-gateway-api-to-xds.yaml, internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.json, internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.yaml, internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.cluster.yaml, internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.endpoint.yaml, internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.listener.yaml, internal/cmd/egctl/translate.go
=> feat(egctl): translate the remain gateway api resources

.github/workflows/release.yaml, tools/make/kube.mk
Closes: https://github.com/envoyproxy/gateway/issues/1045
=> feat: support egctl releases

tools/make/kube.mk
Fixes https://github.com/envoyproxy/gateway/actions/runs/4605767589/jobs/8138221444
=> add missing helm-generate in generate-manifests

internal/xds/translator/cluster.go, internal/xds/translator/cluster_test.go
- https://github.com/envoyproxy/gateway/issues/1078
=> xds: add buildXdsCluster test

internal/xds/translator/cluster_test.go
Due to lack of Merge ordering between https://github.com/envoyproxy/gateway/pull/1257 and https://github.com/envoyproxy/gateway/pull/1107
=> Fix broken xds test

internal/cmd/egctl/testdata/translate/out/default-resources.all.yaml, internal/cmd/egctl/testdata/translate/out/echo-gateway-api.cluster.yaml, internal/cmd/egctl/testdata/translate/out/echo-gateway-api.route.json, internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.json, internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.yaml, internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.bootstrap.yaml, internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.cluster.yaml, internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.endpoint.yaml, internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.listener.yaml, internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.route.yaml, internal/cmd/egctl/testdata/translate/out/multiple-xds.route.json, internal/cmd/egctl/testdata/translate/out/quickstart.route.yaml, internal/cmd/egctl/testdata/translate/out/rejected-http-route.route.yaml, internal/cmd/egctl/translate.go, internal/cmd/egctl/translate_test.go, internal/gatewayapi/resource.go, internal/gatewayapi/translator.go
* Use a TranslationResult struct to hold output
=> refactor egctl translate

.github/workflows/assignee.yaml
auto cc @envoyproxy/gateway-reviewers
=> ci: auto assign reviewer-team when open pr

docs/latest/design/system-design.md
part support #1202 user face doc
=> doc: update envoyproxy dynamic configuration doc.

api/config/v1alpha1/helpers.go, api/config/v1alpha1/shared_types.go, api/config/v1alpha1/validate_test.go, docs/latest/user/rate-limit.md, internal/cmd/version/version.go, internal/envoygateway/config/decoder_test.go, internal/envoygateway/config/testdata/decoder/in/gateway-ratelimit.yaml, internal/infrastructure/kubernetes/ratelimit_deployment.go, internal/infrastructure/kubernetes/ratelimit_deployment_test.go
support #1296 
resolve #1203 review case
cc @arkodg @Xunzhuo
=> fix expose ratelimit image.

.github/workflows/build_and_test.yaml
* Remove k8s v1.24
* Bump patch versions for v1.25 and v1.26
=> test with k8s v1.27.0

docs/latest/user/customize-envoyproxy.md, docs/latest/user/egctl.md
Fixes: https://github.com/envoyproxy/gateway/issues/31
=> docs: for xds bootstrap

docs/latest/user/deployment-mode.md, docs/latest/user_docs.rst
Fixes https://github.com/envoyproxy/gateway/issues/1310
=> doc: add a user doc on deployment mode

.github/workflows/cherrypick.yaml
xref: https://github.com/envoyproxy/gateway/issues/1371
=> ci: allow cherrypick create pull-requests

.github/workflows/cherrypick.yaml
=> ci: allow cherrypick job to create branch

.github/workflows/build_and_test.yaml, charts/gateway-helm/templates/certgen.yaml, tools/linter/yamllint/.yamllint
Fixes: https://github.com/envoyproxy/gateway/issues/810
=> fix: Run yamllint on generated Install Manifests

docs/latest/dev/README.md
fix dev doc expire link
fix dev doc expire link
None
=> docs: fix dev doc expire link

docs/latest/dev/README.md
=> chore: correct dev README.md

internal/xds/translator/authentication.go, internal/xds/translator/testdata/in/xds-ir/authn-multi-route-multi-provider.yaml, internal/xds/translator/testdata/in/xds-ir/authn-multi-route-single-provider.yaml, internal/xds/translator/testdata/out/xds-ir/authn-multi-route-multi-provider.listeners.yaml, internal/xds/translator/testdata/out/xds-ir/authn-multi-route-single-provider.listeners.yaml
Description:
Support ratelimit based on jwt claims
Relates to #851 #1489
=> feat: Support for converting JWT claims into HTTP headers

api/config/v1alpha1/envoyproxy_types.go, charts/gateway-helm/crds/generated/config.gateway.envoyproxy.io_envoyproxies.yaml, docs/latest/api/config_types.md, internal/infrastructure/kubernetes/proxy/resource.go, internal/infrastructure/kubernetes/proxy/resource_provider_test.go, internal/infrastructure/kubernetes/proxy/resource_test.go, internal/infrastructure/kubernetes/proxy/testdata/deployments/bootstrap.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/component-level.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/custom.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/default-env.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/extension-env.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/volumes.yaml
=> api: update ProxyLogging

internal/infrastructure/kubernetes/ratelimit/resource.go
docs: fix code comment grammar error
Fixes #
=> fix(typo): fix redis comment typo

internal/globalratelimit/runner/runner.go, internal/infrastructure/kubernetes/ratelimit/resource.go, internal/infrastructure/kubernetes/ratelimit/testdata/deployments/affinity.yaml, internal/infrastructure/kubernetes/ratelimit/testdata/deployments/custom.yaml, internal/infrastructure/kubernetes/ratelimit/testdata/deployments/default-env.yaml, internal/infrastructure/kubernetes/ratelimit/testdata/deployments/default.yaml, internal/infrastructure/kubernetes/ratelimit/testdata/deployments/extension-env.yaml, internal/infrastructure/kubernetes/ratelimit/testdata/deployments/override-env.yaml, internal/infrastructure/kubernetes/ratelimit/testdata/deployments/redis-tls-settings.yaml, internal/infrastructure/kubernetes/ratelimit/testdata/deployments/tolerations.yaml, internal/infrastructure/kubernetes/ratelimit/testdata/deployments/volumes.yaml
add TLS Support between the gateway and ratelimted services
Relates to https://github.com/envoyproxy/gateway/issues/1454
=> feat(crypto): add ratelimit xds tls function

api/config/v1alpha1/shared_types.go
Fixes deployment strategy to remove patch strategy tag.
=> fix: Fixes deployment strategy to remove patch strategy tag.

api/config/v1alpha1/testdata/different-dynamic-resources-user-bootstrap.yaml, api/config/v1alpha1/testdata/different-xds-cluster-address-bootstrap.yaml, api/config/v1alpha1/testdata/missing-admin-address-user-bootstrap.yaml, api/config/v1alpha1/testdata/valid-user-bootstrap.yaml, docs/latest/user/customize-envoyproxy.md, docs/latest/user/egctl.md, docs/v0.4.0/user/customize-envoyproxy.md, internal/cmd/egctl/testdata/translate/out/default-resources.all.yaml, internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.json, internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.yaml, internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.bootstrap.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/custom.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/default-env.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/extension-env.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/volumes.yaml, internal/xds/bootstrap/bootstrap.yaml.tpl
Description:
modify the bootstrap configuration to remove deprecated fields
Relates to #1538
=> chore: modify the bootstrap configuration to remove deprecated fields

examples/fluent-bit/helm-values.yaml, examples/otel-collector/helm-values.yaml, test/config/gatewayclass.yaml, test/e2e/tests/accesslog.go, tools/make/kube.mk
the previous implement is wrong, this patch fix it and add tests for OpenTelemetry sink
=> e2e: improve accesslog tests

internal/xds/cache/snapshotcache.go
=> fix: fixes snapshotcache invalid memory address or nil pointer.

test/conformance/conformance_test.go
Description:
Fix and enable the skipped HTTPRouteRequestMirror conformance test
Fixes #1522
=> fix: fix HttpRouteRequestMirror test

internal/cmd/server.go
optimize the dump the EG config logic just needs in debug mode.
cc @Xunzhuo @arkodg
=> refactor: optimize dump the EG config logic in debug mode.

docs/latest/user/customize-envoyproxy.md
fix docs typo: https://gateway.envoyproxy.io/latest/user/customize-envoyproxy.html
=> fix: fix docs typo

api/v1alpha1/ratelimitfilter_types.go, charts/gateway-helm/crds/generated/gateway.envoyproxy.io_ratelimitfilters.yaml, docs/latest/api/extension_types.md, docs/latest/user/rate-limit.md, internal/gatewayapi/filters.go, internal/ir/xds.go, internal/xds/translator/ratelimit.go, internal/xds/translator/testdata/in/ratelimit-config/distinct-remote-address-match.yaml, internal/xds/translator/testdata/in/xds-ir/ratelimit-sourceip.yaml, internal/xds/translator/testdata/out/ratelimit-config/distinct-remote-address-match.yaml, internal/xds/translator/testdata/out/xds-ir/ratelimit-sourceip.clusters.yaml, internal/xds/translator/testdata/out/xds-ir/ratelimit-sourceip.endpoints.yaml, internal/xds/translator/testdata/out/xds-ir/ratelimit-sourceip.routes.yaml, test/e2e/testdata/ratelimit-block-all-ips.yaml
This PR is the implementation for distinct rate limiting. 
The detailed description can be found in this issue: https://github.com/envoyproxy/gateway/issues/1150
=> Implementation for distinct rate limiting

.github/workflows/build_and_test.yaml
=> chore: fix ci publish order

test/e2e/tests/accesslog.go
=> e2e: fix OpenTelemetryAccessLog flaky

charts/gateway-helm/templates/envoy-gateway-config.yaml
=> chore: fix gateway cm garbled characters

internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.json
=> fix: incorrect comma in translate testdata

docs/latest/user/installation.md, docs/latest/user/quickstart.md, docs/latest/user_docs.rst
docs: add open ports to installation page
This PR adds new installation page which also includes all the open ports.
Fixes #1598
=> docs: add open ports to installation page

charts/gateway-helm/templates/envoy-gateway-config.yaml, charts/gateway-helm/values.tmpl.yaml
This PR updates the config map manifest in the helm chart to propagate the envoyGateway config map from values file.
Fixes #1607
=> fix(install/helm): envoy gateway configuration propagation from values file to config map

internal/infrastructure/kubernetes/infra_resource.go
optimize the envoy service account create or update logic
Fixes 
- #1604
=> refactor: optimize sa create or update and fix gateway memory leak on openshift.

internal/provider/kubernetes/kubernetes.go, internal/provider/kubernetes/kubernetes_test.go
Relates to https://github.com/envoyproxy/gateway/issues/1117
=> Implement Watch Namespaces

api/v1alpha1/envoypatchpolicy_types.go, charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoypatchpolicies.yaml, docs/latest/api/extension_types.md
* using kube-builder annotations
=> Improve EnvoyPatchPolicy CRD Validations

internal/gatewayapi/filters.go, internal/gatewayapi/testdata/httproute-with-invalid-ratelimitfilter.out.yaml
**What type of PR is this?**  chore
**What this PR does / why we need it**:  Enhance status error messages for RateLimitFilter extension #938
**Which issue(s) this PR fixes**: #938 
Fixes #
=> chore: Enhance status error messages for RateLimitFilter extension

test/e2e/tests/ratelimit.go
https://github.com/envoyproxy/gateway/issues/1616#issuecomment-1624130269
Fixes #1616
=> fix: improve stability of ratelimit tests

.github/workflows/latest_release.yaml
=> ci: add latest install of egctl

internal/cmd/egctl/testdata/translate/out/authn-single-route-single-match-to-xds.all.json
=> ci: fix testdata

docs/latest/dev/README.md
* feature added as part of https://github.com/envoyproxy/gateway/pull/1592
=> chore: add `make testdata` to dev docs

internal/cmd/egctl/testdata/translate/out/default-resources.all.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/custom.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/default-env.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/extension-env.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/volumes.yaml, internal/xds/bootstrap/bootstrap_test.go, internal/xds/bootstrap/testdata/default.yaml
=> chore: fix bootstrap lint

api/config/v1alpha1/validate.go, go.mod, internal/cmd/egctl/translate.go, internal/infrastructure/kubernetes/proxy/resource.go, internal/infrastructure/kubernetes/proxy/resource_provider.go, internal/infrastructure/kubernetes/proxy/resource_provider_test.go, internal/infrastructure/kubernetes/proxy/testdata/deployments/enable-prometheus.yaml, internal/xds/bootstrap/bootstrap.go, internal/xds/bootstrap/bootstrap.yaml.tpl, internal/xds/bootstrap/bootstrap_test.go, internal/xds/bootstrap/testdata/enable-prometheus.yaml, internal/xds/translator/cluster_test.go, test/config/gatewayclass.yaml, test/e2e/testdata/metric-prometheus.yaml, test/e2e/tests/metric.go
=> observability: implement proxy prometheus metric 

internal/infrastructure/kubernetes/infra_client.go, internal/infrastructure/kubernetes/ratelimit/resource_provider.go, internal/infrastructure/kubernetes/ratelimit/resource_provider_test.go, internal/infrastructure/kubernetes/ratelimit/testdata/deployments/affinity.yaml, internal/infrastructure/kubernetes/ratelimit/testdata/deployments/custom.yaml, internal/infrastructure/kubernetes/ratelimit/testdata/deployments/default-env.yaml, internal/infrastructure/kubernetes/ratelimit/testdata/deployments/default.yaml, internal/infrastructure/kubernetes/ratelimit/testdata/deployments/extension-env.yaml, internal/infrastructure/kubernetes/ratelimit/testdata/deployments/override-env.yaml, internal/infrastructure/kubernetes/ratelimit/testdata/deployments/redis-tls-settings.yaml, internal/infrastructure/kubernetes/ratelimit/testdata/deployments/tolerations.yaml, internal/infrastructure/kubernetes/ratelimit/testdata/deployments/volumes.yaml, internal/infrastructure/kubernetes/ratelimit/testdata/envoy-ratelimit-service.yaml, internal/infrastructure/kubernetes/ratelimit/testdata/envoy-ratelimit-serviceaccount.yaml, internal/infrastructure/kubernetes/ratelimit_deployment_test.go, internal/infrastructure/kubernetes/ratelimit_infra.go, internal/infrastructure/kubernetes/ratelimit_infra_test.go, internal/infrastructure/kubernetes/ratelimit_service_test.go, internal/infrastructure/kubernetes/ratelimit_serviceaccount_test.go, internal/infrastructure/runner/runner.go
=> feat: add owner reference for global envoy-ratelimit

docs/latest/user/http-request-mirroring.md, docs/latest/user_docs.rst
Adds user-doc for request mirroring via HTTPRoutes
=> Add request mirroring doc

internal/gatewayapi/helpers.go, internal/gatewayapi/helpers_test.go, internal/gatewayapi/testdata/grpcroute-with-valid-ratelimitfilter.in.yaml, internal/gatewayapi/testdata/grpcroute-with-valid-ratelimitfilter.out.yaml, internal/provider/kubernetes/controller.go, internal/provider/kubernetes/routes.go, internal/provider/kubernetes/routes_test.go
=> feat: add ratelimitfilter support for grpcroute

docs/latest/user/authn.md
Following good idea from https://github.com/envoyproxy/gateway/pull/1762#issuecomment-1664886119, extending request authentication user guide.
Fixes:
- https://github.com/envoyproxy/gateway/issues/1675
=> docs: using GRPCRoute with AuthenticationFilter

OWNERS, docs/latest/dev/CODEOWNERS.md
=> owner: add qicz to maintainers and move youngnick to emeritus

tools/make/helm.mk
* its not used anywhere and is indentical to `helm-package`
=> rm make target `helm-release`

docs/latest/user/quickstart.md
Fixes: https://github.com/envoyproxy/gateway/issues/1842
=> docs: add note in quickstart to ensure LB exists

README.md
=> docs: clean-up readme

internal/provider/kubernetes/routes.go
add `continue` to skip the not found filters that somehow missing in #1766 , nor it will get nil reference if we attach the grpcroute to a non-exist filter.
bug reported by @mazzy89
Fixes #
=> fix: skip the not found filters in grpc routes

docs/latest/design/client-traffic-policy.md
Relates to https://github.com/envoyproxy/gateway/issues/1846
=> design: ClientTrafficPolicy

internal/xds/translator/runner/runner.go, internal/xds/translator/runner/runner_test.go
=> fix: check error first before accessing the result during translation

internal/cmd/server.go, internal/gatewayapi/runner/runner.go, internal/globalratelimit/runner/runner.go, internal/infrastructure/runner/runner.go, internal/message/types.go, internal/provider/kubernetes/controller.go, internal/provider/kubernetes/kubernetes.go, internal/provider/kubernetes/kubernetes_test.go, internal/provider/runner/runner.go, internal/xds/server/runner/runner.go, internal/xds/translator/runner/runner.go
`EnvoyPatchPolicyStatuses` is passing from component to component on top level, this is not followed other policy logics and make it look weird, and if more policies add in the future, the style is not synced and not easy to maintain.
=> opt: codes

site/hugo.toml
=> fix: source link in github

site/content/en/latest/design/tracing.md, site/content/en/v0.5.0/design/tracing.md
docs: correcting doc name
since 0.5.0, the title of `design/tracing.md` is incorrect, causing duplicate doc name.
Fixes #
=> docs: correcting doc name

site/content/en/v0.5.0/user/tls-cert-manager.md
=> fix typos in tls-cert-manager.md

README.md
`fix: update readme link according to new website`
As we have migrated to Hugo. I found that most of the link on our README is not pointing to correct link. So updated that.
Fixes #
=> fix: update readme link according to new website

site/content/en/latest/design/config-api.md, site/content/en/latest/design/rate-limit.md
=> fix typos in docs

tools/make/docs.mk
=> chore: add docs clean targets

internal/provider/kubernetes/controller.go
=> Revert "add GenerationChanged predicate filter to all resources (#1988)"

site/hugo.toml
Fixes https://github.com/envoyproxy/gateway/issues/1986
=> fix: google search engine

site/content/en/latest/install/install-helm.md
Fixes https://github.com/envoyproxy/gateway/issues/1980
=> docs: update envoy gateway open ports

site/content/en/blog/presentations/kubecon-cn-2023/kubecon-cn-2023.md
update presentation link for kubecon 2023 shanghai
=> docs: update presentation link for kubecon 2023 shanghai

site/content/en/latest/user/grafana-integration.md
=> fix: wrong urls for grafana dashboards

.github/workflows/docs.yaml
Follow-up https://github.com/envoyproxy/gateway/issues/2026
=> fix: use make docs in docs workflows

site/content/en/latest/user/customize-envoyproxy.md, site/content/en/latest/user/grafana-integration.md
=> Fix broken links in docs

internal/cmd/egctl/envoy_stats.go, internal/cmd/egctl/stats.go
+ Fix json format output is invalid
+ Clean-up unused prom output type
+ Add alias and short for stats commands
=> fix: egctl stats invalid format

charts/gateway-helm/templates/NOTES.txt
https://gateway.envoyproxy.io/latest/user/quickstart.html is 404
should be https://gateway.envoyproxy.io/latest/user/quickstart now
=> helm: update quickstart ref

OWNERS
team: add new reviewers of eg
Add new reviewers of eg.
Fixes https://github.com/envoyproxy/gateway/issues/2020
=> team: add new reviewers of eg

api/v1alpha1/backendtrafficpolicy_types.go, api/v1alpha1/clienttrafficpolicy_types.go, api/v1alpha1/envoypatchpolicy_types.go, api/v1alpha1/envoyproxy_types.go, api/v1alpha1/securitypolicy_types.go, charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml, charts/gateway-helm/crds/generated/gateway.envoyproxy.io_clienttrafficpolicies.yaml, charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoypatchpolicies.yaml, charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml, charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml
* `btp` for `BackendTrafficPolicy`
* `ctp` for `ClientTrafficPolicy`
* `sp` for `SecurityPolicy`
* `epp` for `EnvoyPatchPolicy`
* `eproxy` for `EnvoyProxy`
=> add shortnames for EG CRDs

test/e2e/e2e_test.go
Relates to https://github.com/envoyproxy/gateway/issues/2095
=> Skip RateLimitBasedJwtClaimsTest test

api/v1alpha1/shared_types.go, internal/infrastructure/kubernetes/proxy/testdata/deployments/bootstrap.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/component-level.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/enable-prometheus.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-concurrency.yaml, internal/infrastructure/kubernetes/ratelimit/testdata/deployments/default.yaml
* Pin envoyproxy to v1.28
* Pin ratelimit to latest sha commit
=> [release/v0.6] Pin EnvoyProxy and RateLimit images

internal/xds/translator/ratelimit.go
Fixes https://github.com/envoyproxy/gateway/issues/2103
cc @zhaohuabing
=> fix: panic when using nil xdsRouteAction

internal/provider/kubernetes/kubernetes_test.go
Fixes https://github.com/envoyproxy/gateway/issues/2113
=> fix: testGatewayClassWithParamRef e2e test flaky

internal/cmd/egctl/testdata/translate/out/default-resources.all.yaml, internal/cmd/egctl/testdata/translate/out/envoy-patch-policy.all.yaml, internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.json, internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.yaml, internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.bootstrap.yaml, internal/cmd/egctl/testdata/translate/out/jwt-single-route-single-match-to-xds.all.json, internal/cmd/egctl/testdata/translate/out/jwt-single-route-single-match-to-xds.all.yaml, internal/cmd/egctl/testdata/translate/out/jwt-single-route-single-match-to-xds.bootstrap.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/custom.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/custom_with_initcontainers.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/default-env.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/enable-prometheus.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/extension-env.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/volumes.yaml, internal/xds/bootstrap/bootstrap.yaml.tpl, internal/xds/bootstrap/testdata/custom-stats-matcher.yaml, internal/xds/bootstrap/testdata/disable-prometheus.yaml, internal/xds/bootstrap/testdata/enable-prometheus.yaml, internal/xds/bootstrap/testdata/otel-metrics.yaml, internal/xds/translator/cluster_test.go
Replace deprecated option 'envoy.config.cluster.v3.Cluster.http2_protocol_options`
Fixes #2023
=> chore: fix http2_protocol_options  warning message

charts/gateway-helm/templates/_rbac.tpl
fix https://github.com/envoyproxy/gateway/issues/2127
=> fix Failed to update SecurityPolicy status

site/content/en/latest/user/jwt-authentication.md
=> fix jwt doc

.github/workflows/latest_release.yaml, tools/src/controller-gen/go.mod, tools/src/crd-ref-docs/go.mod, tools/src/golangci-lint/go.mod, tools/src/helm-docs/go.mod, tools/src/kind/go.mod, tools/src/protoc-gen-go-grpc/go.mod, tools/src/protoc-gen-go/go.mod, tools/src/setup-envtest/go.mod
https://github.com/envoyproxy/gateway/pull/2142 bumps root go version to 1.21 also in github action deps:
```
name: setup-deps
description: Install host system dependencies
runs:
using: composite
steps:
- uses: actions/setup-go@v3
with:
go-version: 1.21.x
cache: true
```
=> fix(ci): bump go version to 1.21

api/v1alpha1/loadbalancer_types.go, charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml, site/content/en/latest/api/extension_types.md
fix comments in loadbalancer api
Fixes #
=> fix comments in loadbalancer api

internal/xds/translator/cors.go
fix https://github.com/envoyproxy/gateway/issues/2132
=> fix: null pointer when CORS maxAge is not specified

site/content/en/blog/releases/v0.2.md, site/content/en/blog/releases/v0.3.md, site/content/en/blog/releases/v0.4.md, site/content/en/blog/releases/v0.5.md, site/content/en/blog/releases/v0.6.md
=> fix: matrix link in release note

site/content/en/latest/user/cors.md, site/content/en/v0.6.0/user/cors.md
=> docs: fix invalid title in cors

go.mod, go.sum, test/e2e/base/manifests.yaml, test/e2e/testdata/udproute.yaml, test/e2e/tests/udproute.go, tools/linter/codespell/.codespell.ignorewords
Fixes https://github.com/envoyproxy/gateway/issues/2011
=> Add E2E Tests for UDPRoute

internal/gatewayapi/clienttrafficpolicy.go, internal/gatewayapi/testdata/clienttrafficpolicy-proxyprotocol.in.yaml, internal/gatewayapi/testdata/clienttrafficpolicy-proxyprotocol.out.yaml, internal/ir/xds.go, internal/xds/translator/listener.go, internal/xds/translator/proxy_protocol.go, internal/xds/translator/testdata/in/xds-ir/listener-proxy-protocol.yaml, internal/xds/translator/testdata/out/xds-ir/listener-proxy-protocol.clusters.yaml, internal/xds/translator/testdata/out/xds-ir/listener-proxy-protocol.endpoints.yaml, internal/xds/translator/testdata/out/xds-ir/listener-proxy-protocol.listeners.yaml, internal/xds/translator/testdata/out/xds-ir/listener-proxy-protocol.routes.yaml, internal/xds/translator/translator_test.go
relates to https://github.com/envoyproxy/gateway/issues/1328
=> feat: proxy protocol in ClientTrafficPolicy

site/content/en/latest/user/basic-auth.md
Related to: https://github.com/envoyproxy/gateway/issues/1660
Close https://github.com/envoyproxy/gateway/issues/2227
=> user docs for basic auth

tools/make/kube.mk
=> chore: update otel collector chart version

site/content/en/latest/user/basic-auth.md, test/e2e/testdata/basic-auth.yaml, test/e2e/tests/basic-auth.go
fix https://github.com/envoyproxy/gateway/issues/2251#issuecomment-1831853013
=> fix flaky test

site/content/en/latest/user/client-traffic-policy.md
Fixes https://github.com/envoyproxy/gateway/issues/2032
=> docs: add ClientTrafficPolicy user guide

site/content/en/announcements/_index.md
=> Update Release Schedules

site/hugo.toml
=> docs: use / as baseURL domain

api/v1alpha1/shared_types.go, site/content/en/latest/api/extension_types.md, site/content/en/latest/user/customize-envoyproxy.md
Add user guide for EnvoyProxy HPA
Related to #2257.
Close #2272
=> docs: add user guide for EnvoyProxy HPA

site/content/en/latest/releases/v0.5.0-rc.1.md
=> fix(docs): v0.5.0-rc.1 title

.github/workflows/docs.yaml
fixes: https://github.com/envoyproxy/gateway/issues/1009
require two action secrets: 
- NETLIFY_SITE_ID
- NETLIFY_AUTH_TOKEN
more usage can be found: https://github.com/nwtgck/actions-netlify
=> feat: support docs preview

internal/provider/kubernetes/kubernetes.go
=> fix typo failted/failed

OWNERS
Fixes https://github.com/envoyproxy/gateway/issues/2302
=> membership: promote @zhaohuabing as maintainer

.github/workflows/build_and_test.yaml, .github/workflows/experimental_conformance.yaml
fixes: https://github.com/envoyproxy/gateway/pull/2317 https://github.com/envoyproxy/gateway/pull/2316
=> Update artifact deps

.github/workflows/cherrypick.yaml
=> ci: update cherry-pick v0.6.0

site/content/en/latest/user/cors.md
The cors configuration in the user doc is wrong.  See https://github.com/envoyproxy/gateway/issues/2312#issuecomment-1867177889
=> fix cors doc

.github/workflows/command.yaml
ref: https://github.com/envoyproxy/envoy/blob/main/.github/workflows/command.yml
fixes: https://github.com/envoyproxy/gateway/issues/2339
=> ci: fix retest command

.github/workflows/command.yaml
see output: https://api.github.com/repos/envoyproxy/gateway/commits/65865866256503e1d726fa7d018a89156bb4796a/check-runs
=> ci: update retest command app-owner

site/content/en/latest/user/global-rate-limit.md, site/content/en/latest/user/local-rate-limit.md
Related: https://github.com/envoyproxy/gateway/issues/2340
=> local rate limit user doc

internal/gatewayapi/backendtrafficpolicy.go, internal/gatewayapi/securitypolicy.go, internal/gatewayapi/testdata/backendtrafficpolicy-with-same-prefix-httproutes.in.yaml, internal/gatewayapi/testdata/backendtrafficpolicy-with-same-prefix-httproutes.out.yaml
fix https://github.com/envoyproxy/gateway/issues/2366
=> fix: perfix match

.github/dependabot.yml, .github/workflows/codeql.yml, tools/github-actions/setup-deps/action.yaml
* chore: setup codeql workflow 
Provides a Static Application Security Testing to comply with OSSF rules.
Relates to #2347
=> Setup Codeql workflow

.github/dependabot.yml, .github/workflows/command.yaml
cc @arkodg 
@tmsnan PTAL, you're the original author.
=> rollback retest action

.github/workflows/latest_release.yaml, .github/workflows/release.yaml
* fix token permissions 
Improve ossf conformity
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
=> ossf: fix token permissions

site/content/en/latest/user/fault-injection.md
docs: fault injection
Fixes #2124
=> docs: fault injection

site/content/en/latest/contributions/CODEOWNERS.md
* also added luke to emeritus and rearranged in alphabetical order
=> Add huabing to maintainers list

site/content/en/latest/user/oidc.md
=> Correct word spelling

internal/gatewayapi/securitypolicy.go
=> LogoutPath nil pointer fix

internal/cmd/egctl/config_test.go, internal/cmd/egctl/translate_test.go, internal/cmd/server_test.go, internal/gatewayapi/translator_test.go, internal/ir/xds_test.go, internal/xds/server/runner/runner_test.go, tools/linter/golangci-lint/.golangci.yml
* chore: testifylint: enable bool-compare, compares, require-error
Helps conformity with testify best practices 
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
=> testifylint: enable bool-compare, compares, require-error

internal/provider/kubernetes/predicates.go, internal/provider/utils/utils.go, internal/provider/utils/utils_test.go, site/content/en/latest/user/oidc.md
simplify `checkObjectNamespaceLabels`, and reduce loops.
Fixes #
=> simplify checkObjectNamespaceLabels

site/content/en/latest/user/customize-envoyproxy.md
Add user guide for EnvoyProxy extraArgs.
Related to #2489
=> docs: add user guide for EnvoyProxy extraArgs

internal/provider/kubernetes/predicates_test.go
=> chore: fix lint

site/content/en/latest/api/extension_types.md, tools/crd-ref-docs/templates/type.tpl
=> docs: show required for API doc

test/e2e/base/manifests.yaml, test/e2e/testdata/preserve-case.yaml, test/e2e/tests/preservecase.go
This PR adds an e2e test for the header case preservation feature implemented in #2506
=> e2e: Add an e2e test for the header case-preserving feature

OWNERS
nominating @liorokman & @guydc as Envoy Gateway reviewers
They've been very active in the community meetings, contributed multiple features, and have reviewed many PRs
=> add liorokman & guydc as reviewers

internal/xds/translator/testdata/out/xds-ir/upstream-tcpkeepalive.listeners.yaml
Between https://github.com/envoyproxy/gateway/pull/2585 &
https://github.com/envoyproxy/gateway/pull/2581
=> bug: fix merge race

internal/gatewayapi/validate.go, internal/provider/kubernetes/kubernetes_test.go, internal/provider/kubernetes/predicates.go, internal/provider/kubernetes/predicates_test.go, internal/provider/kubernetes/test/utils.go
=> fix: surface the status of listeners when MergeGateways enabled

internal/xds/translator/jwt.go, internal/xds/translator/testdata/in/xds-ir/jwt-multi-route-multi-provider.yaml, internal/xds/translator/testdata/out/xds-ir/jwt-multi-route-multi-provider.listeners.yaml
Relates to https://github.com/envoyproxy/gateway/issues/2452
=> feat: recomputeRoute for claim based routing

internal/gatewayapi/testdata/backendtrafficpolicy-with-circuitbreakers-error.out.yaml
fix merge race between #2683 and #2687
=> chore: fix merge race

site/content/en/latest/user/client-traffic-policy.md
Fixes: https://github.com/envoyproxy/gateway/issues/2676
=> docs: Timeouts in CTP

internal/gatewayapi/securitypolicy.go
this err will be always nil, since we have checked it above.
=> chore: remove duplicate logic for err

site/content/en/latest/user/http-routing.md
Fixes: https://github.com/envoyproxy/gateway/issues/2689
cc @arkodg
=> doc: add JWT claim base routing

test/e2e/e2e_test.go, tools/make/kube.mk
support run single e2e test:
```console
E2E_RUN_TEST=ClientTimeout make run-e2e
```
=> chore: support run single e2e test

charts/gateway-helm/templates/envoy-gateway-deployment.yaml, charts/gateway-helm/templates/envoy-gateway-metrics-service.yaml, charts/gateway-helm/values.tmpl.yaml, site/content/en/latest/install/api.md
fix / refactor monitoring service for envoy-gateway deployment
- deployment needs to expose port for it to be accessible via service
- there's no need to expose whole `ports` field from metrics service
- the port on deployment is static as it cannot be adjusted (https://gateway.envoyproxy.io/latest/design/eg-metrics/#envoygatewaymetrics)
N/A
=> fix(helm): refactor monitoring service

site/content/en/latest/user/retry.md
Fixes: https://github.com/envoyproxy/gateway/issues/2680
=> docs: Retry in BackendTrafficPolicy

tools/make/kube.mk
this will help people clean up after e2e
=> chore: add make uninstall-e2e-telemetry

.github/workflows/latest_release.yaml
cancel in progress when multi PRs merged in short time.
=> ci: set github action concurrency

.github/workflows/cherrypick.yaml
=> ci: update cherry-pick v1.0.0

OWNERS
Fixes https://github.com/envoyproxy/gateway/issues/2790
=> promote: guydc as maintainer

.github/workflows/build_and_test.yaml, site/content/en/latest/install/api.md
1. Fixed gen-check
2. Enable docs lint
=> Fix gen check

internal/cmd/egctl/testdata/translate/out/quickstart.all.yaml, internal/cmd/egctl/translate.go, internal/cmd/egctl/translate_test.go, site/content/en/latest/user/operations/egctl.md
Adds support for translating Gateway-API resources to IR.
Fixes #2798
=> feat(egctl): add support for egctl to translate from gateway-api resources to IR

site/content/en/latest/user/observability/proxy-observability.md
=> docs: update EnvoyProxy logs

site/content/en/latest/user/traffic/routing-outside-kubernetes.md
Fixes: https://github.com/envoyproxy/gateway/issues/2482
=> docs: Routing outside k8s

internal/cmd/certgen.go, internal/provider/kubernetes/secrets.go, internal/provider/kubernetes/secrets_test.go
Fix https://github.com/envoyproxy/gateway/issues/2823
=> Fix: failed to create envoy-oidc-hmac secret when upgrading EG

internal/cmd/certgen.go
=> fix existing secret check

api/v1alpha1/shared_types.go, internal/infrastructure/kubernetes/proxy/testdata/deployments/bootstrap.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/component-level.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/disable-prometheus.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/override-labels-and-annotations.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/patch-deployment.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/shutdown-manager.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-annotations.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-concurrency.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-extra-args.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-image-pull-secrets.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-node-selector.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-topology-spread-constraints.yaml
Envoy released v1.29.2, contains a codec revert which caused production incidents.
=> [Release-1.0] pin envoy to v1.29.2

site/content/en/latest/install/custom-cert.md
Fixes: https://github.com/envoyproxy/gateway/issues/866
=> docs: allow users to configure custom certs for control plane auth

site/content/en/latest/user/security/ext-auth.md
Remove the additional "\" in the ext auth doc, which was added by accident.  :-)
=> Remove the uncessary \

site/content/en/latest/user/security/backend-tls.md
=> docs: backend tls policy

internal/gatewayapi/securitypolicy.go, internal/gatewayapi/testdata/securitypolicy-override-replace.in.yaml, internal/gatewayapi/testdata/securitypolicy-override-replace.out.yaml
According to the [design decisions](https://gateway.envoyproxy.io/v0.6.0/design/security-policy/#design-decisions),  replacing with the most specific resource is the default behavior.
Part of https://github.com/envoyproxy/gateway/issues/2734
=> Change the Merge behavior to Replace for SecurityPolicy

internal/gatewayapi/backendtrafficpolicy.go, internal/gatewayapi/testdata/backendtrafficpolicy-override-replace.in.yaml, internal/gatewayapi/testdata/backendtrafficpolicy-override-replace.out.yaml
Fix https://github.com/envoyproxy/gateway/issues/2734
=> Change the Merge behavior to Replace for BackendTrafficPolicy

examples/kubernetes/merged-gateways.yaml, site/content/en/latest/contributions/design/system-design.md, site/content/en/latest/user/operations/deployment-mode.md
- add docs for merge gateways and multiple gatewayclass deployment modes
Fixes https://github.com/envoyproxy/gateway/issues/2030
Fixes https://github.com/envoyproxy/gateway/issues/2654
=> docs: multiple gatewayclass and merge gateways deployment mode

site/content/en/latest/user/operations/deployment-mode.md, site/content/en/v1.0.0/user/operations/deployment-mode.md
=> fix: deployment-mode doc markdown links

site/content/en/latest/user/security/threat-model.md, site/content/en/v1.0.0/user/security/threat-model.md
Fixes name spelling (mine) in the threat model.
None
=> docs: fix name spelling in threat model

test/helm/default.yaml, tools/make/common.mk, tools/make/helm.mk
this will help us to verify the helm chart changes
=> chore: add helm template test

test/helm/default.yaml
=> chore: fix helm-template

internal/gatewayapi/helpers.go, internal/gatewayapi/runner/runner.go, internal/gatewayapi/translator.go, internal/gatewayapi/translator_test.go
=> chore: set mergedGateways in translator runner

internal/xds/translator/testdata/in/xds-ir/oidc.yaml, internal/xds/translator/testdata/out/xds-ir/oidc.secrets.yaml, internal/xds/translator/translator_test.go
This PR adds missing secrets testdata for oidc
=> Add missing secrets testdata for oidc

internal/gatewayapi/securitypolicy.go
xref: https://github.com/envoyproxy/gateway/pull/2944/files/92cb2f87d0d1e28aa9f1556aa5025d8b9653656c#r1531169515
=> minor change to address a missing comment in #2944

test/e2e/tests/connection_limit.go
Temporarily disable connection limit e2e test since it's failing.
=> disable connection limit test

site/content/en/latest/user/traffic/connection-limit.md, test/e2e/testdata/connection-limit.yaml, test/e2e/tests/connection_limit.go
=> fix: use correct connection limit attribute name in e2e, docs

.github/workflows/cherrypick.yaml
learm from https://github.com/marketplace/actions/create-pull-request#action-inputs
=> ci: grant pull-requests permission to cherrypick action

ADOPTERS.md
=> Update ADOPTERS.md for Airspace Link

site/hugo.toml
=> docs: version desc

go.mod, internal/cmd/egctl/experimental.go, internal/cmd/egctl/install.go, internal/cmd/egctl/uninstall.go, internal/utils/helm/package.go, site/content/en/latest/user/operations/egctl.md
feat: Add install and uninstall subcommands to egctl
Fixes #2711
=> feat: add install and uninstall sub cmd to egctl

internal/xds/translator/httpfilters.go, internal/xds/translator/httpfilters_test.go
Change the fault filter order to first
Fixes #3046
=> refactor: reorder fault filter

site/content/en/v1.0.0/user/traffic/http-routing.md
* docs: fixes typo in http-routing.md
=> fixes minor typo in http-routing guide

test/e2e/tests/client_timeout.go
=> e2e: disable client timeout

.github/workflows/build_and_test.yaml
Codecov uploads recently started failing
relates to https://github.com/codecov/codecov-action/issues/1359
=> dont fail CI if codecov upload fails

api/v1alpha1/shared_types.go, internal/infrastructure/kubernetes/proxy/testdata/deployments/bootstrap.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/component-level.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/disable-prometheus.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/override-labels-and-annotations.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/patch-deployment.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/shutdown-manager.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-annotations.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-concurrency.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-extra-args.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-image-pull-secrets.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-node-selector.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-topology-spread-constraints.yaml
Release notes https://www.envoyproxy.io/docs/envoy/v1.29.3/version_history/v1.29/v1.29.3
=> [release/v1.0] Bump to Envoy v1.29.3

.github/dependabot.yml, .github/workflows/build_and_test.yaml
Until https://github.com/codecov/feedback/issues/112 is resolved
=> Revert codecov to v3

.github/workflows/docs.yaml, site/content/en/announcements/v1.0.md, site/content/en/blog/news/1.0-release/1.0-release.md, site/content/zh/_index.md
follow: https://github.com/envoyproxy/gateway/pull/3144
=> ci: remove continue-on-error

site/content/en/latest/contributions/RELEASING.md
=> docs: fix typo in release process

internal/infrastructure/kubernetes/ratelimit/resource_provider_test.go
fix: use ptr.To[uint32] intead of func()*uint32
=> fix: use ptr.To[uint32] intead of func()*uint32

site/content/en/latest/tasks/quickstart.md, site/content/en/v1.0.1/tasks/quickstart.md
(#3179)
docs PR
adds a subsection after completing the quickstart with a suggested list of tasks to try out.
Fixes #3179
=> docs: provides a suggested path through the docs after the quickstart

site/content/en/latest/api/extension_types.md
=> fix merge race caused by #3185

site/content/en/latest/tasks/quickstart.md
alternative for: https://github.com/envoyproxy/gateway/pull/3139
=> docs: use tabpane

internal/xds/translator/testdata/in/xds-ir/jsonpatch.yaml, internal/xds/translator/testdata/out/xds-ir/jsonpatch.listeners.yaml
found out when debuging https://github.com/envoyproxy/gateway/pull/3225
=> chore: update envoypatch test

test/e2e/tests/client_timeout.go, test/e2e/upgrade/eg_upgrade_test.go
nit in https://github.com/envoyproxy/gateway/pull/3306
=> e2e: disable EGUpgradeTest

internal/cmd/egctl/utils.go, test/e2e/e2e_test.go, test/e2e/embed.go, test/e2e/merge_gateways/merge_gateways_test.go, test/e2e/upgrade/eg_upgrade_test.go
=> chore: add gateway-api/apis/v1alpha3 to k8s client support

internal/cmd/egctl/status.go, internal/gatewayapi/translator.go
=> feat: add envoy extension policy support for egctl x status

examples/kubernetes/grpc-routing.yaml, examples/kubernetes/jwt/grpc-jwt.yaml
=> chore: update GRPCRoute version for examples

api/v1alpha1/zz_generated.deepcopy.go
Fix https://github.com/envoyproxy/gateway/issues/3401
=> fix: build is failing

site/content/en/latest/install/install-helm.md, site/content/zh/latest/install/api.md, site/content/zh/latest/install/custom-cert.md, site/content/zh/latest/install/install-helm.md, site/content/zh/latest/install/install-yaml.md
translate Install docs into Chinese:
```
site/content/zh/latest/install/api.md
site/content/zh/latest/install/custom-cert.md
site/content/zh/latest/install/install-helm.md
site/content/zh/latest/install/install-yaml.md
```
=> docs(zh): translate Install docs into Chinese

site/content/zh/latest/releases/_index.md, site/content/zh/latest/releases/v1.0.0.md, site/content/zh/latest/releases/v1.0.1.md
Translate releases docs (1.0.0 and 1.0.1 only) into Chinese:
```
site/content/zh/latest/releases/_index.md
site/content/zh/latest/releases/v1.0.0.md
site/content/zh/latest/releases/v1.0.1.md
```
=> docs(zh): translate releases docs (1.0.0 and 1.0.1 only) into Chinese

.github/workflows/build_and_test.yaml
See https://github.com/envoyproxy/gateway/pull/3421#issuecomment-2119107790
Fixes #
=> ci: fix codecov upload on dependabot PRs

internal/gatewayapi/testdata/envoyproxy-tls-settings-invalid-ns.out.yaml, internal/gatewayapi/testdata/envoyproxy-tls-settings-invalid.out.yaml, site/content/en/latest/api/extension_types.md
Fixes some gen missing in #3103 and #3441
=> chore: fix ci

charts/gateway-helm/README.md, site/content/en/latest/install/api.md, site/content/en/latest/install/gateway-helm-api.md, site/content/en/latest/install/install-helm.md, tools/helm-docs/api.gotmpl, tools/helm-docs/readme.gotmpl, tools/make/docs.mk
fixes: https://github.com/envoyproxy/gateway/issues/3392
=> docs: use helm-docs template

api/v1alpha1/accesslogging_types.go, api/v1alpha1/envoyproxy_metric_types.go, api/v1alpha1/ext_auth_types.go, api/v1alpha1/shared_types.go, api/v1alpha1/tracing_types.go, charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml, charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml, site/content/en/latest/api/extension_types.md
xref: https://github.com/envoyproxy/gateway/pull/3469#discussion_r1618090041
=> fix api nit

.github/codecov.yml
- add `test` to codecov ignore path
- update `zz_generated` file pattern according to https://github.com/envoyproxy/gateway/blob/eaa685d5174918c6093d08728b1014e5c7be8b52/.gitattributes#L7
Fixes #
=> chore: update codecov ignore path

internal/xds/translator/route.go, internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-url-fullpath.routes.yaml, test/e2e/testdata/httproute-rewrite-full-path.yaml, test/e2e/tests/httproute-rewrite-full-path.go
Takes https://github.com/envoyproxy/gateway/pull/2817 forward
=> fix: ReplaceFullPath not working for root path (/)

site/content/en/latest/tasks/observability/grafana-integration.md, site/content/en/v0.6.0/user/grafana-integration.md, site/content/en/v1.0.1/tasks/observability/grafana-integration.md
=> fix: doc broken links

site/content/en/latest/tasks/traffic/gatewayapi-support.md
Fixes https://github.com/envoyproxy/gateway/issues/2572
=> docs: Update docs on gwapi support for backendref filters

charts/gateway-addons-helm/README.md, charts/gateway-helm/README.md, site/content/en/latest/install/gateway-addons-helm-api.md, site/content/zh/latest/install/gateway-addons-helm-api.md, tools/helm-docs/api.gotmpl, tools/helm-docs/readme.gateway-addons-helm.gotmpl, tools/helm-docs/readme.gateway-helm.gotmpl, tools/make/docs.mk, tools/make/helm.mk
=> chore: update make helm-readme-gen

test/config/gatewayclass.yaml, test/e2e/e2e_test.go, test/e2e/multiple_gc/multiple_gc_test.go, test/e2e/testdata/internet-gc.yaml, test/e2e/testdata/private-gc.yaml, test/e2e/tests/multiple-gc.go, test/e2e/tests/tests.go, tools/make/kube.mk
Adopted from https://gateway-api.sigs.k8s.io/api-types/gatewayclass/#gatewayclass
Fixes https://github.com/envoyproxy/gateway/issues/3364
=> e2e: basic multiple gc test

.github/workflows/docs.yaml, site/content/en/v1.0.2/releases/v1.0.2.md
docs: sync 1.0.2 release note to 1.0.2
=> docs: sync 1.0.2 release note to 1.0.2 and fix CI

site/content/zh/latest/releases/v1.0.2.md
Translate release note 1.0.2 into Chinese
=> docs(zh): translate release note 1.0.2 into Chinese

test/e2e/tests/ext_proc.go
=> fix: add retries to ext-proc tests

site/content/en/latest/_index.md, site/content/en/v1.0.2/_index.md
Envoy Gateway is GA and stable, and the alert is no longer applicable
=> docs: rm active development alert

internal/gatewayapi/status/gateway.go
We can always compute how many items `gwAddresses` will get. 
No reason not to preallocate it for a better performance then.
Fixes #
=> chore: preallocate a list of addresses

internal/gatewayapi/envoyextensionpolicy.go, internal/gatewayapi/testdata/envoyextensionpolicy-override-replace.out.yaml, internal/gatewayapi/testdata/envoyextensionpolicy-with-extproc-with-backendtlspolicy.out.yaml, internal/gatewayapi/testdata/envoyextensionpolicy-with-extproc-with-multiple-backendrefs.out.yaml, internal/xds/translator/testdata/in/xds-ir/ext-proc.yaml, internal/xds/translator/testdata/out/xds-ir/ext-proc.listeners.yaml, internal/xds/translator/testdata/out/xds-ir/ext-proc.routes.yaml
Befor: "envoyextensionpolicy/default/policy-for-gateway/0"
After:  "envoyextensionpolicy/default/policy-for-gateway/extproc/0"
Also make it aligned with the wasm ir name.
=> chore: add "extproc" to extproc ir name

go.mod, site/go.mod, tools/src/buf/go.mod, tools/src/controller-gen/go.mod, tools/src/crd-ref-docs/go.mod, tools/src/golangci-lint/go.mod, tools/src/helm-docs/go.mod, tools/src/kind/go.mod, tools/src/protoc-gen-go-grpc/go.mod, tools/src/protoc-gen-go/go.mod, tools/src/setup-envtest/go.mod
https://github.com/envoyproxy/gateway/actions/runs/9769446823/job/26968894833
=> bump go to 1.22.5

internal/wasm/httpfetcher_test.go
fix https://github.com/envoyproxy/gateway/pull/3758
=> fix flaky wasm download test

site/content/en/latest/tasks/operations/customize-envoyproxy.md
close: https://github.com/envoyproxy/gateway/issues/3455
=> docs for customized filter order

site/content/en/latest/tasks/security/basic-auth.md
Should use https instead of http in the test command.
=> fix basic auth doc

.github/workflows/cherrypick.yaml
=> ci: update cherry-pick v1.1.0

site/content/en/news/releases/notes/v1.1.0-rc.1.md, tools/make/common.mk
with this, it's also part of gen-check, and will help https://github.com/envoyproxy/gateway/pull/3810#issuecomment-2221802226.
=> chore: release-notes-docs be part of generate

site/content/en/latest/tasks/observability/grafana-integration.md, site/content/en/v1.0.2/tasks/observability/grafana-integration.md
Reverts envoyproxy/gateway#3818
=> Revert "docs: fix grafana link"

release-notes/v1.1.0-rc.1.yaml, site/content/en/latest/tasks/quickstart.md, site/content/en/news/releases/notes/v1.1.0-rc.1.md, tools/src/release-notes-docs/yml2md.py
- Adds breaking changes
- Adds Deprecation notice
Replaces #3810
=> docs: update v1.1.0-rc.1 release notes

internal/globalratelimit/runner/runner.go
This PR make the rate limit runner report a translate error to `errChan`.
It makes those errors correctly observed in the metric.
https://github.com/envoyproxy/gateway/blob/main/internal/message/watchutil.go#L57
Fixes #
=> chore: report a translate error to errChan to make it observed correctly

internal/provider/kubernetes/controller.go
Fixes omitted check in https://github.com/envoyproxy/gateway/pull/3544
Fixes https://github.com/envoyproxy/gateway/issues/3824
=> [release/v1.0] fix: remove namespace restriction for EnvoyProxy parametersRef

internal/xds/translator/accesslog.go, internal/xds/translator/testdata/out/xds-ir/accesslog.listeners.yaml, tools/make/kube.mk
fixes: https://github.com/envoyproxy/gateway/issues/3737
=> accesslog: remove ALS gRPC initialMetadata

internal/gatewayapi/backendtlspolicy.go
=> fix: backendtls minversion

test/e2e/e2e_test.go, test/e2e/testdata/use-client-protocol.yaml, test/e2e/tests/basic_auth.go, test/e2e/tests/use_client_protocol.go
Add retries and wait for requests to converge to appropriate status code before making assertions on protocol.
Fixes #3473
=> fix: enable use-client-protocol test

examples/extension-server/go.mod, examples/extension-server/go.sum, tools/make/golang.mk
=> chore: go mod tidy

internal/xds/translator/route.go, internal/xds/translator/testdata/in/xds-ir/load-balancer.yaml, internal/xds/translator/testdata/out/xds-ir/load-balancer.clusters.yaml, internal/xds/translator/testdata/out/xds-ir/load-balancer.endpoints.yaml, internal/xds/translator/testdata/out/xds-ir/load-balancer.routes.yaml
Found this while debugging https://github.com/envoyproxy/gateway/pull/3868, will add e2e test for cookie based LB in a follow-up PR.
Fixes #
=> fix: nil pointer err during hash load balancing build

internal/cmd/egctl/testdata/translate/out/default-resources.all.yaml, internal/cmd/egctl/testdata/translate/out/echo-gateway-api.cluster.yaml, internal/cmd/egctl/testdata/translate/out/echo-gateway-api.route.json, internal/cmd/egctl/testdata/translate/out/invalid-envoyproxy.all.yaml, internal/cmd/egctl/testdata/translate/out/rejected-http-route.route.yaml, internal/cmd/egctl/testdata/translate/out/valid-envoyproxy.all.yaml, internal/gatewayapi/conformance/suite.go
already supported with https://github.com/envoyproxy/gateway/pull/3246
=> enable HTTPRouteBackendRequestHeaderModifier test

internal/provider/kubernetes/predicates.go
=> validate for reconcile should check reference from EnvoyProxy

release-notes/v1.1.0-rc.1.yaml, site/content/en/news/releases/notes/v1.1.0-rc.1.md
=> fix: typos in release notes

test/e2e/e2e_test.go, test/e2e/testdata/load_balancing_consistent_hash_cookie.yaml, test/e2e/testdata/load_balancing_consistent_hash_header.yaml, test/e2e/testdata/load_balancing_consistent_hash_source_ip.yaml, test/e2e/testdata/load_balancing_round_robin.yaml, test/e2e/tests/ext_auth_grpc_service.go, test/e2e/tests/load_balancing.go, test/e2e/tests/utils.go
https://github.com/envoyproxy/gateway/actions/runs/10018597540/job/27694209720
=> e2e: refactor and improve lb test

tools/src/sphinx-build/requirements.txt
=> tools: remove sphinx

site/content/en/contributions/RELEASING.md, site/content/en/docs/boilerplates/o11y_prerequisites.md, site/content/en/docs/install/install-helm.md, site/content/en/docs/install/install-yaml.md, site/content/en/docs/tasks/operations/deployment-mode.md, site/content/en/docs/tasks/quickstart.md, site/content/en/docs/tasks/traffic/multicluster-service.md, site/content/en/latest/boilerplates/o11y_prerequisites.md, site/content/en/latest/install/install-helm.md, site/content/en/latest/install/install-yaml.md, site/content/en/latest/tasks/operations/deployment-mode.md, site/content/en/latest/tasks/quickstart.md, site/content/en/latest/tasks/traffic/multicluster-service.md, site/content/en/v1.1/boilerplates/o11y_prerequisites.md, site/content/en/v1.1/install/install-helm.md, site/content/en/v1.1/install/install-yaml.md, site/content/en/v1.1/tasks/operations/deployment-mode.md, site/content/en/v1.1/tasks/quickstart.md, site/content/en/v1.1/tasks/traffic/multicluster-service.md, site/hugo.toml, site/layouts/shortcodes/helm-version.html, site/layouts/shortcodes/yaml-version.html, tools/make/docs.mk
Thi will make it simpler to manage the version of helm chart and yaml file in doc site.
=> docs: add helm-version and yaml-version shortcode

site/content/en/docs/tasks/traffic/circuit-breaker.md, site/content/en/docs/tasks/traffic/client-traffic-policy.md, site/content/en/docs/tasks/traffic/connection-limit.md, site/content/en/docs/tasks/traffic/global-rate-limit.md, site/content/en/docs/tasks/traffic/http3.md, site/content/en/docs/tasks/traffic/local-rate-limit.md, site/content/en/docs/tasks/traffic/retry.md, site/content/en/latest/tasks/traffic/circuit-breaker.md, site/content/en/latest/tasks/traffic/client-traffic-policy.md, site/content/en/latest/tasks/traffic/connection-limit.md, site/content/en/latest/tasks/traffic/global-rate-limit.md, site/content/en/latest/tasks/traffic/http3.md, site/content/en/latest/tasks/traffic/local-rate-limit.md, site/content/en/latest/tasks/traffic/retry.md, site/content/en/v1.1/tasks/traffic/circuit-breaker.md, site/content/en/v1.1/tasks/traffic/client-traffic-policy.md, site/content/en/v1.1/tasks/traffic/connection-limit.md, site/content/en/v1.1/tasks/traffic/global-rate-limit.md, site/content/en/v1.1/tasks/traffic/http3.md, site/content/en/v1.1/tasks/traffic/local-rate-limit.md, site/content/en/v1.1/tasks/traffic/retry.md
fix(docs): remove namespace in policies
=> fix: remove namespace in policies

site/content/en/docs/install/install-helm.md, site/content/en/docs/tasks/operations/deployment-mode.md, site/content/en/docs/tasks/quickstart.md, site/content/en/latest/install/install-helm.md, site/content/en/latest/tasks/operations/deployment-mode.md, site/content/en/latest/tasks/quickstart.md, site/content/en/v1.1/install/install-helm.md, site/content/en/v1.1/tasks/operations/deployment-mode.md, site/content/en/v1.1/tasks/quickstart.md
follow up: https://github.com/envoyproxy/gateway/pull/3766
=> docs: use yaml-version for quickstart yaml

site/content/en/latest/api/extension_types.md, site/content/zh/latest/api/extension_types.md, tools/crd-ref-docs/config.yaml, tools/src/crd-ref-docs/go.mod, tools/src/crd-ref-docs/go.sum
follow up: https://github.com/elastic/crd-ref-docs/pull/82
=> chore: bump crd-ref-docs

.github/workflows/experimental_conformance.yaml, test/conformance/experimental_conformance_test.go
Fixes https://github.com/kubernetes-sigs/gateway-api/pull/3191#issuecomment-2259298817
=> conformance(experimental): enable grpc conformance profile

site/content/en/news/releases/_index.md, test/e2e/tests/eg_upgrade.go
=> chore: udpate release mgmt docs and upgrade test

api/v1alpha1/ext_auth_types.go, charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml, internal/gatewayapi/securitypolicy.go, internal/gatewayapi/testdata/securitypolicy-with-extauth-backend.in.yaml, internal/gatewayapi/testdata/securitypolicy-with-extauth-backend.out.yaml, internal/xds/translator/testdata/in/xds-ir/ext-auth-backend.yaml, internal/xds/translator/testdata/out/xds-ir/ext-auth-backend.clusters.yaml, internal/xds/translator/testdata/out/xds-ir/ext-auth-backend.endpoints.yaml, internal/xds/translator/testdata/out/xds-ir/ext-auth-backend.listeners.yaml, internal/xds/translator/testdata/out/xds-ir/ext-auth-backend.routes.yaml, test/cel-validation/securitypolicy_test.go, test/e2e/testdata/ext-auth-http-backend-securitypolicy.yaml, test/e2e/testdata/ext-auth-http-backend.yaml, test/e2e/tests/ext_auth_http_backend.go
xref: https://github.com/envoyproxy/gateway/issues/3665
=> feat: Support the Backend resource for Ext-Auth

internal/metrics/otel_metric_gauge.go
=> bugfix: fatal error: concurrent map writes

api/v1alpha1/shared_types.go, site/content/en/latest/api/extension_types.md, site/content/zh/latest/api/extension_types.md
docs: mark BackendRef in shared_types.go optional
Fix documentation error
Fixes #4050
=> docs: mark BackendRef in shared_types.go optional

internal/gatewayapi/helpers.go
xref: https://github.com/envoyproxy/gateway/pull/4000
=> use sets and return stable result

site/content/en/docs/tasks/security/basic-auth.md, site/content/en/latest/tasks/security/basic-auth.md, site/content/en/v1.0/tasks/security/basic-auth.md, site/content/en/v1.1/tasks/security/basic-auth.md
=> docs: fix basic-auth.md formatting

internal/gatewayapi/testdata/gateway-http-listener-with-hostname-intersection.in.yaml
=> chore: fix Unchanged files with check annotations

internal/gatewayapi/backendtrafficpolicy.go, internal/gatewayapi/testdata/backendtrafficpolicy-buffer-limit-out-of-range-error.out.yaml, internal/gatewayapi/testdata/backendtrafficpolicy-buffer-limit-with-invalid-value.out.yaml, internal/gatewayapi/testdata/backendtrafficpolicy-with-circuitbreakers-error.out.yaml, internal/gatewayapi/testdata/backendtrafficpolicy-with-loadbalancer-invalid-consistent-hash-table-size.out.yaml, internal/gatewayapi/testdata/backendtrafficpolicy-with-local-ratelimit-invalid-limit-unit.out.yaml, internal/gatewayapi/testdata/backendtrafficpolicy-with-local-ratelimit-invalid-match-type.out.yaml, internal/gatewayapi/testdata/backendtrafficpolicy-with-local-ratelimit-invalid-multiple-route-level-limits.out.yaml, internal/gatewayapi/testdata/backendtrafficpolicy-with-ratelimit-invalid-regex.out.yaml, internal/gatewayapi/testdata/backendtrafficpolicy-with-timeout-error.out.yaml, internal/gatewayapi/testdata/httproute-and-backendtrafficpolicy-with-timeout-error.out.yaml, test/e2e/testdata/backendtrafficpolicy-translation-failed.yaml, test/e2e/tests/backendtrafficpolicy_translation_failed.go, test/e2e/tests/utils.go
refactor(translator)
Return 500 when BackendTrafficPolicy translation fails
Fixes #4061
=> refactor: Return 500 when BackendTrafficPolicy translation fails

.github/workflows/build_and_test.yaml, .github/workflows/latest_release.yaml, .github/workflows/release.yaml, tools/docker/envoy-gateway/Dockerfile
* fix pinned-dependencies
Improve ossf conformity
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
=> ossf: fix pinned-dependencies

internal/infrastructure/kubernetes/proxy/resource_provider.go, internal/infrastructure/kubernetes/ratelimit/resource.go
=> chore: code polish & ratelimit env optimize

internal/gatewayapi/backendtrafficpolicy.go
=> [release-1.1] fix: allow empty slowStart when using LeastRequest

internal/gatewayapi/testdata/httproute-attaching-to-listener-with-backend-backendref.out.yaml, internal/gatewayapi/validate.go
fix: rejected invalid backends in route validation
(cherry picked from commit 646da88131e078517c1f97bb8b82ee09583b6ff7)
Fixes #
=> [release/v1.1] fix: reject invalid backends in route validation (#4209)

internal/gatewayapi/runner/runner.go, internal/gatewayapi/runner/runner_test.go, internal/gatewayapi/status/backend.go, internal/gatewayapi/testdata/backend-invalid-feature-disabled.out.yaml, internal/gatewayapi/testdata/backend-invalid-hostname-address.out.yaml, internal/gatewayapi/testdata/backendtlspolicy-default-ns-targetrefs.out.yaml, internal/gatewayapi/testdata/backendtlspolicy-default-ns.out.yaml, internal/gatewayapi/testdata/envoyextensionpolicy-with-extproc-with-multiple-backendrefs.out.yaml, internal/gatewayapi/testdata/grpcroute-with-backend.out.yaml, internal/gatewayapi/testdata/httproute-attaching-to-listener-with-backend-and-core-backendrefs.out.yaml, internal/gatewayapi/testdata/httproute-attaching-to-listener-with-backend-backendref-mixed-address-type.out.yaml, internal/gatewayapi/testdata/httproute-attaching-to-listener-with-backend-backendref.out.yaml, internal/gatewayapi/testdata/httproute-attaching-to-listener-with-multiple-backend-backendrefs-diff-address-type.out.yaml, internal/gatewayapi/testdata/httproute-attaching-to-listener-with-multiple-backend-backendrefs-same-address-type.out.yaml, internal/gatewayapi/testdata/httproute-rule-with-non-service-backends-and-app-protocols.out.yaml, internal/gatewayapi/testdata/httproute-rule-with-non-service-backends-and-weights.out.yaml, internal/gatewayapi/testdata/tcproute-with-backend.out.yaml, internal/gatewayapi/testdata/tlsroute-with-backend.out.yaml, internal/message/types.go, internal/provider/kubernetes/status.go, test/e2e/tests/route_with_backend.go, test/e2e/tests/utils.go
(cherry picked from commit 7cddd95dccd8b93408dc789fcdf916c482223dda)
Fixes #
=> [release/v1.1] cherry pick #4219

test/e2e/tests/accesslog.go
fixes: https://github.com/envoyproxy/gateway/issues/4177
=> e2e: increase timeout for FileAccessLog

api/v1alpha1/envoypatchpolicy_types.go, charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoypatchpolicies.yaml, charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml, internal/utils/jsonpatch/jsonpathtopointer.go, internal/utils/jsonpatch/jsonpathtopointer_test.go, internal/utils/jsonpatch/patch.go, internal/utils/jsonpatch/patch_test.go, internal/xds/translator/testdata/in/xds-ir/jsonpatch-with-jsonpath-invalid.yaml, internal/xds/translator/translator_test.go, site/content/en/latest/api/extension_types.md, site/content/en/latest/tasks/extensibility/envoy-patch-policy.md, site/content/zh/latest/api/extension_types.md
* "fix: throw error if jsonPath returns no jsonPointers"
* "fix: allow selecting properties in jsonPath with special chars"
* "fix: generate jsonPointer and encode special chars"
* "docs: improved api (property descriptions)"
* "docs: added example"
Fixes #4162 
Fixes #4043
=> EnvoyPatchPolicy JsonPath docs & fixes

test/benchmark/suite/render.go, tools/make/kube.mk
=> chore: include heap profile into benchmark report and add notes for profiles

internal/provider/kubernetes/controller.go
=> fix: Reconcile on HTTPRoute labels change

api/v1alpha1/shared_types.go, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/component-level.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/default.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/disable-prometheus.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/override-labels-and-annotations.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/patch-daemonset.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/shutdown-manager.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-annotations.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-concurrency.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-extra-args.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-image-pull-secrets.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-name.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-node-selector.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-topology-spread-constraints.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/bootstrap.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/component-level.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/disable-prometheus.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/override-labels-and-annotations.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/patch-deployment.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/shutdown-manager.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-annotations.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-concurrency.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-empty-memory-limits.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-extra-args.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-image-pull-secrets.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-name.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-node-selector.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-topology-spread-constraints.yaml
Release Notes: https://github.com/envoyproxy/envoy/releases/tag/v1.31.2
=> [release/v1.1] Bump EnvoyProxy to v1.32.2

internal/gatewayapi/listener.go, internal/gatewayapi/testdata/gateway-with-listener-with-unsupported-protocol.out.yaml
…sign gateway status.
Fixes #4216
=> fix: Unsupported listener protocol type error for nil supportKinds assign gateway status.

README.md
=> chore: add envoy gateway logo into readme

site/content/en/contributions/DEVELOP.md
=> doc: update benchmark result

internal/infrastructure/kubernetes/infra.go, internal/infrastructure/kubernetes/infra_resource.go, internal/infrastructure/kubernetes/proxy/resource_provider.go, internal/infrastructure/kubernetes/ratelimit/resource_provider.go
=> bugfix: ignore some unnecessary requests to apiserver.

.github/workflows/build_and_test.yaml
https://github.com/codecov/codecov-action/issues/1594#issuecomment-2394913029
=> chore: recover Coverage Tests

api/v1alpha1/shared_types.go, internal/infrastructure/kubernetes/infra.go, internal/infrastructure/kubernetes/infra_resource.go, internal/infrastructure/kubernetes/proxy/resource_provider.go, internal/infrastructure/kubernetes/ratelimit/resource_provider.go, internal/infrastructure/kubernetes/ratelimit_infra.go, site/content/en/latest/api/extension_types.md, site/content/zh/latest/api/extension_types.md
xref: https://github.com/envoyproxy/gateway/issues/4380
=> infra: use labels when deleting infra

charts/gateway-helm/templates/infra-manager-rbac.yaml, internal/infrastructure/kubernetes/infra_resource.go, test/helm/gateway-helm/certjen-custom-scheduling.out.yaml, test/helm/gateway-helm/control-plane-with-pdb.out.yaml, test/helm/gateway-helm/default-config.out.yaml, test/helm/gateway-helm/deployment-custom-topology.out.yaml, test/helm/gateway-helm/deployment-images-config.out.yaml, test/helm/gateway-helm/deployment-priorityclass.out.yaml, test/helm/gateway-helm/envoy-gateway-config.out.yaml, test/helm/gateway-helm/global-images-config.out.yaml, test/helm/gateway-helm/service-annotations.out.yaml
following up: https://github.com/envoyproxy/gateway/pull/4430
e2e tracked in: https://github.com/envoyproxy/gateway/issues/4453
=> infra: fix DeleteAllOf rbac

site/assets/scss/_variables_project.scss, site/content/en/docs/tasks/extensibility/extension-server.md, site/content/en/latest/tasks/extensibility/extension-server.md, site/content/en/v1.1/tasks/extensibility/extension-server.md
=> docs: improve a little bit visual

site/content/en/docs/tasks/extensibility/wasm.md, site/content/en/latest/tasks/extensibility/wasm.md, site/content/en/v1.1/tasks/extensibility/wasm.md
xref: https://github.com/envoyproxy/gateway/issues/4466
=> Fix wasm example link

api/v1alpha1/oidc_types.go
Unhide the API as its already been implmented in https://github.com/envoyproxy/gateway/pull/4227
=> Unhide BackendCluster for OIDC provider

test/e2e/testdata/envoyproxy-daemonset.yaml, test/e2e/tests/envoyproxy_daemonset.go
xref: https://github.com/envoyproxy/gateway/issues/3457
=> e2e: add test for DaemonSet

tools/make/common.mk, tools/make/docs.mk
follow up: https://github.com/envoyproxy/gateway/pull/4473
=> docs: skip current in release-notes-docs

charts/gateway-helm/README.md, charts/gateway-helm/templates/certgen.yaml, charts/gateway-helm/templates/envoy-gateway-deployment.yaml, charts/gateway-helm/values.tmpl.yaml, release-notes/current.yaml, site/content/en/latest/install/gateway-helm-api.md, site/content/zh/latest/install/gateway-helm-api.md, test/helm/gateway-helm/certjen-custom-scheduling.out.yaml, test/helm/gateway-helm/control-plane-with-pdb.out.yaml, test/helm/gateway-helm/default-config.out.yaml, test/helm/gateway-helm/deployment-images-config.out.yaml, test/helm/gateway-helm/deployment-priorityclass.out.yaml, test/helm/gateway-helm/deployment-securitycontext.in.yaml, test/helm/gateway-helm/deployment-securitycontext.out.yaml, test/helm/gateway-helm/envoy-gateway-config.out.yaml, test/helm/gateway-helm/global-images-config.out.yaml, test/helm/gateway-helm/service-annotations.out.yaml
Fixes #3887
Release Notes: 
Add support for modifying container securityContext for Envoy Gateway deployment in Helm
=> feat(chart): Make security context configurable

site/content/en/latest/api/extension_types.md, site/content/zh/latest/api/extension_types.md, tools/crd-ref-docs/config.yaml
fixes: https://github.com/envoyproxy/gateway/issues/4582
=> docs: remove List type

.github/workflows/latest_release.yaml, .github/workflows/release.yaml
Fixes: https://github.com/envoyproxy/gateway/issues/4566
=> add envoy-gateway binary to release artifacts

test/e2e/tests/authorization_client_ip.go, test/e2e/tests/authorization_default_action.go, test/e2e/tests/authorization_jwt.go, test/e2e/tests/backend_tls_settings.go, test/e2e/tests/gateway_infra_resource.go, test/e2e/tests/gatewayt-with-envoyproxy.go, test/e2e/tests/wasm_http.go, test/e2e/tests/wasm_oci.go
short name with space broken `E2E_RUN_TEST`
=> chore: donot use space in short name

api/v1alpha1/shared_types.go, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/component-level.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/default.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/disable-prometheus.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/override-labels-and-annotations.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/patch-daemonset.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/shutdown-manager.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-annotations.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-concurrency.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-extra-args.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-image-pull-secrets.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-name.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-node-selector.yaml, internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-topology-spread-constraints.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/bootstrap.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/component-level.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/disable-prometheus.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/override-labels-and-annotations.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/patch-deployment.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/shutdown-manager.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-annotations.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-concurrency.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-empty-memory-limits.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-extra-args.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-image-pull-secrets.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-name.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-node-selector.yaml, internal/infrastructure/kubernetes/proxy/testdata/deployments/with-topology-spread-constraints.yaml
Pin Envoy image to its latest version v1.32.1
=> [release/v1.2] pin envoy image to 1.32.1 

site/layouts/shortcodes/helm-version.html, site/layouts/shortcodes/yaml-version.html
=> chore: update site docs link for latest release

.github/workflows/build_and_test.yaml, .github/workflows/release.yaml, release-notes/current.yaml
Fixes https://github.com/envoyproxy/gateway/issues/2940
=> fix: push a helm chart without v in ther version

.github/workflows/latest_release.yaml, .github/workflows/release.yaml
Missed in https://github.com/envoyproxy/gateway/issues/4566
=> add envoy-gateway binary to latest release artifacts

site/content/en/docs/tasks/traffic/failover.md, site/content/en/news/releases/notes/v1.2.0.md, site/content/en/v1.2/tasks/traffic/failover.md
Add failover docs to v1.2.0.
Also change the release note title to v1.2.0 to align with pervious releases.
=> docs: add failover docs to v1.2.0

site/content/en/docs/install/install-helm.md, site/content/en/docs/install/install-yaml.md, site/content/en/latest/install/install-helm.md, site/content/en/latest/install/install-yaml.md, site/content/en/v1.2/install/install-helm.md, site/content/en/v1.2/install/install-yaml.md
=> docs: update upgrade notes

.github/workflows/release.yaml
(cherry picked from commit dd1c66fb024e1ce76f59fe1480900307e9ae480d)
=> fix release build (#4645)

site/layouts/shortcodes/helm-version.html, site/layouts/shortcodes/yaml-version.html
=> v1.2.1: update helm version short code

site/content/en/news/releases/v1.2.md
Lesser steps for a user to install Envoy Gateway
=> add link to install EG in release news

release-notes/v1.1.4.yaml, site/content/en/news/releases/notes/v1.1.4.md, site/layouts/shortcodes/helm-version.html, site/layouts/shortcodes/yaml-version.html
=> [release/v1.1] release: v1.1.4

internal/provider/kubernetes/controller.go, internal/provider/kubernetes/controller_test.go, internal/provider/kubernetes/indexers.go, release-notes/current.yaml
=> fix: EnvoyExtensionPolicy reference grant

site/content/en/docs/tasks/security/backend-tls.md, site/content/en/latest/tasks/security/backend-tls.md, site/content/en/v1.2/tasks/security/backend-tls.md
Update BackendTLSPolicy docs for https://github.com/envoyproxy/gateway/pull/4784
=> docs: update BackendTLSPolicy docs

internal/xds/translator/testdata/out/xds-ir/http-route-timeout.clusters.yaml
fix https://github.com/envoyproxy/gateway/actions/runs/12268094500/job/34229337374
=> chore: fix gen check

site/data/adopters.yaml
=> [docs] added desc for titan

release-notes/v1.1.4.yaml, site/content/en/news/releases/notes/v1.1.4.md
release: v1.1.4
(cherry picked from commit 685c5dd5149e9a2b6dac3347c90dbe1022b74c81)
Fixes #
=> [release/v1.1] release: v1.1.4 (#4899)

internal/gatewayapi/securitypolicy.go, internal/gatewayapi/testdata/securitypolicy-with-extauth-backend.in.yaml, internal/gatewayapi/testdata/securitypolicy-with-extauth-backend.out.yaml, release-notes/current.yaml
=> fix: nil pointer error

api/v1alpha1/envoygateway_helpers.go, api/v1alpha1/envoygateway_types.go, api/v1alpha1/zz_generated.deepcopy.go, internal/infrastructure/kubernetes/ratelimit/resource_provider.go, internal/infrastructure/kubernetes/ratelimit/resource_provider_test.go, internal/infrastructure/kubernetes/ratelimit/testdata/hpa/custom.yaml, internal/infrastructure/kubernetes/ratelimit/testdata/hpa/default.yaml, internal/infrastructure/kubernetes/ratelimit/testdata/hpa/with-deployment-name.yaml, release-notes/current.yaml, site/content/en/latest/api/extension_types.md, site/content/zh/latest/api/extension_types.md
Adds HPA support for rate limit deployment under the EnvoyGateway API
Allows autoscaling of the rate limit deployment similar to what is done today for the envoy proxy deployment.
Fixes #4930
=> feat(infra): Add rateLimitHpa support in EnvoyGateway API

internal/utils/protocov/protocov.go, internal/xds/filters/wellknown.go, internal/xds/translator/accesslog.go, internal/xds/translator/httpfilters.go, internal/xds/translator/route.go
Fixes: https://github.com/envoyproxy/gateway/issues/4554
Follow up: https://github.com/envoyproxy/gateway/pull/4499
=> chore: always validate the proto messages

internal/gatewayapi/helpers.go, internal/gatewayapi/listener.go, internal/gatewayapi/runner/runner.go, internal/gatewayapi/translator.go, internal/gatewayapi/translator_test.go
Fixes: https://github.com/envoyproxy/gateway/issues/4981
=> fix: dont shift listener ports for Standalone mode

site/hugo.toml, site/layouts/_default/_markup/render-image.html, site/layouts/partials/navbar-version-selector.html
this make it possible to change baseURL to any value in `hugo.toml`.
=> docs: version URL and image support baseURL

test/e2e/tests/authorization_client_ip.go
Skipping to unblock CI
Raised to track fixing the issue https://github.com/envoyproxy/gateway/issues/5063
=> Skip AuthorizationClientIPTrustedCidrsTest

internal/infrastructure/kubernetes/ratelimit/statsd_conf.yaml, internal/infrastructure/kubernetes/ratelimit/testdata/envoy-ratelimit-configmap.yaml, test/e2e/tests/promql.go, test/e2e/tests/ratelimit.go, test/e2e/tests/utils.go
fixes: https://github.com/envoyproxy/gateway/issues/4281
=> ratelimit: make sure remote address ratelimit metrics worked as expected

.gitignore
=> Adds `*.yaml-e` into .gitignore

internal/xds/translator/testdata/in/xds-ir/api-key-auth.yaml, test/e2e/testdata/api-key-auth.yaml, test/e2e/testdata/authorization-client-ip-trusted-cidrs.yaml, tools/linter/yamllint/.yamllint
=> chore: align yaml lint with github

README.md
Links for Code of conduct caption
Fixes #
=> docs(README): intended links extension

api/v1alpha1/clienttrafficpolicy_types.go, api/v1alpha1/envoygateway_types.go, site/content/en/latest/api/extension_types.md, site/content/zh/latest/api/extension_types.md
* add it for kubernetes deploy mode
* rm it from trustedCIDRs
=> update notImplementedHide markers

internal/cmd/server.go, internal/envoygateway/config/config.go, internal/infrastructure/runner/runner.go, internal/provider/kubernetes/controller.go, internal/provider/kubernetes/kubernetes.go, internal/provider/kubernetes/kubernetes_test.go, internal/provider/runner/runner.go, release-notes/current.yaml
* fix panic when updating the envoy-gateway-config configMap
(cherry picked from commit 42ae06d31d66016bc7e3d5af6fccc02ab0402c76)
=> fix panic when updating the envoy-gateway-config configMap (#5066)

examples/envoy-als/Dockerfile, examples/envoy-als/go.mod, examples/extension-server/go.mod, examples/extension-server/tools/src/controller-gen/go.mod, examples/grpc-ext-auth/Dockerfile, examples/grpc-ext-auth/go.mod, examples/grpc-ext-proc/Dockerfile, examples/grpc-ext-proc/go.mod, examples/preserve-case-backend/Dockerfile, examples/preserve-case-backend/go.mod, examples/static-file-server/Dockerfile, examples/static-file-server/go.mod, go.mod, site/go.mod, tools/src/buf/go.mod, tools/src/controller-gen/go.mod, tools/src/crd-ref-docs/go.mod, tools/src/gci/go.mod, tools/src/golangci-lint/go.mod, tools/src/helm-docs/go.mod, tools/src/jb/go.mod, tools/src/jsonnet/go.mod, tools/src/kind/go.mod, tools/src/protoc-gen-go-grpc/go.mod, tools/src/protoc-gen-go/go.mod, tools/src/setup-envtest/go.mod
missed in https://github.com/envoyproxy/gateway/pull/5190
xref: https://github.com/envoyproxy/gateway/actions/runs/13148904309/job/36692606774
=> chore: bump go 1.23.6

OWNERS
* adds @rudrakhp and @sanposhiho as code reviewers
* moves @chauhanshubham and @tmsnan into emeritus reviewers, thank you for your time and effort in reviewing the code !
=> Update Code Reviewers

internal/infrastructure/kubernetes/ratelimit/resource_provider_test.go, internal/infrastructure/kubernetes/ratelimit/testdata/deployments/patch-deployment-containers.yaml
fixes: https://github.com/envoyproxy/gateway/issues/5219
=> chore: add test for patch ratelimit env

test/e2e/testdata/backend-panic-threshold.yaml, test/e2e/tests/backend_panic_threshold.go
E2e conformance test for newly added panic threshold feature to increase coverage.
Fixes #
=> Add conformance e2e test for panic mode

charts/gateway-helm/README.md, charts/gateway-helm/values.tmpl.yaml, site/content/en/latest/install/gateway-helm-api.md, site/content/zh/latest/install/gateway-helm-api.md
Relates to https://github.com/envoyproxy/gateway/issues/5202
=> docs: add docs link for envoyGateway configuration in helm chart

api/v1alpha1/envoyextensionypolicy_types.go, internal/gatewayapi/luavalidator/lua_validator.go, release-notes/current.yaml, site/content/en/latest/api/extension_types.md, site/content/en/latest/tasks/extensibility/lua.md, site/content/zh/latest/api/extension_types.md
docs: Lua EnvoyExtensionPolicy usage and example
Also enable Lua feature in API
Docs for Lua feature and enabling it in API
Resolves #4627 
=> docs: Lua EnvoyExtensionPolicy

tools/make/docs.mk
chore: add canva to ignore lint list
add canva to ignore lint list
=> chore: add canva to ignore lint list

tools/make/docs.mk
too much flaky: https://github.com/envoyproxy/gateway/actions/runs/13389047417/job/37392344325?pr=5304#step:7:1349
=> chore: ignore `sched.co`

.github/workflows/latest_release.yaml
latest release workflow failed for cache overlimit, and latest-release step is no need for setup-deps (benchmark-test step created too big local cache)
https://github.com/Xunzhuo/gateway/actions/runs/13408722684
Fixes https://github.com/envoyproxy/gateway/issues/5308
=> fix: latest release failed for cache overlimit

site/assets/scss/_styles_project.scss, site/content/en/about/index.md, site/layouts/shortcodes/adopters.html
Address font and header styling issues wrt size and styling.
=> site: fix styling issues wrt fonts and headings

site/content/en/about/index.md, site/hugo.toml, site/static/robots.txt
fixed: https://github.com/envoyproxy/gateway/issues/5353
=> docs: add robots.txt

go.mod, go.sum
xref: https://osv.dev/vulnerability/GO-2025-3487 https://osv.dev/vulnerability/GO-2025-3488
=> chore: fix CVE

site/content/en/about/index.md
=> docs: fix duplicate about links

.github/workflows/build_and_test.yaml, .github/workflows/release.yaml
use a var over secret for username when pushing (prevents unwanted obfuscation)
=> github/ci: Update dockerhub user

site/content/en/docs/tasks/traffic/client-traffic-policy.md, site/content/en/latest/tasks/traffic/client-traffic-policy.md, site/content/en/v1.3/tasks/traffic/client-traffic-policy.md
Docs: fix error in client-traffic-policy.md
This document cannot be run successfully.
It's too simple so I didn't raise new issue.
=> docs: fix error in client-traffic-policy.md

examples/kubernetes/metric/stats-compression.yaml, internal/xds/bootstrap/bootstrap.go, internal/xds/bootstrap/bootstrap.yaml.tpl, internal/xds/bootstrap/bootstrap_test.go, internal/xds/bootstrap/testdata/render/enable-prometheus-brotli-compression.yaml, internal/xds/bootstrap/testdata/render/enable-prometheus-gzip-compression.yaml, release-notes/current.yaml, test/e2e/testdata/metric-compressor.yaml, test/e2e/tests/compression.go, test/e2e/tests/metric.go, test/e2e/tests/utils.go, tools/make/kube.mk
I found the configuration was broken for a long while, this patch fixed it, also add e2e test for it.
=> fix: metric compressor not working as expected

cmd/envoy-gateway/main.go, cmd/envoy-gateway/root/root.go, cmd/envoy-gateway/root/root_test.go, internal/cmd/certgen.go, internal/cmd/certgen_test.go, internal/cmd/envoy.go, internal/cmd/envoy_test.go, internal/cmd/server.go, internal/cmd/server_test.go, internal/cmd/versions.go
Refactors the envoy-gateway CLI packages around main program.
Refactors the envoy-gateway CLI packages around main program so that envoyproxy/ai-gateway project can utilize the standalone mode as part of its CLI.
=> Expose root command of envoy-gateway

internal/cmd/egctl/testdata/translate/in/backend-endpoint.yaml, internal/cmd/egctl/testdata/translate/out/backend-endpoint.all.yaml, internal/gatewayapi/resource/load.go, release-notes/current.yaml
=> load BackendTLSPolicy in standalone mode

site/content/en/docs/troubleshooting/_index.md, site/content/en/docs/troubleshooting/configuration.md, site/content/en/latest/troubleshooting/_index.md, site/content/en/latest/troubleshooting/configuration.md, site/content/en/v1.2/troubleshooting/_index.md, site/content/en/v1.2/troubleshooting/configuration.md, site/content/en/v1.3/troubleshooting/_index.md, site/content/en/v1.3/troubleshooting/configuration.md
Relates to https://github.com/envoyproxy/gateway/issues/2855
=> docs: Add troubleshooting section for config

api/v1alpha1/authorization_types.go, site/content/en/latest/api/extension_types.md
Sorry I forgot to unhide API in the implementation PR. :-)
=> chore: unhide header and method authz

internal/admin/server_test.go, internal/cmd/certgen_test.go, internal/cmd/server.go, internal/cmd/server_test.go, internal/envoygateway/config/loader/configloader.go, internal/logging/log.go, internal/logging/log_test.go, internal/xds/translator/listener.go
=> Enables standalone library to configure log output

internal/cmd/server.go, internal/envoygateway/config/loader/configloader.go, internal/envoygateway/config/loader/configloader_test.go
=> Make configloader accept configured logOut

site/content/en/latest/troubleshooting/configuration.md, site/content/en/v1.2/troubleshooting/configuration.md, site/content/en/v1.3/troubleshooting/configuration.md
* "docs: fix typo issue"
N/A
Fixes #
=> Fix typo for "troubleshooting configuration" section

test/fuzz/README.md
=> docs: Add README for Envoy Gateway fuzzing instructions

go.mod, go.sum
xref: https://github.com/envoyproxy/gateway/actions/runs/13923979616/job/38963609294
=> chore: bump github.com/containerd/containerd

internal/kubernetes/client.go, internal/kubernetes/port_forwarder.go, release-notes/current.yaml
Support WebSockets in addition to SPDY.
Fixes #5528
=> feat(egctl): support WebSockets in addition to SPDY

site/content/en/contributions/RELEASING.md, site/hugo.toml, site/layouts/partials/navbar-version-selector.html, site/layouts/partials/page-meta-links.html, site/layouts/partials/version-banner.html
fixes: https://github.com/envoyproxy/gateway/issues/5526
=> docs: version banner

site/layouts/shortcodes/helm-version.html, site/layouts/shortcodes/yaml-version.html
=> update site to use v1.3.2

site/content/en/news/releases/matrix.md
docs: add EOL column to Compatibility Matrix
Adds an EOL column to the Compatibility Matrix so users can access all relevant info in one place.
Fixes ##5559
=> docs: Added EOL column to Compatibility Matrix

site/content/en/v1.2/tasks/traffic/grpc-routing.md, site/content/en/v1.3/tasks/traffic/grpc-routing.md
Fixes https://github.com/envoyproxy/gateway/issues/5622
=> docs: update GRPCRoute version in 1.2 and 1.3 example

api/v1alpha1/tracing_types.go, charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml, internal/gatewayapi/testdata/tracing-sampling-fraction.in.yaml, internal/gatewayapi/testdata/tracing-sampling-fraction.out.yaml, release-notes/current.yaml, site/content/en/latest/api/extension_types.md, test/e2e/testdata/tracing-zipkin.yaml
fixes: https://github.com/envoyproxy/gateway/issues/5571
=> fix tracing SamplingFraction not working

internal/infrastructure/kubernetes/infra.go, internal/infrastructure/kubernetes/infra_client.go, internal/infrastructure/kubernetes/infra_resource.go, release-notes/current.yaml, test/e2e/testdata/envoyproxy-custom-name.yaml, test/e2e/tests/envoyproxy.go
fixes: https://github.com/envoyproxy/gateway/issues/4380
=> infra: delete resource if exists when using customized name

api/v1alpha1/envoyproxy_accesslogging_types.go, api/v1alpha1/envoyproxy_metric_types.go, api/v1alpha1/envoyproxy_tracing_types.go, charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml, internal/gatewayapi/helpers.go, internal/gatewayapi/listener.go, internal/gatewayapi/testdata/accesslog-als-backend.in.yaml, internal/gatewayapi/testdata/accesslog-als-backend.out.yaml, internal/gatewayapi/testdata/backend-invalid-feature-disabled.out.yaml, internal/gatewayapi/testdata/envoyproxy-accesslog-backend-invalid.out.yaml, internal/gatewayapi/testdata/envoyproxy-metric-backend-invalid.out.yaml, internal/gatewayapi/testdata/envoyproxy-tracing-backend-invalid.out.yaml, internal/gatewayapi/testdata/gateway-with-listener-with-tcproute-with-mismatch-port-protocol.out.yaml, internal/gatewayapi/testdata/gateway-with-listener-with-udproute-with-mismatch-port-protocol.out.yaml, internal/gatewayapi/testdata/httproute-attaching-to-listener-with-backend-backendref-mixed-address-type.out.yaml, internal/gatewayapi/testdata/httproute-attaching-to-listener-with-backend-backendref.out.yaml, internal/gatewayapi/testdata/httproute-attaching-to-listener-with-multiple-backend-backendrefs-diff-address-type.out.yaml, internal/gatewayapi/testdata/httproute-attaching-to-listener-with-multiple-backend-backendrefs-same-address-type.out.yaml, internal/gatewayapi/testdata/httproute-with-invalid-backend-ref-bad-port.out.yaml, internal/gatewayapi/testdata/httproute-with-invalid-backend-ref-no-service.import.out.yaml, internal/gatewayapi/testdata/httproute-with-mirror-filter-service-not-found.out.yaml, internal/gatewayapi/validate.go, internal/provider/kubernetes/controller.go, test/cel-validation/envoyproxy_test.go, test/e2e/testdata/accesslog-otel-default.yaml, test/e2e/testdata/tracing-datadog.yaml
fixes: https://github.com/envoyproxy/gateway/issues/3509
=> feat: support backend in EnvoyProxy

internal/wasm/premissioncache.go, internal/wasm/premissioncache_test.go
fix: https://github.com/envoyproxy/gateway/issues/5602
=> fix: flaky wasm permission check tests

site/content/en/contributions/design/envoy-patch-policy.md, site/content/en/v0.5/design/envoy-patch-policy.md, site/content/en/v0.6/design/envoy-patch-policy.md
* docs: fix typos
Make the content even greater.
N/A
=> Fix typo in envoypatchpolicy documentation

internal/infrastructure/kubernetes/infra.go, internal/infrastructure/kubernetes/infra_resource.go, internal/infrastructure/kubernetes/proxy/resource_provider.go, internal/infrastructure/kubernetes/ratelimit/resource_provider.go, test/e2e/testdata/envoyproxy-hpa.yaml, test/e2e/tests/envoyproxy_hpa.go, test/e2e/tests/utils.go
fixes: https://github.com/envoyproxy/gateway/issues/5357
Revert https://github.com/envoyproxy/gateway/commit/fe1e8bd4cce5ba8e0a5c933705587c2c3aca4fd0, add e2e to make sure it worked as expected.
=> Revert "bugfix: ignore some unnecessary requests to apiserver. (#4362)"

internal/gatewayapi/translator_test.go
fix: translator_test.go has been modified by accident.
=> fix: gateway api test

.github/workflows/build_and_test.yaml
fixes: https://github.com/envoyproxy/gateway/issues/5531
=> run conformance test on ipv6/dual

internal/gatewayapi/contexts_test.go, internal/provider/kubernetes/routes_test.go, tools/linter/golangci-lint/.golangci.yml
fix: testifylint issues
Fixes testifylint issues and enable temporary disabled rules
=> fix: testifylint issues

release-notes/current.yaml
xref: https://github.com/envoyproxy/gateway/issues/5486
=> chore: add release notes for per-route tracing

site/content/en/latest/tasks/security/secure-gateways.md, site/content/en/v1.3/tasks/security/secure-gateways.md
The docs page "Secure Gateways" has inconsistent testing sections(ex: only includes instructions for users without a load balancer in RSA+ECDSA testing section). I added tabpanes in each testing section and a precheck section to include instructions for both use cases. 
Also replaced links to the Quickstart page in Prereq sections with the prereq boilerplate and removed output from shell commands.
Page: https://gateway.envoyproxy.io/docs/tasks/security/secure-gateways/
Makes it easier for new users to follow this doc.
Fixes #5756 
=> docs: Made testing sections more consistent & replaced quickstart links with boilerplate in Secure Gateways

site/content/en/latest/tasks/security/credential-injection.md
docs for credential injection.
Closes: https://github.com/envoyproxy/gateway/issues/4757
=> docs: credential injection

site/content/en/latest/tasks/security/cors.md
Update the docs for CORS to include the Gateway API HTTPCORSFilter.
=> docs: cors filter

internal/wasm/premissioncache.go, internal/wasm/premissioncache_test.go
=> fix flaky wasm permission check

go.mod, go.sum
xref: https://github.com/envoyproxy/gateway/actions/runs/14699486279/job/41246359056
=> chore: bump github.com/go-jose/go-jose/v4

charts/gateway-helm/templates/certgen-rbac.yaml, test/helm/gateway-helm/certgen-args.out.yaml, test/helm/gateway-helm/certjen-custom-scheduling.out.yaml, test/helm/gateway-helm/control-plane-with-pdb.out.yaml, test/helm/gateway-helm/default-config.out.yaml, test/helm/gateway-helm/deployment-custom-topology.out.yaml, test/helm/gateway-helm/deployment-images-config.out.yaml, test/helm/gateway-helm/deployment-priorityclass.out.yaml, test/helm/gateway-helm/deployment-repo-no-registry.out.yaml, test/helm/gateway-helm/deployment-securitycontext.out.yaml, test/helm/gateway-helm/envoy-gateway-config.out.yaml, test/helm/gateway-helm/global-images-config.out.yaml, test/helm/gateway-helm/global-pullsecrets-override-deployment.out.yaml, test/helm/gateway-helm/global-pullsecrets-override-global.out.yaml, test/helm/gateway-helm/global-registry-override-deployment.out.yaml, test/helm/gateway-helm/global-registry-override-global.out.yaml, test/helm/gateway-helm/horizontal-pod-autoscaler.out.yaml, test/helm/gateway-helm/service-customization.out.yaml, test/helm/gateway-helm/webhook-disabled.out.yaml
=> Ensure rbac is created before the certgen job when using ArgoCD

api/v1alpha1/backendtrafficpolicy_types.go, api/v1alpha1/clienttrafficpolicy_types.go, api/v1alpha1/shared_types.go, internal/gatewayapi/backendtrafficpolicy.go, internal/gatewayapi/testdata/backendtrafficpolicy-strategic-merge.in.yaml, internal/gatewayapi/testdata/backendtrafficpolicy-strategic-merge.out.yaml, internal/gatewayapi/translator.go, internal/utils/merge.go, internal/utils/merge_test.go, release-notes/current.yaml
xref: https://github.com/envoyproxy/gateway/issues/1934
=> feat: impl mergeType in BackendTrafficPolicy

OWNERS
/kind documentation
This PR removes me from the reviewer list. I shouldn't even be mentioned in emeritus-reviewers because I haven't done many things here.
My entire OSS work time is very limited (since it's just a hobby), and I actually haven't had enough time working on this project since I've been promoted to the reviewer. (sorry 😢 ) I was hoping I'd get some more time for this project as well after my Europe travel period, but very likely I won't because I've got more responsibilities in kubernetes, which I have/want to prioritize, and have been consuming extra time. 
Fixes #
=> fix: remove sanposhiho from reviewers

.github/codecov.yml
=> chore: ignore api types in codecov

site/content/en/latest/tasks/security/jwt-authentication.md
docs for local jwks.
Closes: #2419
=> docs: local jwks

tools/make/helm.mk
fixes: https://github.com/envoyproxy/gateway/issues/5906
=> ci: make helm-generate should failed as expected

site/content/en/latest/tasks/traffic/global-rate-limit.md
This is a documentation update. It improves clarity and correctness in the BackendTrafficPolicy example for global rate limiting. Specifically, it adds a missing header match condition (x-user-id: admin with invert: true) that is required to make the "Distinct Users Except Admin" use case work as described.
This PR fixes a small but critical gap in the documentation for the **Global Rate Limit Distinct Users Except Admin** feature. The missing header configuration for excluding a specific user (e.g., x-user-id: admin) was causing the documented example to not behave as intended. This PR adds those missing lines to help users correctly configure rate limiting for distinct users while excluding admin traffic.
**Which …
=> docs(rate-limit): minor fix in 'Distinct Users Except Admin' section

internal/gatewayapi/clienttrafficpolicy.go, internal/gatewayapi/filters.go, internal/gatewayapi/testdata/clienttrafficpolicy-headers-error.in.yaml, internal/gatewayapi/testdata/clienttrafficpolicy-headers-error.out.yaml, internal/gatewayapi/testdata/httproute-with-header-filter-empty-header-values.out.yaml, internal/gatewayapi/testdata/httproute-with-header-filter-invalid-header-values.in.yaml, internal/gatewayapi/testdata/httproute-with-header-filter-invalid-header-values.out.yaml, internal/gatewayapi/testdata/httproute-with-response-header-filter-empty-header-values.in.yaml, internal/gatewayapi/testdata/httproute-with-response-header-filter-invalid-header-values.in.yaml, internal/gatewayapi/testdata/httproute-with-response-header-filter-invalid-header-values.out.yaml, release-notes/current.yaml
A single malformed header can stall the entire controller. We need to validate header values according to RFC 7230.
The proposed changes catch invalid header values and flag them in status messages.
Fixes #5901
=> fix: add validation for header values

internal/provider/kubernetes/kubernetes.go
fix: Fixed typo in error message.
I found and fixed a typo in an error message.
Fixes #
=> fix: Fixed typo in error message.

release-notes/v1.3.3.yaml, site/content/en/news/releases/notes/v1.3.3.md
=> [release/v1.3] release v1.3.3 notes

release-notes/current.yaml, release-notes/v1.3.3.yaml, site/content/en/news/releases/notes/v1.3.3.md
release v1.3.3 notes
(cherry picked from commit dc2b9ca78a122862c201a03c554bc6aceb77c981)
Fixes #
=> [release/v1.3] Release version v1.3.3

site/layouts/shortcodes/helm-version.html, site/layouts/shortcodes/yaml-version.html
=> [release/v1.3] update site to use v1.3.3

test/e2e/tests/ext_auth_grpc_service.go
fixes: https://github.com/envoyproxy/gateway/issues/5979
=> e2e: fix GRPCExtAuth flaky

test/e2e/tests/ext_auth_grpc_service.go
fixes: https://github.com/envoyproxy/gateway/issues/5979
=> e2e: fix GRPCExtAuth/http_route_with_ext_auth_authentication

test/e2e/tests/accesslog.go, test/e2e/tests/envoyproxy.go
fixes: https://github.com/envoyproxy/gateway/issues/6005
=> e2e: fix EnvoyProxyCustomName

internal/gatewayapi/backendtrafficpolicy.go, internal/utils/merge.go
we should keep use `utils.Merge` everywhere if possible.
=> chore: utils.Merge

internal/wasm/premissioncache.go, internal/wasm/premissioncache_test.go
=> Fix flaky wasm permission cache tests

OWNERS, site/content/en/contributions/CODEOWNERS.md
Fixes: https://github.com/envoyproxy/gateway/issues/6073
=> add @cnvergence and @rudrakhp as maintainers

internal/utils/helm/package.go, test/e2e/tests/eg_upgrade.go, test/e2e/upgrade/eg_upgrade_test.go
fixes: https://github.com/envoyproxy/gateway/issues/6009
=> e2e: enable EGUpgrade test

test/e2e/testdata/backend-tls-settings.yaml, test/e2e/tests/backend_tls_settings.go
fixes: https://github.com/envoyproxy/gateway/issues/6084
=> e2e: fix BackendTLSSettings

api/v1alpha1/ext_proc_types.go, charts/gateway-crds-helm/templates/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml, charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml, test/helm/gateway-crds-helm/all.out.yaml, test/helm/gateway-crds-helm/envoy-gateway-crds.out.yaml
FullDuplexStreamed was added in https://github.com/envoyproxy/gateway/pull/5349. However, the enum was still missing that option, creating CEL validation issues. 
Fixes #
=> fix: add FullDuplexStreamed to enum

test/e2e/tests/session_persistence.go
fixes: https://github.com/envoyproxy/gateway/issues/6062
=> e2e: fix SessionPersistence flaky

site/content/en/news/releases/_index.md
=> doc: update release page

test/e2e/tests/envoyproxy.go
fixes: https://github.com/envoyproxy/gateway/issues/6005
=> e2e: fix EnvoyProxyCustomName flaky

test/e2e/tests/zone_aware_routing.go
xref: https://github.com/envoyproxy/gateway/issues/6119
=> e2e: update ZoneAwareRouting

examples/kubernetes/gateway-namespace-mode.yaml
Fixes https://github.com/envoyproxy/gateway/issues/6138
=> [release/v1.4] fix: missing v1.4 deployment yaml to Gateway Namespace Mode docs

examples/envoy-ext-auth/Dockerfile, examples/envoy-ext-auth/go.mod, examples/extension-server/go.mod, examples/grpc-ext-proc/Dockerfile, examples/grpc-ext-proc/go.mod, examples/preserve-case-backend/Dockerfile, examples/preserve-case-backend/go.mod, examples/simple-extension-server/Dockerfile, examples/simple-extension-server/go.mod, examples/static-file-server/Dockerfile, examples/static-file-server/go.mod, go.mod, go.sum, site/go.mod
fixes: https://github.com/envoyproxy/gateway/pull/6075
=> chore: bump go and purego

api/v1alpha1/envoyproxy_helpers.go, api/v1alpha1/validation/envoyproxy_validate_test.go, internal/infrastructure/common/proxy_args.go
follow up: https://github.com/envoyproxy/gateway/pull/6149#discussion_r2102640665
=> chore: use GetEnvoyProxyComponentLevel

site/content/en/latest/tasks/operations/egctl.md, site/content/en/v1.4/tasks/operations/egctl.md
1. add install steps
2. move `egctl x translate`
3. add `egctl config`
=> docs: update egctl docs

release-notes/v1.4.1.yaml, site/content/en/news/releases/notes/v1.4.1.md
sync https://github.com/envoyproxy/gateway/pull/6254
=> [release/v1.4] add release notes

.github/workflows/experimental_conformance.yaml, test/conformance/experimental_conformance_test.go, tools/linter/yamllint/.yamllint
fixes: https://github.com/envoyproxy/gateway/issues/5666
=> conformance: run experimental conformance test on different mode

examples/envoy-ext-auth/Dockerfile, examples/envoy-ext-auth/go.mod, examples/extension-server/go.mod, examples/grpc-ext-proc/Dockerfile, examples/grpc-ext-proc/go.mod, examples/preserve-case-backend/Dockerfile, examples/preserve-case-backend/go.mod, examples/simple-extension-server/Dockerfile, examples/simple-extension-server/go.mod, examples/static-file-server/Dockerfile, examples/static-file-server/go.mod, go.mod, site/go.mod
for https://github.com/envoyproxy/gateway/actions/runs/15625283269/job/44018217052
=> chore: bump golang to 1.24.4

release-notes/current.yaml
docs: add release note for custom backend
=> docs: add release note for custom backend

internal/gatewayapi/runner/runner.go, internal/globalratelimit/runner/runner.go, internal/infrastructure/runner/runner.go, internal/message/metrics.go, internal/message/types.go, internal/message/watchutil.go, internal/message/watchutil_test.go, internal/provider/kubernetes/controller.go, internal/provider/kubernetes/status.go, internal/xds/server/runner/runner.go, internal/xds/translator/runner/runner.go, release-notes/current.yaml, site/content/en/latest/tasks/observability/gateway-exported-metrics.md
Adds a new metric for publish events: `watchable_publish_total`. 
EG currently records metrics for the subscriber side. The watchable queues may coalesce and drop certain updates sent to subscribers. Users may also want to track the count of store events, in order to understand if certain layers are publishing updates successfully. 
=> feat(translator): add store metric

internal/admin/server.go, internal/admin/server_test.go, internal/cmd/server.go, internal/metrics/otel_metric_sink.go, internal/metrics/register.go, internal/metrics/register_test.go
=> feat: admin and metrics server hot reloading on config change

site/content/en/_index.md
Fix: incorrect envoy ai gw repo link
=> fix: incorrect envoy ai gw repo

site/content/en/contributions/design/envoy-extension-policy.md
Fixes: https://github.com/envoyproxy/gateway/issues/6552
=> rm priority field from EnvoyExtensionPolicy design doc

site/content/en/latest/concepts/introduction/gateway_api_extensions/backend-traffic-policy.md, site/content/en/v1.4/concepts/introduction/gateway_api_extensions/backend-traffic-policy.md
Fixes: https://github.com/envoyproxy/gateway/issues/6024
=> docs: Policy Merging in BTP

site/content/en/v1.4/tasks/operations/airgap-deployment.md
- closes https://github.com/envoyproxy/gateway/issues/6425
=> docs: add airgap deployment guide

release-notes/current.yaml
This PR addes missing release notes.
=> docs: add missing release notes

site/content/en/latest/tasks/traffic/global-rate-limit.md
Update the step for the EnvoyGateway ConfigMap - the current step will override the deploy mode in GatewayNamespace mode or other existing configurations.
=> docs: update global rate limit docs

go.mod, go.sum
fixes: https://github.com/envoyproxy/gateway/actions/runs/16611184207/job/46994429608
=> bump github.com/docker/docker

internal/gatewayapi/testdata/backendtrafficpolicy-with-endpointoverride-loadbalancer-multiple-mixed.out.yaml, internal/gatewayapi/testdata/backendtrafficpolicy-with-endpointoverride-loadbalancer-single-header.out.yaml, internal/gatewayapi/testdata/backendtrafficpolicy-with-endpointoverride-loadbalancer.out.yaml, release-notes/current.yaml
This PR fixed CI failures and add release note for endpoint override policy
=> fix: gen-check and add release note

api/v1alpha1/shared_types.go, charts/gateway-crds-helm/templates/generated/gateway.envoyproxy.io_envoyproxies.yaml, charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml, internal/infrastructure/kubernetes/proxy/resource_test.go, test/cel-validation/envoyproxy_test.go, test/helm/gateway-crds-helm/all.out.yaml, test/helm/gateway-crds-helm/envoy-gateway-crds.out.yaml
* "fix: fix allow imageRepository contains port"
https://github.com/envoyproxy/gateway/issues/6657
=> fix: allow imageRepository contains port

internal/xds/translator/testdata/in/xds-ir/backend-tls-skip-verify.yaml, internal/xds/translator/testdata/out/xds-ir/backend-tls-skip-verify.clusters.yaml, internal/xds/translator/translator.go, test/e2e/testdata/backend-tls.yaml, test/e2e/tests/backend_tls.go
=> fix: nil pointer when InsecureSkipVerify is true

test/e2e/tests/eg_upgrade.go
xref: https://github.com/envoyproxy/gateway/issues/6730
=> update upgrade test to use v1.5

.github/workflows/build_and_test.yaml, release-notes/current.yaml
run `[conformance|e2e|resilience|bench]test` workflows only when those dirs change
=> ci: skip test jobs when changes are not related

.github/workflows/build_and_test.yaml
xref: https://github.com/envoyproxy/gateway/actions/runs/16844330370/job/47721188359
=> ci: fix changes job

site/content/en/news/releases/notes/v1.4.3.md
include update around envoy proxy bump
added in https://github.com/envoyproxy/gateway/pull/6773
=> chore: update release notes for v1.4.3

api/v1alpha1/backendtrafficpolicy_types.go, site/content/en/latest/api/extension_types.md
xref: https://github.com/envoyproxy/gateway/pull/5661
=> api: unhide request buffer in BTP

.github/workflows/experimental_conformance.yaml, tools/make/kube.mk
xref: https://github.com/envoyproxy/gateway/issues/6521
=> conformance: update experimental test report

test/benchmark/suite/render.go, test/benchmark/suite/report.go
* Collect container and process (golang) metrics for EG pod
=> benchmark: add go mem usage for EG

internal/globalratelimit/runner/runner_test.go
fix: https://github.com/envoyproxy/gateway/issues/6855
=> chore: fix test

internal/gatewayapi/backendtrafficpolicy.go, internal/gatewayapi/clienttrafficpolicy.go, internal/gatewayapi/envoyextensionpolicy.go, internal/gatewayapi/extensionserverpolicy.go, internal/gatewayapi/helpers.go, internal/gatewayapi/helpers_test.go, internal/gatewayapi/securitypolicy.go, internal/gatewayapi/testdata/backendtrafficpolicy-multiple-targets-targetselector.in.yaml, internal/gatewayapi/testdata/backendtrafficpolicy-multiple-targets-targetselector.out.yaml
* only select refs in the same namespace as the policy
Relates to https://github.com/envoyproxy/gateway/issues/6899
=> improve targetRef selection for targetSelectors

site/content/en/contributions/RELEASING.md
Update release process doc:
- add `update EP & RL image version` steps in Minor Release and Patch Release section
- update Announce the Release step in Patch Release section
- fix few typos
Fixes #
=> doc: update release process doc

release-notes/v1.5.1.yaml, site/content/en/news/releases/notes/v1.5.1.md
xref: https://github.com/envoyproxy/gateway/pull/6990
=> docs: fix 1.5.1 date

tools/hack/cherrypick-for-patch-release.sh
this should help RM do the cherry-pick
=> ci: add a script for cherrypick

site/content/en/latest/tasks/traffic/http-connect-tunnels.md, site/content/en/v1.5/tasks/traffic/http-connect-tunnels.md
xref: https://github.com/envoyproxy/gateway/issues/6324
=> docs: HTTP CONNECT based tunnels

internal/xds/translator/route.go, internal/xds/translator/testdata/in/xds-ir/http-route-rewrite-url-regex.yaml, internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-url-regex.routes.yaml, release-notes/current.yaml
fix: escape regex metacharacters from path prefix string
Escapes regex metacharacters from path prefix string so regex substitution considers the literal path prefix text instead of evaluating it.
Fixes #6857 
=> fix: escape regex metacharacters from path prefix string

internal/provider/kubernetes/predicates.go, internal/provider/kubernetes/predicates_test.go
=> chore: remove assert

test/e2e/tests/oidc.go
fixes: https://github.com/envoyproxy/gateway/issues/7073
=> e2e: use MakeRequestAndExpectEventuallyConsistentResponse

internal/provider/kubernetes/status.go
* use the one in the gateway-api lib
=> chore: rm duplicate isParentRefEqual func from provider

internal/provider/kubernetes/controller.go
delete GC status from watchable
=> chore: delete GC status from watchable

site/content/en/_index.md, site/content/en/contributions/ENTERPRISE_SUPPORT.md, site/data/enterprise_support.yaml, site/layouts/shortcodes/enterprise_support.html
Fixes: https://github.com/envoyproxy/gateway/issues/3790
=> site: add section for enterprise support

internal/cmd/server.go, internal/infrastructure/runner/runner.go, internal/message/types.go, internal/provider/kubernetes/controller.go
perf: skip infra ir and status subscription for followers
Prevents accumulation of update events since followers do not consume from the subscriptions, which leads to OOM. 
Related #6919 
=> perf: skip infra ir and status subscription for followers
