envoyproxy/gateway

.github/workflows/build_and_test.yaml

Limit GHA to main and release branches

---

.github/CODEOWNERS

* Uses the CODEOWNERS file to automatically assign reviewers to files to speed up reviews
* As the project progresses, the CODEOWNERS file can be updated to
select a subset of the mantainers as owners for a specific area /
directory.

Assign reviewers to PRs

---

.github/workflows/build_and_test.yaml
DEVELOPER.md
Makefile
Makefile.targets.mk
docs/design/SYSTEM_DESIGN.md
tools/Dockerfile.builder
tools/codespell/.codespell.ignorewords
tools/codespell/.codespell.skip
tools/golangci-lint/.golangci.yml
tools/yamllint/.yamllint

Signed-off-by: lianghao208 <roylizard3@gmail.com>
issue: #73

ci: add golangci-lint, yamlllint and codespell

---

README.md

Removes the meeting times from `README.md`. This reduces the number of places to manage meeting details.

Removes Meeting Times from Readme

---

tools/make/image.mk

Fix https://github.com/envoyproxy/gateway/issues/138

chore: implement make target for multi arch image build

---

tools/src/kustomize/go.mod
tools/src/kustomize/go.sum

The `run-kube-local` Make target is failing:
```
/Library/Developer/CommandLineTools/usr/bin/make --warn-undefined-variables -f tools/make/common.mk run-kube-local
tools/bin/controller-gen rbac:roleName=envoy-gateway-role crd webhook paths="./..." output:crd:artifacts:config=pkg/provider/kubernetes/config/crd/bases
cd tools/src/kustomize && GOOS= GOARCH= go build -o /Users/daneyonhansen/go/src/github.com/envoyproxy/gateway/tools/bin/kustomize $(sed -En 's,^import "(.*)".*,\1,p' pin.go)
../../../../../../../pkg/mod/golang.org/x/sys@v0.0.0-20200323222414-85ca7c5b95cd/unix/syscall_darwin.1_13.go:25:3: //go:linkname must refer to declared function or variable
...
```
This PR bumps the Kustomize dep to v3.10.0 to fix the target.

Bumps Kustomize Dep to v3.10.0

---

tools/make/kube.mk

Running `make go.test.coverage` produces:
```
/Library/Developer/CommandLineTools/usr/bin/make --warn-undefined-variables -f tools/make/common.mk go.test.coverage
tools/make/golang.mk:40: warning: undefined variable `ENVTEST_K8S_VERSION'
...
```
This PR adds the env var to the kube make file.

Adds ENVTEST_K8S_VERSION to Makefile

---

go.mod
internal/gatewayapi/contexts.go
internal/gatewayapi/contexts_test.go
internal/gatewayapi/helpers.go
internal/gatewayapi/testdata_test.go
internal/gatewayapi/translator.go
internal/gatewayapi/translator_test.go
pkg/ir/xds.go

Updates #38.
Setting expectations, this should not be considered "done" but does cover much of the core translation logic and gives us something to refine/start integrating with; I didn't want this PR to get any larger than it already is. I have a list of follow-up issues to file to build out the rest of the functionality, including:
- add header modifier filter support
- add redirect filter support
- implement correct behavior for invalid backend refs (i.e. 500 responses)
- implement ReferenceGrant for cross-namespace service/secret references
- finalize approach to Host matching
- add TLS support
- add TLSRoute support
We obviously also need to work on integrating this with the resource providers and the xDS translator, I think that can be done in subsequent PRs.

Adds initial draft of Gateway API translator

---

pkg/provider/kubernetes/kubernetes_test.go
tools/make/golang.mk
tools/make/kube.mk

- Adds build tag to Kube provider integration tests.
- Update Mke targets to use the `integration` build tag.

Fixes go.test.unit Make Target

---

internal/provider/kubernetes/gateway.go
internal/provider/kubernetes/gateway_test.go
internal/provider/kubernetes/gatewayclass_test.go
internal/provider/kubernetes/kubernetes.go
internal/provider/kubernetes/kubernetes_test.go
internal/provider/testdata/in/gateway-experimental-crd.yaml

- Add initial gateway controller.
- Adds applicable unit/integrations tests.

Adds Gateway Controller to Kubernetes Provider

---

internal/ir/infra.go

Introduces the ProxyListener type that describes the listener(s) of the managed proxy infra. This will allow the Infra Manager to perform incremental updates of Kube Services whenever a Gateway address or listener is updated.
xref: #180 

Adds ProxyListener to Infra IR

---

internal/ir/infra.go

Previously, a listener could only have a single port. This PR pluralizes `infra.proxy.listeners[].ports` so a listener can have multiple ports.

Pluralizes Listener Ports of Proxy Infra IR

---

internal/provider/kubernetes/httproute.go
internal/provider/kubernetes/kubernetes.go

Adds an initial version of the HTTPRoute
controller to the Kubernetes provider.
Integration with the message service/the
IR to follow.
Closes #163.
There's not really anything to test yet, so deferred adding tests until things start getting integrated.

internal/provider/kubernetes: add HTTPRoute controller

---

api/config/v1alpha1/helpers.go
internal/cmd/server.go
internal/infrastructure/kubernetes/infra.go
internal/infrastructure/kubernetes/infra_test.go
internal/infrastructure/kubernetes/serviceaccount.go
internal/infrastructure/kubernetes/serviceaccount_test.go
internal/infrastructure/manager.go
internal/infrastructure/translator.go
internal/ir/infra.go
internal/ir/infra_test.go

Adds initial Infra Manager implementation.
Requires: https://github.com/envoyproxy/gateway/pull/183
xref: https://github.com/envoyproxy/gateway/issues/41

Adds Initial Infra Manager

---

internal/gatewayapi/helpers.go
internal/provider/kubernetes/kubernetes_test.go

Adds `ResourceTable` coverage to the Kubernetes provider integration tests
Requires: https://github.com/envoyproxy/gateway/pull/194

Updates Integration Tests

---

internal/infrastructure/kubernetes/deployment.go
internal/infrastructure/kubernetes/deployment_test.go
internal/infrastructure/kubernetes/infra.go
internal/ir/infra.go

Adds initial Envoy deployment support to Infra Manager.
Fixes: #185 

Adds Envoy Deployment Support

---

internal/provider/kubernetes/gateway.go
internal/provider/kubernetes/gateway_test.go
internal/provider/kubernetes/gatewayclass.go
internal/provider/kubernetes/kubernetes.go
internal/provider/kubernetes/kubernetes_test.go
internal/status/conditions.go
internal/status/conditions_test.go
internal/status/gateway.go
internal/status/status.go

Previously, the gateway controller would not update the status of gateways. This PR adds the `StatusUpdater` interface to the gateway controller and sets the "Scheduled=True" status condition for gateways that match the configured GatewayClass controllerName.
Fixes: https://github.com/envoyproxy/gateway/issues/165
Fixes: https://github.com/envoyproxy/gateway/issues/166

Adds Gateway Status Support

---

internal/provider/kubernetes/config/envoy-gateway/deploy_and_ns.yaml

Just removing the probe definitions for now
since they're not implemented to unblock
running EG in-cluster, but we should circle
back and implement these eventually.
Updates #235.

remove unimplemented liveness/readiness probes

---

go.mod
go.sum
hack/create-conformance-cluster.sh
internal/provider/kubernetes/config/samples/gatewayclass.yaml
test/conformance/conformance_test.go
tools/make/kube.mk

Supports running Gateway API conformance in a kind
cluster against the envoyproxy/gateway-dev:latest
image.
Updates https://github.com/envoyproxy/gateway/issues/157.

Add make targets for running Gateway API conformance

---

internal/infrastructure/kubernetes/bootstrap.yaml.tpl
internal/infrastructure/kubernetes/deployment.go
internal/infrastructure/kubernetes/deployment_test.go

With https://github.com/envoyproxy/gateway/pull/206, only the Xds server address is configurable. This PR add support to configure Xds server port, admin server host and port.
Fixes #212 
Signed-off-by: Lahiru De Silva <lahirude@wso2.com>

Add support for exposing additional bootstrap config options

---

internal/infrastructure/kubernetes/deployment.go
internal/infrastructure/manager.go

- Set `Namespace` when creating a new Kube Infra manager.
- Removes the bootstrap config volume and references to the volume in the Envoy deployment.
Fixes: #246 

Updates Kube Infra Namespace and Envoy Deployment

---

internal/infrastructure/kubernetes/deployment.go
internal/infrastructure/kubernetes/deployment_test.go
internal/xds/server/runner/runner.go

* fix xds-server's port within the runner to 18000
* make sure the envoy bootstrap config within the infra library
uses the same constant from the xds server runner
* moved vars to const within the kube infra library and renamed some

Fix xds server port

---

tools/make/common.mk

remove deprecated option in `make help`:
Signed-off-by: Xunzhuo <mixdeers@gmail.com>

chore: remove deprecated MAKE_IN_DOCKER option

---

internal/gatewayapi/runner/runner.go
internal/gatewayapi/translator.go

Adds nil checks for `ProviderResources` gatewayclasses, gateways, and httproutes.
Fixes #214 

Adds ProviderResource Nil Checks

---

tools/make/image.mk

Adds closing parentheses to the `image.build` Make target.
Fixes: #257 

Adds Closing Parentheses to image.build Target

---

internal/gatewayapi/runner/runner.go
internal/message/types.go
internal/message/types_test.go
internal/provider/kubernetes/httproute.go
internal/provider/kubernetes/kubernetes_test.go

Adds HTTPRoute backendRefs to the watchable resource map.
- Adds backendRef validation to HTTPRoute controller. Note that only local Service object references are supported.
- Adds valid backendRefs to the watchable resource map.
- Updates Kube integration tests to ensure that valid backendRefs are added to the watchable resource map.
- Adds backendRefs, e.g. Services, to the gatewayapi runner.
- Adds  Services object type to ProviderResources and updates unit tests accordingly.
Fixes: https://github.com/envoyproxy/gateway/issues/189

Adds HTTPRoute BackendRefs to Resource Map

---

internal/gatewayapi/runner/runner.go
internal/infrastructure/kubernetes/infra.go
internal/ir/infra.go
internal/ir/infra_test.go

* Validate the xds and infra IR in the gatewayapi runner
before sending it to the next stage consuming the IRs
* refactor infra ir validate

validate ir before sending it

---

internal/gatewayapi/testdata/gateway-allows-same-namespace-with-allowed-httproute.out.yaml
internal/gatewayapi/testdata/gateway-with-listener-with-tls-secret-in-other-namespace-allowed-by-refgrant.out.yaml
internal/gatewayapi/testdata/gateway-with-listener-with-valid-tls-configuration.out.yaml
internal/gatewayapi/testdata/httproute-attaching-to-gateway.out.yaml
internal/gatewayapi/testdata/httproute-attaching-to-listener.out.yaml
internal/gatewayapi/testdata/httproute-rule-with-multiple-backends-and-no-weights.out.yaml
internal/gatewayapi/testdata/httproute-rule-with-multiple-backends-and-weights.out.yaml
internal/gatewayapi/testdata/httproute-with-backendref-in-other-namespace-allowed-by-refgrant.out.yaml
internal/gatewayapi/testdata/httproute-with-invalid-backendref-in-other-namespace.out.yaml
internal/gatewayapi/testdata/httproute-with-single-rule-with-exact-path-match.out.yaml
internal/gatewayapi/testdata/httproute-with-single-rule-with-path-prefix-and-exact-header-matches.out.yaml
internal/gatewayapi/translator.go

translator: listener hostnames unset

---

tools/hack/create-cluster.sh
tools/hack/kind-load-image.sh
tools/hack/run-kube-local.sh

Use consistent shebang for other scripts as well.
Otherwise it fails with:
```
tools/hack/run-kube-local.sh: 1: set: Illegal option -o pipefail
```

Add shebang in run-kube-local.sh

---

.github/workflows/build_and_test.yaml

Restrict make build-multiarch to pull_request only, since `make image.push.multiarch` will excute it again.

chore: restrict make build-multiarch to pull_request only

---

.gitignore
tools/hack/build-install-yaml.sh
tools/hack/kind-load-image.sh
tools/hack/release-manifests.sh
tools/make/kube.mk

Adds a Make target to generate:
1. The Kube manifests to run EG.
2. The Gateway API manifests that are supported by the EG release.
This will support
```
kubectl apply -f https://github.com/envoyproxy/gateway/releases/download/${ENVOY_GATEWAY_RELEASE_TAG}/gatewayapi-crds.yaml
kubectl apply -f https://github.com/envoyproxy/gateway/releases/download/${ENVOY_GATEWAY_RELEASE_TAG}/install.yaml
```
xref: https://github.com/envoyproxy/gateway/issues/296
xref: https://github.com/envoyproxy/gateway/pull/298
xref: https://github.com/envoyproxy/gateway/issues/297

Adds Make Target to Generate Release Manifests

---

.github/workflows/release.yaml

* `release` dir was renamed to `release-artifacts`

release GHA: upload files in release-artifacts

---

.github/workflows/release.yaml

Prevent triggering release workflow from weird tags like `vxxx`, any tags with `v` as the first word will trigger the release workflow, we should add restriction to it.
`"v*.*.*"` this pattern only matches standard tag like `v0.2.0` or `v0.2.0-rc1`.

chore: add restrict to tag trigger

---

tools/hack/release-manifests.sh

the image tag was generated as:
`envoyproxy/gateway:[[ 2 == 2 ]]`
which was invalid

ci: fix manifest image tag

---

.github/workflows/release.yaml
tools/make/common.mk
tools/make/golang.mk
tools/make/kube.mk

Fixed:
image tag of EG in release manifests is incorrect 😢, let us fix it.

fix: wrong image name in release manifests

---

tools/github-actions/setup-deps/action.yaml

no longer needed after https://github.com/envoyproxy/gateway/pull/305
was merged

rm docker buildx action setup

---

.github/workflows/release.yaml

* instead of rebuilding and retesting the image,
reuse/retag the envoyproxy/gateway-dev with the matching commit SHA
Addresses https://github.com/envoyproxy/gateway/pull/299#discussion_r959118354

retag gateway-dev image in release GHA

---

.github/workflows/build_and_test.yaml
tools/make/image.mk

Fix #342 
Tested in: https://github.com/Xunzhuo/gateway/runs/8215648214?check_suite_focus=true

chore: split up `push-multiarch` and make dev images manifests matched

---

internal/gatewayapi/testdata/gateway-with-two-listeners-with-same-port-and-hostname.in.yaml
internal/gatewayapi/testdata/gateway-with-two-listeners-with-same-port-and-hostname.out.yaml
internal/gatewayapi/testdata/httproute-with-non-matching-specific-hostname-attaching-to-gateway-with-wildcard-hostname.out.yaml
internal/gatewayapi/testdata/httproute-with-redirect-filter-full-path-replace-https.in.yaml
internal/gatewayapi/testdata/httproute-with-redirect-filter-full-path-replace-https.out.yaml
internal/gatewayapi/testdata/httproute-with-redirect-filter-hostname.in.yaml
internal/gatewayapi/testdata/httproute-with-redirect-filter-hostname.out.yaml
internal/gatewayapi/testdata/httproute-with-redirect-filter-invalid-filter-type.in.yaml
internal/gatewayapi/testdata/httproute-with-redirect-filter-invalid-filter-type.out.yaml
internal/gatewayapi/testdata/httproute-with-redirect-filter-invalid-scheme.in.yaml
internal/gatewayapi/testdata/httproute-with-redirect-filter-invalid-scheme.out.yaml
internal/gatewayapi/testdata/httproute-with-redirect-filter-invalid-status.in.yaml
internal/gatewayapi/testdata/httproute-with-redirect-filter-invalid-status.out.yaml
internal/gatewayapi/testdata/httproute-with-redirect-filter-prefix-replace-with-port-http.in.yaml
internal/gatewayapi/testdata/httproute-with-redirect-filter-prefix-replace-with-port-http.out.yaml

Both the linter and the tests are broken on `main`. A PR that tightens up the `yamllint` config was merged concurrently with several PRs that add YAML that the new config complains about. A PR that adds a field to testdata output files was merged concurrently with PRs that add new testdata output files (and so don't have that new field). These are merge conflicts, but Git wasn't able to recognize them as such; fix those conflicts.

Fix merge-conflict-caused CI breakage

---

tools/make/lint.mk

* replace `` with '' to skip executing 'make manifests'
* rm @ in indented echo cmd within if statement

fix `make gen-check` error msg

---

internal/gatewayapi/runner/runner_test.go
internal/message/types.go
internal/message/types_test.go
internal/provider/kubernetes/gatewayclass.go

Also fixes: https://github.com/envoyproxy/gateway/issues/228

reset watchable map when gatewayclass is empty

---

internal/envoygateway/config/config.go
internal/gatewayapi/translator.go
internal/infrastructure/kubernetes/deployment.go
internal/provider/kubernetes/gateway.go
internal/status/conditions.go
internal/status/conditions_test.go
internal/status/gateway.go

This commit adds support for watching over envoy deployment updates, 
and capture the deployment status to eventually determine the gateway 
status condition. We mark the gateway as ready, if the envoy deployment
has no unavailable replicas.
Resolves #345 

Add Gateway condition based on Envoy deployment status

---

internal/gatewayapi/testdata/httproute-with-header-filter-no-headers.in.yaml
internal/gatewayapi/testdata/httproute-with-header-filter-no-headers.out.yaml
internal/gatewayapi/translator.go
internal/xds/translator/route.go

There were a few outstanding comments from https://github.com/envoyproxy/gateway/pull/363 that were not addressed when it was merged. This PR adds the requested changes and resolves issue https://github.com/envoyproxy/gateway/issues/391.
Changes:
- Fixed a typo in one of the request header modifier filter error statuses.
- Reduced un-necessary indentation
- Added comments with reason behind one of the error cases (Gateway API specification)
- Replaced a deprecated dependency

Address comments from PR#363

---

internal/gatewayapi/testdata/httproute-with-header-filter-no-headers.out.yaml

Adds the `controllerName: gateway.envoyproxy.io/gatewayclass-controller` in the expected output from one of the test manifests.

Set missing controller name in test manifest

---

api/config/v1alpha1/helpers.go
go.mod
go.sum
internal/cmd/certgen.go
internal/cmd/certgen_test.go
internal/cmd/root.go
internal/crypto/certgen.go
internal/crypto/certgen_test.go
internal/envoygateway/config/config.go
internal/infrastructure/kubernetes/bootstrap.yaml.tpl
internal/infrastructure/kubernetes/configmap.go
internal/infrastructure/kubernetes/configmap_test.go
internal/infrastructure/kubernetes/deployment.go
internal/infrastructure/kubernetes/infra.go
internal/provider/kubernetes/config/envoy-gateway/certgen-job.yaml
internal/provider/kubernetes/config/envoy-gateway/deploy_and_ns.yaml
internal/provider/kubernetes/config/envoy-gateway/kustomization.yaml
internal/provider/kubernetes/secrets.go
internal/xds/server/runner/runner.go
internal/xds/server/runner/runner_test.go

- Adds a package for generating control plane auth certs.
- Adds a const to the EG config pkg to represent the default "envoy-gateway-system" ns.
- Updates `ObjectName()` method to get/set the default name of the ProxyInfra type.
fixes: #70 

Adds Support for Control Plane TLS

---

internal/provider/kubernetes/httproute.go
internal/provider/kubernetes/httproute_test.go

Adds support for validating `parentRefs` of an HTTPRoute. Previously, the httproute controller would process an HTTPRoute even if it references a gateway that doesn't. This causes EG to perform unnecessary processing. An HTTPRoute does not contain `status` so an error is surfaced.
Partially Fixes: #301

Adds HTTPRoute ParentRef Validation

---

docs/user/QUICKSTART.md

* port should be the service port `8080`

fix port for curl command example

---

DEVELOPER.md
tools/make/kube.mk

* match the examples to previous `build-multiarch` section
* rm `@` from make target to expose cmds running / improve debuggability

docs: nits for `kube-deploy` docs

---

internal/gatewayapi/runner/runner.go

* Fixes a regression caused by https://github.com/envoyproxy/gateway/pull/420 which stalled namespace notifications until the httproute resource were initialized, but the namespaces are required to be populated to built listener context which affects infra IR creation.

Stall ns notifications until gws have inited

---

.github/workflows/build_and_test.yaml
test/conformance/conformance_test.go
tools/hack/kind-load-image.sh
tools/make/kube.mk

Updates conformance tests to:
- Run in CI
- Run one test, `HTTPRouteSimpleSameNamespace` instead of the entire suite.
- Update Gateways to use different port numbers.
- Adds sets additional test flags to make target.

Update Conformance Tests

---

internal/status/gateway.go

Updates gateway status address caculation to support running conformance tests locally.
Fixes: #427 

Updates Gateway Status Addresses

---

tools/make/kube.mk

```
make kube-demo
kubectl apply -f examples/kubernetes/httpbin.yaml
serviceaccount/httpbin unchanged
service/httpbin unchanged
deployment.apps/httpbin unchanged
kubectl apply -f examples/kubernetes/gatewayclass.yaml
gatewayclass.gateway.networking.k8s.io/eg unchanged
kubectl apply -f examples/kubernetes/gateway.yaml
gateway.gateway.networking.k8s.io/eg configured
kubectl apply -f examples/kubernetes/httproute.yaml
httproute.gateway.networking.k8s.io/httpbin configured
Port forward to the Envoy service using the command below
kubectl -n envoy-gateway-system port-forward service/envoy-default-eg 8888:8080 &
Curl the app through Envoy proxy using the command below
curl --verbose --header "Host: www.example.com" http://localhost:8888/get
```

add make demo to deploy example resources

---

internal/provider/kubernetes/gateway.go
internal/provider/kubernetes/httproute.go
internal/status/conditions.go
internal/status/conditions_test.go
internal/status/gateway.go
internal/status/gatewayclass.go

Fixes: https://github.com/envoyproxy/gateway/issues/414

merge gateway conditions before updating status

---

internal/provider/kubernetes/httproute.go
internal/provider/kubernetes/httproute_test.go

Adds a watch for Gateway objects to the httproute controller. Valid HTTPRoutes that reference gateways managed by EG will be enqueued for reconciliation.
Partially Fixes: #301

Adds Gateway Watch to HTTPRoute Controller

---

DEVELOPER.md

Just adds a little info to DEVELOPER.md that might be helpful to others who want to view the envoy config or were otherwise not aware of how to access the admin interface that we setup.

DEVELOPER.md: add envoy debugging info

---

internal/gatewayapi/runner/runner.go
internal/message/types.go
internal/provider/kubernetes/gateway.go
internal/provider/kubernetes/gatewayclass.go
internal/provider/kubernetes/httproute.go

* removes all the waitgroup logic associated with the provider resources (gatewayclass, gateway, httproute) that was added to ensure that all resources within the watchable map was comepletely initialized before the gateway api translated the resources
* this logic is being removed because the individual waitgroups for each resource are causing a sort of deadlock within the gateway-api runner and not allowing it to process new notifications
* removing this logic does mean that there might some churn in the dataplane during EG reboots. This should get fixed with https://github.com/envoyproxy/gateway/issues/413 which plans on reconciling all resources within a single controller so we cont need to synchonize across multiple controllers using multiple waitgroups
Signed-off-by: Arko Dasgupta …

rm provider resource wait during init logic

---

internal/envoygateway/config/config.go
internal/gatewayapi/runner/runner.go
internal/gatewayapi/runner/runner_test.go
internal/infrastructure/kubernetes/configmap.go
internal/infrastructure/kubernetes/configmap_test.go
internal/infrastructure/kubernetes/deployment.go
internal/infrastructure/kubernetes/infra.go
internal/infrastructure/runner/runner.go
internal/xds/server/runner/runner.go
internal/xds/translator/runner/runner.go
internal/xds/translator/runner/runner_test.go

* Add a function that computes which keys to delete in the gateway-api runner
* Delete above keys from the Infra and Xds IR maps
* Update infra and xds runners to trigger deletes when a delete notification is recieved.
Fixes: https://github.com/envoyproxy/gateway/issues/423

Handle IR Deletes

---

test/conformance/conformance_test.go

Adds HTTPRouteInvalidCrossNamespaceBackendRef to the active conformance tests, should have been fixed by  https://github.com/envoyproxy/gateway/pull/443 and resolves issue https://github.com/envoyproxy/gateway/issues/433

run invalid cross namespace backend conformance test

---

internal/provider/kubernetes/gatewayclass.go
internal/provider/kubernetes/gatewayclass_test.go

This commit removes a gatewayclass object from controllerClasses when a object Deletion is triggered. This also maintains the oldest class in controlledClasses.
Fixes #222

[provider] Remove gateway class from controlledClasses on Delete

---

internal/infrastructure/kubernetes/deployment.go
internal/infrastructure/kubernetes/deployment_test.go
internal/infrastructure/kubernetes/infra.go
internal/infrastructure/kubernetes/infra_test.go
internal/infrastructure/kubernetes/service.go
internal/infrastructure/kubernetes/service_test.go
internal/infrastructure/kubernetes/serviceaccount.go
internal/infrastructure/kubernetes/serviceaccount_test.go

Drops the Resources struct as it was only
being used to record state of the created
Kubernetes resources for testing purposes.
Replaces it with calls to the fake kube
client to fetch the resources.
Closes #370.
This will make implementing #457 easier.
cc @danehans - let me know if I misunderstood the purpose of the existing structure.

internal/infrastructure/kubernetes: drop Resources struct

---

internal/infrastructure/kubernetes/bootstrap.yaml.tpl

Use Delta xDS by default

---

internal/gatewayapi/runner/runner.go
internal/provider/kubernetes/gatewayclass.go

* Delete the gatewayclass from the watchable map if it has been scheduled for deletion
* We always end up storing the accepted gatewayclass in the same controller in the same function
* Clean up the gateway-api runner code which earlier expected a gatewayclass slice with a `nil` element

Fix flow for gatewayclass deletes

---

internal/infrastructure/kubernetes/configmap.go
internal/infrastructure/kubernetes/configmap_test.go
internal/infrastructure/kubernetes/infra_test.go
internal/infrastructure/kubernetes/serviceaccount.go
internal/infrastructure/kubernetes/serviceaccount_test.go

Adds the Gateway owner namespace/name labels
to ConfigMaps and ServiceAccounts to be consistent 
with Deployments and Services.
Closes #457.

add Gateway owner labels to ConfigMap and ServiceAccount

---

internal/provider/kubernetes/gateway.go

1) update the reconciled gateway resource with a newer status in the provider
2) pass that updated resource to the status update goroutine
3) store the updated resource in the watchable map so the gateway api translator performs status updates on the newer resource
Fixes: https://github.com/envoyproxy/gateway/issues/459
Fixes: https://github.com/envoyproxy/gateway/issues/464

Order gateway resource updates in provider

---

internal/provider/kubernetes/gatewayclass.go

The arch has been revised to handle watchable stores and deletes
Fixes: https://github.com/envoyproxy/gateway/issues/467

Dont store nil resources in watchable

---

internal/gatewayapi/runner/runner_test.go
internal/message/types.go
internal/message/types_test.go
internal/provider/kubernetes/gatewayclass.go

There's no need to reset the gatewayclass since we delete the gatewayclass from the watchable map when it is marked for deletion

delete unneeded gatewayclass delete logic

---

DEVELOPER.md
docs/user/QUICKSTART.md

Updates the supported Kube version to `v1.24.0` based on the [create-cluster](https://github.com/envoyproxy/gateway/blob/v0.2.0-rc2/tools/hack/create-cluster.sh#L8) target.

Fixes Supported Kube Version

---

README.md
docs/design/ROADMAP.md

Adds roadmap doc and links from README.md.
Fixes #11 

Adds Roadmap Doc

---

.github/workflows/docs.yaml
DOCS.md
docs/conf.py
docs/index.rst
docs/intro/compatibility.rst
internal/cmd/root.go
internal/cmd/versions.go
tools/make/docs.mk

Include them dynamically in the docs index, and manually in a barebones compatibility matrix.
Reviewers: It is very much worth discussing whether the approach here of pulling versions out
of the code is the Right Way to Do Things™.
Signed-off-by: Flynn emissary@flynn.kodachi.com

Pull Envoy and Gateway API versions out of code.

---

internal/gatewayapi/sort.go
internal/gatewayapi/testdata/httproutes-with-multiple-matches.in.yaml
internal/gatewayapi/testdata/httproutes-with-multiple-matches.out.yaml
internal/gatewayapi/translator.go
test/conformance/conformance_test.go

Sort based on the match precedence defined in
https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.HTTPRouteRule
Fixes: https://github.com/envoyproxy/gateway/issues/436 Fixes: https://github.com/envoyproxy/gateway/issues/483

Sort match conditions based on Gateway API Spec

---

.github/codecov.yml

* add coverage threshold ci test, from base commit coverage to compare against. and we not allow coverage drop. ref: <https://docs.codecov.com/docs/commit-status>
Signed-off-by: ethan <hanjiahao@corp.netease.com>
issue: https://github.com/envoyproxy/gateway/issues/74

Update codecov.yml for threshold check

---

internal/gatewayapi/contexts.go
internal/gatewayapi/helpers.go
internal/gatewayapi/testdata/httproute-attaching-to-gateway-with-more-different-listeners.in.yaml
internal/gatewayapi/testdata/httproute-attaching-to-gateway-with-more-different-listeners.out.yaml
internal/gatewayapi/testdata/httproute-attaching-to-gateway-with-more-listeners.in.yaml
internal/gatewayapi/testdata/httproute-attaching-to-gateway-with-more-listeners.out.yaml

Fixes: https://github.com/envoyproxy/gateway/issues/533

fix: set correct listenerContext order

---

internal/provider/kubernetes/gateway.go
internal/provider/kubernetes/gatewayclass.go
internal/provider/kubernetes/httproute.go
internal/provider/kubernetes/kubernetes_test.go

Leverage the metadata.Generation field to consider whether to update the newly reconciled resource into the watchable map which will trigger translations in the backend.
Fixes: https://github.com/envoyproxy/gateway/issues/407

provider: only store resource if spec has changed

---

internal/gatewayapi/sort.go

No longer needed now that order is maintained
by using a list, thanks to https://github.com/envoyproxy/gateway/pull/535

remove xds ir listener sort

---

.github/workflows/release.yaml
kustomization.yaml

Merges the Gateway API install manifest into the EG install manifest. Now, only the EG install manifest will be produced as a release artifact. Users will only need a single `kubectl apply` command to install EG and dependent resources, e.g. Gateway API CRDs.
Fixes: #485 

Merges Release Manifests

---

internal/gatewayapi/testdata/httproute-with-header-filter-duplicate-add-multiple-filters.out.yaml
internal/gatewayapi/testdata/httproute-with-header-filter-duplicate-adds.out.yaml
internal/gatewayapi/testdata/httproute-with-header-filter-duplicate-remove-multiple-filters.out.yaml
internal/gatewayapi/testdata/httproute-with-header-filter-duplicate-removes.out.yaml
internal/gatewayapi/testdata/httproute-with-header-filter-empty-headers.out.yaml
internal/gatewayapi/testdata/httproute-with-header-filter-invalid-headers.out.yaml
internal/gatewayapi/testdata/httproute-with-header-filter-no-valid-headers.out.yaml
internal/gatewayapi/testdata/httproute-with-redirect-filter-invalid-filter-type.out.yaml
internal/gatewayapi/testdata/httproute-with-redirect-filter-invalid-scheme.out.yaml
internal/gatewayapi/testdata/httproute-with-redirect-filter-invalid-status.out.yaml
internal/gatewayapi/translator.go

Updates the `Accepted` condition type to use [RouteReasonUnsupportedValue](https://pkg.go.dev/sigs.k8s.io/gateway-api/apis/v1beta1@v0.5.1#RouteReasonUnsupportedValue) instead of the `ResolvedRefs` condition type.
Fixes #494 

Updates ParentRef Status Conditions

---

internal/infrastructure/kubernetes/infra.go
internal/infrastructure/kubernetes/infra_test.go
internal/infrastructure/manager.go
internal/infrastructure/runner/runner.go

Resolve: https://github.com/envoyproxy/gateway/issues/182
Since this is a backlog issue, I will work on this after releasing v0.2.0.

feat: set mgr to interface

---

docs/design/SYSTEM_DESIGN.md

Confused by the documented cardinality of Gateway components and their Proxy representations, I deployed the gateway with two HTTPRoutes and did a config dump of the gateway. The docs `Route` refers to the proxy `RouteConfiguration`, but it should indeed refer to `Route`.
Signed-off-by: Fredrik Geijer Haeggström <fredrik.g.haeggstrom@gmail.com>

docs: correcting route ref, system design

---

internal/gatewayapi/testdata/gateway-with-listener-with-invalid-tls-configuration-secret-in-other-namespace.out.yaml
internal/gatewayapi/translator.go
test/conformance/conformance_test.go

Closes https://github.com/envoyproxy/gateway/issues/538.

use RefNotPermitted reason for invalid cross-namespace TLS cert ref 

---

internal/gatewayapi/testdata/httproute-with-header-filter-empty-headers.out.yaml
internal/gatewayapi/testdata/httproute-with-header-filter-invalid-headers.out.yaml
internal/gatewayapi/testdata/httproute-with-header-filter-no-valid-headers.out.yaml
internal/gatewayapi/testdata/httproute-with-redirect-filter-invalid-filter-type.out.yaml
internal/gatewayapi/testdata/httproute-with-redirect-filter-invalid-scheme.out.yaml
internal/gatewayapi/testdata/httproute-with-urlrewrite-filter-invalid-filter-type.in.yaml
internal/gatewayapi/testdata/httproute-with-urlrewrite-filter-invalid-filter-type.out.yaml
internal/gatewayapi/translator.go

Previously, `ProcessHTTPRoutes()` of the gatewayapi translator would set "Accepted=True" as the default status condition. With #516 the status conditions get reset for every HTTPRoute reconciliation and "Accepted=True" should only be set if no status conditions for the parentRef exist.
Fixes: #562

Fixes Calculating ParentRef Status Conditions

---

internal/provider/kubernetes/gateway.go

When a Gateway resource is deleted, its Secrets in resource map which are not referenced from other Gateways should be deleted. It was in the other way around and this  PR is to fix it.

Fix Secrets deletion logic in gateway reconcile method

---

tools/linter/codespell/.codespell.skip

Update spellcheck linter to ignore `./docs/html` docs generated by our docs workflow.

Updates Spellcheck Ignore

---

docs/user/HTTP_TRAFFIC_SPLITTING.md

Adds a user guide for configuring HTTPRoute redirects.
xref: https://github.com/envoyproxy/gateway/issues/501

Add HTTPRoute traffic split doc

---

internal/xds/translator/translator.go

* findXdsHTTPRouteConfigName should only be executed for HTTP listeners, not for HTTPS since we create a new filterChain for them.
Fixes: https://github.com/envoyproxy/gateway/issues/520#issuecomment-1283089969

Fix Merge for HTTPS listeners

---

CODEOWNERS.md

Signed-off-by: alex <alex@datawire.io>
Replacing myself as codeowner given my lack of involvement in the project lately with @AliceProxy who has been much more active and contributing.

Switching codeowners

---

internal/gatewayapi/runner/runner.go
internal/ir/xds.go
internal/ir/xds_test.go

* Printable returns a safe copy that can be printed/logged
* Reintroduce printing xds ir in the gateway api runner

Add a Printable method to Xds IR

---

internal/provider/kubernetes/gateway.go

Fixes: https://github.com/envoyproxy/gateway/issues/588

fix deletions for secrets

---

docs/dev/README.md

Previously, the troubleshooting section of the Dev Guide was using the pre-hashed name for the Envoy deployment.

Updates Dev Guide for Hashed Naming

---

internal/provider/kubernetes/httproute.go
internal/provider/kubernetes/kubernetes_test.go
internal/provider/kubernetes/store_test.go
internal/provider/kubernetes/tlsroute.go

This commit adds tests related to cleaning up of
stale Services from the resource map, and fixes issues around it.

fix service cleanup in resource map add tests

---

internal/xds/translator/listener.go
internal/xds/translator/testdata/in/xds-ir/multiple-listeners-same-port.yaml
internal/xds/translator/testdata/out/xds-ir/multiple-listeners-same-port.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/multiple-listeners-same-port.routes.yaml
internal/xds/translator/testdata/out/xds-ir/multiple-listeners-same-port.secrets.yaml
internal/xds/translator/translator.go

Gracefully handle the case when an https listener is first created, and then an http one is added later. In such a case the route config within the default filter chain wouldnt exist

fix merging https and http listeners on same port

---

tools/make/kube.mk

Resolves: https://github.com/envoyproxy/gateway/issues/596
This command is used for the release manager, update the quickstart.md after cutting a release branch.

chore: add update-quickstart to update tag in quickstart

---

CODEOWNERS.md

Adds @Xunzhuo as a maintainer.

Adds Xunzhuo as a Maintainer

---

.github/workflows/build_and_test.yaml
.github/workflows/docs.yaml

Fixes: https://github.com/envoyproxy/gateway/issues/629
We should be careful about changing the branch naming pattern, if we did change, do not forget to sync to build-and-test and doc workflow, since they should be triggered to run and build the last commit merged into release branch,

fix: update build-and-test workflow to match the latest branch pattern

---

docs/index.rst
docs/releases/v0.2.md

Adds a doc for announcing the v0.2 release.

Adds v0.2 Release Announcement Doc

---

internal/gatewayapi/testdata/httproute-with-single-rule-with-http-method-match.in.yaml
internal/gatewayapi/testdata/httproute-with-single-rule-with-http-method-match.out.yaml
internal/gatewayapi/translator.go

Closes #655.
Note, the conformance test for this was added after Gateway API v0.5.1 so we can't run it until we pick up v0.6.0, but here are the results from running it manually from `main`:
```shell
--- PASS: TestConformance (17.18s)
--- PASS: TestConformance/HTTPRouteMethodMatching (1.04s)
--- PASS: TestConformance/HTTPRouteMethodMatching/2_request_to_'/'_should_receive_a_404 (4.04s)
--- PASS: TestConformance/HTTPRouteMethodMatching/0_request_to_'/'_should_go_to_infra-backend-v1 (4.04s)
--- PASS: TestConformance/HTTPRouteMethodMatching/1_request_to_'/'_should_go_to_infra-backend-v2 (4.05s)
```
I'll file another issue to remind us to enable the test down the road.

internal/gatewayapi: support HTTP method matching

---

internal/gatewayapi/testdata/tlsroute-with-empty-hostname.in.yaml
internal/gatewayapi/testdata/tlsroute-with-empty-hostname.out.yaml
internal/gatewayapi/testdata/tlsroute-with-empty-listener-hostname.in.yaml
internal/gatewayapi/testdata/tlsroute-with-empty-listener-hostname.out.yaml
internal/gatewayapi/translator.go

* use the result from `computeHosts` which returns the list of intersecting hostnames between the listener and the route to populate the SNIs field within the Xds IR TCP Listener
Fixes: https://github.com/envoyproxy/gateway/issues/661

Fix hostname parsing for TLSRoutes

---

.github/workflows/build_and_test.yaml

Addresses deprecations, possibly
helps with the upload flake.
(See e.g. https://github.com/envoyproxy/gateway/actions/runs/3379855695 for the deprecation warning)

update codecov action to v3

---

internal/xds/translator/accesslog.go
internal/xds/translator/listener.go
internal/xds/translator/testdata/out/xds-ir/http-route-direct-response.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-redirect.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-request-headers.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-weighted-invalid-backend.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/multiple-listeners-same-port.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/simple-tls.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/tls-route-passthrough.listeners.yaml

fixes: #684
output as follow:
```
[2022-11-07T01:44:50.341Z] "GET /get HTTP/1.1" 200 - 0 426 0 0 "-" "curl/7.58.0" "f5dec879-4c62-4a7d-a555-d7c044c9d5f0" "www.example.com" "10.96.77.203:3000"
```
this's not for https://github.com/envoyproxy/gateway/issues/699

translator: add accesslog

---

docs/latest/design/roadmap.md

Update roadmap for v0.3.0

---

internal/gatewayapi/testdata/gateway-with-listener-with-tls-terminate-and-passthrough.out.yaml
internal/gatewayapi/testdata/tlsroute-attaching-to-gateway.out.yaml
internal/gatewayapi/testdata/tlsroute-multiple.in.yaml
internal/gatewayapi/testdata/tlsroute-multiple.out.yaml
internal/gatewayapi/testdata/tlsroute-with-backendref-in-other-namespace-allowed-by-refgrant.out.yaml
internal/gatewayapi/testdata/tlsroute-with-empty-hostname.out.yaml
internal/gatewayapi/translator.go

* had to also append the TLSRoute name to the listener to make it unique
Fixes: https://github.com/envoyproxy/gateway/issues/691

Add new Xds IR TCP Listener per TLSRoute

---

README.md

- Adds link for joining the Envoy Slack workspace.
- Removes the Google group reference since it's not being used or monitored.

Updates Readme Slack and Google Group

---

docs/latest/dev/README.md
docs/v0.2.0/dev/README.md

Previously:
```
$ export ENVOY_DEPLOYMENT=$(kubectl get deploy -n envoy-gateway-system --selector=gateway.envoyproxy.io/owning-gateway-namespace=default,gateway.envoyproxy.io/owning-gateway-name=eg -o jsonpath='{.items[0].metadata.name}')
$ echo $ENVOY_DEPLOYMENT
envoy-default-eg-64656661
$ kubectl port-forward deploy/envoy-${ENVOY_DEPLOYMENT} -n envoy-gateway-system 19000:19000
Error from server (NotFound): deployments.apps "envoy-envoy-default-eg-64656661" not found
```
After removing `envoy-`:
```
$ kubectl port-forward deploy/${ENVOY_DEPLOYMENT} -n envoy-gateway-system 19000:19000
Forwarding from 127.0.0.1:19000 -> 19000
Forwarding from [::1]:19000 -> 19000
```

Fixes Envoy Deployment Ref in Dev Doc

---

.github/workflows/build_and_test.yaml
tools/make/image.mk
tools/make/kube.mk

Run conformance test concurrently in multi kube-version.
Roughly calculated that the new mode will save about half the time compared to the previous one.
As we add more kube versions to run conformance tests, the running time of build-and-test workflow will nearly not increase. But the former way will cause the time to grow exponentially.
https://github.com/envoyproxy/gateway/actions/runs/3425534566

opt: run conformance test concurrently in multi-kube-version

---

CODEOWNERS.md

As stated in last week's meeting, I'm moving on from Ambassador Labs and don't anticipate being involved with Envoy Gateway going forward.

CODEOWNERS.md: Remove myself

---

internal/infrastructure/kubernetes/bootstrap.yaml.tpl

Fixes #762 
These settings are unused since they are set from [CLI args](https://github.com/envoyproxy/gateway/blob/v0.2.0/internal/infrastructure/kubernetes/deployment.go#L225-L226).

Removes Duplicate Settings from Bootstrap Config

---

go.mod

Fixes: https://github.com/envoyproxy/gateway/issues/752

chore: bump golang to 1.19

---

internal/cmd/certgen.go
internal/cmd/server.go
internal/crypto/certgen.go
internal/crypto/certgen_test.go
internal/envoygateway/config/config.go
internal/envoygateway/config/config_test.go
internal/gatewayapi/runner/runner_test.go
internal/infrastructure/kubernetes/configmap_test.go
internal/infrastructure/kubernetes/deployment_test.go
internal/infrastructure/kubernetes/infra.go
internal/infrastructure/kubernetes/service_test.go
internal/infrastructure/kubernetes/serviceaccount_test.go
internal/infrastructure/manager.go
internal/provider/kubernetes/controller.go
internal/provider/kubernetes/kubernetes_test.go
internal/provider/kubernetes/predicates.go
internal/xds/translator/runner/runner_test.go

Adds `Namespace` field to the server config API type. This allows the namespace that EG runs in to be consumed by different types, e.g. Kube controllers to filter watches.
Fixes #777

Adds Namespace Support to Server Config Type

---

api/v1alpha1/groupversion_info.go
docs/latest/user/http-traffic-splitting.md
docs/v0.2.0/user/http-traffic-splitting.md
examples/kubernetes/http-routing.yaml
examples/kubernetes/quickstart.yaml
examples/kubernetes/tls-passthrough.yaml

Resolves: https://github.com/envoyproxy/gateway/issues/719

chore: bump echo-server to demonstrate response header modifier

---

internal/provider/kubernetes/controller.go

fix status subscriber shutdown log

---

internal/provider/kubernetes/controller.go
internal/provider/kubernetes/kubernetes_test.go
internal/provider/kubernetes/predicates.go
internal/provider/kubernetes/predicates_test.go
internal/provider/kubernetes/test/utils.go

[provider] unit tests for predicate functions

---

docs/latest/design/gatewayapi-translator.md
docs/latest/dev/CODE_OF_CONDUCT.md
docs/latest/index.rst
docs/latest/user/tls-passthrough.md
docs/v0.2.0/design/gatewayapi-translator.md
docs/v0.2.0/dev/CODE_OF_CONDUCT.md
docs/v0.2.0/index.rst
docs/v0.2.0/user/tls-passthrough.md

`make doc` command generates six warnings：
I have solved the last four warnings, but the first two "warnings" have not been solved
The `warning1` is because there are many subtitles with the same name, the file link is invalid
The `warning2` is that several files have not been determined and added to the directory
The last two warnings cause code block highlighting failure，I'm not sure if my changes are appropriate
Signed-off-by: thredreams <1220474743@qq.com>

fix:solve the warnings in 'make doc'

---

internal/provider/kubernetes/controller.go
internal/provider/kubernetes/helpers.go
internal/provider/kubernetes/routes.go
test/conformance/conformance_test.go

Previously, a route, e.g. HTTPRoute, could not reference a backend in a different namespace due to `validateBackendRef()` returning an error if a BackendRef included the `namespace` field.
- Updates `Reconcile()` to only add a RefereneGrant to the resource tree if the RefereneGrant can be found and only return an error if an error was received when listing RefereneGrants.
- Updates `Reconcile()` to only add s Service to the resource tree if the Service can be found and only return an error if an error was received when Getting the Service.
- Updates `validateBackendRef()` to no longer return an error if the `namespace` field is set for a backendRef.
- Adds the `HTTPRouteReferenceGrant` conformance test.
Fixes #792
Fixes #788
Fixes #545 

Add ReferenceGrant Support for Routes

---

test/conformance/conformance_test.go

Enables `HTTPRoutePartiallyInvalidViaInvalidReferenceGrant`
Fixed by https://github.com/envoyproxy/gateway/pull/793
Closes https://github.com/envoyproxy/gateway/issues/781

Enable remaining refgrant conformance test

---

internal/provider/kubernetes/controller.go
internal/provider/kubernetes/routes_test.go

Caused by merging https://github.com/envoyproxy/gateway/pull/791 without rebasing https://github.com/envoyproxy/gateway/pull/816

Fix package import for HTTPRouteFilterExtensionRef

---

.github/workflows/stale.yml

Set `days-before-close` to `-1` to disable closing stale PRs or Issues. Defined in https://github.com/actions/stale/blob/main/action.yml
Fixes: https://github.com/envoyproxy/gateway/issues/820

Dont close stale Issues or PRs

---

.github/dependabot.yml

* this causes `gen-check` to fail in CI since CI re generates the CRDs and this change causes a change in the CRD as well
* so disable the dependabot bump and make this bump manual instead.
Detailed error logs are here
```
2022-12-21T14:18:59.7382106Z [0;32m===========> Running gen-check ... [0m
2022-12-21T14:18:59.7605231Z [0;31m===========> ERROR: Some files need to be updated[0m
2022-12-21T14:18:59.7634427Z diff --git a/internal/provider/kubernetes/config/crd/bases/config.gateway.envoyproxy.io_envoyproxies.yaml b/internal/provider/kubernetes/config/crd/bases/config.gateway.envoyproxy.io_envoyproxies.yaml
2022-12-21T14:18:59.7635180Z index 09a060b..4660195 100644
2022-12-21T14:18:59.7635783Z --- a/internal/provider/kubernetes/config/crd/bases/config.gateway.envoyproxy.io_envoyproxies …
```

disable dependabot bump for tools/*/controller-gen

---

internal/provider/kubernetes/config/rbac/role.yaml
internal/provider/kubernetes/controller.go
internal/provider/kubernetes/predicates.go
internal/provider/kubernetes/predicates_test.go
internal/provider/kubernetes/rbac.go
internal/provider/kubernetes/routes.go
internal/provider/kubernetes/test/utils.go
internal/xds/translator/listener.go
internal/xds/translator/testdata/out/xds-ir/udp-route.listeners.yaml

This PR is a part of https://github.com/envoyproxy/gateway/issues/641
An example of UDPRoute
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
name: coredns
spec:
parentRefs:
- group: gateway.networking.k8s.io
kind: Gateway
name: eg
rules:
- backendRefs:
- group: ""
kind: Service
name: coredns
port: 53
```

add udproute support to kubernetes provider

---

internal/cmd/server.go
internal/message/types.go

simplify ProviderResources close

---

internal/xds/server/runner/runner.go

Fixes: https://github.com/envoyproxy/gateway/issues/734
Fixes: https://github.com/envoyproxy/gateway/issues/747
Fixes: https://github.com/envoyproxy/gateway/issues/838

fix: start xds server watchable map panics

---

internal/xds/translator/cluster.go
internal/xds/translator/testdata/out/xds-ir/http2-route.clusters.yaml

Envoy deprecated the usage of `Http2ProtocolOptions` in Envoy 1.17. This commit updates the xds.Translate function to follow recommended practices of using the `TypedExtensionProtocolOptions` to set http/2 protocol options.
The existing test case was modified due to the change in expected xDS configuration outputted when http/2 is enabled for a backendRef.
Fixes #844

translator: remove usage of deprecated Http2ProtocolOptions

---

api/config/v1alpha1/envoyproxy_types.go
docs/latest/design/ratelimit.md
internal/provider/kubernetes/config/crd/bases/config.gateway.envoyproxy.io_envoyproxies.yaml

Add details on Global Rate Limit implementation

---

internal/gatewayapi/testdata/gateway-with-listener-with-invalid-allowed-routes-group.out.yaml
internal/gatewayapi/testdata/gateway-with-listener-with-invalid-allowed-routes-kind-and-supported.in.yaml
internal/gatewayapi/testdata/gateway-with-listener-with-invalid-allowed-routes-kind-and-supported.out.yaml
internal/gatewayapi/testdata/gateway-with-listener-with-invalid-allowed-routes-kind.out.yaml
internal/gatewayapi/validate.go
test/conformance/conformance_test.go

The logic for validating `allowedRoute.kinds` of a listener was overwriting the SupportedKinds when multiple kinds are configured. This caused the `GatewayInvalidRouteKind` conformance test to fail. 
Items addressed:
- refactored `validateAllowedRoutes` to reduce nesting
- fixed `validateAllowedRoutes` logic so  it collects all of the SupportedKinds before setting them on the listener
- provide additional context to user to help identify which RouteKind is invalid on a listener
- updated unit tests for translator based on new expected output
- added additional unit test case for translator to test for when multiple Kinds are added which includes valid and invalid Kinds.
Fixes #782

gateway-api: fix supported route kind validation

---

internal/gatewayapi/filters.go
internal/gatewayapi/route.go
internal/gatewayapi/testdata/httproute-with-non-existent-authenfilter-ref.in.yaml
internal/gatewayapi/testdata/httproute-with-non-existent-authenfilter-ref.out.yaml
internal/gatewayapi/testdata/httproute-with-valid-authenfilter.in.yaml
internal/gatewayapi/testdata/httproute-with-valid-authenfilter.out.yaml

Adds AuthenticationFilter support to the resource translator.
xref:https://github.com/envoyproxy/gateway/issues/790

Adds AuthenticationFilter Support to Resource Translator

---

internal/status/status.go

Adds status comparison checks for newer route types recently added - `TCPRoute`, `UDPRoute` and `GRPCRoute`

enhance k8s status compare function for all routes

---

test/conformance/conformance_test.go

Fixes #659
Enable the HTTPRoute method matching test after updating gateway API to v0.6.0
Letting the tests run first to see if other things needed to be updated/fixed

Enable HTTPRouteMethodMatching conformance test

---

internal/xds/translator/listener.go
internal/xds/translator/testdata/out/xds-ir/http-route-direct-response.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-redirect.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-request-headers.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-response-add-headers.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-response-add-remove-headers.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-response-remove-headers.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-url-fullpath.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-url-host.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-url-prefix.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-weighted-backend.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-weighted-invalid-backend.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/multiple-listeners-same-port.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/ratelimit.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/simple-tls.listeners.yaml

Fixes: https://github.com/envoyproxy/gateway/issues/836

Allow upgrade to websocket for HTTP 1.1 listeners

---

internal/gatewayapi/helpers.go
internal/gatewayapi/route.go
internal/gatewayapi/testdata/httproute-attaching-to-listener-matching-port.in.yaml
internal/gatewayapi/testdata/httproute-attaching-to-listener-matching-port.out.yaml
internal/gatewayapi/testdata/httproute-not-attaching-to-listener-non-matching-port.in.yaml
internal/gatewayapi/testdata/httproute-not-attaching-to-listener-non-matching-port.out.yaml
test/conformance/conformance_test.go

When port is specified in a parentRef, only select listeners if they have a matching port, and set
conditions appropriately if not.
Closes #784.

implement parent ref port matching when specified

---

internal/gatewayapi/filters.go
internal/gatewayapi/route.go
internal/gatewayapi/testdata/httproute-with-mirror-filter-duplicates.in.yaml
internal/gatewayapi/testdata/httproute-with-mirror-filter-duplicates.out.yaml
internal/gatewayapi/testdata/httproute-with-mirror-filter-multiple.in.yaml
internal/gatewayapi/testdata/httproute-with-mirror-filter-multiple.out.yaml
internal/gatewayapi/testdata/httproute-with-mirror-filter-service-no-port.in.yaml
internal/gatewayapi/testdata/httproute-with-mirror-filter-service-no-port.out.yaml
internal/gatewayapi/testdata/httproute-with-mirror-filter-service-not-found.in.yaml
internal/gatewayapi/testdata/httproute-with-mirror-filter-service-not-found.out.yaml
internal/gatewayapi/testdata/httproute-with-mirror-filter.in.yaml
internal/gatewayapi/testdata/httproute-with-mirror-filter.out.yaml
internal/gatewayapi/translator_test.go
internal/ir/xds.go
internal/ir/xds_test.go
internal/ir/zz_generated.deepcopy.go
internal/provider/kubernetes/kubernetes_test.go
internal/provider/kubernetes/routes.go
internal/xds/translator/route.go
internal/xds/translator/testdata/in/xds-ir/http-route-mirror.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-mirror.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-mirror.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-mirror.routes.yaml
internal/xds/translator/translator.go
internal/xds/translator/translator_test.go

Adds support for request mirror filters for HTTPRoutes. 
Resolves https://github.com/envoyproxy/gateway/issues/656 but as noted on that issue, the request mirrors will need to be added for gRPCRoutes as well.
if there is anything left that needs to be done for request mirror filters on gRPCRoutes once support for them lands from https://github.com/envoyproxy/gateway/pull/805 then I can take that as a separate/follow-up issue.

Add HTTPRoute support for request mirror filters

---

.golangci.yml
api/v1alpha1/validation/authenticationfilter_test.go
internal/gatewayapi/filters.go
internal/gatewayapi/helpers.go
internal/gatewayapi/listener.go
internal/gatewayapi/resource.go
internal/gatewayapi/route.go
internal/provider/kubernetes/helpers_test.go
internal/provider/kubernetes/test/utils.go
internal/status/conditions_test.go
internal/xds/server/runner/runner.go
internal/xds/translator/runner/runner_test.go
tools/linter/golangci-lint/.golangci.yml

lint: improve golanglint

---

api/config/v1alpha1/envoyproxy_types.go
api/config/v1alpha1/validation/envoyproxy.go
api/config/v1alpha1/validation/envoyproxy_test.go
internal/gatewayapi/resource.go
internal/gatewayapi/zz_generated.deepcopy.go
internal/provider/kubernetes/config/rbac/role.yaml
internal/provider/kubernetes/controller.go
internal/provider/kubernetes/controller_test.go
internal/provider/kubernetes/helpers.go
internal/provider/kubernetes/helpers_test.go
internal/provider/kubernetes/kubernetes_test.go
internal/provider/kubernetes/rbac.go
internal/provider/kubernetes/routes_test.go
internal/provider/kubernetes/test/utils.go
internal/status/conditions.go
internal/status/conditions_test.go
internal/status/gatewayclass.go

Adds EnvoyProxy support to the Kubernetes provider.
- Updates status pkg to support GatewayClass [InvalidParamtersRef](https://github.com/kubernetes-sigs/gateway-api/blob/v0.6.0/apis/v1beta1/gatewayclass_types.go#L172) status condition.
- Updates the Kube controller to watch for EnvoyProxy API objects and trigger GatewayClass reconciliation. This supports processing the paramtersRef and updating GatewayClass status conditions.
- Adds unit and integration tests.

Adds EnvoyProxy Support to Kubernetes Provider

---

go.mod
go.sum
internal/xds/translator/ratelimit.go
internal/xds/translator/testdata/in/ratelimit-config/distinct-match.yaml
internal/xds/translator/testdata/in/ratelimit-config/empty-header-matches.yaml
internal/xds/translator/testdata/in/ratelimit-config/multiple-matches.yaml
internal/xds/translator/testdata/in/ratelimit-config/multiple-routes.yaml
internal/xds/translator/testdata/in/ratelimit-config/multiple-rules.yaml
internal/xds/translator/testdata/in/ratelimit-config/value-match.yaml
internal/xds/translator/testdata/out/ratelimit-config/distinct-match.yaml
internal/xds/translator/testdata/out/ratelimit-config/empty-header-matches.yaml
internal/xds/translator/testdata/out/ratelimit-config/multiple-matches.yaml
internal/xds/translator/testdata/out/ratelimit-config/multiple-routes.yaml
internal/xds/translator/testdata/out/ratelimit-config/multiple-rules.yaml
internal/xds/translator/testdata/out/ratelimit-config/value-match.yaml
internal/xds/translator/translator_test.go

* Translates Xds IR into ratelimit service config https://github.com/envoyproxy/ratelimit#configuration

Build rate limit service config

---

internal/gatewayapi/contexts.go
internal/gatewayapi/contexts_test.go
internal/gatewayapi/testdata/gateway-with-preexisting-status-condition.in.yaml
internal/gatewayapi/testdata/gateway-with-preexisting-status-condition.out.yaml
internal/gatewayapi/testdata/gateway-with-stale-status-condition.in.yaml
internal/gatewayapi/testdata/gateway-with-stale-status-condition.out.yaml
internal/gatewayapi/translator.go

Previously the listener status in the Gateway resource could be left stale if one of the listeners is removed.
We add new method to GatewayContext to reset the listener status and listener contexts and is called before re-computing
Testing:
- Add unit test for new method
- Add a couple of new testcases to the Translation unit tests to check for stale listener conditions and to ensure the status didn't change if the condition did not change.
Fixes #773

bugfix: remove stale listener condition

---

internal/gatewayapi/filters.go
internal/gatewayapi/route.go
internal/gatewayapi/testdata/httproute-with-invalid-ratelimitfilter.in.yaml
internal/gatewayapi/testdata/httproute-with-invalid-ratelimitfilter.out.yaml
internal/gatewayapi/testdata/httproute-with-non-existent-authenfilter-ref.out.yaml
internal/gatewayapi/testdata/httproute-with-non-matching-authenfilter-ref.in.yaml
internal/gatewayapi/testdata/httproute-with-valid-ratelimitfilter.in.yaml
internal/gatewayapi/testdata/httproute-with-valid-ratelimitfilter.out.yaml
internal/ir/xds.go
internal/xds/translator/ratelimit.go

* Also rm'ed `ResetConditon` and instead set `Accepted=False` for negative cases for ExtensionFilter cases

RateLimitFilter: Gateway API to Xds IR translaton

---

internal/cmd/server.go
internal/globalratelimit/runner/runner.go
internal/infrastructure/kubernetes/configmap.go
internal/infrastructure/kubernetes/configmap_test.go
internal/infrastructure/kubernetes/deployment.go
internal/infrastructure/kubernetes/deployment_test.go
internal/infrastructure/kubernetes/infra.go
internal/infrastructure/kubernetes/infra_test.go
internal/infrastructure/kubernetes/labels.go
internal/infrastructure/kubernetes/labels_test.go
internal/infrastructure/kubernetes/service.go
internal/infrastructure/kubernetes/service_test.go
internal/infrastructure/kubernetes/serviceaccount.go
internal/infrastructure/kubernetes/serviceaccount_test.go
internal/infrastructure/manager.go
internal/infrastructure/runner/runner.go

Translate RateLimitInfra into K8s resources

---

api/v1alpha1/authenticationfilter_types.go
api/v1alpha1/validation/authenticationfilter.go
api/v1alpha1/validation/authenticationfilter_test.go
internal/gatewayapi/testdata/httproute-with-valid-multi-match-multi-authenfilter.in.yaml
internal/gatewayapi/testdata/httproute-with-valid-multi-match-multi-authenfilter.out.yaml
internal/ir/xds.go
internal/provider/kubernetes/config/crd/bases/gateway.envoyproxy.io_authenticationfilters.yaml
internal/xds/translator/authentication.go
internal/xds/translator/listener.go
internal/xds/translator/ratelimit.go
internal/xds/translator/route.go
internal/xds/translator/testdata/in/xds-ir/authn-multi-route-multi-provider.yaml
internal/xds/translator/testdata/in/xds-ir/authn-multi-route-single-provider.yaml
internal/xds/translator/testdata/in/xds-ir/authn-ratelimit.yaml
internal/xds/translator/testdata/in/xds-ir/authn-single-route-single-match.yaml
internal/xds/translator/testdata/out/xds-ir/authn-multi-route-multi-provider.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/authn-multi-route-multi-provider.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/authn-multi-route-multi-provider.routes.yaml
internal/xds/translator/testdata/out/xds-ir/authn-multi-route-single-provider.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/authn-multi-route-single-provider.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/authn-multi-route-single-provider.routes.yaml
internal/xds/translator/testdata/out/xds-ir/authn-ratelimit.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/authn-ratelimit.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/authn-ratelimit.routes.yaml
internal/xds/translator/testdata/out/xds-ir/authn-single-route-single-match.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/authn-single-route-single-match.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/authn-single-route-single-match.routes.yaml
internal/xds/translator/translator.go
internal/xds/translator/translator_test.go

Adds initial JWT authentication support to xDS translator.

Adds JWT Authn Support to XDS Translator

---

internal/gatewayapi/route.go
internal/gatewayapi/testdata/httproute-with-empty-matches.in.yaml
internal/gatewayapi/testdata/httproute-with-empty-matches.out.yaml

* Add a Path Prefix match on "/" which matches every request when the matches field is not set
https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.HTTPRouteRule

Support HTTPRoute with empty matches

---

docs/latest/dev/releasing.md

Adds steps to the release doc to update and revert the Envoy proxy image.
xref: #957 

Updates Release Doc to Set Proxy Image

---

internal/ir/infra.go

Hardcodes the proxy image to v1.25. This should be automated for future releases.
xref: #957

Sets Envoy Proxy Image to v1.25

---

docs/latest/conf.py
internal/cmd/root.go
internal/cmd/version/version.go
internal/cmd/versions.go
tools/make/docs.mk

fixes: https://github.com/envoyproxy/gateway/issues/952
1. rename `versions` to `version`, align with kubectl
2. rename `envoyVersion` to `envoyProxyVersion`

align version command

---

internal/xds/translator/route.go
internal/xds/translator/testdata/in/xds-ir/http-route.yaml
internal/xds/translator/testdata/out/xds-ir/http-route.routes.yaml

If `pathMatch` is empty, add a `prefix` path Match to `/`. Envoy expects precisely one of prefix, path, safe_regex, connect_matcher, path_separated_prefix, path_match_policy must be set. From https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html?highlight=routematch#envoy-v3-api-msg-config-route-v3-routematch
If unset, this below validation error is seen in the `xds-server`
```
cache/logrwrapper.go:29	handling v3 xDS resource request, response_nonce 1, nodeID envoy-default-eg-64656661-df8685f8c-zxk4d, node_version v1.25.0, resource_names_subscribe [], resource_names_unsubscribe [], type_url type.googleapis.com/envoy.config.route.v3.RouteConfiguration, errorCode 13, errorMessage Proto constraint validation failed …
```

Always ensure a pathMatch exists

---

docs/latest/dev/releasing.md

- Reorganizes release doc.
- Adds a table of contents.
- Adds a step for updating the Envoy proxy image.
- Updates the RC release process to tag from a release branch instead of main.
Fixes #957 

Updates Dev Release Guide

---

internal/gatewayapi/filters.go
internal/gatewayapi/runner/runner.go
internal/gatewayapi/translator.go
internal/gatewayapi/translator_test.go

Add status in HTTPRoute when Ratelimit is disabled

---

internal/infrastructure/kubernetes/infra.go

The create and delete function names were incorrectly swapped.

fix function names for RL Infra

---

docs/latest/user/grpc-routing.md
docs/latest/user_docs.rst
examples/kubernetes/grpc-routing.yaml

Fixes: https://github.com/envoyproxy/gateway/issues/642

Add docs for GRPCRoute

---

internal/gatewayapi/route.go
internal/gatewayapi/testdata/httproute-with-empty-matches.out.yaml
internal/xds/translator/route.go
internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-url-fullpath.routes.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-url-host.routes.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-url-prefix.routes.yaml
test/conformance/conformance_test.go

We were using `prefix` Route match in xds for
the `PathPrefix` Gateway API match defined here
https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPPathMatch
The match translates to a `path_separated_prefix` instead https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-routematch
This should fix the `HTTPRouteMatching` conformance test where requests with `/v2example` should match `/` and not `/v2`
Fixes: https://github.com/envoyproxy/gateway/issues/995

Use `path_separated_prefix` Route match

---

test/conformance/conformance_test.go

Fixes: https://github.com/envoyproxy/gateway/issues/883

conformance: enable GatewayClassObservedGenerationBump

---

test/conformance/conformance_test.go

Redirect tests are failing due to a possible issue with the way upstream conformance tests have made assumptions Skipping them for now until below issues are resolved
https://github.com/envoyproxy/gateway/issues/992
https://github.com/envoyproxy/gateway/issues/993
https://github.com/envoyproxy/gateway/issues/994

Run all conformance tests except redirect tests

---

internal/xds/translator/authentication.go

the Xds translator should not error out when the IR routes are empty

remove empty route error check in auth xds logic

---

test/conformance/conformance_test.go

Removes the `GatewayObservedGenerationBump` and `HTTPRouteObservedGenerationBump` conformance tests due to #1016.

Removes GatewayObservedGenerationBump and HTTPRouteObservedGenerationBump Tests

---

docs/latest/design/gatewayapi-support.md
docs/v0.2.0/design_docs.rst

Adds a simple doc which goes over which Gateway API resources Envoy Gateway supports with a short description about each containing links to the Gateway API docs.
Fixes #500

Add Gateway API support doc

---

docs/latest/dev/releasing.md

Adds steps for cherry-picking commits from `main` into the release branch.

Adds Cherry-Pick Steps to Release Doc

---

docs/latest/design/gatewayapi-support.md
docs/latest/design_docs.rst
docs/v0.2.0/design_docs.rst

* add note about not supported `filters` for `HTTPBackendRef`
* rm `extensionRef` support for `GRPCRoute`
* move the link under docs/latest

update gateway api support doc

---

docs/v0.3.0/design/gatewayapi-support.md
docs/v0.3.0/design_docs.rst

PR #1026 updated the Gateway API support doc for the `latest` release. However, this PR landed after v0.3 was cut. The updates in PR #1026 improve the UX of this doc. This PR incorporates these updates for v0.3 docs.

Moves PR 1026 Docs to v0.3

---

go.mod
internal/xds/translator/listener.go
internal/xds/translator/testdata/out/xds-ir/authn-multi-route-multi-provider.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/authn-multi-route-single-provider.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/authn-ratelimit.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/authn-single-route-single-match.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-direct-response.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-mirror.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-redirect.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-request-headers.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-response-add-headers.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-response-add-remove-headers.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-response-remove-headers.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-url-fullpath.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-url-host.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-url-prefix.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-weighted-backend.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-weighted-invalid-backend.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http2-route.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/multiple-listeners-same-port.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/ratelimit.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/simple-tls.listeners.yaml

fixes: https://github.com/envoyproxy/gateway/issues/998
cc @arkodg

ensure `use_remote_address` is set

---

internal/infrastructure/kubernetes/proxy_configmap_test.go
internal/infrastructure/kubernetes/proxy_deployment_test.go
internal/infrastructure/kubernetes/proxy_service_test.go
internal/infrastructure/kubernetes/proxy_serviceaccount_test.go
internal/infrastructure/kubernetes/ratelimit_configmap_test.go
internal/infrastructure/kubernetes/ratelimit_deployment_test.go
internal/infrastructure/kubernetes/ratelimit_service_test.go
internal/infrastructure/kubernetes/ratelimit_serviceaccount_test.go

* the k8s infra tests are performing CRUD ops on the same k8s env/cluster. They shouldnt be run in parallel as each test might affect the other.
* tested using `go test ./... -count 50 -race -covermode=atomic` which fails on the current `main` branch
Fixes: https://github.com/envoyproxy/gateway/issues/1034

dont run k8s infra tests in parallel

---

internal/ir/xds.go
internal/xds/translator/authentication.go
internal/xds/translator/cluster.go
internal/xds/translator/ratelimit.go
internal/xds/translator/testdata/out/xds-ir/authn-multi-route-multi-provider.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/authn-multi-route-single-provider.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/authn-ratelimit.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/authn-single-route-single-match.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/ratelimit.clusters.yaml
internal/xds/translator/translator.go

translator: refactor authn and ratelimit to use buildXdsCluster

---

internal/status/status.go

optimize object apply update logic.

---

internal/cmd/certgen.go
internal/cmd/server.go
internal/cmd/server_test.go

Signed-off-by: Bing Han <h.bing612@gmail.com>
Move the cfg.Validate below to validate user config. Without this fix, the test will fail:
```
--- FAIL: TestValidateUserConfig (0.00s)
server_test.go:33:
Error Trace:	/Users/hanbing/repo/go/envoyproxy-gateway/internal/cmd/server_test.go:33
Error:      	An error is expected but got nil.
Test:       	TestValidateUserConfig
FAIL
FAIL	github.com/envoyproxy/gateway/internal/cmd	0.601s
FAIL
```

fix: validate user config

---

internal/cmd/egctl/translate_test.go

Deprecation of package ioutil in Go 1.16

fix: replace deprecated ioutil

---

.github/workflows/latest_release.yaml

Part of: https://github.com/envoyproxy/gateway/issues/1045
Refer: https://github.com/Xunzhuo/gateway/releases/tag/latest

chore: add latest release of egctl

---

docs/latest/user/egctl.md
internal/cmd/egctl/translate.go

Fixes: https://github.com/envoyproxy/gateway/issues/1057

support `egctl x translate -f -`

---

go.mod
go.sum
internal/cmd/egctl/version.go

fixes: #1052 #1054 
cc @arkodg

egctl: only exec on running pod

---

docs/latest/user/grpc-routing.md
internal/gatewayapi/helpers.go
internal/gatewayapi/route.go
internal/gatewayapi/testdata/grpcroute-with-method-and-service-match.in.yaml
internal/gatewayapi/testdata/grpcroute-with-method-and-service-match.out.yaml
internal/gatewayapi/testdata/grpcroute-with-method-match.in.yaml
internal/gatewayapi/testdata/grpcroute-with-method-match.out.yaml
internal/gatewayapi/testdata/grpcroute-with-service-match.in.yaml
internal/gatewayapi/testdata/grpcroute-with-service-match.out.yaml

gatewayapi: adds matching on GRPCRoute method and service

---

internal/cmd/egctl/version.go

feat: add egctl only client version

---

CODEOWNERS.md

Establishes an emeritus section of the CODEOWNERS file and adds @danehans to this section.

Moves @danehans to Emeritus Maintainer

---

api/config/v1alpha1/envoyproxy_types.go
charts/eg/crds/generated/config.gateway.envoyproxy.io_envoyproxies.yaml
docs/latest/design/bootstrap.md
internal/infrastructure/kubernetes/proxy_deployment.go
internal/infrastructure/kubernetes/proxy_deployment_test.go

Relates to https://github.com/envoyproxy/gateway/issues/31

Implement Bootstrap API

---

tools/make/kube.mk

xref: https://github.com/envoyproxy/gateway/pull/1107

chore: controller-gen set webhook output path

---

internal/cmd/egctl/testdata/translate/in/quickstart.yaml
internal/cmd/egctl/testdata/translate/out/quickstart.route.yaml
internal/cmd/egctl/translate.go
internal/cmd/egctl/translate_test.go

Here I use the quickstart.yaml of this project as the test case.
Without this commit, the HTTPRoute in quickstart.yaml will be skipped
because it doesn't have a namespace.
Signed-off-by: muyuan0 <127020730+muyuan0@users.noreply.github.com>

fix(egctl): don't skip resource caused by ns mismatch

---

internal/xds/translator/route.go
internal/xds/translator/testdata/in/xds-ir/http-route-regex.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-regex.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-regex.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-regex.routes.yaml
internal/xds/translator/translator_test.go

Fix #1056
Signed-off-by: muyuan0 <127020730+muyuan0@users.noreply.github.com>

update deprecated RegexMatcher

---

internal/xds/translator/route.go
internal/xds/translator/testdata/in/xds-ir/http-route-rewrite-root-path-url-prefix.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-root-path-url-prefix.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-root-path-url-prefix.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-root-path-url-prefix.routes.yaml
internal/xds/translator/translator_test.go

fix & support #1044 
the upstream receive double "/" needs envoy fix , issue https://github.com/envoyproxy/envoy/issues/26024

fix PathSeparatedPrefix & optimize the prefix ends with / logic.

---

.github/workflows/build_and_test.yaml

Reverts envoyproxy/gateway#1131
After docker login, we do not need to helm login anymore.
Need to create a repo called envoy-gateway in dockerhub to release helm chart.
We cannot reuse gateway / gateway-dev , preventing conflicts and overrides the same tag.
Hold after creating a new repo in dockerhub.

Revert "ci: add helm login to prevent authorization failed"

---

.github/workflows/build_and_test.yaml

Temporaily remove helm push from CI until the repo has been created
Relates to https://github.com/envoyproxy/gateway/issues/1139

Remove `helm push` from CI

---

go.mod
go.sum
internal/xds/server/runner/runner.go
internal/xds/server/runner/runner_test.go
tools/make/golang.mk

The serveXdsServer will crash if the net.Listen failed, because of:
1. the log call uses an odd number of arguments in argument pair
2. the code continues to execute and will access the nil listener.
This PR fixes the behavior.

fix crash in serveXdsServer when failed to listen

---

internal/infrastructure/kubernetes/proxy_deployment.go

When apply config as bellow:
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
name: gateway-class
spec:
controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
name: shared-gw
namespace: qat-infra
spec:
gatewayClassName: gateway-class
listeners:
- name: http
protocol: HTTP
port: 8080
allowedRoutes:
namespaces:
from: All
```
It throws an error and does not create envoy instance:
`2023-03-22T01:02:38.760+0700    ERROR   runner/runner.go:68     failed to create new infra      {"runner": "infrastructure", "error": "failed to update deployment envoy-gateway-system/envoy-qat-infra-shared-gw-7161742d: Deployment.apps \"envoy-qat-infra-shared-gw-7161742d\" is invalid: …

Fix `invalid: protocol: Unsupported value: "HTTP"` error

---

.gitignore
charts/gateway-helm/.helmignore
charts/gateway-helm/values.tmpl.yaml
helm/main.go
tools/make/common.mk
tools/make/env.mk
tools/make/helm.mk
tools/make/image.mk
tools/make/kube.mk

This commit allows generating `values.yaml` using a `values.tmpl.yaml` (template file)
in order to dynamically fill in the image repository and tag details while doing helm packaging.
Note that helm does not natively support templates in values.yaml hence the additional overlay
This also introduces a separate `helm-release` target that does helm packaging with image
`docker.io/envoyproxy/gateway:<tag>`.
The old `helm-package` target will continue building based on `${IMAGE}:${TAG}` vars.
If used, the helm install CLI will not require explicit `--set` commands into the deployment object
Fixes #1178

templatize values.yaml to allow passing custom image repo and tag

---

internal/gatewayapi/helpers.go
internal/gatewayapi/helpers_test.go
internal/gatewayapi/resource.go
internal/gatewayapi/testdata/httproute-with-redirect-filter-invalid-filter-type.out.yaml
internal/gatewayapi/zz_generated.deepcopy.go
internal/provider/kubernetes/controller.go
internal/provider/kubernetes/filters.go
internal/provider/kubernetes/routes.go
internal/provider/kubernetes/routes_test.go

Updates Kubernetes provider to watch for resources registered in the extensions config
This PR makes the assumption that registered resources are filters to be referenced in `HTTPRouteFIlter.extensionRef`. Policy attachments from extensions can be handled in a future iteration when we decide on a way to handle PolicyAttachements in general for EG
Relates to:
- https://github.com/envoyproxy/gateway/issues/20
- https://github.com/envoyproxy/gateway/pull/1074
- https://github.com/envoyproxy/gateway/pull/1163

provider: watch for resources from extensions

---

internal/gatewayapi/filters.go
internal/gatewayapi/route.go
internal/gatewayapi/runner/runner.go
internal/gatewayapi/testdata/extensions/httproute-with-extension-filter-invalid-group.in.yaml
internal/gatewayapi/testdata/extensions/httproute-with-extension-filter-invalid-group.out.yaml
internal/gatewayapi/testdata/extensions/httproute-with-non-matching-extension-filter.in.yaml
internal/gatewayapi/testdata/extensions/httproute-with-non-matching-extension-filter.out.yaml
internal/gatewayapi/testdata/extensions/httproute-with-unsupported-extension-filter.in.yaml
internal/gatewayapi/testdata/extensions/httproute-with-unsupported-extension-filter.out.yaml
internal/gatewayapi/testdata/extensions/httproute-with-valid-extension-filter.in.yaml
internal/gatewayapi/testdata/extensions/httproute-with-valid-extension-filter.out.yaml
internal/gatewayapi/translator.go
internal/gatewayapi/translator_test.go
internal/ir/xds.go

Work has already landed to support Envoy Gateway watching resources from extensions, and also for passing those resources back to the extension whenever the Route level xDS hook is called. This is the last piece of the work that updates the gateway API translator to store these watched resources in the IR so that they can be consumed later.

Extensions: pass watched resources to IR

---

tools/make/kube.mk

Fixes: https://github.com/envoyproxy/gateway/issues/1268
+ Helm install default timeout is `5m`, change it to `15m`
+ Enable helm install debug, to see the process of installation.

helm: enable debug and change time-out in conformance test

---

api/config/v1alpha1/shared_types.go

542a6047 is the most recent ratelimit tag as of this PR other than `master`

0.4.0-rc.1: Pin Envoy Proxy and Envoy Ratelimit for release

---

.github/PULL_REQUEST_TEMPLATE.md
docs/latest/dev/CONTRIBUTING.md
docs/latest/dev/README.md

docs: add pull request template & update contributing docs.

---

api/config/v1alpha1/shared_types.go

https://github.com/envoyproxy/envoy/releases/tag/v1.26.0
Releases the latest version of envoy proxy with the latest version of envoy gateway

[release/v0.4] chore: bump envoy proxy to v1.26

---

docs/latest/design/rate-limit.md
docs/v0.3.0/design/ratelimit.md

Signed-off-by: aimuz <mr.imuz@gmail.com>
docs(ratelimit): add syntax explanation for missing code block location
Fixes #

docs(ratelimit): add syntax explanation for missing code block location

---

charts/gateway-helm/templates/certgen-rbac.yaml
charts/gateway-helm/templates/certgen.yaml
charts/gateway-helm/templates/envoy-gateway-config.yaml
charts/gateway-helm/templates/envoy-gateway-deployment.yaml
charts/gateway-helm/templates/envoy-gateway-metrics-service.yaml
charts/gateway-helm/templates/envoy-gateway-service.yaml
charts/gateway-helm/templates/infra-manager-rbac.yaml
charts/gateway-helm/templates/leader-election-rbac.yaml
charts/gateway-helm/templates/metrics-reader-rbac.yaml
charts/gateway-helm/templates/namespace.yaml
charts/gateway-helm/values.tmpl.yaml
tools/make/kube.mk

This is an unfortunate workaround due the difference in UX between `helm template` and `helm install`
The project recommends `helm install` as a way to install EG which supports a `--create-namespace` flag to create a namespace However we also generate a static YAML using `helm template` as part of the release artifact so a user can install the YAML directly using `kubectl` instead of `helm` . The issue here is `helm template` does not support `--create-namespace`, so instead this commit adds a knob called `createNamespace` to the Helm chart which is `false` by default, but turned on during `make generate-manifests`
Fixes: https://github.com/envoyproxy/gateway/issues/1307

fix: add the namespace resource within helm templates

---

internal/extension/testutils/hooks.go
internal/xds/translator/extension.go

previously I was under the false impression that despite the linter warning about an ineffectual assignment that things were working as intended. This was because the test cases directly operated on passed-in pointers instead of ensuring that the returned pointer was being used.
I added a new `func copyPtr()` `func` to assist with the copying of xDS resource pointer fields instead of doing the following because of the mutex copy.
```
*x = *y
```
I don't like how `copyPtr()` exists twice in two different files and would like to move it to a `helpers`/`utils` file/package. All the existing helpers/utils files seem pretty package specific so I didn't think it would fit in any of them. I might just make a more general/top-level utils package and move it there so let me know if you're a +1/-1 …

Extension: fix pointer error

---

charts/gateway-helm/templates/certgen-rbac.yaml
charts/gateway-helm/templates/certgen.yaml
charts/gateway-helm/templates/envoy-gateway-config.yaml
charts/gateway-helm/templates/envoy-gateway-deployment.yaml
charts/gateway-helm/templates/envoy-gateway-metrics-service.yaml
charts/gateway-helm/templates/envoy-gateway-service.yaml
charts/gateway-helm/templates/infra-manager-rbac.yaml
charts/gateway-helm/templates/leader-election-rbac.yaml
charts/gateway-helm/templates/metrics-reader-rbac.yaml
charts/gateway-helm/templates/namespace.yaml
charts/gateway-helm/values.tmpl.yaml
internal/extension/testutils/hooks.go
internal/xds/translator/extension.go
tools/make/kube.mk

Pulls in two commits from `main` for the `0.4.0` release. 
https://github.com/envoyproxy/gateway/pull/1332
https://github.com/envoyproxy/gateway/pull/1323

Release - 0.4.0: Cherry Pick Fixes

---

internal/cmd/egctl/testdata/translate/out/default-resources.all.yaml

Updates a section of `internal/cmd/egctl/testdata/translate/out/default-resources.all.yaml` to expect the new default fields set by https://github.com/envoyproxy/gateway/pull/1341

Fix testdata missing default fields (merge order bug)

---

docs/latest/user/rate-limit.md
docs/v0.4.0/user/rate-limit.md

* move the optional RL Deloyment to the end of the user doc since its an optional feature
* fix the image tag to use a valid one - `master`

docs: move rateLimit deployment customization to end

---

docs/latest/api/config_types.md
tools/crd-ref-docs/config.yaml
tools/src/crd-ref-docs/go.mod
tools/src/crd-ref-docs/go.sum

docs: update config types doc
Fixes #1247

docs: update config types doc

---

internal/provider/kubernetes/predicates.go

* Its not an error case when the managed envoy service or deployment get reconciled after a gateway is deleted, since deleting the managed service and deployment asscoiated with the gateway might not be instanteous.
Fixes: https://github.com/envoyproxy/gateway/issues/1347

bug: change err log to info in findOwningGateway

---

docs/latest/design/gatewayapi-support.md
docs/v0.4.0/design/gatewayapi-support.md

Remove the note around not support multiple cert references because we support it now (thanks to https://github.com/envoyproxy/gateway/pull/1241)

docs: update Gateway API support doc for multi cert ref

---

.github/dependabot.yml
tools/src/sphinx-build/requirements.txt

* Renable dependabot updates since the latest modules are compatible
Fixes https://github.com/envoyproxy/gateway/issues/848

chore: bump sphinx to v6.2.1 and myst-parser to v1.0.0

---

charts/gateway-helm/README.md
charts/gateway-helm/templates/certgen.yaml
charts/gateway-helm/templates/envoy-gateway-deployment.yaml
charts/gateway-helm/values.tmpl.yaml
internal/cmd/egctl/translate.go
internal/crypto/certgen.go
internal/envoygateway/config/config.go
internal/infrastructure/kubernetes/ratelimit/resource.go
internal/infrastructure/kubernetes/ratelimit/resource_provider_test.go
internal/xds/translator/runner/runner.go
internal/xds/translator/testdata/in/xds-ir/ratelimit-custom-domain.yaml
internal/xds/translator/testdata/out/xds-ir/ratelimit-custom-domain.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/ratelimit-custom-domain.endpoints.yaml
internal/xds/translator/testdata/out/xds-ir/ratelimit-custom-domain.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/ratelimit-custom-domain.routes.yaml
internal/xds/translator/translator_test.go

kubernetes: support custom cluster dns domain
Fixes #1280

kubernetes: support custom cluster dns domain

---

docs/latest/user/secure-gateways.md
docs/v0.4.0/user/secure-gateways.md

Adds documentation to test SNI based selection when multiple certificates are 
provided in Gateway to terminate TLS traffic. The certificate to be served is chosen
based on the SNI in the client request. The doc adds a scenario and testing steps for the same.
Fixes #1275

docs: multiple certificates, sni based selection

---

internal/gatewayapi/runner/runner.go
internal/message/types.go
internal/provider/kubernetes/controller.go

Fixes https://github.com/envoyproxy/gateway/issues/1367

fix: Pass Status instead of entire obj in watchable

---

.github/workflows/cc_reviewers_pr.yaml

* GH recommends using CODEOWNERS to automatically request reviewers on PRs.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#about-code-owners. However the teams mentioned within the `CODEOWNERS` file must have WRITE access. Since this is not the case for `envoyproxy/gateway-reviewers` who have `triage` access today, this PR adds a Github Action that adds envoyproxy/gateway-reviewers as reviewers using the GH CLI whenever a PR is opened
Adapted from https://stackoverflow.com/questions/66557514/how-to-automatically-request-a-review-from-someone-using-github-actions

chore: GHA to request reviews from gateway-reviewers

---

docs/latest/design/roadmap.md
docs/v0.4.0/design/roadmap.md

* Moves #24 into v0.5.0 since it carries over from v0.4.0
* Adds #1365 since it tracks the work items of the Scale theme
* Removed other items not tied directly to the roadmap theme
* Added a placeholder roadmap theme for v0.6.0

Update roadmap for v0.5.0

---

docs/latest/design/local-envoy-gateway.md
docs/latest/design_docs.rst

Relates to https://github.com/envoyproxy/gateway/issues/1001 & https://github.com/envoyproxy/gateway/issues/1035

design: Run Envoy Gateway locally on host

---

api/config/v1alpha1/shared_types.go
charts/gateway-helm/crds/generated/config.gateway.envoyproxy.io_envoyproxies.yaml
docs/latest/api/config_types.md

Adds missing comment for NodePort type service

docs: missing NodePort service type description comment

---

go.mod
go.sum

Relates to https://github.com/envoyproxy/gateway/pull/1386 where we pinned controller runtime to a SHA commit to unblock us to import a newer Gateway API version

chore: Bump controller-runtime to v0.15.0-alpha.0

---

charts/gateway-helm/templates/generated/rbac/roles.yaml
internal/provider/kubernetes/controller.go
internal/provider/kubernetes/rbac.go

For issue https://github.com/envoyproxy/gateway/issues/1420
in the corresponding failed pipeline: https://github.com/envoyproxy/gateway/actions/runs/4957252173/jobs/8868696936?pr=1407
The error occured when the first Update failed, and was retried later, while trying to remove Finalizer from GatewayClass.
Instead of doing a Get and Update, in loop, this PR updates the logic to use a single Patch call.

chore: use patch for finalizer updates on GC

---

go.mod
internal/cmd/server.go

feat: add spew dump for envoy-gateway config when starting up, as the envoy gateway config grows bigger and more complex.
we should provide a direct way in log to see how the config recieved by eg looks like.

feat: add spew dump for envoy-gateway config when starting up

---

.github/workflows/cherrypick.yaml

default action permissions:
cherrypick action permissions:

ci: try to fix permissions for cherrypick action

---

examples/kubernetes/envoy-proxy-config.yaml

#1232 changed the `KubernetesDeploymentSpec` layout, and the example should have been updated to match.
None.

docs: Fix examples/kubernetes/envoy-proxy-config.yaml for #1232.

---

.github/workflows/retest.yaml

* The codecov step is very flaky and PRs are blocked because of this.
* With this Github Action, users can comment `/retest` which should retrigger the `Build and Test` Workflow

feat(ci): Allow a commiter to run /retest to kick CI

---

internal/cmd/egctl/config.go
internal/cmd/egctl/config_cmd.go
internal/infrastructure/kubernetes/proxy/resource.go
internal/kubernetes/client.go

xref: https://github.com/envoyproxy/gateway/issues/1069

feat: add namespaced all proxies config dump support

---

internal/status/gateway.go

Dont append, just set/override the gw.Status.Addresses with the values from gw.Spec.Addresses (which eventually get set in svc.Spec.ExternalIPs)
Relates to https://github.com/envoyproxy/gateway/issues/1463
https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.Gateway

fix: only set gw.Spec.Addresses in gw.Status.Addresses

---

docs/latest/user/tls-cert-manager.md
docs/latest/user_docs.rst

This shows how to set up cert-manager to work with Envoy Gateway.
cert-manager is useful both for self-signed and Let's Encrypt.
Fixes #954

docs: add user/tls-cert-manager.md

---

test/e2e/tests/ratelimit.go
tools/make/kube.mk

remove the two TODO lines in RL e2e test.
- as for first TODO, wait for deployment/envoy-gateway to finish restart, so the deployment/envoy-ratelimit can be created, and the `Sleep` can be removed
- as for second TODO, make the resp and req more explicit

complement for RL e2e test

---

charts/gateway-helm/templates/generated/rbac/roles.yaml
internal/gatewayapi/resource.go
internal/gatewayapi/zz_generated.deepcopy.go
internal/provider/kubernetes/controller.go
internal/provider/kubernetes/predicates.go
internal/provider/kubernetes/predicates_test.go
internal/provider/kubernetes/rbac.go
internal/provider/kubernetes/test/utils.go

* Reconcile relavant EndpointSlices associated with a Service that is referenced in a xRoute
* Add the EndpointSlices to the provider message
Relates to https://github.com/envoyproxy/gateway/issues/1256

feat: Support EndpointSlice in Kubernetes Provider

---

internal/gatewayapi/contexts.go
internal/gatewayapi/filters.go
internal/gatewayapi/route.go

* Use common `processRouteDestinations` functions for all xRoute
* Precursor to https://github.com/envoyproxy/gateway/issues/1256

chore: Cleanup Gateway API Route Destination Logic

---

internal/crypto/certgen.go
internal/crypto/certgen_test.go
internal/infrastructure/kubernetes/ratelimit/resource.go
internal/infrastructure/kubernetes/ratelimit/resource_provider_test.go
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/affinity.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/custom.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/default-env.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/default.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/extension-env.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/override-env.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/redis-tls-settings.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/tolerations.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/volumes.yaml
internal/provider/kubernetes/secrets.go
internal/xds/translator/ratelimit.go
internal/xds/translator/testdata/out/xds-ir/authn-ratelimit.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/ratelimit-custom-domain.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/ratelimit-sourceip.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/ratelimit.clusters.yaml

add TLS Support between the envoy and ratelimted services
Relates to #1454

feat(crypto): control plane TLS support for Rate Limit Service phase I

---

api/config/v1alpha1/helpers.go
api/config/v1alpha1/shared_types.go
api/config/v1alpha1/zz_generated.deepcopy.go
charts/gateway-helm/crds/generated/config.gateway.envoyproxy.io_envoyproxies.yaml
docs/latest/api/config_types.md
internal/envoygateway/config/decoder_test.go
internal/envoygateway/config/testdata/decoder/in/gateway-ratelimit.yaml
internal/infrastructure/kubernetes/proxy/resource_provider.go
internal/infrastructure/kubernetes/proxy/resource_provider_test.go
internal/infrastructure/kubernetes/proxy/testdata/deployments/bootstrap.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/component-level.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/custom.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/default-env.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/extension-env.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/volumes.yaml
internal/infrastructure/kubernetes/ratelimit/resource_provider.go
internal/infrastructure/kubernetes/ratelimit/resource_provider_test.go
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/affinity.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/custom.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/default-env.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/default.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/extension-env.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/override-env.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/redis-tls-settings.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/tolerations.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/volumes.yaml
internal/infrastructure/kubernetes/resource/resource.go

Fixes #1520 
For more others settings, users can use the deployment patch yaml set them. like follows
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
labels:
app.kubernetes.io/name: envoy
app.kubernetes.io/component: proxy
app.kubernetes.io/managed-by: envoy-gateway
gateway.envoyproxy.io/owning-gateway-name: default
gateway.envoyproxy.io/owning-gateway-namespace: default
name: envoy-default-eg-63636f73
namespace: envoy-gateway-system
spec:
strategy:
type: RollingUpdate
rollingUpdate:
maxSurge: 50%
maxUnavailable: 70%
```

feat: support deployment strategy settings.

---

api/config/v1alpha1/accesslogging_types.go
examples/fluent-bit/helm-values.yaml
examples/otel-collector/helm-values.yaml
internal/gatewayapi/listener.go
internal/xds/translator/accesslog.go
internal/xds/translator/testdata/in/xds-ir/accesslog.yaml
internal/xds/translator/testdata/out/xds-ir/accesslog.listeners.yaml
test/e2e/tests/accesslog.go

With fluent-bit, your can get these informations from [Kubernetes Filter](https://docs.fluentbit.io/manual/pipeline/filters/kubernetes); with OpenTelemetry sink, we need send these manually.

accesslog: always send k8s.namespace.name and k8s.pod.name

---

tools/make/image.mk

* Use `buildx` for all builds
* Adds the `--load` flag to `docker buildx build` to save
the image in the local image store.

Fix `make conformance` on Mac

---

test/e2e/testdata/accesslog-file.yaml
test/e2e/testdata/accesslog-otel.yaml
test/e2e/tests/accesslog.go

see https://github.com/envoyproxy/gateway/issues/1563#issuecomment-1608562099, split HttpRoute for differnet tests
fixes: #1563

e2e: improve accesslog tests

---

internal/cmd/egctl/testdata/translate/out/default-resources.all.yaml
internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.json
internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.yaml
internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.listener.yaml
internal/xds/translator/listener.go
internal/xds/translator/testdata/out/xds-ir/http2-route.listeners.yaml

There is no good reason to pin to HTTP2 and disable HTTP1.1 when a GRPCRoute and HTTPRoute are attached to the same listener.
More info on codec type in https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
Fixes: https://github.com/envoyproxy/gateway/issues/1142

Always set codec type to AUTO in the xds listener

---

docs/latest/user_docs.rst

docs: missing docs for tls termination for tcp
TLS termination was added in this [PR](https://github.com/envoyproxy/gateway/pull/1431) and docs was also added but it was not added to user_docs.rst file so it is not visible on the latest docs.
Fixes #1642

docs: missing docs for tls termination for tcp

---

docs/latest/design/envoy-patch-policy.md
internal/cmd/egctl/testdata/translate/in/envoy-patch-policy.yaml
internal/cmd/egctl/testdata/translate/out/envoy-patch-policy.all.yaml
internal/cmd/egctl/translate.go
internal/cmd/egctl/translate_test.go

Relates to https://github.com/envoyproxy/gateway/issues/24

feat: `egctl x translate` support for EnvoyPatchPolicy

---

api/config/v1alpha1/envoygateway_types.go
docs/latest/api/config_types.md
internal/cmd/certgen.go
internal/infrastructure/kubernetes/ratelimit_infra_test.go
internal/provider/kubernetes/secrets.go

* Make sure certgen does not update the control plane cert secrets if they already exist. This ensures that if a user creates certs as part of https://github.com/envoyproxy/gateway/issues/866 they are not overriden by certgen.
* If `overwriteControlPlaneCerts` is set in the `EnvoyGateway` config, certgen can be used to update the secrets with newer certs
Fixes: https://github.com/envoyproxy/gateway/issues/1471

Update control plane certs only if user opts in

---

tools/make/tools.mk
tools/src/buf/pin.go
tools/src/controller-gen/pin.go
tools/src/crd-ref-docs/pin.go
tools/src/golangci-lint/pin.go
tools/src/helm-docs/pin.go
tools/src/kind/pin.go
tools/src/kustomize/pin.go
tools/src/protoc-gen-go-grpc/pin.go
tools/src/protoc-gen-go/pin.go
tools/src/setup-envtest/pin.go

Add a [blank](https://go.dev/ref/spec#Blank_identifier) identifier to pin.go so the imported tool packages won't be automatically deleted by  Goland.

fix: the imported packages in pin.go are removed by goland

---

.github/workflows/cherrypick.yaml

update cherry-pick GHA for v0.5

---

api/config/v1alpha1/shared_types.go
internal/infrastructure/kubernetes/proxy/testdata/deployments/bootstrap.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/component-level.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/enable-prometheus.yaml
internal/infrastructure/kubernetes/ratelimit/testdata/deployments/default.yaml

* Bumped Envoy Proxy to `v1.27` https://www.envoyproxy.io/docs/envoy/v1.27.0/version_history/v1.27/v1.27.0
* Bumped Envoy RateLimit to `e059638d` https://hub.docker.com/r/envoyproxy/ratelimit/tags
Fixes: https://github.com/envoyproxy/gateway/issues/1716

[release/v0.5] Bump Envoy Proxy and RateLimit

---

internal/infrastructure/kubernetes/proxy/resource.go
internal/infrastructure/kubernetes/proxy/testdata/deployments/bootstrap.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/component-level.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/custom.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/default-env.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/enable-prometheus.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/extension-env.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/volumes.yaml

* Use cpuset size instead of total hardware threads to determine total worker threads.
* Can be overridden by explicitly setting `--concurrency` arg
More in https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-cpuset-threads
Discussion in https://github.com/envoyproxy/envoy/pull/5975
Relates to https://github.com/envoyproxy/gateway/issues/1718

feat: Set `--cpuset-threads` in EnvoyProxy cmdline arg

---

examples/kubernetes/metric/pod-monitor.yaml
internal/infrastructure/kubernetes/proxy/resource.go
internal/infrastructure/kubernetes/proxy/testdata/deployments/enable-prometheus.yaml

xref: https://github.com/envoyproxy/gateway/issues/699#issuecomment-1658646684

observability: add container port for metrics

---

internal/utils/field/field.go
internal/utils/field/field_test.go

test: add setvalue unit tests coverage

---

api/v1alpha1/envoypatchpolicy_types.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoypatchpolicies.yaml
docs/latest/user/envoy-patch-policy.md
examples/redis/redis.yaml
internal/provider/kubernetes/controller.go
internal/status/envoypatchpolicy.go
test/e2e/testdata/envoy-patch-policy.yaml
test/e2e/tests/envoy-patch-policy.go

misc fixes:
* Only add EnvoyPatchPolicy to provider resources if enabled in
EnvoyGateway API
* Add `omitempty` tag to `priority` field to make it optional
e2e
* Use LocalReplyConfig to return a custom status code `406` when there is no valid route match
Relates to https://github.com/envoyproxy/gateway/issues/24

e2e & misc fixes for EnvoyPatchPolicy

---

OWNERS

This PR removes me from Envoy Gateway maintainers. I haven't been able to contribute anything worth while for some time, so I think that this is really updating to reflect the actual state.
I've really enjoyed working with everyone on this project, and I really wish the project and everyone involved all the best.

Remove youngnick from maintainers

---

.github/codecov.yml

Else it ends up using the current project coverage as the default threshold

Update codecov patch coverage threshold to 60%

---

charts/gateway-helm/crds/gatewayapi-crds.yaml
go.mod
go.sum
internal/status/conditions_test.go
internal/status/gateway.go
internal/status/gateway_test.go

Fixes https://github.com/envoyproxy/gateway/issues/1777

api: bump gwapi to v0.8.0-rc1

---

charts/gateway-helm/values.tmpl.yaml

- bump kubebuilder/kube-rbac-proxy from v0.11.0 to v0.14.1
- bump kubebuilder/kube-rbac-proxy from v0.11.0 to v0.14.1
- kube-rbac-proxy image is stale.
- none.

build(deps): bump kube-rbac-proxy from v0.11.0 to v0.14.1

---

internal/cmd/egctl/testdata/translate/out/authn-single-route-single-match-to-xds.all.json
internal/cmd/egctl/testdata/translate/out/authn-single-route-single-match-to-xds.all.yaml
internal/cmd/egctl/testdata/translate/out/authn-single-route-single-match-to-xds.bootstrap.yaml
internal/cmd/egctl/testdata/translate/out/default-resources.all.yaml
internal/cmd/egctl/testdata/translate/out/envoy-patch-policy.all.yaml
internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.json
internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.yaml
internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.bootstrap.yaml
internal/cmd/egctl/testdata/translate/out/rate-limit-filter-single-route-single-match-to-xds.all.json
internal/cmd/egctl/testdata/translate/out/rate-limit-filter-single-route-single-match-to-xds.all.yaml
internal/cmd/egctl/testdata/translate/out/rate-limit-filter-single-route-single-match-to-xds.bootstrap.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/custom.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/default-env.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/enable-prometheus.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/extension-env.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/volumes.yaml
internal/xds/bootstrap/bootstrap.yaml.tpl
internal/xds/bootstrap/testdata/default.yaml
internal/xds/bootstrap/testdata/enable-prometheus.yaml
internal/xds/bootstrap/testdata/otel-metrics.yaml
internal/xds/server/runner/runner.go

Add XDS keepalives

---

OWNERS
docs/latest/dev/CODEOWNERS.md

Move @skriss to emeritus maintainers
NA

move skriss to emeritus maintainers

---

internal/cmd/egctl/testdata/translate/out/authn-single-route-single-match-to-xds.all.json
internal/cmd/egctl/testdata/translate/out/authn-single-route-single-match-to-xds.all.yaml
internal/cmd/egctl/testdata/translate/out/authn-single-route-single-match-to-xds.listener.yaml
internal/xds/translator/authentication.go
internal/xds/translator/testdata/out/xds-ir/authn-multi-route-multi-provider.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/authn-multi-route-single-provider.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/authn-ratelimit.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/authn-single-route-single-match.listeners.yaml

Async is useful because it will not block requests with jwt fetches, will not need to jwt fetch per thread Retrying once after a failed fetch is also useful

Make jwt fetch more reliable

---

internal/ir/xds.go
internal/ir/xds_test.go
internal/message/watchutil_test.go

This change implements the comparable interface used by watchable to sort ir.Xds listeners when checking for differences. This reduces the number of xds updates that get pushed to envoy during re-syncs of k8s resources.
fixes #1634

fix: implement comparable interface for ir.Xds to skip unnecessary updates

---

internal/message/watchutil_test.go

TestXdsIRUpdates added in #1795 is flaky. This adds a sleep to reduce the chance of failing. Open to suggestions to avoid the sleep but this pattern is also used in another test here https://github.com/envoyproxy/gateway/blob/080674a93bc42504575d7c0c83d21300abbb6e00/internal/message/watchutil_test.go#L43

fix: ensure all updates are processed in xds ir update test

---

internal/provider/kubernetes/controller.go
internal/provider/kubernetes/controller_test.go

The current behavior of the controller is to run `Reconcile` for each resource that is updated. This gets quite expensive when you have 100s-1000s of resources.
This change allows for multiple resource updates to result in a single run of `Reconcile`.
This greatly reduces the cpu/memory consumption at startup and during periodic re-syncs of all resources.
Fixes #1797

fix: enqueue a single request for all resources

---

internal/logging/log.go
internal/logging/log_test.go

Fix: EG can't show debug level logging message because the sugar logger created in the WithName function is incorrect.

fix: can't show debug level logging message

---

docs/latest/design/accesslog.md
docs/latest/user/proxy-observability.md
docs/v0.5.0/design/accesslog.md
docs/v0.5.0/user/proxy-observability.md
examples/kubernetes/accesslog/disable-accesslog.yaml

* docs: fix a typo: disabled -> disable, the API actually is `telemetry.accesslog.disable` not `telemetry.accesslog.disabled`. I fixed the typo in the docs and example YAML files. See the [API types](https://gateway.envoyproxy.io/latest/design/accesslog.html#proxyaccesslog-api-type).

fix a typo: disabled -> disable

---

examples/kubernetes/tracing/default.yaml

Fix the tracing example configuration error: missing the required field "type", see the [TracingProvider](https://gateway.envoyproxy.io/latest/api/config_types.html#tracingprovider).

add the missing required field type

---

api/config/v1alpha1/validation/validate.go
api/config/v1alpha1/validation/validate_test.go
internal/gatewayapi/listener.go
internal/gatewayapi/testdata/envoyproxy-accesslog-file-json-no-format.in.yaml
internal/gatewayapi/testdata/envoyproxy-accesslog-file-json-no-format.out.yaml
internal/gatewayapi/testdata/envoyproxy-accesslog-file-json.in.yaml
internal/gatewayapi/testdata/envoyproxy-accesslog-file-json.out.yaml
internal/gatewayapi/testdata/envoyproxy-accesslog-with-bad-sinks.in.yaml
internal/gatewayapi/testdata/envoyproxy-accesslog-with-bad-sinks.out.yaml

Fixes #1830 
Additionally, I also added a test for JSON format type Access Log.

fix: prevent nil pointer panic because of nonexist attribute of Access Log

---

api/config/v1alpha1/accesslogging_types.go
charts/gateway-helm/crds/generated/config.gateway.envoyproxy.io_envoyproxies.yaml
docs/latest/api/config_types.md

make sure user specifies a file name when sink is set to file

fix docs string for access logs

---

docs/latest/user/multicluster-service.md
docs/latest/user_docs.rst
examples/kubernetes/multicluster-service.yaml

+ Add missing index
+ Set EnvoyProxy Service Type to ClusterIP, since LoadBalancer is not supported in default submariner env.
+ Upgrade RG to v1beta1.

:bug: Fix: follow-up of #1852

---

internal/xds/translator/jsonpatch.go
internal/xds/translator/testdata/out/xds-ir/jsonpatch-invalid-patch.envoypatchpolicies.yaml

fixes error: https://github.com/envoyproxy/gateway/actions/runs/6141855691/job/16663397611?pr=1875
cc @arkodg @zhaohuabing

chore: fix unicode error

---

docs/latest/user/gateway-api-metrics.md
docs/latest/user_docs.rst

Docs, new user guide
This PR adds a new User Guide for installing and using [Gateway API State Metrics](https://github.com/Kuadrant/gateway-api-state-metrics) (metrics, dashboards and alerts).
Fixes #1823

docs: Add user guide for Gateway API State Metrics

---

.github/workflows/build_and_test.yaml
.github/workflows/experimental_conformance.yaml
charts/gateway-helm/crds/gatewayapi-crds.yaml
test/conformance/experimental_conformance_test.go
tools/make/kube.mk

+ add experimental conformance support
+ generate conformance report

feat: add experimental conformance support

---

.github/dependabot.yml

inspired from https://github.com/envoyproxy/go-control-plane/pull/774 which reduces the number of dependabot PRs

chore: group k8s gomod depencies together

---

internal/xds/translator/authentication.go
internal/xds/translator/route.go
internal/xds/translator/testdata/in/xds-ir/mixed-tls-jwt-authn.yaml
internal/xds/translator/testdata/out/xds-ir/mixed-tls-jwt-authn.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/mixed-tls-jwt-authn.endpoints.yaml
internal/xds/translator/testdata/out/xds-ir/mixed-tls-jwt-authn.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/mixed-tls-jwt-authn.routes.yaml
internal/xds/translator/testdata/out/xds-ir/mixed-tls-jwt-authn.secrets.yaml
internal/xds/translator/translator.go
internal/xds/translator/translator_test.go

Bug Fix
HTTPS and JWT authentication was not working in tandem because for some reason we were getting the information for JWTRequirement from HCM in DefaultFilterChain. DefaultFilterChain is not populated in case of HTTPS.
The question is irRoute already have all the information about JWT Requirement as the HCM of listener is also populated from route only which only checks if the listener has JWT Filter on the route and patch listener. Then why reverse check is done if httpfilter has the JWT requirements?  
Fixes https://github.com/envoyproxy/gateway/issues/1768

fix tls with jwt authn usecase

---

charts/gateway-helm/crds/gatewayapi-crds.yaml
go.mod
go.sum
test/conformance/conformance_test.go
test/conformance/experimental_conformance_test.go

https://github.com/kubernetes-sigs/gateway-api/releases/tag/v0.8.1

chore: bump gateway api to v0.8.1

---

charts/gateway-helm/templates/envoy-gateway-rbac.yaml
charts/gateway-helm/values.tmpl.yaml

helm lint indentifies the following error:
```
templates/: template: gateway-helm/templates/envoy-gateway-rbac.yaml:3:27: executing "gateway-helm/templates/envoy-gateway-rbac.yaml" at <$kube.watch.namespaces>: nil pointer evaluating interface
```
two adjustments:
- values now hove the path `config.envoyGateway.provider.kubernetes.watch.namespaces`
- also adjusting logic to handle empty list in `templates.envoy-gateway-rbac.yaml`

Address 'helm lint' error <.watch.namespaces>: nil pointer

---

internal/gatewayapi/clienttrafficpolicy.go
internal/gatewayapi/envoypatchpolicy.go

* Defaults to the policy namespace as recommend by upstream
https://github.com/kubernetes-sigs/gateway-api/blob/d38e6c81ba3d3f137012ceeec8262ab40ad0cd81/apis/v1alpha2/policy_types.go#L47

Allow policy target namespace to be optional

---

api/v1alpha1/envoygateway_types.go
api/v1alpha1/envoyproxy_types.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
docs/latest/api/extension_types.md
docs/latest/design/accesslog.md
docs/latest/design/client-traffic-policy.md
docs/latest/design/metrics.md
docs/latest/design/rate-limit.md
docs/latest/design/request-authentication.md
docs/latest/design/tracing.md
docs/latest/releases/v0.5.md
docs/latest/user/envoy-patch-policy.md
docs/v0.3.0/api/config_types.md
docs/v0.3.0/design/ratelimit.md
docs/v0.3.0/design/request-authentication.md
docs/v0.4.0/api/config_types.md
docs/v0.4.0/design/rate-limit.md
docs/v0.4.0/design/request-authentication.md
docs/v0.5.0/api/config_types.md
docs/v0.5.0/design/accesslog.md
docs/v0.5.0/design/metrics.md
docs/v0.5.0/design/rate-limit.md
docs/v0.5.0/design/request-authentication.md
docs/v0.5.0/design/tracing.md
docs/v0.5.0/releases/v0.5.md
docs/v0.5.0/user/envoy-patch-policy.md
internal/gatewayapi/testdata/gateway-with-listener-with-invalid-multiple-tls-configuration.out.yaml
internal/gatewayapi/tls.go
internal/ir/xds.go
tools/src/codespell/requirements.txt

Taking https://github.com/envoyproxy/gateway/pull/1924 forward

chore:bump codespell and fix existing codespell errs

---

internal/status/status.go

Relates to https://github.com/envoyproxy/gateway/issues/1846

Add status eq check for ClientTrafficPolicy

---

internal/ir/xds.go
internal/ir/xds_test.go

Empty matches are supported in the gateway api spec e.g. https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1alpha2.GRPCRouteRule and we are also tranlating it correctly in the gateway-api layer e.g. https://github.com/envoyproxy/gateway/blob/76704d1124eccaf06b81634a96390c95722a0554/internal/gatewayapi/route.go#L212 but the IR layer is rejecting this valid config
Relates to https://github.com/envoyproxy/gateway/issues/1958#issuecomment-1760149916

fix: Remove ErrHTTPRouteMatchEmpty check for Xds IR

---

internal/gatewayapi/resource.go
internal/gatewayapi/route.go
internal/gatewayapi/testdata/httproute-attaching-to-listener-with-serviceimport-backendref.in.yaml
internal/gatewayapi/testdata/httproute-attaching-to-listener-with-serviceimport-backendref.out.yaml
internal/gatewayapi/testdata/httproute-with-backendref-serviceimport-in-other-namespace-allowed-by-refgrant.in.yaml
internal/gatewayapi/testdata/httproute-with-backendref-serviceimport-in-other-namespace-allowed-by-refgrant.out.yaml

Feature: Multicluster services API
With https://github.com/envoyproxy/gateway/pull/1494 EndpointSlice support is added for backends for gateway. This PR do the same for ServiceImport.
Fixes https://github.com/envoyproxy/gateway/issues/1908

Endpoint Slice support for ServiceImport

---

examples/kubernetes/grpc-routing.yaml

Deploying yages with `quay.io/mhausenblas/yages:0.1.0` resulted in `Error: ErrImagePull`.
```bash
Warning Failed 9s kubelet Failed to pull image "quay.io/mhausenblas/yages:0.1.0": rpc error: 
code = Unknown desc = Error response from daemon: application/vnd.docker.distribution.manifest.v1+prettyjws not supported
```
Propose: change image `quay.io/mhausenblas/yages` to forked and updated `ghcr.io/projectcontour/yages`.

fix: update outdated image in grpc routing docs

---

tools/make/docs.mk

make `generate` does not include `helm-readme-gen`, which makes the lint CI can not check if the helm docs is the latest.

chore: add helm-readme-gen to docs-api to generate

---

internal/provider/kubernetes/controller.go

Per review of https://github.com/envoyproxy/gateway/pull/1938#discussion_r1358956623, it would be valuable to add GenerationChanged predicate to all resources.
This skip events that have no change in the object Spec and only the metadata and/or status fields are changed.

add GenerationChanged predicate filter to all resources

---

internal/provider/kubernetes/controller.go
internal/provider/kubernetes/controller_test.go
internal/provider/kubernetes/kubernetes_test.go

This reverts commit e158ef139a7a038c97e95666d3a2d7bd08f3f998.
Relates to https://github.com/envoyproxy/gateway/pull/1999#discussion_r1364431432

Revert "provider: finalize EnvoyProxy referenced by a managed GatewayClass(#1534)

---

site/content/en/latest/user/rate-limit.md

fix Rate Limit All Requests by GRPCRoute in rate-limit.md
fix the docs
Fixes #2008

docs: fix Rate Limit All Requests by GRPCRoute in rate-limit.md

---

internal/envoygateway/scheme.go
internal/gatewayapi/resource.go
internal/gatewayapi/translator_test.go
internal/gatewayapi/validate.go
internal/gatewayapi/zz_generated.deepcopy.go
internal/provider/kubernetes/controller.go
site/content/en/latest/user/secure-gateways.md
test/conformance/conformance_test.go
test/conformance/experimental_conformance_test.go

* `ReferenceGrant` is still on v1beta1
Fixes: https://github.com/envoyproxy/gateway/issues/2005

register for v1beta1 gateway api

---

charts/gateway-helm/templates/certgen-rbac.yaml
charts/gateway-helm/templates/certgen.yaml
charts/gateway-helm/values.tmpl.yaml
site/content/en/latest/install/api.md

feat(helm): support annotations for certgen resources
* support annotations for certgen resources
* support configuration for certgen job ttlSecondsAfterFinished
Fixes #1954

feat(helm): support annotations for certgen resources

---

tools/make/docs.mk

Fixes https://github.com/envoyproxy/gateway/issues/2026

fix: missing get-egctl.sh

---

api/v1alpha1/backendtrafficpolicy_types.go
api/v1alpha1/clienttrafficpolicy_types.go
api/v1alpha1/securitypolicy_types.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_clienttrafficpolicies.yaml
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml
test/cel-validation/backendtrafficpolicy_test.go
test/cel-validation/clienttrafficpolicy_test.go
test/cel-validation/securitypolicy_test.go

adds some more validation to the new Policy CRDs.
Resolves:
- #1964 
- #1965

add more crd (mostly CEL) validation

---

.github/workflows/docs.yaml

Docs GHA only runs on `main`
Fixes this error https://github.com/envoyproxy/gateway/actions/runs/6673931411/job/18140221080

[release/v0.6] dont run docs GHA on release branches

---

api/v1alpha1/securitypolicy_types.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml
examples/kubernetes/jwt/grpc-jwt.yaml
examples/kubernetes/jwt/jwt.yaml
internal/cmd/egctl/testdata/translate/in/jwt-single-route-single-match-to-xds.yaml
internal/cmd/egctl/testdata/translate/out/jwt-single-route-single-match-to-xds.all.json
internal/cmd/egctl/testdata/translate/out/jwt-single-route-single-match-to-xds.all.yaml
internal/cmd/egctl/testdata/translate/out/jwt-single-route-single-match-to-xds.listener.yaml
site/content/en/latest/design/rate-limit.md
site/content/en/latest/design/security-policy.md
site/content/en/latest/user/rate-limit.md
site/content/en/v0.5.0/design/rate-limit.md
site/content/en/v0.5.0/user/rate-limit.md
test/e2e/e2e_test.go
test/e2e/testdata/ratelimit-based-jwt-claims.yaml

Fix https://github.com/envoyproxy/gateway/issues/2095
Related: https://github.com/envoyproxy/gateway/pull/2086  https://github.com/envoyproxy/gateway/pull/2096

Fix TestE2E/RateLimitBasedJwtClaims test

---

internal/gatewayapi/route.go

All the translations and assignments now happen in the policy translators

remove cors, jwt, rl assignment from route translator

---

api/v1alpha1/envoygateway_types.go
site/content/en/latest/api/extension_types.md

fix: use lowercases of eg admin config fields

---

api/v1alpha1/loadbalancer_types.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml
test/cel-validation/backendtrafficpolicy_test.go

feat: CEL Validation in BackendTrafficPolicy
CEL Validation in BackendTrafficPolicy for load balancer field
Fixes #2066
PS: issues also mentioned that we need to disable `targetRef.sectionName` field . But I found that it was already Implemented by Alice.

feat: CEL Validation in BackendTrafficPolicy

---

test/e2e/testdata/prometheus.yaml
test/e2e/tests/controlplane.go
test/e2e/tests/metric.go
test/e2e/tests/prometheus.go

xhref: https://github.com/envoyproxy/gateway/issues/2088

e2e: eg controlplane metrics

---

internal/status/status.go

fix: add missing status equal for SecurityPolicy

---

internal/cmd/egctl/testdata/translate/out/multiple-xds.route.json
internal/gatewayapi/sort.go
internal/gatewayapi/testdata/grpcroute-with-service-match.out.yaml
internal/gatewayapi/testdata/httproute-with-single-rule-with-multiple-rules.out.yaml
internal/xds/translator/route.go
internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-root-path-url-prefix.routes.yaml
test/conformance/conformance_test.go
test/conformance/experimental_conformance_test.go

* Addresses this conformance test https://github.com/kubernetes-sigs/gateway-api/blob/8f1b718543caae927bb4f57dfb538aff1efc8159/conformance/tests/httproute-rewrite-path.yaml#L32 by using a regex match and replace instead of a prefix replace, since a prefix replace adds a double slash
* tries to implement https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.HTTPPathModifier
* reverts #1125 which tried to solve the same problem
* trim the `/` suffix when it comes to prefix matches because Gateway API recommends ignoring the trailing `/` and envoy errors out when the trailing char is `/` for path separated prefix
* enhance IR sorting function so preference is given to exact match over path prefix match, this is needed when exact match of `/match` and path prefix match …

Enable HTTPRouteRewritePath test

---

internal/gatewayapi/securitypolicy.go
internal/xds/translator/httpfilters.go
internal/xds/translator/route.go
site/content/en/latest/user/cors.md

This PR adds user docs for CORS.
Related: https://github.com/envoyproxy/gateway/pull/2065

doc: user doc for CORS

---

test/e2e/testdata/cors.yaml
test/e2e/tests/cors.go

test: add e2e test for CORS

---

site/content/en/latest/user/customize-envoyproxy.md

The example to customize the bootstrap config is wrong and leads to an error:
```
cat eg.yaml| egctl x translate --from gateway-api --to xds  -f - 
Error: proto: syntax error (line 1:10): unexpected token [
proto: syntax error (line 1:10): unexpected token [
```

docs: fix typo in bootstrap example

---

api/v1alpha1/envoygateway_helpers.go
internal/provider/kubernetes/kubernetes.go

opt: move gateway namespace mode to common helper

---

site/content/en/latest/user/tls-cert-manager.md
site/content/en/v0.6.0/user/tls-cert-manager.md

Annotation for cluster-issuer was also changed it seems:
Checkout https://cert-manager.io/docs/usage/gateway/#supported-annotations

doc: small patch cert-manager doc better experience

---

internal/xds/translator/runner/runner.go
internal/xds/translator/runner/runner_test.go
internal/xds/translator/testdata/in/xds-ir/http-route-partial-invalid.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-partial-invalid.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-partial-invalid.endpoints.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-partial-invalid.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-partial-invalid.routes.yaml
internal/xds/translator/translator.go
internal/xds/translator/translator_test.go

fix: https://github.com/envoyproxy/gateway/issues/2200

fix: xds translation return early, should be done in a best-effort manner

---

site/content/en/latest/install/install-egctl.md
site/content/en/v0.6.0/install/install-egctl.md

chore: update egctl install cmd

---

api/v1alpha1/jwt_types.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml
site/content/en/latest/api/extension_types.md

docs: fix broken format on JWT

---

charts/gateway-helm/Chart.yaml
tools/make/helm.mk

chore: add `helm lint` at `make lint` stage.
Fixes [2057](https://github.com/envoyproxy/gateway/issues/2057)

chore: add helm lint

---

site/content/en/latest/user/oidc.md

close https://github.com/envoyproxy/gateway/issues/2208

user doc for oidc

---

test/e2e/tests/udproute.go

e2e bug fix
`dns.Exchange` method should not return its error directly, nor it will end `PollUntilContextTimeout` immediately without any retry.
Fixes #2266

e2e: fix retry logic for e2e udp route

---

.github/workflows/welcome.yaml

We tried a couple of ways to auto request reviews from @envoyproxy/gateway-reviewers, but it failed, and I tried it too today, failed again.
So current way is to add a welcome comment to cc @envoyproxy/gateway-maintainers and @envoyproxy/gateway-reviewers, they should get the ping too.

ci: add PR comment and cc reviewers

---

internal/provider/kubernetes/predicates.go

Fixes https://github.com/envoyproxy/gateway/issues/2282

fix: mergeGateways panics when restarting control plane

---

internal/cmd/egctl/testdata/translate/out/jwt-single-route-single-match-to-xds.all.json
internal/cmd/egctl/testdata/translate/out/jwt-single-route-single-match-to-xds.all.yaml
internal/cmd/egctl/testdata/translate/out/jwt-single-route-single-match-to-xds.listener.yaml
internal/xds/translator/jwt.go
internal/xds/translator/testdata/out/xds-ir/jwt-custom-extractor.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/jwt-multi-route-multi-provider.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/jwt-multi-route-single-provider.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/jwt-ratelimit.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/jwt-single-route-single-match.listeners.yaml

related: https://github.com/envoyproxy/gateway/issues/2295

forward jwt tokens after verification

---

.github/workflows/build_and_test.yaml

* rm'd v1.26 for now, since we are only running last 3 versions
* k8s support matrix should be revisited pre GA

Run CI on k8s v1.29.0

---

api/v1alpha1/envoyproxy_types.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
test/cel-validation/envoyproxy_test.go

According to hpa [spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#horizontalpodautoscalerspec-v2-autoscaling) `maxReplicas` cannot be less that `minReplicas`. The current cel validation also forbids it to be equal to `minReplicas`.
This PR fixes the validation to be aligned with the spec and also adds a test.
**Which issue(s) this PR fixes**: N/A

fix: allow envoyHpa maxReplicas to be equal to minReplicas

---

api/v1alpha1/envoygateway_types.go
internal/envoygateway/config/decoder_test.go
internal/envoygateway/config/testdata/decoder/in/gateway-ns-watch.yaml
internal/envoygateway/config/testdata/decoder/in/gateway-nsselector-watch.yaml
site/content/en/latest/api/extension_types.md

refactor: update watch ns api & add tests

---

charts/gateway-helm/templates/envoy-gateway-deployment.yaml
charts/gateway-helm/values.tmpl.yaml
site/content/en/latest/install/api.md

Feature - Add support for affinity configuration in `EnvoyGateway` pod.
A sample use case for affinity configuration is making `EnvoyGateway` HA on different nodes (By adding AntiAffinity rule).
**Which issue(s) this PR fixes**: N/A

feat(helm): support affinity configuration for EnvoyGateway pod

---

charts/gateway-helm/templates/certgen.yaml
charts/gateway-helm/templates/envoy-gateway-deployment.yaml

Bug fix. 
It fixes wrong indentation of imagePullSecrets in both EG deployment and certgen job - should be under pod spec instead of under container.
Tested by installing chart to kind cluster - once with default values and once with secret ref.
**Which issue(s) this PR fixes**: N/A

fix(helm): fix incorrect imagePullSecrets indentation

---

.github/workflows/build_and_test.yaml
.github/workflows/cherrypick.yaml
.github/workflows/command.yaml
.github/workflows/docs.yaml
.github/workflows/experimental_conformance.yaml
.github/workflows/issue-comment.yaml
.github/workflows/latest_release.yaml
.github/workflows/release.yaml
.github/workflows/scorecard.yml
.github/workflows/stale.yml
README.md
site/content/en/latest/contributions/RELEASING.md
site/content/en/v0.2.0/contributions/RELEASING.md
site/content/en/v0.3.0/contributions/RELEASING.md
site/content/en/v0.4.0/contributions/RELEASING.md
site/content/en/v0.5.0/contributions/RELEASING.md
site/content/en/v0.6.0/contributions/RELEASING.md

* chore: Enable OpenSSF Scorecard
* seup scorecard workflow ans pin actions versions
Fixes #2347
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

chore: Enable OpenSSF Scorecard

---

api/v1alpha1/validation/securitypolicy_validate.go
go.mod
internal/cmd/certgen.go
internal/cmd/egctl/envoy_stats.go
internal/cmd/egctl/version.go
internal/crypto/certgen.go
internal/crypto/certgen_test.go
internal/infrastructure/kubernetes/infra.go
internal/infrastructure/kubernetes/infra_client.go
internal/kubernetes/client.go
internal/kubernetes/port-forwarder.go
internal/kubernetes/secret.go
internal/provider/kubernetes/controller.go
internal/provider/kubernetes/filters.go
internal/provider/kubernetes/helpers.go
internal/provider/kubernetes/kubernetes.go
internal/provider/kubernetes/routes.go
internal/utils/regex/regex.go
internal/xds/bootstrap/bootstrap.go
internal/xds/server/runner/runner_test.go
internal/xds/translator/jsonpatch.go
internal/xds/translator/tracing.go
internal/xds/types/resourceversiontable.go
test/e2e/tests/metric.go
tools/linter/golangci-lint/.golangci.yml

* chore: use go standard errors and enable errorlint
github.com/pkg/errors is not maintained and can be replaced by go standard errors 

use go standard errors

---

internal/gatewayapi/backendtrafficpolicy.go
internal/gatewayapi/helpers.go
internal/gatewayapi/securitypolicy.go

This is a small change to move "/" to route prefix so we can reuse the `irRoutePrefix` function and avoid duplicating code.

move "/" to route prefix

---

site/content/en/latest/user/circuit-breaker.md

Docs for the circuit breaker settings in Backend Traffic Policy. 
Fixes https://github.com/envoyproxy/gateway/issues/2342

docs:circuit breaker

---

api/v1alpha1/cors_types.go
api/v1alpha1/zz_generated.deepcopy.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml
internal/gatewayapi/securitypolicy.go
internal/gatewayapi/securitypolicy_test.go
internal/gatewayapi/testdata/securitypolicy-with-cors.in.yaml
internal/gatewayapi/testdata/securitypolicy-with-cors.out.yaml
site/content/en/latest/api/extension_types.md
site/content/en/latest/user/cors.md
test/cel-validation/securitypolicy_test.go
test/e2e/testdata/cors.yaml

The current CORS api uses regex to match the allowed origins. This PR changes this behavior to use wildcard matching instead. Using wildcard matching is more intuitive and easier to use, and also aligns with the gateway api hostname matching.
before:
```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
name: cors
spec:
cors:
allowMethods:
- GET
- HEAD
- PUT
- PATCH
- POST
- DELETE
allowOrigins:
- type: RegularExpression
value: .*\.example\.com
allowCredentials: true
targetRef:
group: gateway.networking.k8s.io
kind: HTTPRoute
name: backend
```
after:
```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
name: cors
spec:
cors:
allowMethods:
- GET
- HEAD
- PUT
- PATCH
- POST
- DELETE
allowOrigins:
- https://*.example.com …
```

use wildcard to match alloworigins

---

.github/dependabot.yml
site/Dockerfile
tools/docker/envoy-gateway/Dockerfile

* chore : pin Dockerfile images version
* Setup dependabot accordingly
Improve OSSF score

chore: pin Docker images versions

---

.github/workflows/latest_release.yaml
.github/workflows/release.yaml

defualted all base permissions to contents: read using https://github.com/envoyproxy/gateway/pull/2398
which broke the latest release action
https://github.com/envoyproxy/gateway/actions/runs/7415213672/job/20179669381

bug: use contents:write permission for release actions

---

.github/workflows/command.yaml

chore
address github actions lint comment that shown in recent PRs.

chore: address github action lint comments

---

test/cel-validation/clienttrafficpolicy_test.go

This PR adds a missing unit test for a CEL validation rule that was introduced in #2287 .

fix: Add a CEL validation unit test to verify that no ciphers can be specified if the minimal TLS version is 1.3

---

api/v1alpha1/tls_types.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_clienttrafficpolicies.yaml
site/content/en/latest/api/extension_types.md

**Before:**
**After:**
Fixes #2427

docs: fix TLSSettings format

---

api/v1alpha1/validation/envoygateway_validate_test.go
api/v1alpha1/validation/envoyproxy_validate_test.go
internal/admin/server_test.go
internal/cmd/egctl/config_test.go
internal/cmd/egctl/translate_test.go
internal/cmd/server_test.go
internal/crypto/certgen_test.go
internal/envoygateway/config/decoder_test.go
internal/gatewayapi/contexts_test.go
internal/gatewayapi/securitypolicy_test.go
internal/gatewayapi/translator_test.go
internal/infrastructure/kubernetes/proxy_serviceaccount_test.go
internal/infrastructure/kubernetes/ratelimit_serviceaccount_test.go
internal/logging/log_test.go
internal/provider/kubernetes/helpers_test.go
internal/utils/env/env_test.go
internal/xds/bootstrap/bootstrap_test.go
internal/xds/server/runner/runner_test.go
test/conformance/experimental_conformance_test.go
tools/linter/golangci-lint/.golangci.yml

* chore: enable testifylint linter
This linter helps ensuring the best practices for testify are being applied.

chore: enable testifylint linter

---

api/v1alpha1/validation/envoyproxy_validate.go
internal/gatewayapi/securitypolicy.go
internal/ir/xds.go
internal/xds/translator/utils.go

Description:
Golang `net/netip` package was imported in Go 1.18, and it defines IP address by [Addr](https://pkg.go.dev/net/netip#Addr) instead of [net.IP](https://pkg.go.dev/net#IP). Compared to the `net.IP` type, `Addr` type takes less memory, is immutable, and is comparable (supports == and being a map key). This project is using `go 1.21`, so I recommend that to change this package.

Replace the net.ParseIP with netip.ParseAddr for IP address parsing.

---

charts/gateway-helm/templates/_rbac.tpl

Helm chart cleanup.
Remove unused patch & update RBAC verbs from EG role.
Fixes #2449

fix(helm): remove unused RBAC verbs

---

api/v1alpha1/backendtrafficpolicy_types.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml
site/content/en/latest/api/extension_types.md

* "docs: fix the wrong description"
According the description of https://github.com/envoyproxy/gateway/issues/1821, the BackendTrafficPolicy is about the policy of the connection between Envoy Proxy listener and backend service.
n/a

Fix the description for BackendTrafficPolicy

---

go.mod
go.sum
internal/cmd/egctl/config.go
internal/cmd/egctl/envoy_stats.go
internal/gatewayapi/securitypolicy.go
internal/ir/xds.go
internal/xds/translator/basicauth.go
internal/xds/translator/jsonpatch.go
internal/xds/translator/jwt.go
internal/xds/translator/oidc.go
internal/xds/translator/translator.go
tools/linter/golangci-lint/.golangci.yml

* chore: use go standard errors instead of multierror
standard errors now supports Joining list of errors so there is no need to rely on custom packages

Use go standard errors instead of multierror

---

internal/provider/kubernetes/controller.go
internal/provider/kubernetes/filters.go
internal/provider/kubernetes/predicates.go
internal/provider/kubernetes/predicates_test.go
internal/provider/kubernetes/routes.go

Fix the checkObjectNamespaceLabels function param type so that it can support passing in common interface types. Avoid obtaining namespace in advance outside the function.
Fixes #

fix: fix checkObjectNamespaceLabels func param type

---

site/content/en/latest/user/cors.md

Add a note to the CORS doc to remind user to allow `OPTIONS` in the targeted HTTPRoute.
```
The targeted HTTPRoute or the HTTPRoutes that the targeted Gateway routes to must allow the OPTIONS method for the CORS filter to work. Otherwise, the OPTIONS request won't match the routes and the CORS filter won't be invoked.
```

update CORS docs

---

internal/gatewayapi/route.go
internal/gatewayapi/testdata/httproute-rule-with-multiple-backends-and-weights.in.yaml
internal/gatewayapi/testdata/httproute-rule-with-multiple-backends-and-weights.out.yaml
internal/gatewayapi/translator_test.go

* Envoy's `LocalityLbEndpoints.LoadBalancingWeight` only accepts weights greater than 0. So skip such backends/endpoints in the gateway api layer
* From the API spec, no other processing is required for such cases https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.BackendRef
```
If weight is set to 0, no traffic should be forwarded for this entry.
```
Fixes https://github.com/envoyproxy/gateway/issues/2495

bug: skip backendRefs with weight set to 0

---

api/v1alpha1/envoyproxy_types.go
api/v1alpha1/shared_types.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
test/cel-validation/envoyproxy_test.go

fix: LoadBalancerIP validation to prevent trailing period
Current validation allowed `loadBalancerIP` to have a trailing period. This corrects the match expression to reject values such as `1.2.3.4.` and moves the validation rules for shared types to reside with the objects they are validating.

fix: LoadBalancerIP validation to prevent trailing period

---

internal/cmd/egctl/testdata/translate/out/default-resources.all.yaml
internal/cmd/egctl/testdata/translate/out/envoy-patch-policy.all.yaml
internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.json
internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.yaml
internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.bootstrap.yaml
internal/cmd/egctl/testdata/translate/out/jwt-single-route-single-match-to-xds.all.json
internal/cmd/egctl/testdata/translate/out/jwt-single-route-single-match-to-xds.all.yaml
internal/cmd/egctl/testdata/translate/out/jwt-single-route-single-match-to-xds.bootstrap.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/custom.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/custom_with_initcontainers.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/default-env.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/enable-prometheus.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/extension-env.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/override-labels-and-annotations.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/volumes.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-annotations.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-extra-args.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-image-pull-secrets.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-node-selector.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-topology-spread-constraints.yaml
internal/xds/bootstrap/bootstrap.yaml.tpl
internal/xds/bootstrap/testdata/custom-stats-matcher.yaml
internal/xds/bootstrap/testdata/disable-prometheus.yaml
internal/xds/bootstrap/testdata/enable-prometheus.yaml
internal/xds/bootstrap/testdata/otel-metrics.yaml

fix: Envoy rejects XDS at runtime losing all routes on restart
By default Envoy rejects regex routes with a max program size > 100, which is very easy to trigger with simple regex matches:
```
rejected: regex '^/api/v1/object/[\w]{32}/action$' RE2 program size of 107 > max program size of 100
```
When envoy restarts, it loses all it's config resulting in 404 responses to all requests. This change lifts the deprecated validation done by `max_program_size` leaving in place a warning threshold which can be used to monitor for high complexity regex routes without putting stability of the system at risk. See thread on the related issue for full details.
Relates #2543

fix: Envoy rejects XDS at runtime losing all routes on restart

---

internal/xds/translator/route.go
internal/xds/translator/testdata/out/xds-ir/http-route-request-headers.routes.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-response-add-headers.routes.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-response-add-remove-headers.routes.yaml

fix: Deprecated field error when using RequestHeaderModifier filter
Applying the attached `HTTPRoute` currently results in envoy logging a warning:
```
4-02-07 15:09:47.684][1][warning][misc] [source/common/protobuf/message_validator_impl.cc:21] Deprecated field: type envoy.config.core.v3.HeaderValueOption Using deprecated option 'envoy.config.core.v3.HeaderValueOption.append' from file base.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-f …
```

fix: Deprecated field error when using RequestHeaderModifier filter

---

internal/infrastructure/kubernetes/proxy/resource_provider.go
internal/infrastructure/kubernetes/proxy/resource_provider_test.go
internal/infrastructure/kubernetes/proxy/testdata/services/clusterIP-custom-addresses.yaml
internal/status/gateway.go

fix:  when service type = clusterIP set the address to service.clusterIP 
This commit solves the problem that when setting Service Type=ClusterIP and customizing the address for Gateway.spec.addresses, the address is incorrectly set to externalIPs.
I fixed it so that it can be correctly set to the ClusterIP
Fixes #2166

fix: when service type = clusterIP set the address to service.clusterIP

---

internal/xds/translator/testdata/out/xds-ir/mutual-tls.listeners.yaml

chore: fix failed test case introduced by #2490

---

internal/xds/server/runner/runner.go

fix: modifies gateway to use ADS mode
This pr will ensure that the delta watches are sent in correct order (see https://github.com/envoyproxy/go-control-plane/blob/main/pkg/cache/v3/simple.go#L301-L304)
Fixes #2521
Like mentioned in issue, after this modification everything works great! and I can run my go script to verify it:
```
% go run main.go 
httproute.gateway.networking.k8s.io/echoserver-ext configured
2024/02/16 23:41:06 fetching code
securitypolicy.gateway.envoyproxy.io/echoserver-ext-oidc created
2024/02/16 23:41:06 fetching code
2024/02/16 23:41:07 fetching code
securitypolicy.gateway.envoyproxy.io "echoserver-ext-oidc" deleted
httproute.gateway.networking.k8s.io …
```

use ADS cache to ensure the rule order

---

api/v1alpha1/shared_types.go
internal/gatewayapi/testdata/disable-accesslog.in.yaml
internal/gatewayapi/testdata/disable-accesslog.out.yaml
internal/gatewayapi/testdata/envoyproxy-accesslog-file-json-no-format.in.yaml
internal/gatewayapi/testdata/envoyproxy-accesslog-file-json-no-format.out.yaml
internal/gatewayapi/testdata/envoyproxy-accesslog-file-json.in.yaml
internal/gatewayapi/testdata/envoyproxy-accesslog-file-json.out.yaml
internal/gatewayapi/testdata/envoyproxy-accesslog-with-bad-sinks.in.yaml
internal/gatewayapi/testdata/envoyproxy-accesslog-with-bad-sinks.out.yaml
internal/gatewayapi/testdata/envoyproxy-accesslog.in.yaml
internal/gatewayapi/testdata/envoyproxy-accesslog.out.yaml
internal/gatewayapi/testdata/envoyproxy-valid.in.yaml
internal/gatewayapi/testdata/envoyproxy-valid.out.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/bootstrap.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/component-level.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/enable-prometheus.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/override-labels-and-annotations.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-annotations.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-concurrency.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-extra-args.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-image-pull-secrets.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-node-selector.yaml
internal/infrastructure/kubernetes/proxy/testdata/deployments/with-topology-spread-constraints.yaml

This PR updates the Envoy proxy image used to distroless dev builds for the `main` branch.

chore: Update Envoy proxy image to envoy:distroless-dev in main

---

internal/gatewayapi/clienttrafficpolicy.go

Fixes 
- https://github.com/envoyproxy/gateway/issues/2661

fix: match mergedGateways irKey for ClientTrafficPolicy

---

internal/gatewayapi/testdata/securitypolicy-with-basic-auth.out.yaml
internal/gatewayapi/testdata/securitypolicy-with-extauth.out.yaml
internal/gatewayapi/testdata/securitypolicy-with-oidc.in.yaml
internal/gatewayapi/testdata/securitypolicy-with-oidc.out.yaml
internal/gatewayapi/translator.go
internal/xds/translator/basicauth.go
internal/xds/translator/cors.go
internal/xds/translator/extauth.go
internal/xds/translator/fault.go
internal/xds/translator/httpfilters.go
internal/xds/translator/jwt.go
internal/xds/translator/local_ratelimit.go
internal/xds/translator/oidc.go
internal/xds/translator/testdata/out/xds-ir/basic-auth.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/basic-auth.routes.yaml
internal/xds/translator/testdata/out/xds-ir/ext-auth.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/ext-auth.routes.yaml
internal/xds/translator/testdata/out/xds-ir/oidc.listeners.yaml
internal/xds/translator/testdata/out/xds-ir/oidc.routes.yaml
internal/xds/translator/translator.go
site/content/en/latest/user/oidc.md
test/e2e/tests/basic-auth.go

This PR disables per-route filters in `http_filters`, and removes the filter configuration in the `route_config`.
This fixes https://github.com/envoyproxy/gateway/issues/2606 without needing to add a `catch-all-return-404` route.
Fix https://github.com/envoyproxy/gateway/issues/2606
Related: https://github.com/envoyproxy/envoy/issues/32484

Fix: requests not matching defined routes trigger per-route filters

---

api/v1alpha1/envoygateway_helpers.go

- fix: allow passing empty metrics fields in config
When using the following EnvoyGateway setup, envoy does not start due to invalid handing of nil values.
Config passed:
```yaml
data:
envoy-gateway.yaml: |
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyGateway
gateway:
controllerName: gateway.envoyproxy.io/gatewayclass-controller
logging:
level:
default: warn
provider:
kubernetes:
overwrite_control_plane_certs: false
type: Kubernetes
telemetry:
tracing:
provider:
host: otelcol-gateway-collector.observability
port: 6831
type: OpenTelemetry
```
Envoy logs:
```
2024-02-23T08:33:08.765Z	INFO	admin	admin/server.go:39	starting admin server	{"address": "127.0.0.1:19000", "enablePprof": false}
panic: runtime error: …
```

fix: allow passing empty metrics config

---

internal/gatewayapi/backendtrafficpolicy.go
internal/gatewayapi/testdata/backendtrafficpolicy-with-circuitbreakers-error.in.yaml
internal/gatewayapi/testdata/backendtrafficpolicy-with-circuitbreakers-error.out.yaml
internal/gatewayapi/testdata/backendtrafficpolicy-with-circuitbreakers.out.yaml

Translation from API to IR was originally omitted from the implementation: #2508 
Fix translation and tests.

fix: fix translation of MaxRequestsPerConnection

---

internal/cmd/egctl/config_test.go
internal/cmd/egctl/dashboard.go
internal/cmd/egctl/envoy_dashboard.go
internal/cmd/egctl/experimental.go
internal/kubernetes/port-forwarder.go
site/content/en/latest/user/egctl.md

/feature
Render the admin dashboard for the proxy, to see things like configdumps without extra steps.

feat: add `egctl experimental dashboard  envoy-proxy` to render the admin dashboard for the proxy

---

internal/cmd/egctl/config.go
internal/cmd/egctl/config_cmd.go
internal/cmd/egctl/config_ratelimit.go
internal/cmd/egctl/config_test.go
internal/cmd/egctl/envoy_stats.go
internal/infrastructure/kubernetes/ratelimit/resource.go
internal/infrastructure/kubernetes/ratelimit/resource_provider_test.go
site/content/en/latest/design/egctl.md

feat(egctl): add egctl ratelimit config support
Add the `egctl ratelimit` subcommand to `egctl`. This subcommand can help developers or users quickly view the ratelimit configuration or debug the ratelimit.
Fixes #2584

feat: add egctl ratelimit config support

---

internal/gatewayapi/contexts.go
internal/gatewayapi/filters.go
internal/gatewayapi/route.go
internal/gatewayapi/testdata/httproute-with-invalid-backend-ref-unsupported-filter.in.yaml
internal/gatewayapi/testdata/httproute-with-invalid-backend-ref-unsupported-filter.out.yaml
internal/gatewayapi/validate.go

- highlight unsupported BackendRef filters using a status condition
- introduce BackendRefContext in translator
Fixes 
- https://github.com/envoyproxy/gateway/issues/2572

fix: add unsupported status condition for filters within BackendRef

---

api/v1alpha1/backendtrafficpolicy_types.go
api/v1alpha1/clienttrafficpolicy_types.go
api/v1alpha1/envoypatchpolicy_types.go
api/v1alpha1/envoyproxy_types.go
api/v1alpha1/securitypolicy_types.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_clienttrafficpolicies.yaml
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoypatchpolicies.yaml
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml

with this patch, you can get all eg resources with following command:
```shell
kubctl get envoy-gateway
```

chore: add crd categories

---

internal/xds/translator/route.go
internal/xds/translator/testdata/in/xds-ir/http-route-timeout.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-timeout.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-timeout.endpoints.yaml
internal/xds/translator/testdata/out/xds-ir/http-route-timeout.routes.yaml

Fixes bug where default `stream_idle_timeout` in connection manager interferes with request timeouts set on HTTPRoute when set greater than 5 minutes preventing high request timeouts from being used without patching connection manager settings.
**What this PR does**:
If an HTTP request `timeout` is configured on the route and is non-zero, the `idle_timeout` will be set to the greater of 1hr or the configured request timeout. If the `timeout` on the HTTPRoute is set to `0` the `idle_timeout` is also set to `0` disabling both timeouts on the route.
**How to reproduce**:
1. Deploy demo into kind cluster and set a fault injection delay of 500s:
```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
name: fault-injection-delay
spec: …
```

fix: Configure idle timeout when timeout is set on HTTPRoute

---

charts/gateway-helm/README.md

* "docs: fix helm chart install script"

docs: fix helm chart install docs

---

test/e2e/testdata/jwt.yaml
test/e2e/tests/jwt.go

Fixes: https://github.com/envoyproxy/gateway/issues/2690

e2e: add test for jwt claim base routing

---

internal/gatewayapi/route.go
internal/gatewayapi/testdata/grpcroute-with-empty-backends.in.yaml
internal/gatewayapi/testdata/grpcroute-with-empty-backends.out.yaml
internal/gatewayapi/testdata/httproute-rule-with-empty-backends-and-no-filters.in.yaml
internal/gatewayapi/testdata/httproute-rule-with-empty-backends-and-no-filters.out.yaml

This PR fixes a panic which occurs when adding either an `HTTPRoute` or `GRPCRoute` with no filters or backendRefs. For example:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
name: empty-backends
spec:
parentRefs:
- group: gateway.networking.k8s.io
kind: Gateway
name: eg
rules:
- matches:
- path:
type: PathPrefix
value: /
```
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x190dadc]
goroutine 59 [running]:
github.com/envoyproxy/gateway/internal/xds/translator.buildXdsRouteAction(...)
/Users/davidalger/work/envoyproxy/gateway/internal/xds/translator/route.go:214
github.com/envoyproxy/gateway/internal/xds/translator.buildXdsRoute(0x40007c2680) …
```

fix(translator): Panic when translating routes with empty backends

---

tools/make/kube.mk

remove following warning message:
```console
make uninstall-e2e-telemetry
tools/make/kube.mk:121: warning: undefined variable `E2E_RUN_TEST'
```

chore: clean warning message

---

test/e2e/testdata/circuitbreaker.yaml

not sure why there's no error, looks like there's a field named `maxRequests`, got following error:
```console
Error from server (BadRequest): error when creating "BackendTrafficPolicy/circuitbreaker.yaml": BackendTrafficPolicy in version "v1alpha1" cannot be handled as a BackendTrafficPolicy: strict decoding error: unknown field "spec.circuitBreaker.maxRequests"
```

fix circuitbreaker BTP

---

api/v1alpha1/retry_types.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml
internal/ir/xds.go
internal/xds/translator/route.go
internal/xds/translator/testdata/in/xds-ir/retry-partial-invalid.yaml
internal/xds/translator/testdata/out/xds-ir/retry-partial-invalid.routes.yaml

fix: reset translate in retry

---

site/content/en/latest/user/http-timeouts.md

* "docs: add http timeouts docs"

docs: add http-timeouts docs

---

test/e2e/tests/circuitbreaker.go

Allows responses to converge to a closed circuit breaker, instead of demanding that the first request will already have the circuit breaker enforced. 
Fixes #2758

fix: Circuit Breaker flaky test

---

release-notes/v1.0.0-rc.1.yaml

+ Add missing release note details
+ Reorganize release note details

fix: add missing release notes details and re organize it

---

internal/xds/translator/cluster.go
internal/xds/translator/testdata/in/xds-ir/tls-route-passthrough.yaml
internal/xds/translator/testdata/out/xds-ir/tls-route-passthrough.clusters.yaml
internal/xds/translator/testdata/out/xds-ir/tls-route-passthrough.endpoints.yaml
internal/xds/translator/testdata/out/xds-ir/tls-route-passthrough.listeners.yaml
internal/xds/translator/translator.go

Fixes: https://github.com/envoyproxy/gateway/issues/2832

bug: compute endpointType for all protocol types

---

site/content/en/latest/user/security/mutual-tls.md

Fixes: https://github.com/envoyproxy/gateway/issues/2613

docs: mtls to the gateway

---

internal/infrastructure/kubernetes/resource/resource.go
internal/infrastructure/kubernetes/resource/resource_test.go

Fixes: https://github.com/envoyproxy/gateway/issues/1820

ignore finalizers when comparing envoy proxy svc

---

internal/provider/kubernetes/controller.go
internal/provider/kubernetes/routes.go
site/content/en/latest/user/security/oidc.md

This PR removes `allAssociatedRefGrants` from `resourceMappings` and directly add `ReferenceGrant` to `Resources`.

Chore: remove the uncessary allAssociatedRefGrants from resourceMappings

---

internal/cmd/envoy/shutdown_manager.go

This PR resolves a race condition created when the original implementation of `/shutdown/ready` [was altered](https://github.com/envoyproxy/gateway/pull/2633#discussion_r1499870618) in an attempt to safeguard against CPU usage from excessive polling if a malicious actor issued a large number of requests to the `/shutdown/ready` endpoint of active proxy pods. In reality that is likely a very low risk compared to the tradeoff of the race condition.
Given this change has been proven to result in a race condition that causes real harm (breaks the graceful drain), I'm proposing we revert to the original implementation where `/shutdown/ready` blocks until the readiness indicator turns up or until it's timeout is reached preventing the race condition.
More …

fix: Address race condition disrupting graceful shutdown process

---

internal/xds/translator/listener.go
internal/xds/translator/testdata/out/xds-ir/http3.listeners.yaml

Fixes: https://github.com/envoyproxy/gateway/issues/2875

bug: add h3 alpn by default if http3 is enabled

---

internal/gatewayapi/runner/runner.go
internal/provider/kubernetes/controller.go
internal/xds/translator/runner/runner.go

* https://github.com/envoyproxy/gateway/pull/2802 skips computing status if a target resource cannot be found, mainly because that target maybe irrelevant to this specific translation, its hard to proactively find that out in the provider layer
* This fix ensures that any empty status is not published and resets any existing status for a policy

skip publishing empty status for policies

---

site/content/en/latest/user/security/oidc.md

Fix oidc doc

---

site/package.json

after:
```shell
Environment: "dev"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 0.0.0.0)
```

chore: improve docs-serve

---

api/v1alpha1/ratelimit_types.go
charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml
test/cel-validation/backendtrafficpolicy_test.go

feat: increase rate-limit global rules limit
Fixes #2900

api: increase rate-limit global rules limit

---

site/content/en/v1.0.0/install/api.md
site/content/en/v1.0.0/install/install-helm.md
site/content/en/v1.0.0/user/operations/deployment-mode.md
site/content/en/v1.0.0/user/traffic/multicluster-service.md

Should we use v1.0.0 instead of the latest in the v1.0.0 docs since it's a GA version ? @envoyproxy/gateway-maintainers

Pin version to v1.0.0 in 1.0.0 docs

---

charts/gateway-helm/templates/certgen.yaml

Run certgen when upgrading EG helm chart because a new secret(HMAC) has been added after v0.0.6, and more may be added later. 
Fix https://github.com/envoyproxy/gateway/issues/2930

Run certgen when upgrading

---

test/e2e/tests/eg_upgrade.go

Now that v1.0.0 is released, we should use it a baseline for upgrade tests in CI.

chore: use v1.0.0 as default for upgrade test

---

test/config/gatewayclass.yaml

Use default shutdown manager settings in the upgrade suite, allowing connections to gracefully close over a longer period of time. 
relates to #2937

e2e: use default shutdown mgr settings in upgrade test suite

---

internal/xds/translator/extauth.go
internal/xds/translator/testdata/out/xds-ir/ext-auth.listeners.yaml

fix: [can't configure pathPrefix for extAuth.](https://github.com/envoyproxy/gateway/issues/3016)

fix: set path prefix for http ext auth service

---

charts/gateway-helm/templates/infra-manager-rbac.yaml
internal/infrastructure/kubernetes/infra_client.go
internal/infrastructure/kubernetes/proxy_configmap_test.go
internal/infrastructure/kubernetes/proxy_deployment_test.go
internal/infrastructure/kubernetes/proxy_infra_test.go
internal/infrastructure/kubernetes/proxy_serviceaccount_test.go
internal/infrastructure/kubernetes/ratelimit_deployment_test.go
internal/infrastructure/kubernetes/ratelimit_serviceaccount_test.go
test/helm/default.yaml

Instead of utilizing the Update API for the infra-client, this PR changed it to the Patch API with ApplyPatch.
Fixes #2995

fix: use Patch API for infra-client

---

internal/gatewayapi/clienttrafficpolicy.go
internal/gatewayapi/securitypolicy.go
internal/gatewayapi/testdata/conflicting-policies.out.yaml
internal/gatewayapi/testdata/merge-with-isolated-policies-2.in.yaml
internal/gatewayapi/testdata/merge-with-isolated-policies-2.out.yaml

fix: Allow Policy to attach to multiple http listeners 

---

internal/cmd/envoy/shutdown_manager.go
internal/gatewayapi/route.go
internal/xds/translator/basicauth.go
internal/xds/translator/extauth.go
internal/xds/translator/fault.go
internal/xds/translator/jwt.go
internal/xds/translator/oidc.go
internal/xds/translator/translator.go
tools/linter/golangci-lint/.golangci.yml

Adds `govet` linter cleaning up unused writes and tautological nilness checks:
```
internal/cmd/envoy/shutdown_manager.go:111:12: nilness: tautological condition: nil == nil (govet)
case err == nil:
^
internal/xds/translator/basicauth.go:115:13: nilness: tautological condition: non-nil != nil (govet)
if irRoute != nil &&
^
internal/xds/translator/extauth.go:209:13: nilness: tautological condition: non-nil != nil (govet)
if irRoute != nil &&
^
internal/xds/translator/fault.go:112:13: nilness: tautological condition: non-nil != nil (govet)
if irRoute != nil &&
^
internal/xds/translator/jwt.go:330:13: nilness: tautological condition: non-nil != nil (govet)
if irRoute != nil &&
^
internal/xds/translator/oidc.go:185:13: nilness: tautological condition: non-nil != …
```

chore: Address unused write and tautological nilness checks

---

examples/kubernetes/accesslog/json-accesslog.yaml

Resolves an error encountered applying one of the examples:
```
$ kubectl apply -f examples/kubernetes/accesslog/json-accesslog.yaml 
gatewayclass.gateway.networking.k8s.io/eg configured
Error from server (BadRequest): error when creating "examples/kubernetes/accesslog/json-accesslog.yaml": EnvoyProxy in version "v1alpha1" cannot be handled as a EnvoyProxy: strict decoding error: unknown field "spec.telemetry.accessLog.settings[0].json", unknown field "spec.telemetry.accessLog.settings[0].type", unknown field "spec.telemetry.accessLog.sinks"
```

fix: BadRequest error applying JSON access log example

---

go.mod
go.sum
internal/metrics/sample_counter_test.go
internal/metrics/sample_gauge_test.go
internal/metrics/sample_histogram_test.go
internal/metrics/testdata/counter_metric.yaml
internal/metrics/testdata/gauge_metric.yaml
internal/metrics/testdata/histogram_metric.yaml

test: The original metrics test is too simple, I have enhanced it

test: supplementary metrics test

---

test/helm/default.yaml
tools/make/helm.mk

After https://github.com/envoyproxy/gateway/pull/2793

fix: helm-template should explicitly set ns
